# CrystalOSD — PS2 OSDSYS Matching Decomp Makefile
# Requires: PS2 toolchain (ee-gcc, ee-as) from ps2dev/ps2toolchain
#
# Two parallel build flows:
#   1. ELF link  (make elf)        — splat output → byte-perfect rebuild
#   2. objdiff   (make all)        — per-subsystem .o for matching diffs
#
# Splat-driven layout (used by ELF link):
#   asm/texttmp.s         — full code dump (one big file)
#   asm/data/*.s          — data sections (.data, .rodata, .bss, .sdata)
#   OSDSYS_A.ld           — linker script generated by splat
#   build/asm/...         — objects assembled from splat output
#
# objdiff layout (matching workflow):
#   asm/<subsystem>/*.s   — hand-curated per-subsystem .s for diffing
#   src/<subsystem>/*.c   — our C reconstruction
#   build/target/...      — assembled original .o (ground truth)
#   build/base/...        — compiled our .o (what we're matching)

# ── Toolchain ──────────────────────────────────────────
PREFIX  ?= mips64r5900el-ps2-elf-
CC      := $(PREFIX)gcc
# Matching compiler (ee-gcc 2.9-991111) — REQUIRED for ALL C compilation. Modern GCC
# ($(CC)) is used ONLY to assemble + link; it will NOT produce byte-matching C output.
# Install ee-gcc2.9-991111 (decompme/compilers) and export MATCH_CC to point at it.
# No silent fallback to $(CC): a wrong-compiler C object would break the byte-perfect ELF.
# NOTE (WSL): ee-gcc is a 32-bit 1999 binary; its stat() EOVERFLOWs on the /mnt/c (9p)
# mount, so C sources must live on native ext4. Use tools/wsl/build_verify.sh (compiles
# via /tmp) or a native WSL clone of the repo. See docs/SETUP_WSL.md.
MATCH_CC ?=
AS      := $(PREFIX)as
LD      := $(PREFIX)ld
OBJCOPY := $(PREFIX)objcopy

# ── Compiler Flags ─────────────────────────────────────
# Match original OSDSYS: ee-gcc 2.9-991111 + -O2 -G0
CFLAGS  := -O2 -G0 -Wall -D_EE -mabi=eabi -mno-abicalls
CFLAGS  += -fno-common -fno-exceptions

# Per-function small-data threshold (-G) override. Globals in .sdata/.sbss are accessed
# gp-relative and need -G8; the default -G0 keeps others absolute. The LAST -G on the
# command line wins, so $(GADD) overrides CFLAGS' -G0. Add one line per gp-relative
# function. Keep in sync with tools/wsl/build_verify.sh's ee_g_for().
GADD :=
build/base/graph/pktSetAD.o build/src/graph/pktSetAD.c.o: GADD := -G8
CFLAGS  += -I include -I $(PS2SDK)/ee/include -I $(PS2SDK)/common/include
ASFLAGS := -march=r5900 -mabi=eabi -G0 -I include
LDFLAGS := -m elf32lr5900 -EL -nostdlib --no-check-sections -G 0 --defsym=_gp=0x377970 -e 0x200008 -s
LDFLAGS += -T undefined_syms_auto.txt -T undefined_funcs_auto.txt

# ── Directories ────────────────────────────────────────
ASM_DIR     := asm
SRC_DIR     := src
TARGET_DIR  := build/target
BASE_DIR    := build/base
ASM_BUILD   := build/asm
ELF_OUT     := build/OSDSYS.elf
ELF_MAP     := build/OSDSYS.map
ORIG_ELF    := OSDSYS_A_XLF_decrypted_unpacked.elf
LINKER      := OSDSYS_A.ld

# ── ELF link inputs ────────────────────────────────────
# Link EXACTLY the objects the linker script references — not every *.s in the tree.
# The committed asm tree contains orphan duplicates (gap_*.s superseded by align_*.s, and
# per-symbol D_*.s overlapping align_* blocks) left behind by split_aligns.py. Linking the
# whole tree yields "multiple definition". OSDSYS_A.ld is the authoritative object set.
ELF_OBJS := $(sort $(shell grep -oE 'build/[A-Za-z0-9_./-]+\.o' $(LINKER) 2>/dev/null))

# ── objdiff match inputs ───────────────────────────────
SUBSYSTEMS     := core browser cdvd clock config graph history module opening sound data
ASM_SRCS       := $(shell find $(ASM_DIR) -mindepth 2 -name '*.s' -type f 2>/dev/null)
C_SRCS         := $(shell find $(SRC_DIR) -name '*.c' -type f 2>/dev/null)

ASM_MATCH_OBJS := $(patsubst $(ASM_DIR)/%.s,$(TARGET_DIR)/%.o,$(ASM_SRCS))
C_OBJS         := $(patsubst $(SRC_DIR)/%.c,$(BASE_DIR)/%.o,$(C_SRCS))
C_OBJS         := $(patsubst $(SRC_DIR)/%.c,$(BASE_DIR)/%.o,$(C_SRCS))

# ── Phony targets ──────────────────────────────────────
.PHONY: all elf split verify sha1 clean check-toolchain require-match-cc dirs target base progress progress-json progress-crossref progress-md stats coverage help

# default: objdiff workflow (legacy behaviour)
all: check-toolchain dirs target base
	@python3 tools/generate_objdiff.py
	@echo "=== objdiff build complete ==="
	@echo "Target objects: $(words $(ASM_MATCH_OBJS))"
	@echo "Base objects:   $(words $(C_OBJS))"

# ── Splat: regenerate asm/ + linker script ────────────
split:
	python3 configure.py

# ── ELF link: full rebuild from splat output ──────────
elf: check-toolchain $(ELF_OUT)

$(ELF_OUT): $(ELF_OBJS) $(LINKER)
	@mkdir -p $(dir $@)
	$(LD) $(LDFLAGS) -T $(LINKER) -Map=$(ELF_MAP) -o $@.tmp $(ELF_OBJS)
	$(OBJCOPY) --strip-section-headers $@.tmp $@
	@dd if=$@ of=$@.payload bs=4096 skip=2 2>/dev/null
	@dd if=$(ORIG_ELF) of=$@.header bs=4096 count=1 2>/dev/null
	@cat $@.header $@.payload > $@
	@rm -f $@.tmp $@.payload $@.header
	@echo "=== ELF built: $@ ==="

# Pattern: asm/foo.s  →  build/asm/foo.s.o   (note: extension preserved)
$(ASM_BUILD)/%.s.o: $(ASM_DIR)/%.s
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) -o $@ $<

# Fail loudly if a C compile is attempted without the matching compiler set.
require-match-cc:
	@test -n "$(MATCH_CC)" && test -x "$(MATCH_CC)" || ( \
	  echo "ERROR: MATCH_CC is not set to an executable ee-gcc 2.9-991111." ; \
	  echo "  C must be compiled with the matching compiler, not modern GCC." ; \
	  echo "  Install: https://github.com/decompme/compilers/releases (ee-gcc2.9-991111)" ; \
	  echo "  Then:    export MATCH_CC=\$$HOME/ee-gcc2.9-991111/bin/ee-gcc" ; \
	  exit 1 )

# Pattern: src/foo.c → build/src/foo.c.o
build/src/%.c.o: src/%.c | require-match-cc
	@mkdir -p $(dir $@)
	$(MATCH_CC) $(CFLAGS) $(GADD) -c -o $@ $<

# Verify byte-perfect rebuild against original
verify: $(ELF_OUT)
	@cmp $(ELF_OUT) $(ORIG_ELF) && \
		echo "✅ byte-perfect match: $(ELF_OUT) == $(ORIG_ELF)" || \
		(echo "❌ ELF differs from original" && exit 1)

# SHA1 verification (CI-friendly, doesn't need original ELF)
sha1: $(ELF_OUT)
	@shasum -a 1 $(ELF_OUT) > build/build.sha1
	@if [ -f config/build.sha1 ]; then \
		EXPECTED=$$(awk '{print $$1}' config/build.sha1); \
		ACTUAL=$$(awk '{print $$1}' build/build.sha1); \
		if [ "$$EXPECTED" = "$$ACTUAL" ]; then \
			echo "✅ SHA1 match: $$ACTUAL"; \
		else \
			echo "❌ SHA1 mismatch: expected $$EXPECTED, got $$ACTUAL"; \
			exit 1; \
		fi; \
	else \
		echo "⚠️  No config/build.sha1 — SHA1: $$(cat build/build.sha1)"; \
	fi

# ── Toolchain check ───────────────────────────────────
check-toolchain:
	@which $(CC) > /dev/null 2>&1 || \
		(echo "ERROR: $(CC) not found." && \
		 echo "" && \
		 echo "Install options for macOS:" && \
		 echo "  1. Pre-built release: https://github.com/ps2dev/ps2dev/releases" && \
		 echo "  2. Docker:            https://github.com/ps2dev/ps2toolchain (Dockerfile included)" && \
		 echo "  3. Build from source: ~/CodingProjects/ps2toolchain/toolchain.sh" && \
		 exit 1)

# ── objdiff: matching workflow build rules ────────────
dirs:
	@$(foreach sub,$(SUBSYSTEMS), \
		mkdir -p $(TARGET_DIR)/$(sub) $(BASE_DIR)/$(sub);)

target: $(ASM_MATCH_OBJS)

$(TARGET_DIR)/%.o: $(ASM_DIR)/%.s | dirs
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) -o $@ $<

base: $(C_OBJS)

$(BASE_DIR)/%.o: $(SRC_DIR)/%.c | dirs require-match-cc
	@mkdir -p $(dir $@)
	$(MATCH_CC) $(CFLAGS) $(GADD) -c -o $@ $<

# ── Clean ──────────────────────────────────────────────
clean:
	rm -rf build/

# ── Progress ──────────────────────────────────────────
progress:
	@python3 tools/progress.py

progress-json:
	@python3 tools/progress.py --json

progress-crossref:
	@python3 tools/progress.py --crossref

progress-md:
	@python3 tools/progress.py --markdown

# ── Subsystem Stats ──────────────────────────────────
stats:
	@python3 tools/split_functions.py --stats

coverage:
	@python3 tools/split_functions.py --check-coverage

help:
	@echo "CrystalOSD Makefile"
	@echo ""
	@echo "Build:"
	@echo "  make split    — Run splat (regenerate asm/ + OSDSYS_A.ld)"
	@echo "  make elf      — Link full ELF from splat output → build/OSDSYS.elf"
	@echo "  make verify   — Compare rebuilt ELF against original (byte-perfect)"
	@echo "  make sha1     — SHA1 verification (CI-friendly, no original ELF needed)"
	@echo "  make all      — objdiff matching build (target + base .o)"
	@echo "  make target   — Assemble per-subsystem matching .s → .o"
	@echo "  make base     — Compile our .c → .o"
	@echo "  make clean    — Remove build/"
	@echo ""
	@echo "Progress:"
	@echo "  make progress        — Console progress bars"
	@echo "  make progress-json   — JSON output for decomp.dev"
	@echo "  make progress-md     — Markdown progress table"
	@echo "  make progress-crossref — Theseus-style cross-reference"
	@echo "  make stats           — Subsystem code size breakdown"
	@echo "  make coverage        — Check .text address coverage"
	@echo ""
	@echo "Matching:"
	@echo "  ./tools/permuter_import.sh <func> <src> — Import function into permuter"
	@echo "  cd tools/decomp-permuter && python3 ./permuter.py nonmatchings/<func> -j8"
	@echo ""
	@echo "Workflow:"
	@echo "  1. make split          (run once after symbol changes)"
	@echo "  2. make elf            (rebuild ELF)"
	@echo "  3. make verify         (sanity check byte-perfect)"
	@echo "  4. Test build/OSDSYS.elf in PCSX2"
