.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching clock_input_check_handler_p6_p7_tgt, 0x374

glabel clock_input_check_handler_p6_p7_tgt
    /* 269B8 002259B8 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 269BC 002259BC 2000B2FF */  sd         $s2, 0x20($sp)
    /* 269C0 002259C0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 269C4 002259C4 2B00123C */  lui        $s2, %hi(D_002B2170)
    /* 269C8 002259C8 1000B1FF */  sd         $s1, 0x10($sp)
    /* 269CC 002259CC 1F00103C */  lui        $s0, (0x1F064C >> 16)
    /* 269D0 002259D0 3000BFFF */  sd         $ra, 0x30($sp)
    /* 269D4 002259D4 70215126 */  addiu      $s1, $s2, %lo(D_002B2170)
    /* 269D8 002259D8 440600AE */  sw         $zero, (0x1F0644 & 0xFFFF)($s0)
    /* 269DC 002259DC 6C97080C */  jal        module_clock_init_resources
    /* 269E0 002259E0 040020AE */   sw        $zero, 0x4($s1)
    /* 269E4 002259E4 C02F080C */  jal        StartFrame
    /* 269E8 002259E8 00000000 */   nop
    /* 269EC 002259EC A40C048E */  lw         $a0, (0x1F0CA4 & 0xFFFF)($s0)
    /* 269F0 002259F0 01000524 */  addiu      $a1, $zero, 0x1
    /* 269F4 002259F4 0C00028E */  lw         $v0, (0x1F000C & 0xFFFF)($s0)
    /* 269F8 002259F8 4C06038E */  lw         $v1, (0x1F064C & 0xFFFF)($s0)
    /* 269FC 002259FC 080024AE */  sw         $a0, 0x8($s1)
    /* 26A00 00225A00 05006510 */  beq        $v1, $a1, .L00225A18
    /* 26A04 00225A04 0C9182AF */   sw        $v0, %gp_rel(D_00370A7C)($gp)
    /* 26A08 00225A08 BEBF080C */  jal        func_0022FEF8
    /* 26A0C 00225A0C 00000000 */   nop
    /* 26A10 00225A10 05004010 */  beqz       $v0, .L00225A28
    /* 26A14 00225A14 70215126 */   addiu     $s1, $s2, %lo(D_002B2170)
  .L00225A18:
    /* 26A18 00225A18 64000224 */  addiu      $v0, $zero, 0x64
    /* 26A1C 00225A1C 0C9182AF */  sw         $v0, %gp_rel(D_00370A7C)($gp)
    /* 26A20 00225A20 70215126 */  addiu      $s1, $s2, %lo(D_002B2170)
    /* 26A24 00225A24 00000000 */  nop
  .L00225A28:
    /* 26A28 00225A28 1F00023C */  lui        $v0, (0x1F000C >> 16)
    /* 26A2C 00225A2C 0400238E */  lw         $v1, 0x4($s1)
    /* 26A30 00225A30 0C00508C */  lw         $s0, (0x1F000C & 0xFFFF)($v0)
    /* 26A34 00225A34 05006010 */  beqz       $v1, .L00225A4C
    /* 26A38 00225A38 0C91828F */   lw        $v0, %gp_rel(D_00370A7C)($gp)
    /* 26A3C 00225A3C BEBF080C */  jal        func_0022FEF8
    /* 26A40 00225A40 00000000 */   nop
    /* 26A44 00225A44 2D004010 */  beqz       $v0, .L00225AFC
    /* 26A48 00225A48 0C91828F */   lw        $v0, %gp_rel(D_00370A7C)($gp)
  .L00225A4C:
    /* 26A4C 00225A4C 1F005010 */  beq        $v0, $s0, .L00225ACC
    /* 26A50 00225A50 96FF0326 */   addiu     $v1, $s0, -0x6A
    /* 26A54 00225A54 0B00622C */  sltiu      $v0, $v1, 0xB
    /* 26A58 00225A58 17004010 */  beqz       $v0, .L00225AB8
    /* 26A5C 00225A5C 3600023C */   lui       $v0, %hi(jtbl_00365500)
    /* 26A60 00225A60 80180300 */  sll        $v1, $v1, 2
    /* 26A64 00225A64 00554224 */  addiu      $v0, $v0, %lo(jtbl_00365500)
    /* 26A68 00225A68 21186200 */  addu       $v1, $v1, $v0
    /* 26A6C 00225A6C 0000648C */  lw         $a0, 0x0($v1)
    /* 26A70 00225A70 08008000 */  jr         $a0
    /* 26A74 00225A74 00000000 */   nop
    /* 26A78 00225A78 1F00023C */  lui        $v0, (0x1F0D58 >> 16)
    /* 26A7C 00225A7C 580D428C */  lw         $v0, (0x1F0D58 & 0xFFFF)($v0)
    /* 26A80 00225A80 10004018 */  blez       $v0, .L00225AC4
    /* 26A84 00225A84 01000224 */   addiu     $v0, $zero, 0x1
    /* 26A88 00225A88 CABF080C */  jal        func_0022FF28
    /* 26A8C 00225A8C 00000000 */   nop
    /* 26A90 00225A90 05004010 */  beqz       $v0, .L00225AA8
    /* 26A94 00225A94 70214326 */   addiu     $v1, $s2, %lo(D_002B2170)
    /* 26A98 00225A98 BEBF080C */  jal        func_0022FEF8
    /* 26A9C 00225A9C 00000000 */   nop
    /* 26AA0 00225AA0 03004010 */  beqz       $v0, .L00225AB0
    /* 26AA4 00225AA4 70214326 */   addiu     $v1, $s2, %lo(D_002B2170)
  .L00225AA8:
    /* 26AA8 00225AA8 01000224 */  addiu      $v0, $zero, 0x1
    /* 26AAC 00225AAC 040062AC */  sw         $v0, 0x4($v1)
  .L00225AB0:
    /* 26AB0 00225AB0 03000010 */  b          .L00225AC0
    /* 26AB4 00225AB4 0C9190AF */   sw        $s0, %gp_rel(D_00370A7C)($gp)
  .L00225AB8:
    /* 26AB8 00225AB8 0C9190AF */  sw         $s0, %gp_rel(D_00370A7C)($gp)
    /* 26ABC 00225ABC 040020AE */  sw         $zero, 0x4($s1)
  .L00225AC0:
    /* 26AC0 00225AC0 01000224 */  addiu      $v0, $zero, 0x1
  .L00225AC4:
    /* 26AC4 00225AC4 1F00013C */  lui        $at, (0x1F0D4C >> 16)
    /* 26AC8 00225AC8 4C0D22AC */  sw         $v0, (0x1F0D4C & 0xFFFF)($at)
  .L00225ACC:
    /* 26ACC 00225ACC E6BF080C */  jal        func_0022FF98
    /* 26AD0 00225AD0 00000000 */   nop
    /* 26AD4 00225AD4 32004010 */  beqz       $v0, .L00225BA0
    /* 26AD8 00225AD8 0C91838F */   lw        $v1, %gp_rel(D_00370A7C)($gp)
    /* 26ADC 00225ADC 74000224 */  addiu      $v0, $zero, 0x74
    /* 26AE0 00225AE0 02006210 */  beq        $v1, $v0, .L00225AEC
    /* 26AE4 00225AE4 0F270224 */   addiu     $v0, $zero, 0x270F
    /* 26AE8 00225AE8 0C9182AF */  sw         $v0, %gp_rel(D_00370A7C)($gp)
  .L00225AEC:
    /* 26AEC 00225AEC 70214326 */  addiu      $v1, $s2, %lo(D_002B2170)
    /* 26AF0 00225AF0 01000224 */  addiu      $v0, $zero, 0x1
    /* 26AF4 00225AF4 2A000010 */  b          .L00225BA0
    /* 26AF8 00225AF8 040062AC */   sw        $v0, 0x4($v1)
  .L00225AFC:
    /* 26AFC 00225AFC E0D2080C */  jal        func_00234B80
    /* 26B00 00225B00 00000000 */   nop
    /* 26B04 00225B04 22004014 */  bnez       $v0, .L00225B90
    /* 26B08 00225B08 0C91828F */   lw        $v0, %gp_rel(D_00370A7C)($gp)
    /* 26B0C 00225B0C 96FF4424 */  addiu      $a0, $v0, -0x6A
    /* 26B10 00225B10 0A00832C */  sltiu      $v1, $a0, 0xA
    /* 26B14 00225B14 15006010 */  beqz       $v1, .L00225B6C
    /* 26B18 00225B18 3600023C */   lui       $v0, %hi(jtbl_00365530)
    /* 26B1C 00225B1C 80180400 */  sll        $v1, $a0, 2
    /* 26B20 00225B20 30554224 */  addiu      $v0, $v0, %lo(jtbl_00365530)
    /* 26B24 00225B24 21186200 */  addu       $v1, $v1, $v0
    /* 26B28 00225B28 0000648C */  lw         $a0, 0x0($v1)
    /* 26B2C 00225B2C 08008000 */  jr         $a0
    /* 26B30 00225B30 00000000 */   nop
    /* 26B34 00225B34 50610424 */  addiu      $a0, $zero, 0x6150
    /* 26B38 00225B38 02000524 */  addiu      $a1, $zero, 0x2
    /* 26B3C 00225B3C 2D300000 */  daddu      $a2, $zero, $zero
    /* 26B40 00225B40 0003080C */  jal        sound_handler_queue_cmd
    /* 26B44 00225B44 0E000724 */   addiu     $a3, $zero, 0xE
    /* 26B48 00225B48 0D000010 */  b          .L00225B80
    /* 26B4C 00225B4C 00000000 */   nop
    /* 26B50 00225B50 50610424 */  addiu      $a0, $zero, 0x6150
    /* 26B54 00225B54 02000524 */  addiu      $a1, $zero, 0x2
    /* 26B58 00225B58 2D300000 */  daddu      $a2, $zero, $zero
    /* 26B5C 00225B5C 0003080C */  jal        sound_handler_queue_cmd
    /* 26B60 00225B60 0F000724 */   addiu     $a3, $zero, 0xF
    /* 26B64 00225B64 06000010 */  b          .L00225B80
    /* 26B68 00225B68 00000000 */   nop
  .L00225B6C:
    /* 26B6C 00225B6C 50610424 */  addiu      $a0, $zero, 0x6150
    /* 26B70 00225B70 02000524 */  addiu      $a1, $zero, 0x2
    /* 26B74 00225B74 2D300000 */  daddu      $a2, $zero, $zero
    /* 26B78 00225B78 0003080C */  jal        sound_handler_queue_cmd
    /* 26B7C 00225B7C 2D380000 */   daddu     $a3, $zero, $zero
  .L00225B80:
    /* 26B80 00225B80 0AD3080C */  jal        func_00234C28
    /* 26B84 00225B84 03000424 */   addiu     $a0, $zero, 0x3
    /* 26B88 00225B88 05000010 */  b          .L00225BA0
    /* 26B8C 00225B8C 00000000 */   nop
  .L00225B90:
    /* 26B90 00225B90 DED2080C */  jal        get_clock_should_render_orbs
    /* 26B94 00225B94 00000000 */   nop
    /* 26B98 00225B98 0C004018 */  blez       $v0, .L00225BCC
    /* 26B9C 00225B9C 0C91838F */   lw        $v1, %gp_rel(D_00370A7C)($gp)
  .L00225BA0:
    /* 26BA0 00225BA0 A097080C */  jal        clock_orb_rendering_func
    /* 26BA4 00225BA4 00000000 */   nop
    /* 26BA8 00225BA8 EA2F080C */  jal        OpeningDoWaitNextFrame
    /* 26BAC 00225BAC 00000000 */   nop
    /* 26BB0 00225BB0 1F00023C */  lui        $v0, (0x1F0CA4 >> 16)
    /* 26BB4 00225BB4 70214426 */  addiu      $a0, $s2, %lo(D_002B2170)
    /* 26BB8 00225BB8 A40C438C */  lw         $v1, (0x1F0CA4 & 0xFFFF)($v0)
    /* 26BBC 00225BBC 8E2F080C */  jal        graph_reset_related3
    /* 26BC0 00225BC0 080083AC */   sw        $v1, 0x8($a0)
    /* 26BC4 00225BC4 98FF0010 */  b          .L00225A28
    /* 26BC8 00225BC8 70215126 */   addiu     $s1, $s2, %lo(D_002B2170)
  .L00225BCC:
    /* 26BCC 00225BCC 70000224 */  addiu      $v0, $zero, 0x70
    /* 26BD0 00225BD0 3A006210 */  beq        $v1, $v0, .L00225CBC
    /* 26BD4 00225BD4 71006228 */   slti      $v0, $v1, 0x71
    /* 26BD8 00225BD8 11004010 */  beqz       $v0, .L00225C20
    /* 26BDC 00225BDC 6E006228 */   slti      $v0, $v1, 0x6E
    /* 26BE0 00225BE0 0A004010 */  beqz       $v0, .L00225C0C
    /* 26BE4 00225BE4 6C006228 */   slti      $v0, $v1, 0x6C
    /* 26BE8 00225BE8 1D004010 */  beqz       $v0, .L00225C60
    /* 26BEC 00225BEC 6A006228 */   slti      $v0, $v1, 0x6A
    /* 26BF0 00225BF0 33004014 */  bnez       $v0, .L00225CC0
    /* 26BF4 00225BF4 1F00023C */   lui       $v0, (0x1F064C >> 16)
    /* 26BF8 00225BF8 1F00033C */  lui        $v1, (0x1F0010 >> 16)
    /* 26BFC 00225BFC 02000224 */  addiu      $v0, $zero, 0x2
    /* 26C00 00225C00 100062AC */  sw         $v0, (0x1F0010 & 0xFFFF)($v1)
    /* 26C04 00225C04 33000010 */  b          .L00225CD4
    /* 26C08 00225C08 1F00103C */   lui       $s0, (0x1F0BB0 >> 16)
  .L00225C0C:
    /* 26C0C 00225C0C 6E000224 */  addiu      $v0, $zero, 0x6E
    /* 26C10 00225C10 18006210 */  beq        $v1, $v0, .L00225C74
    /* 26C14 00225C14 1F00023C */   lui       $v0, (0x1F064C >> 16)
    /* 26C18 00225C18 2A000010 */  b          .L00225CC4
    /* 26C1C 00225C1C 03000324 */   addiu     $v1, $zero, 0x3
  .L00225C20:
    /* 26C20 00225C20 73000224 */  addiu      $v0, $zero, 0x73
    /* 26C24 00225C24 1D006210 */  beq        $v1, $v0, .L00225C9C
    /* 26C28 00225C28 74006228 */   slti      $v0, $v1, 0x74
    /* 26C2C 00225C2C 07004010 */  beqz       $v0, .L00225C4C
    /* 26C30 00225C30 71000224 */   addiu     $v0, $zero, 0x71
    /* 26C34 00225C34 12006210 */  beq        $v1, $v0, .L00225C80
    /* 26C38 00225C38 72000224 */   addiu     $v0, $zero, 0x72
    /* 26C3C 00225C3C 15006210 */  beq        $v1, $v0, .L00225C94
    /* 26C40 00225C40 1F00023C */   lui       $v0, (0x1F064C >> 16)
    /* 26C44 00225C44 1F000010 */  b          .L00225CC4
    /* 26C48 00225C48 03000324 */   addiu     $v1, $zero, 0x3
  .L00225C4C:
    /* 26C4C 00225C4C 74000224 */  addiu      $v0, $zero, 0x74
    /* 26C50 00225C50 17006210 */  beq        $v1, $v0, .L00225CB0
    /* 26C54 00225C54 0F270224 */   addiu     $v0, $zero, 0x270F
    /* 26C58 00225C58 19000010 */  b          .L00225CC0
    /* 26C5C 00225C5C 1F00023C */   lui       $v0, (0x1F064C >> 16)
  .L00225C60:
    /* 26C60 00225C60 1F00033C */  lui        $v1, (0x1F0010 >> 16)
    /* 26C64 00225C64 01000224 */  addiu      $v0, $zero, 0x1
    /* 26C68 00225C68 100062AC */  sw         $v0, (0x1F0010 & 0xFFFF)($v1)
    /* 26C6C 00225C6C 19000010 */  b          .L00225CD4
    /* 26C70 00225C70 1F00103C */   lui       $s0, (0x1F0BB0 >> 16)
  .L00225C74:
    /* 26C74 00225C74 100040AC */  sw         $zero, (0x1F0010 & 0xFFFF)($v0)
    /* 26C78 00225C78 16000010 */  b          .L00225CD4
    /* 26C7C 00225C7C 1F00103C */   lui       $s0, (0x1F0BB0 >> 16)
  .L00225C80:
    /* 26C80 00225C80 1F00033C */  lui        $v1, (0x1F0010 >> 16)
    /* 26C84 00225C84 05000224 */  addiu      $v0, $zero, 0x5
    /* 26C88 00225C88 100062AC */  sw         $v0, (0x1F0010 & 0xFFFF)($v1)
    /* 26C8C 00225C8C 11000010 */  b          .L00225CD4
    /* 26C90 00225C90 1F00103C */   lui       $s0, (0x1F0BB0 >> 16)
  .L00225C94:
    /* 26C94 00225C94 0B000010 */  b          .L00225CC4
    /* 26C98 00225C98 05000324 */   addiu     $v1, $zero, 0x5
  .L00225C9C:
    /* 26C9C 00225C9C 1F00033C */  lui        $v1, (0x1F0010 >> 16)
    /* 26CA0 00225CA0 03000224 */  addiu      $v0, $zero, 0x3
    /* 26CA4 00225CA4 100062AC */  sw         $v0, (0x1F0010 & 0xFFFF)($v1)
    /* 26CA8 00225CA8 0A000010 */  b          .L00225CD4
    /* 26CAC 00225CAC 1F00103C */   lui       $s0, (0x1F0BB0 >> 16)
  .L00225CB0:
    /* 26CB0 00225CB0 1F00023C */  lui        $v0, (0x1F064C >> 16)
    /* 26CB4 00225CB4 03000010 */  b          .L00225CC4
    /* 26CB8 00225CB8 04000324 */   addiu     $v1, $zero, 0x4
  .L00225CBC:
    /* 26CBC 00225CBC 1F00023C */  lui        $v0, (0x1F064C >> 16)
  .L00225CC0:
    /* 26CC0 00225CC0 03000324 */  addiu      $v1, $zero, 0x3
  .L00225CC4:
    /* 26CC4 00225CC4 480643AC */  sw         $v1, (0x1F0648 & 0xFFFF)($v0)
    /* 26CC8 00225CC8 02000424 */  addiu      $a0, $zero, 0x2
    /* 26CCC 00225CCC 4C0644AC */  sw         $a0, (0x1F064C & 0xFFFF)($v0)
    /* 26CD0 00225CD0 1F00103C */  lui        $s0, (0x1F0BB0 >> 16)
  .L00225CD4:
    /* 26CD4 00225CD4 01000224 */  addiu      $v0, $zero, 0x1
    /* 26CD8 00225CD8 440602AE */  sw         $v0, (0x1F0644 & 0xFFFF)($s0)
    /* 26CDC 00225CDC FCFE090C */  jal        VSync_WaitVblankStart
    /* 26CE0 00225CE0 00000000 */   nop
    /* 26CE4 00225CE4 CC97080C */  jal        func_00225F30
    /* 26CE8 00225CE8 00000000 */   nop
    /* 26CEC 00225CEC C00A03DE */  ld         $v1, (0x1F0AC0 & 0xFFFF)($s0)
    /* 26CF0 00225CF0 00800424 */  addiu      $a0, $zero, -0x8000
    /* 26CF4 00225CF4 B00B02DE */  ld         $v0, (0x1F0BB0 & 0xFFFF)($s0)
    /* 26CF8 00225CF8 0E000524 */  addiu      $a1, $zero, 0xE
    /* 26CFC 00225CFC 24186400 */  and        $v1, $v1, $a0
    /* 26D00 00225D00 3000BFDF */  ld         $ra, 0x30($sp)
    /* 26D04 00225D04 24104400 */  and        $v0, $v0, $a0
    /* 26D08 00225D08 25186500 */  or         $v1, $v1, $a1
    /* 26D0C 00225D0C 25104500 */  or         $v0, $v0, $a1
    /* 26D10 00225D10 C00A03FE */  sd         $v1, (0x1F0AC0 & 0xFFFF)($s0)
    /* 26D14 00225D14 B00B02FE */  sd         $v0, (0x1F0BB0 & 0xFFFF)($s0)
    /* 26D18 00225D18 2000B2DF */  ld         $s2, 0x20($sp)
    /* 26D1C 00225D1C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 26D20 00225D20 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26D24 00225D24 0800E003 */  jr         $ra
    /* 26D28 00225D28 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel clock_input_check_handler_p6_p7_tgt
