.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching clock_timezone_str_related, 0x43C

glabel clock_timezone_str_related
    /* 2DFA0 0022CFA0 C0FABD27 */  addiu      $sp, $sp, -0x540
    /* 2DFA4 0022CFA4 2005BEFF */  sd         $fp, 0x520($sp)
    /* 2DFA8 0022CFA8 1005B7FF */  sd         $s7, 0x510($sp)
    /* 2DFAC 0022CFAC 0005B6FF */  sd         $s6, 0x500($sp)
    /* 2DFB0 0022CFB0 2DB8E000 */  daddu      $s7, $a3, $zero
    /* 2DFB4 0022CFB4 C004B2FF */  sd         $s2, 0x4C0($sp)
    /* 2DFB8 0022CFB8 2DB0A000 */  daddu      $s6, $a1, $zero
    /* 2DFBC 0022CFBC A004B0FF */  sd         $s0, 0x4A0($sp)
    /* 2DFC0 0022CFC0 2D90C000 */  daddu      $s2, $a2, $zero
    /* 2DFC4 0022CFC4 3005BFFF */  sd         $ra, 0x530($sp)
    /* 2DFC8 0022CFC8 E004B4FF */  sd         $s4, 0x4E0($sp)
    /* 2DFCC 0022CFCC D004B3FF */  sd         $s3, 0x4D0($sp)
    /* 2DFD0 0022CFD0 B004B1FF */  sd         $s1, 0x4B0($sp)
    /* 2DFD4 0022CFD4 9004A4AF */  sw         $a0, 0x490($sp)
    /* 2DFD8 0022CFD8 F004B5FF */  sd         $s5, 0x4F0($sp)
    /* 2DFDC 0022CFDC BCAA080C */  jal        func_0022AAF0
    /* 2DFE0 0022CFE0 0800958C */   lw        $s5, 0x8($a0)
    /* 2DFE4 0022CFE4 4000103C */  lui        $s0, %hi(D_00404F48)
    /* 2DFE8 0022CFE8 2DF04000 */  daddu      $fp, $v0, $zero
    /* 2DFEC 0022CFEC 3420080C */  jal        thunk_config_get_osd_language
    /* 2DFF0 0022CFF0 484F1026 */   addiu     $s0, $s0, %lo(D_00404F48)
    /* 2DFF4 0022CFF4 80100200 */  sll        $v0, $v0, 2
    /* 2DFF8 0022CFF8 3800C48F */  lw         $a0, 0x38($fp)
    /* 2DFFC 0022CFFC 21105000 */  addu       $v0, $v0, $s0
    /* 2E000 0022D000 0000428C */  lw         $v0, 0x0($v0)
    /* 2E004 0022D004 05008010 */  beqz       $a0, .L0022D01C
    /* 2E008 0022D008 9404A2AF */   sw        $v0, 0x494($sp)
    /* 2E00C 0022D00C 84B0080C */  jal        func_0022C210
    /* 2E010 0022D010 00000000 */   nop
    /* 2E014 0022D014 02004014 */  bnez       $v0, .L0022D020
    /* 2E018 0022D018 3800C2AF */   sw        $v0, 0x38($fp)
  .L0022D01C:
    /* 2E01C 0022D01C A48895AF */  sw         $s5, %gp_rel(D_00370214)($gp)
  .L0022D020:
    /* 2E020 0022D020 9404A38F */  lw         $v1, 0x494($sp)
    /* 2E024 0022D024 01006224 */  addiu      $v0, $v1, 0x1
    /* 2E028 0022D028 C2270200 */  srl        $a0, $v0, 31
    /* 2E02C 0022D02C 3700033C */  lui        $v1, %hi(D_00370208)
    /* 2E030 0022D030 21104400 */  addu       $v0, $v0, $a0
    /* 2E034 0022D034 08027024 */  addiu      $s0, $v1, %lo(D_00370208)
    /* 2E038 0022D038 43100200 */  sra        $v0, $v0, 1
    /* 2E03C 0022D03C 2D20A002 */  daddu      $a0, $s5, $zero
    /* 2E040 0022D040 2318C202 */  subu       $v1, $s6, $v0
    /* 2E044 0022D044 2D880002 */  daddu      $s1, $s0, $zero
    /* 2E048 0022D048 2110C202 */  addu       $v0, $s6, $v0
    /* 2E04C 0022D04C 9804A3AF */  sw         $v1, 0x498($sp)
    /* 2E050 0022D050 02004224 */  addiu      $v0, $v0, 0x2
    /* 2E054 0022D054 1E32080C */  jal        get_timezone_info_struct
    /* 2E058 0022D058 9C04A2AF */   sw        $v0, 0x49C($sp)
    /* 2E05C 0022D05C 2D384000 */  daddu      $a3, $v0, $zero
    /* 2E060 0022D060 0500E104 */  bgez       $a3, .L0022D078
    /* 2E064 0022D064 3C000224 */   addiu     $v0, $zero, 0x3C
    /* 2E068 0022D068 3700023C */  lui        $v0, %hi(D_00370210)
    /* 2E06C 0022D06C 23380700 */  negu       $a3, $a3
    /* 2E070 0022D070 10025024 */  addiu      $s0, $v0, %lo(D_00370210)
    /* 2E074 0022D074 3C000224 */  addiu      $v0, $zero, 0x3C
  .L0022D078:
    /* 2E078 0022D078 1004B427 */  addiu      $s4, $sp, 0x410
    /* 2E07C 0022D07C 1A00E200 */  div        $zero, $a3, $v0
    /* 2E080 0022D080 01004050 */  beql       $v0, $zero, .L0022D088
    /* 2E084 0022D084 CD010000 */   break     0, 7
  .L0022D088:
    /* 2E088 0022D088 3600133C */  lui        $s3, %hi(aR050gmtSD02dR0)
    /* 2E08C 0022D08C 2D300002 */  daddu      $a2, $s0, $zero
    /* 2E090 0022D090 2D208002 */  daddu      $a0, $s4, $zero
    /* 2E094 0022D094 F0566526 */  addiu      $a1, $s3, %lo(aR050gmtSD02dR0)
    /* 2E098 0022D098 12380000 */  mflo       $a3
    /* 2E09C 0022D09C 10400000 */  mfhi       $t0
    /* 2E0A0 0022D0A0 EC720A0C */  jal        sprintf
    /* 2E0A4 0022D0A4 2D802002 */   daddu     $s0, $s1, $zero
    /* 2E0A8 0022D0A8 A488848F */  lw         $a0, %gp_rel(D_00370214)($gp)
    /* 2E0AC 0022D0AC 05008004 */  bltz       $a0, .L0022D0C4
    /* 2E0B0 0022D0B0 00000000 */   nop
    /* 2E0B4 0022D0B4 1E32080C */  jal        get_timezone_info_struct
    /* 2E0B8 0022D0B8 00000000 */   nop
    /* 2E0BC 0022D0BC 04000010 */  b          .L0022D0D0
    /* 2E0C0 0022D0C0 2D384000 */   daddu     $a3, $v0, $zero
  .L0022D0C4:
    /* 2E0C4 0022D0C4 1E32080C */  jal        get_timezone_info_struct
    /* 2E0C8 0022D0C8 2D20A002 */   daddu     $a0, $s5, $zero
    /* 2E0CC 0022D0CC 2D384000 */  daddu      $a3, $v0, $zero
  .L0022D0D0:
    /* 2E0D0 0022D0D0 0500E104 */  bgez       $a3, .L0022D0E8
    /* 2E0D4 0022D0D4 3C000224 */   addiu     $v0, $zero, 0x3C
    /* 2E0D8 0022D0D8 3700023C */  lui        $v0, %hi(D_00370210)
    /* 2E0DC 0022D0DC 23380700 */  negu       $a3, $a3
    /* 2E0E0 0022D0E0 10025024 */  addiu      $s0, $v0, %lo(D_00370210)
    /* 2E0E4 0022D0E4 3C000224 */  addiu      $v0, $zero, 0x3C
  .L0022D0E8:
    /* 2E0E8 0022D0E8 5004B127 */  addiu      $s1, $sp, 0x450
    /* 2E0EC 0022D0EC 1A00E200 */  div        $zero, $a3, $v0
    /* 2E0F0 0022D0F0 01004050 */  beql       $v0, $zero, .L0022D0F8
    /* 2E0F4 0022D0F4 CD010000 */   break     0, 7
  .L0022D0F8:
    /* 2E0F8 0022D0F8 3C000324 */  addiu      $v1, $zero, 0x3C
    /* 2E0FC 0022D0FC F0566526 */  addiu      $a1, $s3, %lo(aR050gmtSD02dR0)
    /* 2E100 0022D100 2D300002 */  daddu      $a2, $s0, $zero
    /* 2E104 0022D104 12380000 */  mflo       $a3
    /* 2E108 0022D108 10400000 */  mfhi       $t0
    /* 2E10C 0022D10C EC720A0C */  jal        sprintf
    /* 2E110 0022D110 2D202002 */   daddu     $a0, $s1, $zero
    /* 2E114 0022D114 944F080C */  jal        func_00213E50
    /* 2E118 0022D118 3700103C */   lui       $s0, %hi(aSS_3)
    /* 2E11C 0022D11C 03000324 */  addiu      $v1, $zero, 0x3
    /* 2E120 0022D120 1A004300 */  div        $zero, $v0, $v1
    /* 2E124 0022D124 18021026 */  addiu      $s0, $s0, %lo(aSS_3)
    /* 2E128 0022D128 01006050 */  beql       $v1, $zero, .L0022D130
    /* 2E12C 0022D12C CD010000 */   break     0, 7
  .L0022D130:
    /* 2E130 0022D130 2D20A002 */  daddu      $a0, $s5, $zero
    /* 2E134 0022D134 12100000 */  mflo       $v0
    /* 2E138 0022D138 F231080C */  jal        get_timezone_name_index
    /* 2E13C 0022D13C 23904202 */   subu      $s2, $s2, $v0
    /* 2E140 0022D140 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2E144 0022D144 2D204000 */   daddu     $a0, $v0, $zero
    /* 2E148 0022D148 1004A627 */  addiu      $a2, $sp, 0x410
    /* 2E14C 0022D14C 2D384000 */  daddu      $a3, $v0, $zero
    /* 2E150 0022D150 1000A427 */  addiu      $a0, $sp, 0x10
    /* 2E154 0022D154 EC720A0C */  jal        sprintf
    /* 2E158 0022D158 2D280002 */   daddu     $a1, $s0, $zero
    /* 2E15C 0022D15C A488848F */  lw         $a0, %gp_rel(D_00370214)($gp)
    /* 2E160 0022D160 F231080C */  jal        get_timezone_name_index
    /* 2E164 0022D164 1002B327 */   addiu     $s3, $sp, 0x210
    /* 2E168 0022D168 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2E16C 0022D16C 2D204000 */   daddu     $a0, $v0, $zero
    /* 2E170 0022D170 2D280002 */  daddu      $a1, $s0, $zero
    /* 2E174 0022D174 2D302002 */  daddu      $a2, $s1, $zero
    /* 2E178 0022D178 2D384000 */  daddu      $a3, $v0, $zero
    /* 2E17C 0022D17C EC720A0C */  jal        sprintf
    /* 2E180 0022D180 2D206002 */   daddu     $a0, $s3, $zero
    /* 2E184 0022D184 9088838F */  lw         $v1, %gp_rel(D_00370200)($gp)
    /* 2E188 0022D188 12006014 */  bnez       $v1, .L0022D1D4
    /* 2E18C 0022D18C 2B00023C */   lui       $v0, %hi(D_002B2550)
    /* 2E190 0022D190 2B000A3C */  lui        $t2, %hi(D_002B2540)
    /* 2E194 0022D194 3D000224 */  addiu      $v0, $zero, 0x3D
    /* 2E198 0022D198 40254A25 */  addiu      $t2, $t2, %lo(D_002B2540)
    /* 2E19C 0022D19C 0800A2AF */  sw         $v0, 0x8($sp)
    /* 2E1A0 0022D1A0 0000AAAF */  sw         $t2, 0x0($sp)
    /* 2E1A4 0022D1A4 2D284002 */  daddu      $a1, $s2, $zero
    /* 2E1A8 0022D1A8 9404A68F */  lw         $a2, 0x494($sp)
    /* 2E1AC 0022D1AC 2D586002 */  daddu      $t3, $s3, $zero
    /* 2E1B0 0022D1B0 3800C88F */  lw         $t0, 0x38($fp)
    /* 2E1B4 0022D1B4 2D20C002 */  daddu      $a0, $s6, $zero
    /* 2E1B8 0022D1B8 2D38E002 */  daddu      $a3, $s7, $zero
    /* 2E1BC 0022D1BC 14B1080C */  jal        func_0022C450
    /* 2E1C0 0022D1C0 1000A927 */   addiu     $t1, $sp, 0x10
    /* 2E1C4 0022D1C4 944F080C */  jal        func_00213E50
    /* 2E1C8 0022D1C8 00000000 */   nop
    /* 2E1CC 0022D1CC 25000010 */  b          .L0022D264
    /* 2E1D0 0022D1D0 21904202 */   addu      $s2, $s2, $v0
  .L0022D1D4:
    /* 2E1D4 0022D1D4 2D38E002 */  daddu      $a3, $s7, $zero
    /* 2E1D8 0022D1D8 50255124 */  addiu      $s1, $v0, %lo(D_002B2550)
    /* 2E1DC 0022D1DC 5025448C */  lw         $a0, %lo(D_002B2550)($v0)
    /* 2E1E0 0022D1E0 0400258E */  lw         $a1, 0x4($s1)
    /* 2E1E4 0022D1E4 1C4A080C */  jal        Font_SetColor
    /* 2E1E8 0022D1E8 0800268E */   lw        $a2, 0x8($s1)
    /* 2E1EC 0022D1EC 3700103C */  lui        $s0, %hi(aO005_1)
    /* 2E1F0 0022D1F0 20021026 */  addiu      $s0, $s0, %lo(aO005_1)
    /* 2E1F4 0022D1F4 BA4F080C */  jal        func_00213EE8
    /* 2E1F8 0022D1F8 2D200002 */   daddu     $a0, $s0, $zero
    /* 2E1FC 0022D1FC 9804A38F */  lw         $v1, 0x498($sp)
    /* 2E200 0022D200 2D284002 */  daddu      $a1, $s2, $zero
    /* 2E204 0022D204 F0FF6424 */  addiu      $a0, $v1, -0x10
    /* 2E208 0022D208 A449080C */  jal        Font_SetLocate
    /* 2E20C 0022D20C 23208200 */   subu      $a0, $a0, $v0
    /* 2E210 0022D210 904F080C */  jal        j_Font_PutsPackets
    /* 2E214 0022D214 2D200002 */   daddu     $a0, $s0, $zero
    /* 2E218 0022D218 9C04A28F */  lw         $v0, 0x49C($sp)
    /* 2E21C 0022D21C 2D284002 */  daddu      $a1, $s2, $zero
    /* 2E220 0022D220 A449080C */  jal        Font_SetLocate
    /* 2E224 0022D224 10004424 */   addiu     $a0, $v0, 0x10
    /* 2E228 0022D228 3700043C */  lui        $a0, %hi(aO006_1)
    /* 2E22C 0022D22C 904F080C */  jal        j_Font_PutsPackets
    /* 2E230 0022D230 28028424 */   addiu     $a0, $a0, %lo(aO006_1)
    /* 2E234 0022D234 9004A38F */  lw         $v1, 0x490($sp)
    /* 2E238 0022D238 F231080C */  jal        get_timezone_name_index
    /* 2E23C 0022D23C 0800648C */   lw        $a0, 0x8($v1)
    /* 2E240 0022D240 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2E244 0022D244 2D204000 */   daddu     $a0, $v0, $zero
    /* 2E248 0022D248 2D302002 */  daddu      $a2, $s1, $zero
    /* 2E24C 0022D24C 2D408002 */  daddu      $t0, $s4, $zero
    /* 2E250 0022D250 2D484000 */  daddu      $t1, $v0, $zero
    /* 2E254 0022D254 2D20C002 */  daddu      $a0, $s6, $zero
    /* 2E258 0022D258 2D284002 */  daddu      $a1, $s2, $zero
    /* 2E25C 0022D25C 289B080C */  jal        func_00226CA0
    /* 2E260 0022D260 2D38E002 */   daddu     $a3, $s7, $zero
  .L0022D264:
    /* 2E264 0022D264 944F080C */  jal        func_00213E50
    /* 2E268 0022D268 00000000 */   nop
    /* 2E26C 0022D26C 9004A38F */  lw         $v1, 0x490($sp)
    /* 2E270 0022D270 21904202 */  addu       $s2, $s2, $v0
    /* 2E274 0022D274 DA31080C */  jal        func_0020C768
    /* 2E278 0022D278 0800648C */   lw        $a0, 0x8($v1)
    /* 2E27C 0022D27C 0200422C */  sltiu      $v0, $v0, 0x2
    /* 2E280 0022D280 4B004014 */  bnez       $v0, .L0022D3B0
    /* 2E284 0022D284 3005BFDF */   ld        $ra, 0x530($sp)
    /* 2E288 0022D288 944F080C */  jal        func_00213E50
    /* 2E28C 0022D28C 00000000 */   nop
    /* 2E290 0022D290 05000324 */  addiu      $v1, $zero, 0x5
    /* 2E294 0022D294 01000524 */  addiu      $a1, $zero, 0x1
    /* 2E298 0022D298 1A004300 */  div        $zero, $v0, $v1
    /* 2E29C 0022D29C 01006050 */  beql       $v1, $zero, .L0022D2A4
    /* 2E2A0 0022D2A0 CD010000 */   break     0, 7
  .L0022D2A4:
    /* 2E2A4 0022D2A4 9088848F */  lw         $a0, %gp_rel(D_00370200)($gp)
    /* 2E2A8 0022D2A8 12100000 */  mflo       $v0
    /* 2E2AC 0022D2AC 19008514 */  bne        $a0, $a1, .L0022D314
    /* 2E2B0 0022D2B0 23904202 */   subu      $s2, $s2, $v0
    /* 2E2B4 0022D2B4 EA31080C */  jal        func_0020C7A8
    /* 2E2B8 0022D2B8 2D20A002 */   daddu     $a0, $s5, $zero
    /* 2E2BC 0022D2BC 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2E2C0 0022D2C0 2D204000 */   daddu     $a0, $v0, $zero
    /* 2E2C4 0022D2C4 A488848F */  lw         $a0, %gp_rel(D_00370214)($gp)
    /* 2E2C8 0022D2C8 EA31080C */  jal        func_0020C7A8
    /* 2E2CC 0022D2CC 2D804000 */   daddu     $s0, $v0, $zero
    /* 2E2D0 0022D2D0 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2E2D4 0022D2D4 2D204000 */   daddu     $a0, $v0, $zero
    /* 2E2D8 0022D2D8 2B000A3C */  lui        $t2, %hi(D_002B2540)
    /* 2E2DC 0022D2DC 3D000324 */  addiu      $v1, $zero, 0x3D
    /* 2E2E0 0022D2E0 40254A25 */  addiu      $t2, $t2, %lo(D_002B2540)
    /* 2E2E4 0022D2E4 0800A3AF */  sw         $v1, 0x8($sp)
    /* 2E2E8 0022D2E8 0000AAAF */  sw         $t2, 0x0($sp)
    /* 2E2EC 0022D2EC 2D20C002 */  daddu      $a0, $s6, $zero
    /* 2E2F0 0022D2F0 9404A68F */  lw         $a2, 0x494($sp)
    /* 2E2F4 0022D2F4 2D284002 */  daddu      $a1, $s2, $zero
    /* 2E2F8 0022D2F8 3800C88F */  lw         $t0, 0x38($fp)
    /* 2E2FC 0022D2FC 2D38E002 */  daddu      $a3, $s7, $zero
    /* 2E300 0022D300 2D480002 */  daddu      $t1, $s0, $zero
    /* 2E304 0022D304 14B1080C */  jal        func_0022C450
    /* 2E308 0022D308 2D584000 */   daddu     $t3, $v0, $zero
    /* 2E30C 0022D30C 25000010 */  b          .L0022D3A4
    /* 2E310 0022D310 00000000 */   nop
  .L0022D314:
    /* 2E314 0022D314 2B00023C */  lui        $v0, %hi(D_002B2550)
    /* 2E318 0022D318 2D38E002 */  daddu      $a3, $s7, $zero
    /* 2E31C 0022D31C 50255124 */  addiu      $s1, $v0, %lo(D_002B2550)
    /* 2E320 0022D320 5025448C */  lw         $a0, %lo(D_002B2550)($v0)
    /* 2E324 0022D324 0400258E */  lw         $a1, 0x4($s1)
    /* 2E328 0022D328 1C4A080C */  jal        Font_SetColor
    /* 2E32C 0022D32C 0800268E */   lw        $a2, 0x8($s1)
    /* 2E330 0022D330 3700103C */  lui        $s0, %hi(aO005_1)
    /* 2E334 0022D334 20021026 */  addiu      $s0, $s0, %lo(aO005_1)
    /* 2E338 0022D338 BA4F080C */  jal        func_00213EE8
    /* 2E33C 0022D33C 2D200002 */   daddu     $a0, $s0, $zero
    /* 2E340 0022D340 9804A38F */  lw         $v1, 0x498($sp)
    /* 2E344 0022D344 2D284002 */  daddu      $a1, $s2, $zero
    /* 2E348 0022D348 F0FF6424 */  addiu      $a0, $v1, -0x10
    /* 2E34C 0022D34C A449080C */  jal        Font_SetLocate
    /* 2E350 0022D350 23208200 */   subu      $a0, $a0, $v0
    /* 2E354 0022D354 904F080C */  jal        j_Font_PutsPackets
    /* 2E358 0022D358 2D200002 */   daddu     $a0, $s0, $zero
    /* 2E35C 0022D35C 9C04A28F */  lw         $v0, 0x49C($sp)
    /* 2E360 0022D360 2D284002 */  daddu      $a1, $s2, $zero
    /* 2E364 0022D364 A449080C */  jal        Font_SetLocate
    /* 2E368 0022D368 10004424 */   addiu     $a0, $v0, 0x10
    /* 2E36C 0022D36C 3700043C */  lui        $a0, %hi(aO006_1)
    /* 2E370 0022D370 904F080C */  jal        j_Font_PutsPackets
    /* 2E374 0022D374 28028424 */   addiu     $a0, $a0, %lo(aO006_1)
    /* 2E378 0022D378 9004A38F */  lw         $v1, 0x490($sp)
    /* 2E37C 0022D37C EA31080C */  jal        func_0020C7A8
    /* 2E380 0022D380 0800648C */   lw        $a0, 0x8($v1)
    /* 2E384 0022D384 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2E388 0022D388 2D204000 */   daddu     $a0, $v0, $zero
    /* 2E38C 0022D38C 2D20C002 */  daddu      $a0, $s6, $zero
    /* 2E390 0022D390 2D284002 */  daddu      $a1, $s2, $zero
    /* 2E394 0022D394 2D302002 */  daddu      $a2, $s1, $zero
    /* 2E398 0022D398 2D38E002 */  daddu      $a3, $s7, $zero
    /* 2E39C 0022D39C 009B080C */  jal        draw_menu_item
    /* 2E3A0 0022D3A0 2D404000 */   daddu     $t0, $v0, $zero
  .L0022D3A4:
    /* 2E3A4 0022D3A4 944F080C */  jal        func_00213E50
    /* 2E3A8 0022D3A8 00000000 */   nop
    /* 2E3AC 0022D3AC 3005BFDF */  ld         $ra, 0x530($sp)
  .L0022D3B0:
    /* 2E3B0 0022D3B0 2005BEDF */  ld         $fp, 0x520($sp)
    /* 2E3B4 0022D3B4 1005B7DF */  ld         $s7, 0x510($sp)
    /* 2E3B8 0022D3B8 0005B6DF */  ld         $s6, 0x500($sp)
    /* 2E3BC 0022D3BC F004B5DF */  ld         $s5, 0x4F0($sp)
    /* 2E3C0 0022D3C0 E004B4DF */  ld         $s4, 0x4E0($sp)
    /* 2E3C4 0022D3C4 D004B3DF */  ld         $s3, 0x4D0($sp)
    /* 2E3C8 0022D3C8 C004B2DF */  ld         $s2, 0x4C0($sp)
    /* 2E3CC 0022D3CC B004B1DF */  ld         $s1, 0x4B0($sp)
    /* 2E3D0 0022D3D0 A004B0DF */  ld         $s0, 0x4A0($sp)
    /* 2E3D4 0022D3D4 0800E003 */  jr         $ra
    /* 2E3D8 0022D3D8 4005BD27 */   addiu     $sp, $sp, 0x540
endlabel clock_timezone_str_related
