.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching clock_config_get_initial_value, 0x28

glabel clock_config_get_initial_value
    /* 29448 00228448 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 2944C 0022844C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 29450 00228450 F0A0080C */  jal        func_002283C0
    /* 29454 00228454 00000000 */   nop
    /* 29458 00228458 2B00023C */  lui        $v0, %hi(D_002B2E1C)
    /* 2945C 0022845C 0000BFDF */  ld         $ra, 0x0($sp)
    /* 29460 00228460 348880AF */  sw         $zero, %gp_rel(D_003701A4)($gp)
    /* 29464 00228464 1C2E40AC */  sw         $zero, %lo(D_002B2E1C)($v0)
    /* 29468 00228468 0800E003 */  jr         $ra
    /* 2946C 0022846C 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel clock_config_get_initial_value
