.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching do_show_version_info, 0x4CC

glabel do_show_version_info
    /* 2AD08 00229D08 20FFBD27 */  addiu      $sp, $sp, -0xE0
    /* 2AD0C 00229D0C 4000023C */  lui        $v0, %hi(D_00400B10)
    /* 2AD10 00229D10 5000B1FF */  sd         $s1, 0x50($sp)
    /* 2AD14 00229D14 2D280000 */  daddu      $a1, $zero, $zero
    /* 2AD18 00229D18 D000BFFF */  sd         $ra, 0xD0($sp)
    /* 2AD1C 00229D1C 100B4424 */  addiu      $a0, $v0, %lo(D_00400B10)
    /* 2AD20 00229D20 C000BEFF */  sd         $fp, 0xC0($sp)
    /* 2AD24 00229D24 CE130624 */  addiu      $a2, $zero, 0x13CE
    /* 2AD28 00229D28 B000B7FF */  sd         $s7, 0xB0($sp)
    /* 2AD2C 00229D2C 2D880000 */  daddu      $s1, $zero, $zero
    /* 2AD30 00229D30 A000B6FF */  sd         $s6, 0xA0($sp)
    /* 2AD34 00229D34 9000B5FF */  sd         $s5, 0x90($sp)
    /* 2AD38 00229D38 8000B4FF */  sd         $s4, 0x80($sp)
    /* 2AD3C 00229D3C 7000B3FF */  sd         $s3, 0x70($sp)
    /* 2AD40 00229D40 6000B2FF */  sd         $s2, 0x60($sp)
    /* 2AD44 00229D44 5E710A0C */  jal        memset
    /* 2AD48 00229D48 4000B0FF */   sd        $s0, 0x40($sp)
    /* 2AD4C 00229D4C 2B00033C */  lui        $v1, %hi(D_002B2FE8)
    /* 2AD50 00229D50 1F00023C */  lui        $v0, (0x1F1298 >> 16)
    /* 2AD54 00229D54 9812428C */  lw         $v0, (0x1F1298 & 0xFFFF)($v0)
    /* 2AD58 00229D58 E82F6424 */  addiu      $a0, $v1, %lo(D_002B2FE8)
    /* 2AD5C 00229D5C 0000A0AF */  sw         $zero, 0x0($sp)
    /* 2AD60 00229D60 2D500000 */  daddu      $t2, $zero, $zero
    /* 2AD64 00229D64 100080AC */  sw         $zero, 0x10($a0)
    /* 2AD68 00229D68 FA004010 */  beqz       $v0, .L0022A154
    /* 2AD6C 00229D6C 140080AC */   sw        $zero, 0x14($a0)
    /* 2AD70 00229D70 1F00053C */  lui        $a1, (0x1F1298 >> 16)
    /* 2AD74 00229D74 0400A5AF */  sw         $a1, 0x4($sp)
    /* 2AD78 00229D78 9812A534 */  ori        $a1, $a1, (0x1F1298 & 0xFFFF)
    /* 2AD7C 00229D7C 0400A5AF */  sw         $a1, 0x4($sp)
    /* 2AD80 00229D80 0C000624 */  addiu      $a2, $zero, 0xC
    /* 2AD84 00229D84 00000000 */  nop
  .L00229D88:
    /* 2AD88 00229D88 1F00023C */  lui        $v0, (0x1F12A0 >> 16)
    /* 2AD8C 00229D8C 18802602 */  mult       $s0, $s1, $a2
    /* 2AD90 00229D90 A0124234 */  ori        $v0, $v0, (0x1F12A0 & 0xFFFF)
    /* 2AD94 00229D94 FFFF0524 */  addiu      $a1, $zero, -0x1
    /* 2AD98 00229D98 2D300000 */  daddu      $a2, $zero, $zero
    /* 2AD9C 00229D9C 2D380000 */  daddu      $a3, $zero, $zero
    /* 2ADA0 00229DA0 21100202 */  addu       $v0, $s0, $v0
    /* 2ADA4 00229DA4 0000578C */  lw         $s7, 0x0($v0)
    /* 2ADA8 00229DA8 3000AA7F */  sq         $t2, 0x30($sp)
    /* 2ADAC 00229DAC AA21080C */  jal        func_002086A8
    /* 2ADB0 00229DB0 2D20E002 */   daddu     $a0, $s7, $zero
    /* 2ADB4 00229DB4 2DF04000 */  daddu      $fp, $v0, $zero
    /* 2ADB8 00229DB8 06000224 */  addiu      $v0, $zero, 0x6
    /* 2ADBC 00229DBC 0400E216 */  bne        $s7, $v0, .L00229DD0
    /* 2ADC0 00229DC0 3000AA7B */   lq        $t2, 0x30($sp)
    /* 2ADC4 00229DC4 2B00023C */  lui        $v0, %hi(D_002B2FE8)
    /* 2ADC8 00229DC8 E82F4224 */  addiu      $v0, $v0, %lo(D_002B2FE8)
    /* 2ADCC 00229DCC 100051AC */  sw         $s1, 0x10($v0)
  .L00229DD0:
    /* 2ADD0 00229DD0 0400A68F */  lw         $a2, 0x4($sp)
    /* 2ADD4 00229DD4 1F00033C */  lui        $v1, (0x1F129C >> 16)
    /* 2ADD8 00229DD8 2B00043C */  lui        $a0, %hi(D_002B2FE8)
    /* 2ADDC 00229DDC 9C126334 */  ori        $v1, $v1, (0x1F129C & 0xFFFF)
    /* 2ADE0 00229DE0 E82F8424 */  addiu      $a0, $a0, %lo(D_002B2FE8)
    /* 2ADE4 00229DE4 21100602 */  addu       $v0, $s0, $a2
    /* 2ADE8 00229DE8 0000488C */  lw         $t0, 0x0($v0)
    /* 2ADEC 00229DEC 21180302 */  addu       $v1, $s0, $v1
    /* 2ADF0 00229DF0 0400858C */  lw         $a1, 0x4($a0)
    /* 2ADF4 00229DF4 00111100 */  sll        $v0, $s1, 4
    /* 2ADF8 00229DF8 0000648C */  lw         $a0, 0x0($v1)
    /* 2ADFC 00229DFC 21104500 */  addu       $v0, $v0, $a1
    /* 2AE00 00229E00 040044AC */  sw         $a0, 0x4($v0)
    /* 2AE04 00229E04 08005EAC */  sw         $fp, 0x8($v0)
    /* 2AE08 00229E08 000048AC */  sw         $t0, 0x0($v0)
    /* 2AE0C 00229E0C C500C01B */  blez       $fp, .L0022A124
    /* 2AE10 00229E10 0C0057AC */   sw        $s7, 0xC($v0)
    /* 2AE14 00229E14 54000224 */  addiu      $v0, $zero, 0x54
    /* 2AE18 00229E18 4000033C */  lui        $v1, %hi(D_00404370)
    /* 2AE1C 00229E1C 18302202 */  mult       $a2, $s1, $v0
    /* 2AE20 00229E20 38000424 */  addiu      $a0, $zero, 0x38
    /* 2AE24 00229E24 4000023C */  lui        $v0, %hi(D_00403CE0)
    /* 2AE28 00229E28 70436724 */  addiu      $a3, $v1, %lo(D_00404370)
    /* 2AE2C 00229E2C E03C4224 */  addiu      $v0, $v0, %lo(D_00403CE0)
    /* 2AE30 00229E30 1000E324 */  addiu      $v1, $a3, 0x10
    /* 2AE34 00229E34 13004000 */  mtlo       $v0
    /* 2AE38 00229E38 0000A28F */  lw         $v0, 0x0($sp)
    /* 2AE3C 00229E3C 00284470 */  madd       $a1, $v0, $a0
    /* 2AE40 00229E40 2110C700 */  addu       $v0, $a2, $a3
    /* 2AE44 00229E44 2120E600 */  addu       $a0, $a3, $a2
    /* 2AE48 00229E48 000048AC */  sw         $t0, 0x0($v0)
    /* 2AE4C 00229E4C 08009EAC */  sw         $fp, 0x8($a0)
    /* 2AE50 00229E50 2140C300 */  addu       $t0, $a2, $v1
    /* 2AE54 00229E54 2D188000 */  daddu      $v1, $a0, $zero
    /* 2AE58 00229E58 0000028D */  lw         $v0, 0x0($t0)
    /* 2AE5C 00229E5C 2A105E00 */  slt        $v0, $v0, $fp
    /* 2AE60 00229E60 04004014 */  bnez       $v0, .L00229E74
    /* 2AE64 00229E64 040065AC */   sw        $a1, 0x4($v1)
    /* 2AE68 00229E68 FFFFC227 */  addiu      $v0, $fp, -0x1
    /* 2AE6C 00229E6C 000002AD */  sw         $v0, 0x0($t0)
    /* 2AE70 00229E70 140062AC */  sw         $v0, 0x14($v1)
  .L00229E74:
    /* 2AE74 00229E74 A300C01B */  blez       $fp, .L0022A104
    /* 2AE78 00229E78 2DA80000 */   daddu     $s5, $zero, $zero
    /* 2AE7C 00229E7C 0000A38F */  lw         $v1, 0x0($sp)
    /* 2AE80 00229E80 01003126 */  addiu      $s1, $s1, 0x1
    /* 2AE84 00229E84 0800B1AF */  sw         $s1, 0x8($sp)
    /* 2AE88 00229E88 21187E00 */  addu       $v1, $v1, $fp
    /* 2AE8C 00229E8C 0C00A3AF */  sw         $v1, 0xC($sp)
  .L00229E90:
    /* 2AE90 00229E90 0000A48F */  lw         $a0, 0x0($sp)
    /* 2AE94 00229E94 A9000624 */  addiu      $a2, $zero, 0xA9
    /* 2AE98 00229E98 4000053C */  lui        $a1, %hi(D_00400B10)
    /* 2AE9C 00229E9C 3000AA7F */  sq         $t2, 0x30($sp)
    /* 2AEA0 00229EA0 21B09500 */  addu       $s6, $a0, $s5
    /* 2AEA4 00229EA4 100BA224 */  addiu      $v0, $a1, %lo(D_00400B10)
    /* 2AEA8 00229EA8 1880C602 */  mult       $s0, $s6, $a2
    /* 2AEAC 00229EAC 2D20E002 */  daddu      $a0, $s7, $zero
    /* 2AEB0 00229EB0 2D28A002 */  daddu      $a1, $s5, $zero
    /* 2AEB4 00229EB4 FFFF0624 */  addiu      $a2, $zero, -0x1
    /* 2AEB8 00229EB8 21800202 */  addu       $s0, $s0, $v0
    /* 2AEBC 00229EBC AA21080C */  jal        func_002086A8
    /* 2AEC0 00229EC0 2D380002 */   daddu     $a3, $s0, $zero
    /* 2AEC4 00229EC4 2DA04000 */  daddu      $s4, $v0, $zero
    /* 2AEC8 00229EC8 3000AA7B */  lq         $t2, 0x30($sp)
    /* 2AECC 00229ECC 38000224 */  addiu      $v0, $zero, 0x38
    /* 2AED0 00229ED0 4000053C */  lui        $a1, %hi(D_00401EE0)
    /* 2AED4 00229ED4 1838C202 */  mult       $a3, $s6, $v0
    /* 2AED8 00229ED8 4000033C */  lui        $v1, %hi(D_00403CE0)
    /* 2AEDC 00229EDC E01EA524 */  addiu      $a1, $a1, %lo(D_00401EE0)
    /* 2AEE0 00229EE0 40210A00 */  sll        $a0, $t2, 5
    /* 2AEE4 00229EE4 E03C6224 */  addiu      $v0, $v1, %lo(D_00403CE0)
    /* 2AEE8 00229EE8 21208500 */  addu       $a0, $a0, $a1
    /* 2AEEC 00229EEC 0200862A */  slti       $a2, $s4, 0x2
    /* 2AEF0 00229EF0 2118E200 */  addu       $v1, $a3, $v0
    /* 2AEF4 00229EF4 21284700 */  addu       $a1, $v0, $a3
    /* 2AEF8 00229EF8 000070AC */  sw         $s0, 0x0($v1)
    /* 2AEFC 00229EFC 2D10A000 */  daddu      $v0, $a1, $zero
    /* 2AF00 00229F00 100044AC */  sw         $a0, 0x10($v0)
    /* 2AF04 00229F04 0800C014 */  bnez       $a2, .L00229F28
    /* 2AF08 00229F08 0400B4AC */   sw        $s4, 0x4($a1)
    /* 2AF0C 00229F0C 4000063C */  lui        $a2, %hi(D_00403CF4)
    /* 2AF10 00229F10 2300033C */  lui        $v1, %hi(D_00229978)
    /* 2AF14 00229F14 F43CC624 */  addiu      $a2, $a2, %lo(D_00403CF4)
    /* 2AF18 00229F18 78996324 */  addiu      $v1, $v1, %lo(D_00229978)
    /* 2AF1C 00229F1C 2110E600 */  addu       $v0, $a3, $a2
    /* 2AF20 00229F20 05000010 */  b          .L00229F38
    /* 2AF24 00229F24 000043AC */   sw        $v1, 0x0($v0)
  .L00229F28:
    /* 2AF28 00229F28 4000043C */  lui        $a0, %hi(D_00403CF4)
    /* 2AF2C 00229F2C F43C8424 */  addiu      $a0, $a0, %lo(D_00403CF4)
    /* 2AF30 00229F30 2110E400 */  addu       $v0, $a3, $a0
    /* 2AF34 00229F34 000040AC */  sw         $zero, 0x0($v0)
  .L00229F38:
    /* 2AF38 00229F38 38000524 */  addiu      $a1, $zero, 0x38
    /* 2AF3C 00229F3C 2300063C */  lui        $a2, %hi(D_00229A18)
    /* 2AF40 00229F40 1880C502 */  mult       $s0, $s6, $a1
    /* 2AF44 00229F44 2300023C */  lui        $v0, %hi(D_00229A90)
    /* 2AF48 00229F48 189AC524 */  addiu      $a1, $a2, %lo(D_00229A18)
    /* 2AF4C 00229F4C 4000043C */  lui        $a0, %hi(D_00403CE0)
    /* 2AF50 00229F50 909A4624 */  addiu      $a2, $v0, %lo(D_00229A90)
    /* 2AF54 00229F54 2300033C */  lui        $v1, %hi(nullsub_13)
    /* 2AF58 00229F58 E03C8424 */  addiu      $a0, $a0, %lo(D_00403CE0)
    /* 2AF5C 00229F5C 009D6724 */  addiu      $a3, $v1, %lo(nullsub_13)
    /* 2AF60 00229F60 21109000 */  addu       $v0, $a0, $s0
    /* 2AF64 00229F64 4000033C */  lui        $v1, %hi(D_00403CE0)
    /* 2AF68 00229F68 180045AC */  sw         $a1, 0x18($v0)
    /* 2AF6C 00229F6C E03C6324 */  addiu      $v1, $v1, %lo(D_00403CE0)
    /* 2AF70 00229F70 4000053C */  lui        $a1, %hi(D_00403D04)
    /* 2AF74 00229F74 21207000 */  addu       $a0, $v1, $s0
    /* 2AF78 00229F78 043DA524 */  addiu      $a1, $a1, %lo(D_00403D04)
    /* 2AF7C 00229F7C 1C0086AC */  sw         $a2, 0x1C($a0)
    /* 2AF80 00229F80 21180502 */  addu       $v1, $s0, $a1
    /* 2AF84 00229F84 0D00E016 */  bnez       $s7, .L00229FBC
    /* 2AF88 00229F88 000067AC */   sw        $a3, 0x0($v1)
    /* 2AF8C 00229F8C 4000033C */  lui        $v1, %hi(D_00403CEC)
    /* 2AF90 00229F90 4000063C */  lui        $a2, %hi(D_00403D00)
    /* 2AF94 00229F94 EC3C6324 */  addiu      $v1, $v1, %lo(D_00403CEC)
    /* 2AF98 00229F98 2300023C */  lui        $v0, %hi(clock_config_change_cb_diagnosis)
    /* 2AF9C 00229F9C 21200302 */  addu       $a0, $s0, $v1
    /* 2AFA0 00229FA0 003DC624 */  addiu      $a2, $a2, %lo(D_00403D00)
    /* 2AFA4 00229FA4 21280602 */  addu       $a1, $s0, $a2
    /* 2AFA8 00229FA8 509C4224 */  addiu      $v0, $v0, %lo(clock_config_change_cb_diagnosis)
    /* 2AFAC 00229FAC 04000324 */  addiu      $v1, $zero, 0x4
    /* 2AFB0 00229FB0 0000A2AC */  sw         $v0, 0x0($a1)
    /* 2AFB4 00229FB4 22000010 */  b          .L0022A040
    /* 2AFB8 00229FB8 000083AC */   sw        $v1, 0x0($a0)
  .L00229FBC:
    /* 2AFBC 00229FBC 2D20E002 */  daddu      $a0, $s7, $zero
    /* 2AFC0 00229FC0 2D28A002 */  daddu      $a1, $s5, $zero
    /* 2AFC4 00229FC4 FEFF0624 */  addiu      $a2, $zero, -0x2
    /* 2AFC8 00229FC8 2D380000 */  daddu      $a3, $zero, $zero
    /* 2AFCC 00229FCC AA21080C */  jal        func_002086A8
    /* 2AFD0 00229FD0 3000AA7F */   sq        $t2, 0x30($sp)
    /* 2AFD4 00229FD4 2D184000 */  daddu      $v1, $v0, $zero
    /* 2AFD8 00229FD8 07000224 */  addiu      $v0, $zero, 0x7
    /* 2AFDC 00229FDC 0D00E216 */  bne        $s7, $v0, .L0022A014
    /* 2AFE0 00229FE0 3000AA7B */   lq        $t2, 0x30($sp)
    /* 2AFE4 00229FE4 4000043C */  lui        $a0, %hi(D_00403CEC)
    /* 2AFE8 00229FE8 4000063C */  lui        $a2, %hi(D_00403D00)
    /* 2AFEC 00229FEC EC3C8424 */  addiu      $a0, $a0, %lo(D_00403CEC)
    /* 2AFF0 00229FF0 2300023C */  lui        $v0, %hi(clock_config_change_cb_dvdp_reset_progressive)
    /* 2AFF4 00229FF4 21280402 */  addu       $a1, $s0, $a0
    /* 2AFF8 00229FF8 003DC624 */  addiu      $a2, $a2, %lo(D_00403D00)
    /* 2AFFC 00229FFC D89C4224 */  addiu      $v0, $v0, %lo(clock_config_change_cb_dvdp_reset_progressive)
    /* 2B000 0022A000 21180602 */  addu       $v1, $s0, $a2
    /* 2B004 0022A004 15000424 */  addiu      $a0, $zero, 0x15
    /* 2B008 0022A008 000062AC */  sw         $v0, 0x0($v1)
    /* 2B00C 0022A00C 0C000010 */  b          .L0022A040
    /* 2B010 0022A010 0000A4AC */   sw        $a0, 0x0($a1)
  .L0022A014:
    /* 2B014 0022A014 4000043C */  lui        $a0, %hi(D_00403CEC)
    /* 2B018 0022A018 4000063C */  lui        $a2, %hi(D_00403D00)
    /* 2B01C 0022A01C EC3C8424 */  addiu      $a0, $a0, %lo(D_00403CEC)
    /* 2B020 0022A020 2300023C */  lui        $v0, %hi(clock_config_change_cb_ps1drv)
    /* 2B024 0022A024 21280402 */  addu       $a1, $s0, $a0
    /* 2B028 0022A028 003DC624 */  addiu      $a2, $a2, %lo(D_00403D00)
    /* 2B02C 0022A02C F09B4224 */  addiu      $v0, $v0, %lo(clock_config_change_cb_ps1drv)
    /* 2B030 0022A030 1E006324 */  addiu      $v1, $v1, 0x1E
    /* 2B034 0022A034 21200602 */  addu       $a0, $s0, $a2
    /* 2B038 0022A038 0000A3AC */  sw         $v1, 0x0($a1)
    /* 2B03C 0022A03C 000082AC */  sw         $v0, 0x0($a0)
  .L0022A040:
    /* 2B040 0022A040 2800801A */  blez       $s4, .L0022A0E4
    /* 2B044 0022A044 2D880000 */   daddu     $s1, $zero, $zero
    /* 2B048 0022A048 4000093C */  lui        $t1, %hi(D_400B31)
    /* 2B04C 0022A04C 2B00083C */  lui        $t0, (0x2B0000 >> 16)
    /* 2B050 0022A050 21985401 */  addu       $s3, $t2, $s4
    /* 2B054 0022A054 0100B226 */  addiu      $s2, $s5, 0x1
  .L0022A058:
    /* 2B058 0022A058 A9000224 */  addiu      $v0, $zero, 0xA9
    /* 2B05C 0022A05C 00191100 */  sll        $v1, $s1, 4
    /* 2B060 0022A060 1880C202 */  mult       $s0, $s6, $v0
    /* 2B064 0022A064 21187100 */  addu       $v1, $v1, $s1
    /* 2B068 0022A068 310B2225 */  addiu      $v0, $t1, %lo(D_400B31)
    /* 2B06C 0022A06C 2D20E002 */  daddu      $a0, $s7, $zero
    /* 2B070 0022A070 21186200 */  addu       $v1, $v1, $v0
    /* 2B074 0022A074 2D28A002 */  daddu      $a1, $s5, $zero
    /* 2B078 0022A078 2D302002 */  daddu      $a2, $s1, $zero
    /* 2B07C 0022A07C 1000A87F */  sq         $t0, 0x10($sp)
    /* 2B080 0022A080 21800302 */  addu       $s0, $s0, $v1
    /* 2B084 0022A084 2000A97F */  sq         $t1, 0x20($sp)
    /* 2B088 0022A088 2D380002 */  daddu      $a3, $s0, $zero
    /* 2B08C 0022A08C AA21080C */  jal        func_002086A8
    /* 2B090 0022A090 3000AA7F */   sq        $t2, 0x30($sp)
    /* 2B094 0022A094 3000AA7B */  lq         $t2, 0x30($sp)
    /* 2B098 0022A098 4000053C */  lui        $a1, %hi(D_00401EE0)
    /* 2B09C 0022A09C 1000A87B */  lq         $t0, 0x10($sp)
    /* 2B0A0 0022A0A0 E01EA524 */  addiu      $a1, $a1, %lo(D_00401EE0)
    /* 2B0A4 0022A0A4 21185101 */  addu       $v1, $t2, $s1
    /* 2B0A8 0022A0A8 4000063C */  lui        $a2, %hi(D_00401EF0)
    /* 2B0AC 0022A0AC 40190300 */  sll        $v1, $v1, 5
    /* 2B0B0 0022A0B0 F01EC624 */  addiu      $a2, $a2, %lo(D_00401EF0)
    /* 2B0B4 0022A0B4 21106500 */  addu       $v0, $v1, $a1
    /* 2B0B8 0022A0B8 50250425 */  addiu      $a0, $t0, 0x2550
    /* 2B0BC 0022A0BC 21186600 */  addu       $v1, $v1, $a2
    /* 2B0C0 0022A0C0 040050AC */  sw         $s0, 0x4($v0)
    /* 2B0C4 0022A0C4 00008678 */  lq         $a2, 0x0($a0)
    /* 2B0C8 0022A0C8 0000667C */  sq         $a2, 0x0($v1)
    /* 2B0CC 0022A0CC 01003126 */  addiu      $s1, $s1, 0x1
    /* 2B0D0 0022A0D0 2A103402 */  slt        $v0, $s1, $s4
    /* 2B0D4 0022A0D4 E0FF4014 */  bnez       $v0, .L0022A058
    /* 2B0D8 0022A0D8 2000A97B */   lq        $t1, 0x20($sp)
    /* 2B0DC 0022A0DC 04000010 */  b          .L0022A0F0
    /* 2B0E0 0022A0E0 2DA84002 */   daddu     $s5, $s2, $zero
  .L0022A0E4:
    /* 2B0E4 0022A0E4 21985401 */  addu       $s3, $t2, $s4
    /* 2B0E8 0022A0E8 0100B226 */  addiu      $s2, $s5, 0x1
    /* 2B0EC 0022A0EC 2DA84002 */  daddu      $s5, $s2, $zero
  .L0022A0F0:
    /* 2B0F0 0022A0F0 2A10BE02 */  slt        $v0, $s5, $fp
    /* 2B0F4 0022A0F4 66FF4014 */  bnez       $v0, .L00229E90
    /* 2B0F8 0022A0F8 2D506002 */   daddu     $t2, $s3, $zero
    /* 2B0FC 0022A0FC 07000010 */  b          .L0022A11C
    /* 2B100 0022A100 0C00A38F */   lw        $v1, 0xC($sp)
  .L0022A104:
    /* 2B104 0022A104 0000A28F */  lw         $v0, 0x0($sp)
    /* 2B108 0022A108 01003126 */  addiu      $s1, $s1, 0x1
    /* 2B10C 0022A10C 0800B1AF */  sw         $s1, 0x8($sp)
    /* 2B110 0022A110 21F05E00 */  addu       $fp, $v0, $fp
    /* 2B114 0022A114 0C00BEAF */  sw         $fp, 0xC($sp)
    /* 2B118 0022A118 0C00A38F */  lw         $v1, 0xC($sp)
  .L0022A11C:
    /* 2B11C 0022A11C 03000010 */  b          .L0022A12C
    /* 2B120 0022A120 0000A3AF */   sw        $v1, 0x0($sp)
  .L0022A124:
    /* 2B124 0022A124 01003126 */  addiu      $s1, $s1, 0x1
    /* 2B128 0022A128 0800B1AF */  sw         $s1, 0x8($sp)
  .L0022A12C:
    /* 2B12C 0022A12C 0800B18F */  lw         $s1, 0x8($sp)
    /* 2B130 0022A130 2000222A */  slti       $v0, $s1, 0x20
    /* 2B134 0022A134 07004010 */  beqz       $v0, .L0022A154
    /* 2B138 0022A138 0400A38F */   lw        $v1, 0x4($sp)
    /* 2B13C 0022A13C 13006000 */  mtlo       $v1
    /* 2B140 0022A140 0C000324 */  addiu      $v1, $zero, 0xC
    /* 2B144 0022A144 00102372 */  madd       $v0, $s1, $v1
    /* 2B148 0022A148 0000438C */  lw         $v1, 0x0($v0)
    /* 2B14C 0022A14C 0EFF6014 */  bnez       $v1, .L00229D88
    /* 2B150 0022A150 0C000624 */   addiu     $a2, $zero, 0xC
  .L0022A154:
    /* 2B154 0022A154 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2B158 0022A158 59000424 */   addiu     $a0, $zero, 0x59
    /* 2B15C 0022A15C 2B00043C */  lui        $a0, %hi(D_002B2FE8)
    /* 2B160 0022A160 E82F8324 */  addiu      $v1, $a0, %lo(D_002B2FE8)
    /* 2B164 0022A164 E82F82AC */  sw         $v0, %lo(D_002B2FE8)($a0)
    /* 2B168 0022A168 1000648C */  lw         $a0, 0x10($v1)
    /* 2B16C 0022A16C 0C00628C */  lw         $v0, 0xC($v1)
    /* 2B170 0022A170 1400658C */  lw         $a1, 0x14($v1)
    /* 2B174 0022A174 23108200 */  subu       $v0, $a0, $v0
    /* 2B178 0022A178 080071AC */  sw         $s1, 0x8($v1)
    /* 2B17C 0022A17C 01004224 */  addiu      $v0, $v0, 0x1
    /* 2B180 0022A180 2A18A200 */  slt        $v1, $a1, $v0
    /* 2B184 0022A184 04006054 */  bnel       $v1, $zero, .L0022A198
    /* 2B188 0022A188 2D184000 */   daddu     $v1, $v0, $zero
    /* 2B18C 0022A18C 2D18A000 */  daddu      $v1, $a1, $zero
    /* 2B190 0022A190 2A108300 */  slt        $v0, $a0, $v1
    /* 2B194 0022A194 0B188200 */  movn       $v1, $a0, $v0
  .L0022A198:
    /* 2B198 0022A198 2B00053C */  lui        $a1, %hi(D_002B2FE8)
    /* 2B19C 0022A19C D000BFDF */  ld         $ra, 0xD0($sp)
    /* 2B1A0 0022A1A0 E82FA224 */  addiu      $v0, $a1, %lo(D_002B2FE8)
    /* 2B1A4 0022A1A4 C000BEDF */  ld         $fp, 0xC0($sp)
    /* 2B1A8 0022A1A8 B000B7DF */  ld         $s7, 0xB0($sp)
    /* 2B1AC 0022A1AC A000B6DF */  ld         $s6, 0xA0($sp)
    /* 2B1B0 0022A1B0 9000B5DF */  ld         $s5, 0x90($sp)
    /* 2B1B4 0022A1B4 8000B4DF */  ld         $s4, 0x80($sp)
    /* 2B1B8 0022A1B8 7000B3DF */  ld         $s3, 0x70($sp)
    /* 2B1BC 0022A1BC 6000B2DF */  ld         $s2, 0x60($sp)
    /* 2B1C0 0022A1C0 5000B1DF */  ld         $s1, 0x50($sp)
    /* 2B1C4 0022A1C4 4000B0DF */  ld         $s0, 0x40($sp)
    /* 2B1C8 0022A1C8 140043AC */  sw         $v1, 0x14($v0)
    /* 2B1CC 0022A1CC 0800E003 */  jr         $ra
    /* 2B1D0 0022A1D0 E000BD27 */   addiu     $sp, $sp, 0xE0
endlabel do_show_version_info
