.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00233D90, 0x44

glabel func_00233D90
    /* 34D90 00233D90 0010043C */  lui        $a0, (0x10009000 >> 16)
    /* 34D94 00233D94 0010033C */  lui        $v1, (0x1000A000 >> 16)
    /* 34D98 00233D98 00908434 */  ori        $a0, $a0, (0x10009000 & 0xFFFF)
    /* 34D9C 00233D9C 00A06334 */  ori        $v1, $v1, (0x1000A000 & 0xFFFF)
  .L00233DA0:
    /* 34DA0 00233DA0 0000828C */  lw         $v0, 0x0($a0)
    /* 34DA4 00233DA4 00014230 */  andi       $v0, $v0, 0x100
    /* 34DA8 00233DA8 00000000 */  nop
    /* 34DAC 00233DAC 00000000 */  nop
    /* 34DB0 00233DB0 00000000 */  nop
    /* 34DB4 00233DB4 FAFF4014 */  bnez       $v0, .L00233DA0
    /* 34DB8 00233DB8 00000000 */   nop
    /* 34DBC 00233DBC 0000628C */  lw         $v0, 0x0($v1)
    /* 34DC0 00233DC0 00014230 */  andi       $v0, $v0, 0x100
    /* 34DC4 00233DC4 F6FF4014 */  bnez       $v0, .L00233DA0
    /* 34DC8 00233DC8 00000000 */   nop
    /* 34DCC 00233DCC 0800E003 */  jr         $ra
    /* 34DD0 00233DD0 00000000 */   nop
endlabel func_00233D90
