.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00231FB0, 0x6C

glabel func_00231FB0
    /* 32FB0 00231FB0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 32FB4 00231FB4 2B00023C */  lui        $v0, %hi(D_002B2E78)
    /* 32FB8 00231FB8 1000B1FF */  sd         $s1, 0x10($sp)
    /* 32FBC 00231FBC 02000524 */  addiu      $a1, $zero, 0x2
    /* 32FC0 00231FC0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 32FC4 00231FC4 2D888000 */  daddu      $s1, $a0, $zero
    /* 32FC8 00231FC8 782E5024 */  addiu      $s0, $v0, %lo(D_002B2E78)
    /* 32FCC 00231FCC 2000BFFF */  sd         $ra, 0x20($sp)
    /* 32FD0 00231FD0 A6D2080C */  jal        func_00234A98
    /* 32FD4 00231FD4 2D200002 */   daddu     $a0, $s0, $zero
    /* 32FD8 00231FD8 0C004010 */  beqz       $v0, .L0023200C
    /* 32FDC 00231FDC 2000BFDF */   ld        $ra, 0x20($sp)
    /* 32FE0 00231FE0 B8D2080C */  jal        func_00234AE0
    /* 32FE4 00231FE4 2D200002 */   daddu     $a0, $s0, $zero
    /* 32FE8 00231FE8 08002016 */  bnez       $s1, .L0023200C
    /* 32FEC 00231FEC 2000BFDF */   ld        $ra, 0x20($sp)
    /* 32FF0 00231FF0 00630424 */  addiu      $a0, $zero, 0x6300
    /* 32FF4 00231FF4 1000B1DF */  ld         $s1, 0x10($sp)
    /* 32FF8 00231FF8 01000524 */  addiu      $a1, $zero, 0x1
    /* 32FFC 00231FFC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 33000 00232000 04000624 */  addiu      $a2, $zero, 0x4
    /* 33004 00232004 14CA0808 */  j          j_sound_handler_queue_command_3
    /* 33008 00232008 3000BD27 */   addiu     $sp, $sp, 0x30
  .L0023200C:
    /* 3300C 0023200C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 33010 00232010 0000B0DF */  ld         $s0, 0x0($sp)
    /* 33014 00232014 0800E003 */  jr         $ra
    /* 33018 00232018 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00231FB0
