.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00227480, 0x8

glabel func_00227480
    /* 28480 00227480 2A9C0808 */  j          clock_str_related
    /* 28484 00227484 01000824 */   addiu     $t0, $zero, 0x1
endlabel func_00227480
