.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00234AA8, 0x8

glabel func_00234AA8
    /* 35AA8 00234AA8 0800E003 */  jr         $ra
    /* 35AAC 00234AAC 0800828C */   lw        $v0, 0x8($a0)
endlabel func_00234AA8
