.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0022A360, 0xB0

glabel func_0022A360
    /* 2B360 0022A360 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 2B364 0022A364 01000524 */  addiu      $a1, $zero, 0x1
    /* 2B368 0022A368 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2B36C 0022A36C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2B370 0022A370 2B00113C */  lui        $s1, %hi(D_002B3000)
    /* 2B374 0022A374 00303026 */  addiu      $s0, $s1, %lo(D_002B3000)
    /* 2B378 0022A378 2000BFFF */  sd         $ra, 0x20($sp)
    /* 2B37C 0022A37C A6D2080C */  jal        func_00234A98
    /* 2B380 0022A380 2D200002 */   daddu     $a0, $s0, $zero
    /* 2B384 0022A384 11004050 */  beql       $v0, $zero, .L0022A3CC
    /* 2B388 0022A388 00303026 */   addiu     $s0, $s1, %lo(D_002B3000)
    /* 2B38C 0022A38C 9AD2080C */  jal        func_00234A68
    /* 2B390 0022A390 2D200002 */   daddu     $a0, $s0, $zero
    /* 2B394 0022A394 01000324 */  addiu      $v1, $zero, 0x1
    /* 2B398 0022A398 0C004354 */  bnel       $v0, $v1, .L0022A3CC
    /* 2B39C 0022A39C 00303026 */   addiu     $s0, $s1, %lo(D_002B3000)
    /* 2B3A0 0022A3A0 1491858F */  lw         $a1, %gp_rel(D_00370A84)($gp)
    /* 2B3A4 0022A3A4 01000424 */  addiu      $a0, $zero, 0x1
    /* 2B3A8 0022A3A8 1249080C */  jal        func_00212448
    /* 2B3AC 0022A3AC 2D300000 */   daddu     $a2, $zero, $zero
    /* 2B3B0 0022A3B0 05004050 */  beql       $v0, $zero, .L0022A3C8
    /* 2B3B4 0022A3B4 040000AE */   sw        $zero, 0x4($s0)
    /* 2B3B8 0022A3B8 42A7080C */  jal        do_show_version_info
    /* 2B3BC 0022A3BC 00303026 */   addiu     $s0, $s1, %lo(D_002B3000)
    /* 2B3C0 0022A3C0 03000010 */  b          .L0022A3D0
    /* 2B3C4 0022A3C4 2D280000 */   daddu     $a1, $zero, $zero
  .L0022A3C8:
    /* 2B3C8 0022A3C8 00303026 */  addiu      $s0, $s1, %lo(D_002B3000)
  .L0022A3CC:
    /* 2B3CC 0022A3CC 2D280000 */  daddu      $a1, $zero, $zero
  .L0022A3D0:
    /* 2B3D0 0022A3D0 A6D2080C */  jal        func_00234A98
    /* 2B3D4 0022A3D4 2D200002 */   daddu     $a0, $s0, $zero
    /* 2B3D8 0022A3D8 09004010 */  beqz       $v0, .L0022A400
    /* 2B3DC 0022A3DC 2000BFDF */   ld        $ra, 0x20($sp)
    /* 2B3E0 0022A3E0 0800028E */  lw         $v0, 0x8($s0)
    /* 2B3E4 0022A3E4 07004010 */  beqz       $v0, .L0022A404
    /* 2B3E8 0022A3E8 1000B1DF */   ld        $s1, 0x10($sp)
    /* 2B3EC 0022A3EC 2000BFDF */  ld         $ra, 0x20($sp)
    /* 2B3F0 0022A3F0 2D200000 */  daddu      $a0, $zero, $zero
    /* 2B3F4 0022A3F4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2B3F8 0022A3F8 B0990808 */  j          func_002266C0
    /* 2B3FC 0022A3FC 3000BD27 */   addiu     $sp, $sp, 0x30
  .L0022A400:
    /* 2B400 0022A400 1000B1DF */  ld         $s1, 0x10($sp)
  .L0022A404:
    /* 2B404 0022A404 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2B408 0022A408 0800E003 */  jr         $ra
    /* 2B40C 0022A40C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_0022A360
