.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching get_summer_time_str, 0xA0

glabel get_summer_time_str
    /* 2E3E0 0022D3E0 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 2E3E4 0022D3E4 4000B4FF */  sd         $s4, 0x40($sp)
    /* 2E3E8 0022D3E8 3000B3FF */  sd         $s3, 0x30($sp)
    /* 2E3EC 0022D3EC 2DA08000 */  daddu      $s4, $a0, $zero
    /* 2E3F0 0022D3F0 2000B2FF */  sd         $s2, 0x20($sp)
    /* 2E3F4 0022D3F4 2D98E000 */  daddu      $s3, $a3, $zero
    /* 2E3F8 0022D3F8 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2E3FC 0022D3FC 2D90A000 */  daddu      $s2, $a1, $zero
    /* 2E400 0022D400 5000BFFF */  sd         $ra, 0x50($sp)
    /* 2E404 0022D404 2D88C000 */  daddu      $s1, $a2, $zero
    /* 2E408 0022D408 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2E40C 0022D40C 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2E410 0022D410 94000424 */   addiu     $a0, $zero, 0x94
    /* 2E414 0022D414 00004380 */  lb         $v1, 0x0($v0)
    /* 2E418 0022D418 0D006010 */  beqz       $v1, .L0022D450
    /* 2E41C 0022D41C 2B00103C */   lui       $s0, %hi(D_002B2540)
    /* 2E420 0022D420 94000424 */  addiu      $a0, $zero, 0x94
    /* 2E424 0022D424 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2E428 0022D428 40251026 */   addiu     $s0, $s0, %lo(D_002B2540)
    /* 2E42C 0022D42C 2D282002 */  daddu      $a1, $s1, $zero
    /* 2E430 0022D430 2D404000 */  daddu      $t0, $v0, $zero
    /* 2E434 0022D434 2D300002 */  daddu      $a2, $s0, $zero
    /* 2E438 0022D438 2D204002 */  daddu      $a0, $s2, $zero
    /* 2E43C 0022D43C 009B080C */  jal        draw_menu_item
    /* 2E440 0022D440 2D386002 */   daddu     $a3, $s3, $zero
    /* 2E444 0022D444 944F080C */  jal        func_00213E50
    /* 2E448 0022D448 00000000 */   nop
    /* 2E44C 0022D44C 21882202 */  addu       $s1, $s1, $v0
  .L0022D450:
    /* 2E450 0022D450 2D208002 */  daddu      $a0, $s4, $zero
    /* 2E454 0022D454 2D284002 */  daddu      $a1, $s2, $zero
    /* 2E458 0022D458 2D302002 */  daddu      $a2, $s1, $zero
    /* 2E45C 0022D45C 2D386002 */  daddu      $a3, $s3, $zero
    /* 2E460 0022D460 5000BFDF */  ld         $ra, 0x50($sp)
    /* 2E464 0022D464 4000B4DF */  ld         $s4, 0x40($sp)
    /* 2E468 0022D468 3000B3DF */  ld         $s3, 0x30($sp)
    /* 2E46C 0022D46C 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2E470 0022D470 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2E474 0022D474 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2E478 0022D478 96AF0808 */  j          func_0022BE58
    /* 2E47C 0022D47C 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel get_summer_time_str
