.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching module_clock_22FEF0, 0x8

glabel module_clock_22FEF0
    /* 30EF0 0022FEF0 0800E003 */  jr         $ra
    /* 30EF4 0022FEF4 3491828F */   lw        $v0, %gp_rel(D_00370AA4)($gp)
endlabel module_clock_22FEF0
