.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching module_clock_getdesc, 0xC

glabel module_clock_getdesc
    /* 26870 00225870 3700023C */  lui        $v0, %hi(D_00370110)
    /* 26874 00225874 0800E003 */  jr         $ra
    /* 26878 00225878 10014224 */   addiu     $v0, $v0, %lo(D_00370110)
endlabel module_clock_getdesc
