.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching module_clock_225F38, 0xC8

glabel module_clock_225F38
    /* 26F38 00225F38 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 26F3C 00225F3C 2B00023C */  lui        $v0, %hi(D_002B2190)
    /* 26F40 00225F40 3000B1FF */  sd         $s1, 0x30($sp)
    /* 26F44 00225F44 90214224 */  addiu      $v0, $v0, %lo(D_002B2190)
    /* 26F48 00225F48 2D888000 */  daddu      $s1, $a0, $zero
    /* 26F4C 00225F4C 2000B0FF */  sd         $s0, 0x20($sp)
    /* 26F50 00225F50 2D20A000 */  daddu      $a0, $a1, $zero
    /* 26F54 00225F54 4000BFFF */  sd         $ra, 0x40($sp)
    /* 26F58 00225F58 1000B027 */  addiu      $s0, $sp, 0x10
    /* 26F5C 00225F5C 00004678 */  lq         $a2, 0x0($v0)
    /* 26F60 00225F60 0000067E */  sq         $a2, 0x0($s0)
    /* 26F64 00225F64 1800A1C7 */  lwc1       $f1, 0x18($sp)
    /* 26F68 00225F68 2B00023C */  lui        $v0, %hi(D_002B2170)
    /* 26F6C 00225F6C 109180C7 */  lwc1       $f0, %gp_rel(D_00370A80)($gp)
    /* 26F70 00225F70 70214224 */  addiu      $v0, $v0, %lo(D_002B2170)
    /* 26F74 00225F74 0045013C */  lui        $at, (0x45000000 >> 16)
    /* 26F78 00225F78 00788144 */  mtc1       $at, $f15
    /* 26F7C 00225F7C 40080046 */  add.s      $f1, $f1, $f0
    /* 26F80 00225F80 803F013C */  lui        $at, (0x3F800000 >> 16)
    /* 26F84 00225F84 00888144 */  mtc1       $at, $f17
    /* 26F88 00225F88 8047013C */  lui        $at, (0x47800000 >> 16)
    /* 26F8C 00225F8C 00008144 */  mtc1       $at, $f0
    /* 26F90 00225F90 067C0046 */  mov.s      $f16, $f15
    /* 26F94 00225F94 10004EC4 */  lwc1       $f14, 0x10($v0)
    /* 26F98 00225F98 C68C0046 */  mov.s      $f19, $f17
    /* 26F9C 00225F9C 0C004DC4 */  lwc1       $f13, 0xC($v0)
    /* 26FA0 00225FA0 0044013C */  lui        $at, (0x44000000 >> 16)
    /* 26FA4 00225FA4 00608144 */  mtc1       $at, $f12
    /* 26FA8 00225FA8 1C8292C7 */  lwc1       $f18, %gp_rel(D_0036FB8C)($gp)
    /* 26FAC 00225FAC 1800A1E7 */  swc1       $f1, 0x18($sp)
    /* 26FB0 00225FB0 8AED090C */  jal        sceVu0ViewScreenMatrix
    /* 26FB4 00225FB4 0000A0E7 */   swc1      $f0, 0x0($sp)
    /* 26FB8 00225FB8 2B00063C */  lui        $a2, %hi(D_002B21A0)
    /* 26FBC 00225FBC 2B00073C */  lui        $a3, %hi(D_002B21B0)
    /* 26FC0 00225FC0 2B00083C */  lui        $t0, %hi(D_002B21C0)
    /* 26FC4 00225FC4 2D202002 */  daddu      $a0, $s1, $zero
    /* 26FC8 00225FC8 2D280002 */  daddu      $a1, $s0, $zero
    /* 26FCC 00225FCC A021C624 */  addiu      $a2, $a2, %lo(D_002B21A0)
    /* 26FD0 00225FD0 B021E724 */  addiu      $a3, $a3, %lo(D_002B21B0)
    /* 26FD4 00225FD4 70E3080C */  jal        module_clock_238DC0
    /* 26FD8 00225FD8 C0210825 */   addiu     $t0, $t0, %lo(D_002B21C0)
    /* 26FDC 00225FDC 109180C7 */  lwc1       $f0, %gp_rel(D_00370A80)($gp)
    /* 26FE0 00225FE0 208281C7 */  lwc1       $f1, %gp_rel(D_0036FB90)($gp)
    /* 26FE4 00225FE4 4000BFDF */  ld         $ra, 0x40($sp)
    /* 26FE8 00225FE8 02000146 */  mul.s      $f0, $f0, $f1
    /* 26FEC 00225FEC 3000B1DF */  ld         $s1, 0x30($sp)
    /* 26FF0 00225FF0 2000B0DF */  ld         $s0, 0x20($sp)
    /* 26FF4 00225FF4 109180E7 */  swc1       $f0, %gp_rel(D_00370A80)($gp)
    /* 26FF8 00225FF8 0800E003 */  jr         $ra
    /* 26FFC 00225FFC 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel module_clock_225F38
