.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching browser_device_icon_render, 0x1A8

glabel browser_device_icon_render
    /* 44558 00243558 F0FDBD27 */  addiu      $sp, $sp, -0x210
    /* 4455C 0024355C 8001B0FF */  sd         $s0, 0x180($sp)
    /* 44560 00243560 F001B7FF */  sd         $s7, 0x1F0($sp)
    /* 44564 00243564 2D80C000 */  daddu      $s0, $a2, $zero
    /* 44568 00243568 E001B6FF */  sd         $s6, 0x1E0($sp)
    /* 4456C 0024356C 2DB8A000 */  daddu      $s7, $a1, $zero
    /* 44570 00243570 C001B4FF */  sd         $s4, 0x1C0($sp)
    /* 44574 00243574 2DB00001 */  daddu      $s6, $t0, $zero
    /* 44578 00243578 B001B3FF */  sd         $s3, 0x1B0($sp)
    /* 4457C 0024357C 2DA0E000 */  daddu      $s4, $a3, $zero
    /* 44580 00243580 0002BFFF */  sd         $ra, 0x200($sp)
    /* 44584 00243584 2D988000 */  daddu      $s3, $a0, $zero
    /* 44588 00243588 D001B5FF */  sd         $s5, 0x1D0($sp)
    /* 4458C 0024358C 0901022A */  slti       $v0, $s0, 0x109
    /* 44590 00243590 A001B2FF */  sd         $s2, 0x1A0($sp)
    /* 44594 00243594 4F004010 */  beqz       $v0, .L002436D4
    /* 44598 00243598 9001B1FF */   sd        $s1, 0x190($sp)
    /* 4459C 0024359C 02000424 */  addiu      $a0, $zero, 0x2
    /* 445A0 002435A0 324A080C */  jal        func_002128C8
    /* 445A4 002435A4 2D288002 */   daddu     $a1, $s4, $zero
    /* 445A8 002435A8 D0838CC7 */  lwc1       $f12, %gp_rel(D_0036FD40)($gp)
    /* 445AC 002435AC EE49080C */  jal        Font_SetRatio
    /* 445B0 002435B0 0800152A */   slti      $s5, $s0, 0x8
    /* 445B4 002435B4 0500A016 */  bnez       $s5, .L002435CC
    /* 445B8 002435B8 02000426 */   addiu     $a0, $s0, 0x2
    /* 445BC 002435BC 01000424 */  addiu      $a0, $zero, 0x1
    /* 445C0 002435C0 04000326 */  addiu      $v1, $s0, 0x4
    /* 445C4 002435C4 0801023A */  xori       $v0, $s0, 0x108
    /* 445C8 002435C8 0B206200 */  movn       $a0, $v1, $v0
  .L002435CC:
    /* 445CC 002435CC 2C00023C */  lui        $v0, %hi(D_002BB938)
    /* 445D0 002435D0 80881000 */  sll        $s1, $s0, 2
    /* 445D4 002435D4 38B95224 */  addiu      $s2, $v0, %lo(D_002BB938)
    /* 445D8 002435D8 21105102 */  addu       $v0, $s2, $s1
    /* 445DC 002435DC 4E4F090C */  jal        browser_get_device_name_string
    /* 445E0 002435E0 2C04458C */   lw        $a1, 0x42C($v0)
    /* 445E4 002435E4 2D200002 */  daddu      $a0, $s0, $zero
    /* 445E8 002435E8 2D304000 */  daddu      $a2, $v0, $zero
    /* 445EC 002435EC 4C0D090C */  jal        func_00243530
    /* 445F0 002435F0 2D28A003 */   daddu     $a1, $sp, $zero
    /* 445F4 002435F4 BA4F080C */  jal        func_00213EE8
    /* 445F8 002435F8 2D20A003 */   daddu     $a0, $sp, $zero
    /* 445FC 002435FC C21F0200 */  srl        $v1, $v0, 31
    /* 44600 00243600 B0010424 */  addiu      $a0, $zero, 0x1B0
    /* 44604 00243604 21186200 */  addu       $v1, $v1, $v0
    /* 44608 00243608 8A00E526 */  addiu      $a1, $s7, 0x8A
    /* 4460C 0024360C 43180300 */  sra        $v1, $v1, 1
    /* 44610 00243610 00290500 */  sll        $a1, $a1, 4
    /* 44614 00243614 23208300 */  subu       $a0, $a0, $v1
    /* 44618 00243618 00210400 */  sll        $a0, $a0, 4
    /* 4461C 0024361C 1036090C */  jal        func_0024D840
    /* 44620 00243620 21209300 */   addu      $a0, $a0, $s3
    /* 44624 00243624 904F080C */  jal        j_Font_PutsPackets
    /* 44628 00243628 2D20A003 */   daddu     $a0, $sp, $zero
    /* 4462C 0024362C 2500C052 */  beql       $s6, $zero, .L002436C4
    /* 44630 00243630 A08B80AF */   sw        $zero, %gp_rel(D_00370510)($gp)
    /* 44634 00243634 2200A012 */  beqz       $s5, .L002436C0
    /* 44638 00243638 21105102 */   addu      $v0, $s2, $s1
    /* 4463C 0024363C 740C438C */  lw         $v1, 0xC74($v0)
    /* 44640 00243640 08006014 */  bnez       $v1, .L00243664
    /* 44644 00243644 2D20A003 */   daddu     $a0, $sp, $zero
    /* 44648 00243648 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 4464C 0024364C 2D000424 */   addiu     $a0, $zero, 0x2D
    /* 44650 00243650 2D284000 */  daddu      $a1, $v0, $zero
    /* 44654 00243654 64740A0C */  jal        strcpy
    /* 44658 00243658 2D20A003 */   daddu     $a0, $sp, $zero
    /* 4465C 0024365C 04000010 */  b          .L00243670
    /* 44660 00243660 A08B828F */   lw        $v0, %gp_rel(D_00370510)($gp)
  .L00243664:
    /* 44664 00243664 E84F090C */  jal        browser_get_device_free_string
    /* 44668 00243668 5008458C */   lw        $a1, 0x850($v0)
    /* 4466C 0024366C A08B828F */  lw         $v0, %gp_rel(D_00370510)($gp)
  .L00243670:
    /* 44670 00243670 2D200000 */  daddu      $a0, $zero, $zero
    /* 44674 00243674 0A004224 */  addiu      $v0, $v0, 0xA
    /* 44678 00243678 2A188202 */  slt        $v1, $s4, $v0
    /* 4467C 0024367C 0B108302 */  movn       $v0, $s4, $v1
    /* 44680 00243680 2D284000 */  daddu      $a1, $v0, $zero
    /* 44684 00243684 324A080C */  jal        func_002128C8
    /* 44688 00243688 A08B82AF */   sw        $v0, %gp_rel(D_00370510)($gp)
    /* 4468C 0024368C D4838CC7 */  lwc1       $f12, %gp_rel(D_0036FD44)($gp)
    /* 44690 00243690 EE49080C */  jal        Font_SetRatio
    /* 44694 00243694 00000000 */   nop
    /* 44698 00243698 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 4469C 0024369C 0F006426 */  addiu      $a0, $s3, 0xF
    /* 446A0 002436A0 2A105300 */  slt        $v0, $v0, $s3
    /* 446A4 002436A4 9700E526 */  addiu      $a1, $s7, 0x97
    /* 446A8 002436A8 0B206202 */  movn       $a0, $s3, $v0
    /* 446AC 002436AC 2D30A003 */  daddu      $a2, $sp, $zero
    /* 446B0 002436B0 4036090C */  jal        func_0024D900
    /* 446B4 002436B4 03210400 */   sra       $a0, $a0, 4
    /* 446B8 002436B8 02000010 */  b          .L002436C4
    /* 446BC 002436BC 00000000 */   nop
  .L002436C0:
    /* 446C0 002436C0 A08B80AF */  sw         $zero, %gp_rel(D_00370510)($gp)
  .L002436C4:
    /* 446C4 002436C4 803F013C */  lui        $at, (0x3F800000 >> 16)
    /* 446C8 002436C8 00608144 */  mtc1       $at, $f12
    /* 446CC 002436CC EE49080C */  jal        Font_SetRatio
    /* 446D0 002436D0 00000000 */   nop
  .L002436D4:
    /* 446D4 002436D4 0002BFDF */  ld         $ra, 0x200($sp)
    /* 446D8 002436D8 F001B7DF */  ld         $s7, 0x1F0($sp)
    /* 446DC 002436DC E001B6DF */  ld         $s6, 0x1E0($sp)
    /* 446E0 002436E0 D001B5DF */  ld         $s5, 0x1D0($sp)
    /* 446E4 002436E4 C001B4DF */  ld         $s4, 0x1C0($sp)
    /* 446E8 002436E8 B001B3DF */  ld         $s3, 0x1B0($sp)
    /* 446EC 002436EC A001B2DF */  ld         $s2, 0x1A0($sp)
    /* 446F0 002436F0 9001B1DF */  ld         $s1, 0x190($sp)
    /* 446F4 002436F4 8001B0DF */  ld         $s0, 0x180($sp)
    /* 446F8 002436F8 0800E003 */  jr         $ra
    /* 446FC 002436FC 1002BD27 */   addiu     $sp, $sp, 0x210
endlabel browser_device_icon_render
