.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching do_makesema, 0x58

glabel do_makesema
    /* 72258 00271258 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 7225C 0027125C 01000224 */  addiu      $v0, $zero, 0x1
    /* 72260 00271260 2000B0FF */  sd         $s0, 0x20($sp)
    /* 72264 00271264 2D808000 */  daddu      $s0, $a0, $zero
    /* 72268 00271268 3000BFFF */  sd         $ra, 0x30($sp)
    /* 7226C 0027126C 100000AE */  sw         $zero, 0x10($s0)
    /* 72270 00271270 2D20A003 */  daddu      $a0, $sp, $zero
    /* 72274 00271274 0C0000AE */  sw         $zero, 0xC($s0)
    /* 72278 00271278 040005AE */  sw         $a1, 0x4($s0)
    /* 7227C 0027127C 080006AE */  sw         $a2, 0x8($s0)
    /* 72280 00271280 0400A2AF */  sw         $v0, 0x4($sp)
    /* 72284 00271284 0800A0AF */  sw         $zero, 0x8($sp)
    /* 72288 00271288 B4FE090C */  jal        CreateSema
    /* 7228C 0027128C 1400A0AF */   sw        $zero, 0x14($sp)
    /* 72290 00271290 000002AE */  sw         $v0, 0x0($s0)
    /* 72294 00271294 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 72298 00271298 2A186200 */  slt        $v1, $v1, $v0
    /* 7229C 0027129C 3000BFDF */  ld         $ra, 0x30($sp)
    /* 722A0 002712A0 2000B0DF */  ld         $s0, 0x20($sp)
    /* 722A4 002712A4 0B100300 */  movn       $v0, $zero, $v1
    /* 722A8 002712A8 0800E003 */  jr         $ra
    /* 722AC 002712AC 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel do_makesema
