.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching Fep_SetData2Fifo, 0x118

glabel Fep_SetData2Fifo
    /* 6D1D0 0026C1D0 80F2BD27 */  addiu      $sp, $sp, -0xD80
    /* 6D1D4 0026C1D4 00010624 */  addiu      $a2, $zero, 0x100
    /* 6D1D8 0026C1D8 600DB5FF */  sd         $s5, 0xD60($sp)
    /* 6D1DC 0026C1DC 2D28A003 */  daddu      $a1, $sp, $zero
    /* 6D1E0 0026C1E0 4F00153C */  lui        $s5, %hi(D_004EB190)
    /* 6D1E4 0026C1E4 200DB1FF */  sd         $s1, 0xD20($sp)
    /* 6D1E8 0026C1E8 700DBFFF */  sd         $ra, 0xD70($sp)
    /* 6D1EC 0026C1EC 90B1A426 */  addiu      $a0, $s5, %lo(D_004EB190)
    /* 6D1F0 0026C1F0 500DB4FF */  sd         $s4, 0xD50($sp)
    /* 6D1F4 0026C1F4 2D880000 */  daddu      $s1, $zero, $zero
    /* 6D1F8 0026C1F8 400DB3FF */  sd         $s3, 0xD40($sp)
    /* 6D1FC 0026C1FC 300DB2FF */  sd         $s2, 0xD30($sp)
    /* 6D200 0026C200 2AE1090C */  jal        sceAtokGetConvertedStr
    /* 6D204 0026C204 100DB0FF */   sd        $s0, 0xD10($sp)
    /* 6D208 0026C208 0000A293 */  lbu        $v0, 0x0($sp)
    /* 6D20C 0026C20C 14004010 */  beqz       $v0, .L0026C260
    /* 6D210 0026C210 000DBDAF */   sw        $sp, 0xD00($sp)
    /* 6D214 0026C214 000DB227 */  addiu      $s2, $sp, 0xD00
    /* 6D218 0026C218 0009B027 */  addiu      $s0, $sp, 0x900
    /* 6D21C 0026C21C 0001B327 */  addiu      $s3, $sp, 0x100
    /* 6D220 0026C220 3100143C */  lui        $s4, %hi(D_00311C00)
    /* 6D224 0026C224 00000000 */  nop
  .L0026C228:
    /* 6D228 0026C228 263C0A0C */  jal        sceCccDecodeSJIS
    /* 6D22C 0026C22C 2D204002 */   daddu     $a0, $s2, $zero
    /* 6D230 0026C230 2D204000 */  daddu      $a0, $v0, $zero
    /* 6D234 0026C234 DA400A0C */  jal        sceCccJIStoUCS
    /* 6D238 0026C238 2D280000 */   daddu     $a1, $zero, $zero
    /* 6D23C 0026C23C 80181100 */  sll        $v1, $s1, 2
    /* 6D240 0026C240 000DA48F */  lw         $a0, 0xD00($sp)
    /* 6D244 0026C244 21180302 */  addu       $v1, $s0, $v1
    /* 6D248 0026C248 000062AC */  sw         $v0, 0x0($v1)
    /* 6D24C 0026C24C 00008290 */  lbu        $v0, 0x0($a0)
    /* 6D250 0026C250 F5FF4014 */  bnez       $v0, .L0026C228
    /* 6D254 0026C254 01003126 */   addiu     $s1, $s1, 0x1
    /* 6D258 0026C258 04000010 */  b          .L0026C26C
    /* 6D25C 0026C25C 2D280000 */   daddu     $a1, $zero, $zero
  .L0026C260:
    /* 6D260 0026C260 0001B327 */  addiu      $s3, $sp, 0x100
    /* 6D264 0026C264 3100143C */  lui        $s4, %hi(D_00311C00)
    /* 6D268 0026C268 2D280000 */  daddu      $a1, $zero, $zero
  .L0026C26C:
    /* 6D26C 0026C26C 0F00201A */  blez       $s1, .L0026C2AC
    /* 6D270 0026C270 0009B027 */   addiu     $s0, $sp, 0x900
    /* 6D274 0026C274 C0301100 */  sll        $a2, $s1, 3
  .L0026C278:
    /* 6D278 0026C278 80100500 */  sll        $v0, $a1, 2
    /* 6D27C 0026C27C C0180500 */  sll        $v1, $a1, 3
    /* 6D280 0026C280 21100202 */  addu       $v0, $s0, $v0
    /* 6D284 0026C284 21186302 */  addu       $v1, $s3, $v1
    /* 6D288 0026C288 0000448C */  lw         $a0, 0x0($v0)
    /* 6D28C 0026C28C 0100A524 */  addiu      $a1, $a1, 0x1
    /* 6D290 0026C290 060060A4 */  sh         $zero, 0x6($v1)
    /* 6D294 0026C294 2A10B100 */  slt        $v0, $a1, $s1
    /* 6D298 0026C298 000064AC */  sw         $a0, 0x0($v1)
    /* 6D29C 0026C29C F6FF4014 */  bnez       $v0, .L0026C278
    /* 6D2A0 0026C2A0 040060A0 */   sb        $zero, 0x4($v1)
    /* 6D2A4 0026C2A4 03000010 */  b          .L0026C2B4
    /* 6D2A8 0026C2A8 001C8426 */   addiu     $a0, $s4, %lo(D_00311C00)
  .L0026C2AC:
    /* 6D2AC 0026C2AC C0301100 */  sll        $a2, $s1, 3
    /* 6D2B0 0026C2B0 001C8426 */  addiu      $a0, $s4, %lo(D_00311C00)
  .L0026C2B4:
    /* 6D2B4 0026C2B4 40C5090C */  jal        FifoSendData
    /* 6D2B8 0026C2B8 2D286002 */   daddu     $a1, $s3, $zero
    /* 6D2BC 0026C2BC 26E1090C */  jal        sceAtokFlushConverted
    /* 6D2C0 0026C2C0 90B1A426 */   addiu     $a0, $s5, %lo(D_004EB190)
    /* 6D2C4 0026C2C4 700DBFDF */  ld         $ra, 0xD70($sp)
    /* 6D2C8 0026C2C8 600DB5DF */  ld         $s5, 0xD60($sp)
    /* 6D2CC 0026C2CC 500DB4DF */  ld         $s4, 0xD50($sp)
    /* 6D2D0 0026C2D0 400DB3DF */  ld         $s3, 0xD40($sp)
    /* 6D2D4 0026C2D4 300DB2DF */  ld         $s2, 0xD30($sp)
    /* 6D2D8 0026C2D8 200DB1DF */  ld         $s1, 0xD20($sp)
    /* 6D2DC 0026C2DC 100DB0DF */  ld         $s0, 0xD10($sp)
    /* 6D2E0 0026C2E0 0800E003 */  jr         $ra
    /* 6D2E4 0026C2E4 800DBD27 */   addiu     $sp, $sp, 0xD80
endlabel Fep_SetData2Fifo
