.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0024BC30, 0xC

glabel func_0024BC30
    /* 4CC30 0024BC30 9BFF8224 */  addiu      $v0, $a0, -0x65
    /* 4CC34 0024BC34 0800E003 */  jr         $ra
    /* 4CC38 0024BC38 0400422C */   sltiu     $v0, $v0, 0x4
endlabel func_0024BC30
