.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0024C200, 0xEC

glabel func_0024C200
    /* 4D200 0024C200 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 4D204 0024C204 30000224 */  addiu      $v0, $zero, 0x30
    /* 4D208 0024C208 0000B0FF */  sd         $s0, 0x0($sp)
    /* 4D20C 0024C20C 18208200 */  mult       $a0, $a0, $v0
    /* 4D210 0024C210 4C00103C */  lui        $s0, %hi(D_004BA100)
    /* 4D214 0024C214 00A11026 */  addiu      $s0, $s0, %lo(D_004BA100)
    /* 4D218 0024C218 782C0500 */  dsll       $a1, $a1, 17
    /* 4D21C 0024C21C 0020023C */  lui        $v0, (0x20000038 >> 16)
    /* 4D220 0024C220 0100033C */  lui        $v1, (0x10000 >> 16)
    /* 4D224 0024C224 25800202 */  or         $s0, $s0, $v0
    /* 4D228 0024C228 2528A300 */  or         $a1, $a1, $v1
    /* 4D22C 0024C22C 1000BFFF */  sd         $ra, 0x10($sp)
    /* 4D230 0024C230 0010023C */  lui        $v0, (0x10000000 >> 16)
    /* 4D234 0024C234 3C100200 */  dsll32     $v0, $v0, 0
    /* 4D238 0024C238 03804234 */  ori        $v0, $v0, 0x8003
    /* 4D23C 0024C23C 2C00033C */  lui        $v1, %hi(D_002BCFC0)
    /* 4D240 0024C240 000002FE */  sd         $v0, (0x20000000 & 0xFFFF)($s0)
    /* 4D244 0024C244 C0CF6324 */  addiu      $v1, $v1, %lo(D_002BCFC0)
    /* 4D248 0024C248 0E000624 */  addiu      $a2, $zero, 0xE
    /* 4D24C 0024C24C 47000724 */  addiu      $a3, $zero, 0x47
    /* 4D250 0024C250 080006FE */  sd         $a2, (0x20000008 & 0xFFFF)($s0)
    /* 4D254 0024C254 21106400 */  addu       $v0, $v1, $a0
    /* 4D258 0024C258 100005FE */  sd         $a1, (0x20000010 & 0xFFFF)($s0)
    /* 4D25C 0024C25C 180007FE */  sd         $a3, (0x20000018 & 0xFFFF)($s0)
    /* 4D260 0024C260 2D304000 */  daddu      $a2, $v0, $zero
    /* 4D264 0024C264 21488300 */  addu       $t1, $a0, $v1
    /* 4D268 0024C268 2D404000 */  daddu      $t0, $v0, $zero
    /* 4D26C 0024C26C 1000C5DC */  ld         $a1, 0x10($a2)
    /* 4D270 0024C270 2D184000 */  daddu      $v1, $v0, $zero
    /* 4D274 0024C274 200047DC */  ld         $a3, 0x20($v0)
    /* 4D278 0024C278 42000A24 */  addiu      $t2, $zero, 0x42
    /* 4D27C 0024C27C 080006DD */  ld         $a2, 0x8($t0)
    /* 4D280 0024C280 38290500 */  dsll       $a1, $a1, 4
    /* 4D284 0024C284 000022DD */  ld         $v0, 0x0($t1)
    /* 4D288 0024C288 3C380700 */  dsll32     $a3, $a3, 0
    /* 4D28C 0024C28C 180064DC */  ld         $a0, 0x18($v1)
    /* 4D290 0024C290 B8300600 */  dsll       $a2, $a2, 2
    /* 4D294 0024C294 2528A600 */  or         $a1, $a1, $a2
    /* 4D298 0024C298 25104700 */  or         $v0, $v0, $a3
    /* 4D29C 0024C29C 25104500 */  or         $v0, $v0, $a1
    /* 4D2A0 0024C2A0 B8210400 */  dsll       $a0, $a0, 6
    /* 4D2A4 0024C2A4 25104400 */  or         $v0, $v0, $a0
    /* 4D2A8 0024C2A8 05000B24 */  addiu      $t3, $zero, 0x5
    /* 4D2AC 0024C2AC 08000324 */  addiu      $v1, $zero, 0x8
    /* 4D2B0 0024C2B0 200002FE */  sd         $v0, (0x20000020 & 0xFFFF)($s0)
    /* 4D2B4 0024C2B4 28000AFE */  sd         $t2, (0x20000028 & 0xFFFF)($s0)
    /* 4D2B8 0024C2B8 2D200000 */  daddu      $a0, $zero, $zero
    /* 4D2BC 0024C2BC 30000BFE */  sd         $t3, (0x20000030 & 0xFFFF)($s0)
    /* 4D2C0 0024C2C0 2D280000 */  daddu      $a1, $zero, $zero
    /* 4D2C4 0024C2C4 EA240A0C */  jal        sceGsSyncPath
    /* 4D2C8 0024C2C8 380003FE */   sd        $v1, (0x20000038 & 0xFFFF)($s0)
    /* 4D2CC 0024C2CC CC230A0C */  jal        sceGsPutDrawEnv
    /* 4D2D0 0024C2D0 2D200002 */   daddu     $a0, $s0, $zero
    /* 4D2D4 0024C2D4 1000BFDF */  ld         $ra, 0x10($sp)
    /* 4D2D8 0024C2D8 2D200000 */  daddu      $a0, $zero, $zero
    /* 4D2DC 0024C2DC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 4D2E0 0024C2E0 2D280000 */  daddu      $a1, $zero, $zero
    /* 4D2E4 0024C2E4 EA240A08 */  j          sceGsSyncPath
    /* 4D2E8 0024C2E8 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0024C200
