.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00252A78, 0x8

glabel func_00252A78
    /* 53A78 00252A78 364A0908 */  j          func_002528D8
    /* 53A7C 00252A7C 00000000 */   nop
endlabel func_00252A78
