.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00249928, 0x60

glabel func_00249928
    /* 4A928 00249928 2C00033C */  lui        $v1, %hi(D_002BB938)
    /* 4A92C 0024992C 3801C88C */  lw         $t0, 0x138($a2)
    /* 4A930 00249930 38B96324 */  addiu      $v1, $v1, %lo(D_002BB938)
    /* 4A934 00249934 80380400 */  sll        $a3, $a0, 2
    /* 4A938 00249938 2C046324 */  addiu      $v1, $v1, 0x42C
    /* 4A93C 0024993C 80100500 */  sll        $v0, $a1, 2
    /* 4A940 00249940 21104300 */  addu       $v0, $v0, $v1
    /* 4A944 00249944 2138E300 */  addu       $a3, $a3, $v1
    /* 4A948 00249948 0000498C */  lw         $t1, 0x0($v0)
    /* 4A94C 0024994C C001C624 */  addiu      $a2, $a2, 0x1C0
    /* 4A950 00249950 0000E38C */  lw         $v1, 0x0($a3)
    /* 4A954 00249954 06000224 */  addiu      $v0, $zero, 0x6
    /* 4A958 00249958 10000A8D */  lw         $t2, 0x10($t0)
    /* 4A95C 0024995C 02000724 */  addiu      $a3, $zero, 0x2
    /* 4A960 00249960 B88C82AF */  sw         $v0, %gp_rel(D_00370628)($gp)
    /* 4A964 00249964 C48C83AF */  sw         $v1, %gp_rel(D_00370634)($gp)
    /* 4A968 00249968 C88C89AF */  sw         $t1, %gp_rel(D_00370638)($gp)
    /* 4A96C 0024996C D48C86AF */  sw         $a2, %gp_rel(D_00370644)($gp)
    /* 4A970 00249970 CC8C8AAF */  sw         $t2, %gp_rel(D_0037063C)($gp)
    /* 4A974 00249974 948C87AF */  sw         $a3, %gp_rel(D_00370604)($gp)
    /* 4A978 00249978 BC8C84AF */  sw         $a0, %gp_rel(D_0037062C)($gp)
    /* 4A97C 0024997C C08C85AF */  sw         $a1, %gp_rel(D_00370630)($gp)
    /* 4A980 00249980 0800E003 */  jr         $ra
    /* 4A984 00249984 A88C80AF */   sw        $zero, %gp_rel(D_00370618)($gp)
endlabel func_00249928
