.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00255358, 0x64

glabel func_00255358
    /* 56358 00255358 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 5635C 0025535C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 56360 00255360 B225090C */  jal        func_002496C8
    /* 56364 00255364 00000000 */   nop
    /* 56368 00255368 3E0F080C */  jal        config_get_spdif_mode
    /* 5636C 0025536C 00000000 */   nop
    /* 56370 00255370 03004014 */  bnez       $v0, .L00255380
    /* 56374 00255374 1F00033C */   lui       $v1, (0x1F0114 >> 16)
    /* 56378 00255378 02000010 */  b          .L00255384
    /* 5637C 0025537C 14000224 */   addiu     $v0, $zero, 0x14
  .L00255380:
    /* 56380 00255380 15000224 */  addiu      $v0, $zero, 0x15
  .L00255384:
    /* 56384 00255384 140162AC */  sw         $v0, (0x1F0114 & 0xFFFF)($v1)
    /* 56388 00255388 888D838F */  lw         $v1, %gp_rel(D_003706F8)($gp)
    /* 5638C 0025538C 03000224 */  addiu      $v0, $zero, 0x3
    /* 56390 00255390 08006210 */  beq        $v1, $v0, .L002553B4
    /* 56394 00255394 0000BFDF */   ld        $ra, 0x0($sp)
    /* 56398 00255398 1F00033C */  lui        $v1, (0x1F0D40 >> 16)
    /* 5639C 0025539C 01000224 */  addiu      $v0, $zero, 0x1
    /* 563A0 002553A0 01000424 */  addiu      $a0, $zero, 0x1
    /* 563A4 002553A4 7C1262AC */  sw         $v0, (0x1F127C & 0xFFFF)($v1)
    /* 563A8 002553A8 400D60AC */  sw         $zero, (0x1F0D40 & 0xFFFF)($v1)
    /* 563AC 002553AC 2A460808 */  j          sema_related_2118A8
    /* 563B0 002553B0 1000BD27 */   addiu     $sp, $sp, 0x10
  .L002553B4:
    /* 563B4 002553B4 0800E003 */  jr         $ra
    /* 563B8 002553B8 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_00255358
