.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0025AB58, 0x30

glabel func_0025AB58
    /* 5BB58 0025AB58 2E00023C */  lui        $v0, %hi(D_002DA620)
    /* 5BB5C 0025AB5C 801A0400 */  sll        $v1, $a0, 10
    /* 5BB60 0025AB60 20A64424 */  addiu      $a0, $v0, %lo(D_002DA620)
    /* 5BB64 0025AB64 21106400 */  addu       $v0, $v1, $a0
    /* 5BB68 0025AB68 0500A010 */  beqz       $a1, .L0025AB80
    /* 5BB6C 0025AB6C F80345AC */   sw        $a1, 0x3F8($v0)
    /* 5BB70 0025AB70 288D82DF */  ld         $v0, %gp_rel(D_00370698)($gp)
    /* 5BB74 0025AB74 21188300 */  addu       $v1, $a0, $v1
    /* 5BB78 0025AB78 01004264 */  daddiu     $v0, $v0, 0x1
    /* 5BB7C 0025AB7C F00362FC */  sd         $v0, 0x3F0($v1)
  .L0025AB80:
    /* 5BB80 0025AB80 0800E003 */  jr         $ra
    /* 5BB84 0025AB84 00000000 */   nop
endlabel func_0025AB58
