.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0023FDB8, 0x70

glabel func_0023FDB8
    /* 40DB8 0023FDB8 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 40DBC 0023FDBC 6400822C */  sltiu      $v0, $a0, 0x64
    /* 40DC0 0023FDC0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 40DC4 0023FDC4 2D800000 */  daddu      $s0, $zero, $zero
    /* 40DC8 0023FDC8 3000B3FF */  sd         $s3, 0x30($sp)
    /* 40DCC 0023FDCC 0B808200 */  movn       $s0, $a0, $v0
    /* 40DD0 0023FDD0 2000B2FF */  sd         $s2, 0x20($sp)
    /* 40DD4 0023FDD4 1000B1FF */  sd         $s1, 0x10($sp)
    /* 40DD8 0023FDD8 2D90C000 */  daddu      $s2, $a2, $zero
    /* 40DDC 0023FDDC 2D88A000 */  daddu      $s1, $a1, $zero
    /* 40DE0 0023FDE0 2D98E000 */  daddu      $s3, $a3, $zero
    /* 40DE4 0023FDE4 4000BFFF */  sd         $ra, 0x40($sp)
    /* 40DE8 0023FDE8 50FF080C */  jal        func_0023FD40
    /* 40DEC 0023FDEC 2E000426 */   addiu     $a0, $s0, 0x2E
    /* 40DF0 0023FDF0 000022AE */  sw         $v0, 0x0($s1)
    /* 40DF4 0023FDF4 50FF080C */  jal        func_0023FD40
    /* 40DF8 0023FDF8 3A000426 */   addiu     $a0, $s0, 0x3A
    /* 40DFC 0023FDFC 000042AE */  sw         $v0, 0x0($s2)
    /* 40E00 0023FE00 50FF080C */  jal        func_0023FD40
    /* 40E04 0023FE04 46000426 */   addiu     $a0, $s0, 0x46
    /* 40E08 0023FE08 000062AE */  sw         $v0, 0x0($s3)
    /* 40E0C 0023FE0C 4000BFDF */  ld         $ra, 0x40($sp)
    /* 40E10 0023FE10 3000B3DF */  ld         $s3, 0x30($sp)
    /* 40E14 0023FE14 2000B2DF */  ld         $s2, 0x20($sp)
    /* 40E18 0023FE18 1000B1DF */  ld         $s1, 0x10($sp)
    /* 40E1C 0023FE1C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 40E20 0023FE20 0800E003 */  jr         $ra
    /* 40E24 0023FE24 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_0023FDB8
