.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00245B30, 0x8

glabel func_00245B30
    /* 46B30 00245B30 D0160908 */  j          func_00245B40
    /* 46B34 00245B34 2D200000 */   daddu     $a0, $zero, $zero
endlabel func_00245B30
