.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002565D8, 0x150

glabel func_002565D8
    /* 575D8 002565D8 D0FEBD27 */  addiu      $sp, $sp, -0x130
    /* 575DC 002565DC F000B0FF */  sd         $s0, 0xF0($sp)
    /* 575E0 002565E0 2C00103C */  lui        $s0, %hi(D_002BA7E0)
    /* 575E4 002565E4 0001B1FF */  sd         $s1, 0x100($sp)
    /* 575E8 002565E8 E0A70CC6 */  lwc1       $f12, %lo(D_002BA7E0)($s0)
    /* 575EC 002565EC 2D888000 */  daddu      $s1, $a0, $zero
    /* 575F0 002565F0 2001B4E7 */  swc1       $f20, 0x120($sp)
    /* 575F4 002565F4 1001BFFF */  sd         $ra, 0x110($sp)
    /* 575F8 002565F8 F237090C */  jal        func_0024DFC8
    /* 575FC 002565FC E0A71026 */   addiu     $s0, $s0, %lo(D_002BA7E0)
    /* 57600 00256600 803F013C */  lui        $at, (0x3F800000 >> 16)
    /* 57604 00256604 00A08144 */  mtc1       $at, $f20
    /* 57608 00256608 04000CC6 */  lwc1       $f12, 0x4($s0)
    /* 5760C 0025660C F237090C */  jal        func_0024DFC8
    /* 57610 00256610 C000A0E7 */   swc1      $f0, 0xC0($sp)
    /* 57614 00256614 08000CC6 */  lwc1       $f12, 0x8($s0)
    /* 57618 00256618 F237090C */  jal        func_0024DFC8
    /* 5761C 0025661C C400A0E7 */   swc1      $f0, 0xC4($sp)
    /* 57620 00256620 8000B027 */  addiu      $s0, $sp, 0x80
    /* 57624 00256624 C800A0E7 */  swc1       $f0, 0xC8($sp)
    /* 57628 00256628 CC00B4E7 */  swc1       $f20, 0xCC($sp)
    /* 5762C 0025662C 50EC090C */  jal        sceVu0UnitMatrix
    /* 57630 00256630 2D200002 */   daddu     $a0, $s0, $zero
    /* 57634 00256634 2D200002 */  daddu      $a0, $s0, $zero
    /* 57638 00256638 2D280002 */  daddu      $a1, $s0, $zero
    /* 5763C 0025663C F6EC090C */  jal        sceVu0RotMatrix
    /* 57640 00256640 C000A627 */   addiu     $a2, $sp, 0xC0
    /* 57644 00256644 2D20A003 */  daddu      $a0, $sp, $zero
    /* 57648 00256648 C0042526 */  addiu      $a1, $s1, 0x4C0
    /* 5764C 0025664C D0042626 */  addiu      $a2, $s1, 0x4D0
    /* 57650 00256650 40ED090C */  jal        sceVu0NormalLightMatrix
    /* 57654 00256654 E0042726 */   addiu     $a3, $s1, 0x4E0
    /* 57658 00256658 2D300002 */  daddu      $a2, $s0, $zero
    /* 5765C 0025665C 2D20A003 */  daddu      $a0, $sp, $zero
    /* 57660 00256660 92EB090C */  jal        sceVu0MulMatrix
    /* 57664 00256664 2D28A003 */   daddu     $a1, $sp, $zero
    /* 57668 00256668 D08D838F */  lw         $v1, %gp_rel(D_00370740)($gp)
    /* 5766C 0025666C 0A000224 */  addiu      $v0, $zero, 0xA
    /* 57670 00256670 1E006214 */  bne        $v1, $v0, .L002566EC
    /* 57674 00256674 4000B027 */   addiu     $s0, $sp, 0x40
    /* 57678 00256678 588E848F */  lw         $a0, %gp_rel(D_003707C8)($gp)
    /* 5767C 0025667C E000A527 */  addiu      $a1, $sp, 0xE0
    /* 57680 00256680 E400A627 */  addiu      $a2, $sp, 0xE4
    /* 57684 00256684 6EFF080C */  jal        func_0023FDB8
    /* 57688 00256688 E800A727 */   addiu     $a3, $sp, 0xE8
    /* 5768C 0025668C E000A1C7 */  lwc1       $f1, 0xE0($sp)
    /* 57690 00256690 60088046 */  cvt.s.w    $f1, $f1
    /* 57694 00256694 003C013C */  lui        $at, (0x3C000000 >> 16)
    /* 57698 00256698 00008144 */  mtc1       $at, $f0
    /* 5769C 0025669C E400A2C7 */  lwc1       $f2, 0xE4($sp)
    /* 576A0 002566A0 A0108046 */  cvt.s.w    $f2, $f2
    /* 576A4 002566A4 4000B027 */  addiu      $s0, $sp, 0x40
    /* 576A8 002566A8 E800A3C7 */  lwc1       $f3, 0xE8($sp)
    /* 576AC 002566AC E0188046 */  cvt.s.w    $f3, $f3
    /* 576B0 002566B0 DC00B4E7 */  swc1       $f20, 0xDC($sp)
    /* 576B4 002566B4 42080046 */  mul.s      $f1, $f1, $f0
    /* 576B8 002566B8 10052726 */  addiu      $a3, $s1, 0x510
    /* 576BC 002566BC 82100046 */  mul.s      $f2, $f2, $f0
    /* 576C0 002566C0 2D200002 */  daddu      $a0, $s0, $zero
    /* 576C4 002566C4 C2180046 */  mul.s      $f3, $f3, $f0
    /* 576C8 002566C8 F0042526 */  addiu      $a1, $s1, 0x4F0
    /* 576CC 002566CC D000A1E7 */  swc1       $f1, 0xD0($sp)
    /* 576D0 002566D0 00052626 */  addiu      $a2, $s1, 0x500
    /* 576D4 002566D4 D400A2E7 */  swc1       $f2, 0xD4($sp)
    /* 576D8 002566D8 D000A827 */  addiu      $t0, $sp, 0xD0
    /* 576DC 002566DC 70ED090C */  jal        sceVu0LightColorMatrix
    /* 576E0 002566E0 D800A3E7 */   swc1      $f3, 0xD8($sp)
    /* 576E4 002566E4 08000010 */  b          .L00256708
    /* 576E8 002566E8 2D280002 */   daddu     $a1, $s0, $zero
  .L002566EC:
    /* 576EC 002566EC 20052826 */  addiu      $t0, $s1, 0x520
    /* 576F0 002566F0 2D200002 */  daddu      $a0, $s0, $zero
    /* 576F4 002566F4 F0042526 */  addiu      $a1, $s1, 0x4F0
    /* 576F8 002566F8 00052626 */  addiu      $a2, $s1, 0x500
    /* 576FC 002566FC 70ED090C */  jal        sceVu0LightColorMatrix
    /* 57700 00256700 10052726 */   addiu     $a3, $s1, 0x510
    /* 57704 00256704 2D280002 */  daddu      $a1, $s0, $zero
  .L00256708:
    /* 57708 00256708 60E9080C */  jal        func_0023A580
    /* 5770C 0025670C 2D20A003 */   daddu     $a0, $sp, $zero
    /* 57710 00256710 1001BFDF */  ld         $ra, 0x110($sp)
    /* 57714 00256714 0001B1DF */  ld         $s1, 0x100($sp)
    /* 57718 00256718 F000B0DF */  ld         $s0, 0xF0($sp)
    /* 5771C 0025671C 2001B4C7 */  lwc1       $f20, 0x120($sp)
    /* 57720 00256720 0800E003 */  jr         $ra
    /* 57724 00256724 3001BD27 */   addiu     $sp, $sp, 0x130
endlabel func_002565D8
