.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002569D8, 0x164

glabel func_002569D8
    /* 579D8 002569D8 1C000224 */  addiu      $v0, $zero, 0x1C
    /* 579DC 002569DC B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 579E0 002569E0 18508200 */  mult       $t2, $a0, $v0
    /* 579E4 002569E4 2C00033C */  lui        $v1, %hi(D_002BD910)
    /* 579E8 002569E8 2000B2FF */  sd         $s2, 0x20($sp)
    /* 579EC 002569EC 10D96324 */  addiu      $v1, $v1, %lo(D_002BD910)
    /* 579F0 002569F0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 579F4 002569F4 3C280500 */  dsll32     $a1, $a1, 0
    /* 579F8 002569F8 3F280500 */  dsra32     $a1, $a1, 0
    /* 579FC 002569FC 3000B3FF */  sd         $s3, 0x30($sp)
    /* 57A00 00256A00 2D80E000 */  daddu      $s0, $a3, $zero
    /* 57A04 00256A04 21904301 */  addu       $s2, $t2, $v1
    /* 57A08 00256A08 1000B1FF */  sd         $s1, 0x10($sp)
    /* 57A0C 00256A0C 4000BFFF */  sd         $ra, 0x40($sp)
    /* 57A10 00256A10 3C480900 */  dsll32     $t1, $t1, 0
    /* 57A14 00256A14 3F480900 */  dsra32     $t1, $t1, 0
    /* 57A18 00256A18 2D98C000 */  daddu      $s3, $a2, $zero
    /* 57A1C 00256A1C 2D880001 */  daddu      $s1, $t0, $zero
    /* 57A20 00256A20 3C201000 */  dsll32     $a0, $s0, 0
    /* 57A24 00256A24 3F200400 */  dsra32     $a0, $a0, 0
    /* 57A28 00256A28 000045AE */  sw         $a1, 0x0($s2)
    /* 57A2C 00256A2C BA37090C */  jal        func_0024DEE8
    /* 57A30 00256A30 180049AE */   sw        $t1, 0x18($s2)
    /* 57A34 00256A34 3C201100 */  dsll32     $a0, $s1, 0
    /* 57A38 00256A38 3F200400 */  dsra32     $a0, $a0, 0
    /* 57A3C 00256A3C BA37090C */  jal        func_0024DEE8
    /* 57A40 00256A40 100042AE */   sw        $v0, 0x10($s2)
    /* 57A44 00256A44 3F001066 */  daddiu     $s0, $s0, 0x3F
    /* 57A48 00256A48 3C201300 */  dsll32     $a0, $s3, 0
    /* 57A4C 00256A4C 3F200400 */  dsra32     $a0, $a0, 0
    /* 57A50 00256A50 B82E1000 */  dsll       $a1, $s0, 26
    /* 57A54 00256A54 3F280500 */  dsra32     $a1, $a1, 0
    /* 57A58 00256A58 EDFF6366 */  daddiu     $v1, $s3, -0x13
    /* 57A5C 00256A5C 140042AE */  sw         $v0, 0x14($s2)
    /* 57A60 00256A60 0200632C */  sltiu      $v1, $v1, 0x2
    /* 57A64 00256A64 080044AE */  sw         $a0, 0x8($s2)
    /* 57A68 00256A68 07006010 */  beqz       $v1, .L00256A88
    /* 57A6C 00256A6C 0C0045AE */   sw        $a1, 0xC($s2)
    /* 57A70 00256A70 C2170500 */  srl        $v0, $a1, 31
    /* 57A74 00256A74 2110A200 */  addu       $v0, $a1, $v0
    /* 57A78 00256A78 43100200 */  sra        $v0, $v0, 1
    /* 57A7C 00256A7C 2310A200 */  subu       $v0, $a1, $v0
    /* 57A80 00256A80 40100200 */  sll        $v0, $v0, 1
    /* 57A84 00256A84 0C0042AE */  sw         $v0, 0xC($s2)
  .L00256A88:
    /* 57A88 00256A88 1000458E */  lw         $a1, 0x10($s2)
    /* 57A8C 00256A8C C837090C */  jal        func_0024DF20
    /* 57A90 00256A90 02000424 */   addiu     $a0, $zero, 0x2
    /* 57A94 00256A94 1400458E */  lw         $a1, 0x14($s2)
    /* 57A98 00256A98 2D804000 */  daddu      $s0, $v0, $zero
    /* 57A9C 00256A9C C837090C */  jal        func_0024DF20
    /* 57AA0 00256AA0 02000424 */   addiu     $a0, $zero, 0x2
    /* 57AA4 00256AA4 2D200002 */  daddu      $a0, $s0, $zero
    /* 57AA8 00256AA8 42640A0C */  jal        __muldi3
    /* 57AAC 00256AAC 2D284000 */   daddu     $a1, $v0, $zero
    /* 57AB0 00256AB0 2D204000 */  daddu      $a0, $v0, $zero
    /* 57AB4 00256AB4 02000224 */  addiu      $v0, $zero, 0x2
    /* 57AB8 00256AB8 0C006212 */  beq        $s3, $v0, .L00256AEC
    /* 57ABC 00256ABC 0300622E */   sltiu     $v0, $s3, 0x3
    /* 57AC0 00256AC0 0B004054 */  bnel       $v0, $zero, .L00256AF0
    /* 57AC4 00256AC4 08000524 */   addiu     $a1, $zero, 0x8
    /* 57AC8 00256AC8 13000224 */  addiu      $v0, $zero, 0x13
    /* 57ACC 00256ACC 05006212 */  beq        $s3, $v0, .L00256AE4
    /* 57AD0 00256AD0 14000224 */   addiu     $v0, $zero, 0x14
    /* 57AD4 00256AD4 06006216 */  bne        $s3, $v0, .L00256AF0
    /* 57AD8 00256AD8 08000524 */   addiu     $a1, $zero, 0x8
    /* 57ADC 00256ADC 04000010 */  b          .L00256AF0
    /* 57AE0 00256AE0 01000524 */   addiu     $a1, $zero, 0x1
  .L00256AE4:
    /* 57AE4 00256AE4 02000010 */  b          .L00256AF0
    /* 57AE8 00256AE8 02000524 */   addiu     $a1, $zero, 0x2
  .L00256AEC:
    /* 57AEC 00256AEC 04000524 */  addiu      $a1, $zero, 0x4
  .L00256AF0:
    /* 57AF0 00256AF0 42640A0C */  jal        __muldi3
    /* 57AF4 00256AF4 00000000 */   nop
    /* 57AF8 00256AF8 FFFF4464 */  daddiu     $a0, $v0, -0x1
    /* 57AFC 00256AFC FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 57B00 00256B00 2A186400 */  slt        $v1, $v1, $a0
    /* 57B04 00256B04 FE014264 */  daddiu     $v0, $v0, 0x1FE
    /* 57B08 00256B08 0B108300 */  movn       $v0, $a0, $v1
    /* 57B0C 00256B0C 4000BFDF */  ld         $ra, 0x40($sp)
    /* 57B10 00256B10 7B120200 */  dsra       $v0, $v0, 9
    /* 57B14 00256B14 3000B3DF */  ld         $s3, 0x30($sp)
    /* 57B18 00256B18 01004264 */  daddiu     $v0, $v0, 0x1
    /* 57B1C 00256B1C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 57B20 00256B20 3C100200 */  dsll32     $v0, $v0, 0
    /* 57B24 00256B24 3F100200 */  dsra32     $v0, $v0, 0
    /* 57B28 00256B28 0000B0DF */  ld         $s0, 0x0($sp)
    /* 57B2C 00256B2C 040042AE */  sw         $v0, 0x4($s2)
    /* 57B30 00256B30 2000B2DF */  ld         $s2, 0x20($sp)
    /* 57B34 00256B34 0800E003 */  jr         $ra
    /* 57B38 00256B38 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_002569D8
    /* 57B3C 00256B3C 00000000 */  nop
