.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002547C0, 0x64

glabel func_002547C0
    /* 557C0 002547C0 B88D828F */  lw         $v0, %gp_rel(D_00370728)($gp)
    /* 557C4 002547C4 C0010324 */  addiu      $v1, $zero, 0x1C0
    /* 557C8 002547C8 2C00043C */  lui        $a0, %hi(D_002BD420)
    /* 557CC 002547CC C88E8527 */  addiu      $a1, $gp, %gp_rel(D_00370838)
    /* 557D0 002547D0 18184300 */  mult       $v1, $v0, $v1
    /* 557D4 002547D4 20D48424 */  addiu      $a0, $a0, %lo(D_002BD420)
    /* 557D8 002547D8 80100200 */  sll        $v0, $v0, 2
    /* 557DC 002547DC 2D300000 */  daddu      $a2, $zero, $zero
    /* 557E0 002547E0 21104500 */  addu       $v0, $v0, $a1
    /* 557E4 002547E4 21186400 */  addu       $v1, $v1, $a0
    /* 557E8 002547E8 A001638C */  lw         $v1, 0x1A0($v1)
    /* 557EC 002547EC 0B006018 */  blez       $v1, .L0025481C
    /* 557F0 002547F0 0000458C */   lw        $a1, 0x0($v0)
    /* 557F4 002547F4 00000000 */  nop
  .L002547F8:
    /* 557F8 002547F8 9000A28C */  lw         $v0, 0x90($a1)
    /* 557FC 002547FC 08004230 */  andi       $v0, $v0, 0x8
    /* 55800 00254800 03004010 */  beqz       $v0, .L00254810
    /* 55804 00254804 0100C624 */   addiu     $a2, $a2, 0x1
    /* 55808 00254808 0800E003 */  jr         $ra
    /* 5580C 0025480C 2D100000 */   daddu     $v0, $zero, $zero
  .L00254810:
    /* 55810 00254810 2A10C300 */  slt        $v0, $a2, $v1
    /* 55814 00254814 F8FF4014 */  bnez       $v0, .L002547F8
    /* 55818 00254818 A006A524 */   addiu     $a1, $a1, 0x6A0
  .L0025481C:
    /* 5581C 0025481C 0800E003 */  jr         $ra
    /* 55820 00254820 01000224 */   addiu     $v0, $zero, 0x1
endlabel func_002547C0
