.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0026D2F8, 0x64

glabel func_0026D2F8
    /* 6E2F8 0026D2F8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 6E2FC 0026D2FC 5000023C */  lui        $v0, %hi(D_004FD1A8)
    /* 6E300 0026D300 0000B0FF */  sd         $s0, 0x0($sp)
    /* 6E304 0026D304 01000324 */  addiu      $v1, $zero, 0x1
    /* 6E308 0026D308 A8D15024 */  addiu      $s0, $v0, %lo(D_004FD1A8)
    /* 6E30C 0026D30C 1000BFFF */  sd         $ra, 0x10($sp)
    /* 6E310 0026D310 A8D144AC */  sw         $a0, -0x2E58($v0)
    /* 6E314 0026D314 00200624 */  addiu      $a2, $zero, 0x2000
    /* 6E318 0026D318 184005AE */  sw         $a1, 0x4018($s0)
    /* 6E31C 0026D31C 18000426 */  addiu      $a0, $s0, 0x18
    /* 6E320 0026D320 040003AE */  sw         $v1, 0x4($s0)
    /* 6E324 0026D324 2D280000 */  daddu      $a1, $zero, $zero
    /* 6E328 0026D328 080000AE */  sw         $zero, 0x8($s0)
    /* 6E32C 0026D32C 5E710A0C */  jal        memset
    /* 6E330 0026D330 0C0000AE */   sw        $zero, 0xC($s0)
    /* 6E334 0026D334 18200426 */  addiu      $a0, $s0, 0x2018
    /* 6E338 0026D338 2D280000 */  daddu      $a1, $zero, $zero
    /* 6E33C 0026D33C 5E710A0C */  jal        memset
    /* 6E340 0026D340 00200624 */   addiu     $a2, $zero, 0x2000
    /* 6E344 0026D344 140000A6 */  sh         $zero, 0x14($s0)
    /* 6E348 0026D348 100000A2 */  sb         $zero, 0x10($s0)
    /* 6E34C 0026D34C 1000BFDF */  ld         $ra, 0x10($sp)
    /* 6E350 0026D350 0000B0DF */  ld         $s0, 0x0($sp)
    /* 6E354 0026D354 0800E003 */  jr         $ra
    /* 6E358 0026D358 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0026D2F8
