.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0025A4F0, 0xA4

glabel func_0025A4F0
    /* 5B4F0 0025A4F0 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 5B4F4 0025A4F4 C88E8327 */  addiu      $v1, $gp, %gp_rel(D_00370838)
    /* 5B4F8 0025A4F8 2000B2FF */  sd         $s2, 0x20($sp)
    /* 5B4FC 0025A4FC 1000B1FF */  sd         $s1, 0x10($sp)
    /* 5B500 0025A500 01001224 */  addiu      $s2, $zero, 0x1
    /* 5B504 0025A504 4000B4E7 */  swc1       $f20, 0x40($sp)
    /* 5B508 0025A508 2D880000 */  daddu      $s1, $zero, $zero
    /* 5B50C 0025A50C 3000BFFF */  sd         $ra, 0x30($sp)
    /* 5B510 0025A510 0000B0FF */  sd         $s0, 0x0($sp)
    /* 5B514 0025A514 803F013C */  lui        $at, (0x3F800000 >> 16)
    /* 5B518 0025A518 00A08144 */  mtc1       $at, $f20
    /* 5B51C 0025A51C 2001828C */  lw         $v0, 0x120($a0)
    /* 5B520 0025A520 80100200 */  sll        $v0, $v0, 2
    /* 5B524 0025A524 21104300 */  addu       $v0, $v0, $v1
    /* 5B528 0025A528 0000508C */  lw         $s0, 0x0($v0)
    /* 5B52C 0025A52C 00000000 */  nop
  .L0025A530:
    /* 5B530 0025A530 2D200002 */  daddu      $a0, $s0, $zero
    /* 5B534 0025A534 2D280000 */  daddu      $a1, $zero, $zero
    /* 5B538 0025A538 5E710A0C */  jal        memset
    /* 5B53C 0025A53C A0060624 */   addiu     $a2, $zero, 0x6A0
    /* 5B540 0025A540 940011AE */  sw         $s1, 0x94($s0)
    /* 5B544 0025A544 900012AE */  sw         $s2, 0x90($s0)
    /* 5B548 0025A548 01003126 */  addiu      $s1, $s1, 0x1
    /* 5B54C 0025A54C 000000AE */  sw         $zero, 0x0($s0)
    /* 5B550 0025A550 0004222A */  slti       $v0, $s1, 0x400
    /* 5B554 0025A554 040000AE */  sw         $zero, 0x4($s0)
    /* 5B558 0025A558 080000AE */  sw         $zero, 0x8($s0)
    /* 5B55C 0025A55C 0C0014E6 */  swc1       $f20, 0xC($s0)
    /* 5B560 0025A560 100000AE */  sw         $zero, 0x10($s0)
    /* 5B564 0025A564 140000AE */  sw         $zero, 0x14($s0)
    /* 5B568 0025A568 180000AE */  sw         $zero, 0x18($s0)
    /* 5B56C 0025A56C 1C0014E6 */  swc1       $f20, 0x1C($s0)
    /* 5B570 0025A570 EFFF4014 */  bnez       $v0, .L0025A530
    /* 5B574 0025A574 A0061026 */   addiu     $s0, $s0, 0x6A0
    /* 5B578 0025A578 3000BFDF */  ld         $ra, 0x30($sp)
    /* 5B57C 0025A57C 2000B2DF */  ld         $s2, 0x20($sp)
    /* 5B580 0025A580 1000B1DF */  ld         $s1, 0x10($sp)
    /* 5B584 0025A584 0000B0DF */  ld         $s0, 0x0($sp)
    /* 5B588 0025A588 4000B4C7 */  lwc1       $f20, 0x40($sp)
    /* 5B58C 0025A58C 0800E003 */  jr         $ra
    /* 5B590 0025A590 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_0025A4F0
