.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0023F6F8, 0x148

glabel func_0023F6F8
    /* 406F8 0023F6F8 80FBBD27 */  addiu      $sp, $sp, -0x480
    /* 406FC 0023F6FC AC9180AF */  sw         $zero, %gp_rel(D_00370B1C)($gp)
    /* 40700 0023F700 0004B1FF */  sd         $s1, 0x400($sp)
    /* 40704 0023F704 5004B6FF */  sd         $s6, 0x450($sp)
    /* 40708 0023F708 4700113C */  lui        $s1, (0x470EE0 >> 16)
    /* 4070C 0023F70C 4004B5FF */  sd         $s5, 0x440($sp)
    /* 40710 0023F710 2DB0C000 */  daddu      $s6, $a2, $zero
    /* 40714 0023F714 3004B4FF */  sd         $s4, 0x430($sp)
    /* 40718 0023F718 2DA88000 */  daddu      $s5, $a0, $zero
    /* 4071C 0023F71C F003B0FF */  sd         $s0, 0x3F0($sp)
    /* 40720 0023F720 2DA0A000 */  daddu      $s4, $a1, $zero
    /* 40724 0023F724 E00E3026 */  addiu      $s0, $s1, %lo(D_00470EE0)
    /* 40728 0023F728 6004B7FF */  sd         $s7, 0x460($sp)
    /* 4072C 0023F72C 2004B3FF */  sd         $s3, 0x420($sp)
    /* 40730 0023F730 2DB82001 */  daddu      $s7, $t1, $zero
    /* 40734 0023F734 1004B2FF */  sd         $s2, 0x410($sp)
    /* 40738 0023F738 2D980001 */  daddu      $s3, $t0, $zero
    /* 4073C 0023F73C 2D90E000 */  daddu      $s2, $a3, $zero
    /* 40740 0023F740 7004BFFF */  sd         $ra, 0x470($sp)
    /* 40744 0023F744 2D200002 */  daddu      $a0, $s0, $zero
    /* 40748 0023F748 2D280000 */  daddu      $a1, $zero, $zero
    /* 4074C 0023F74C 5E710A0C */  jal        memset
    /* 40750 0023F750 00080624 */   addiu     $a2, $zero, 0x800
    /* 40754 0023F754 10040426 */  addiu      $a0, $s0, 0x410
    /* 40758 0023F758 64740A0C */  jal        strcpy
    /* 4075C 0023F75C 2D288002 */   daddu     $a1, $s4, $zero
    /* 40760 0023F760 20000426 */  addiu      $a0, $s0, 0x20
    /* 40764 0023F764 64740A0C */  jal        strcpy
    /* 40768 0023F768 2D288002 */   daddu     $a1, $s4, $zero
    /* 4076C 0023F76C E00E36AE */  sw         $s6, (0x470EE0 & 0xFFFF)($s1)
    /* 40770 0023F770 8000C426 */  addiu      $a0, $s6, 0x80
    /* 40774 0023F774 0C0012AE */  sw         $s2, 0xC($s0)
    /* 40778 0023F778 2D288002 */  daddu      $a1, $s4, $zero
    /* 4077C 0023F77C 140015AE */  sw         $s5, 0x14($s0)
    /* 40780 0023F780 100015AE */  sw         $s5, 0x10($s0)
    /* 40784 0023F784 64740A0C */  jal        strcpy
    /* 40788 0023F788 180000AE */   sw        $zero, 0x18($s0)
    /* 4078C 0023F78C 01000224 */  addiu      $v0, $zero, 0x1
    /* 40790 0023F790 08006212 */  beq        $s3, $v0, .L0023F7B4
    /* 40794 0023F794 080017AE */   sw        $s7, 0x8($s0)
    /* 40798 0023F798 05000224 */  addiu      $v0, $zero, 0x5
    /* 4079C 0023F79C 05006212 */  beq        $s3, $v0, .L0023F7B4
    /* 407A0 0023F7A0 03000224 */   addiu     $v0, $zero, 0x3
    /* 407A4 0023F7A4 03006212 */  beq        $s3, $v0, .L0023F7B4
    /* 407A8 0023F7A8 07000224 */   addiu     $v0, $zero, 0x7
    /* 407AC 0023F7AC 07006216 */  bne        $s3, $v0, .L0023F7CC
    /* 407B0 0023F7B0 0010E232 */   andi      $v0, $s7, 0x1000
  .L0023F7B4:
    /* 407B4 0023F7B4 2D20A002 */  daddu      $a0, $s5, $zero
    /* 407B8 0023F7B8 2D288002 */  daddu      $a1, $s4, $zero
    /* 407BC 0023F7BC DAF7080C */  jal        func_0023DF68
    /* 407C0 0023F7C0 2D30C002 */   daddu     $a2, $s6, $zero
    /* 407C4 0023F7C4 13000010 */  b          .L0023F814
    /* 407C8 0023F7C8 7004BFDF */   ld        $ra, 0x470($sp)
  .L0023F7CC:
    /* 407CC 0023F7CC 0C004010 */  beqz       $v0, .L0023F800
    /* 407D0 0023F7D0 2D308002 */   daddu     $a2, $s4, $zero
    /* 407D4 0023F7D4 3700053C */  lui        $a1, %hi(aSS_6)
    /* 407D8 0023F7D8 2D38C000 */  daddu      $a3, $a2, $zero
    /* 407DC 0023F7DC 2804A524 */  addiu      $a1, $a1, %lo(aSS_6)
    /* 407E0 0023F7E0 EC720A0C */  jal        sprintf
    /* 407E4 0023F7E4 2D20A003 */   daddu     $a0, $sp, $zero
    /* 407E8 0023F7E8 2D20A002 */  daddu      $a0, $s5, $zero
    /* 407EC 0023F7EC 2D30C002 */  daddu      $a2, $s6, $zero
    /* 407F0 0023F7F0 DAF7080C */  jal        func_0023DF68
    /* 407F4 0023F7F4 2D28A003 */   daddu     $a1, $sp, $zero
    /* 407F8 0023F7F8 06000010 */  b          .L0023F814
    /* 407FC 0023F7FC 7004BFDF */   ld        $ra, 0x470($sp)
  .L0023F800:
    /* 40800 0023F800 2D20A002 */  daddu      $a0, $s5, $zero
    /* 40804 0023F804 2D288002 */  daddu      $a1, $s4, $zero
    /* 40808 0023F808 50FD080C */  jal        browser_icon_sys_related_ps1
    /* 4080C 0023F80C 2D30C002 */   daddu     $a2, $s6, $zero
    /* 40810 0023F810 7004BFDF */  ld         $ra, 0x470($sp)
  .L0023F814:
    /* 40814 0023F814 2D100000 */  daddu      $v0, $zero, $zero
    /* 40818 0023F818 6004B7DF */  ld         $s7, 0x460($sp)
    /* 4081C 0023F81C 5004B6DF */  ld         $s6, 0x450($sp)
    /* 40820 0023F820 4004B5DF */  ld         $s5, 0x440($sp)
    /* 40824 0023F824 3004B4DF */  ld         $s4, 0x430($sp)
    /* 40828 0023F828 2004B3DF */  ld         $s3, 0x420($sp)
    /* 4082C 0023F82C 1004B2DF */  ld         $s2, 0x410($sp)
    /* 40830 0023F830 0004B1DF */  ld         $s1, 0x400($sp)
    /* 40834 0023F834 F003B0DF */  ld         $s0, 0x3F0($sp)
    /* 40838 0023F838 0800E003 */  jr         $ra
    /* 4083C 0023F83C 8004BD27 */   addiu     $sp, $sp, 0x480
endlabel func_0023F6F8
