.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0023A708, 0xEC

glabel func_0023A708
    /* 3B708 0023A708 2D408000 */  daddu      $t0, $a0, $zero
    /* 3B70C 0023A70C 201C033C */  lui        $v1, (0x1C208000 >> 16)
    /* 3B710 0023A710 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 3B714 0023A714 00806334 */  ori        $v1, $v1, (0x1C208000 & 0xFFFF)
    /* 3B718 0023A718 0010043C */  lui        $a0, (0x10009020 >> 16)
    /* 3B71C 0023A71C 2B00053C */  lui        $a1, %hi(D_002A8010)
    /* 3B720 0023A720 FF0F023C */  lui        $v0, (0xFFFFFFF >> 16)
    /* 3B724 0023A724 0000BFFF */  sd         $ra, 0x0($sp)
    /* 3B728 0023A728 25180301 */  or         $v1, $t0, $v1
    /* 3B72C 0023A72C 20908434 */  ori        $a0, $a0, (0x10009020 & 0xFFFF)
    /* 3B730 0023A730 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFF & 0xFFFF)
    /* 3B734 0023A734 1080A524 */  addiu      $a1, $a1, %lo(D_002A8010)
    /* 3B738 0023A738 2428A200 */  and        $a1, $a1, $v0
    /* 3B73C 0023A73C 000080AC */  sw         $zero, 0x0($a0)
    /* 3B740 0023A740 3C180300 */  dsll32     $v1, $v1, 0
    /* 3B744 0023A744 3C400800 */  dsll32     $t0, $t0, 0
    /* 3B748 0023A748 3E180300 */  dsrl32     $v1, $v1, 0
    /* 3B74C 0023A74C 00E00234 */  ori        $v0, $zero, 0xE000
    /* 3B750 0023A750 78140200 */  dsll       $v0, $v0, 17
    /* 3B754 0023A754 80800434 */  ori        $a0, $zero, 0x8080
    /* 3B758 0023A758 BC220400 */  dsll32     $a0, $a0, 10
    /* 3B75C 0023A75C 0010063C */  lui        $a2, (0x10009030 >> 16)
    /* 3B760 0023A760 2B00093C */  lui        $t1, %hi(D_002A8050)
    /* 3B764 0023A764 3090C634 */  ori        $a2, $a2, (0x10009030 & 0xFFFF)
    /* 3B768 0023A768 25186200 */  or         $v1, $v1, $v0
    /* 3B76C 0023A76C 25400401 */  or         $t0, $t0, $a0
    /* 3B770 0023A770 0000C5AC */  sw         $a1, 0x0($a2)
    /* 3B774 0023A774 50802225 */  addiu      $v0, $t1, %lo(D_002A8050)
    /* 3B778 0023A778 508023FD */  sd         $v1, %lo(D_002A8050)($t1)
    /* 3B77C 0023A77C 80000424 */  addiu      $a0, $zero, 0x80
    /* 3B780 0023A780 3C200400 */  dsll32     $a0, $a0, 0
    /* 3B784 0023A784 80008434 */  ori        $a0, $a0, 0x80
    /* 3B788 0023A788 0010073C */  lui        $a3, (0x1000E010 >> 16)
    /* 3B78C 0023A78C 61000624 */  addiu      $a2, $zero, 0x61
    /* 3B790 0023A790 10E0E734 */  ori        $a3, $a3, (0x1000E010 & 0xFFFF)
    /* 3B794 0023A794 02000524 */  addiu      $a1, $zero, 0x2
    /* 3B798 0023A798 400044FC */  sd         $a0, 0x40($v0)
    /* 3B79C 0023A79C 2D200000 */  daddu      $a0, $zero, $zero
    /* 3B7A0 0023A7A0 0000E5AC */  sw         $a1, 0x0($a3)
    /* 3B7A4 0023A7A4 100046FC */  sd         $a2, 0x10($v0)
    /* 3B7A8 0023A7A8 E4FE090C */  jal        FlushCache
    /* 3B7AC 0023A7AC 200048FC */   sd        $t0, 0x20($v0)
    /* 3B7B0 0023A7B0 0010023C */  lui        $v0, (0x10009000 >> 16)
    /* 3B7B4 0023A7B4 45010324 */  addiu      $v1, $zero, 0x145
    /* 3B7B8 0023A7B8 00904234 */  ori        $v0, $v0, (0x10009000 & 0xFFFF)
    /* 3B7BC 0023A7BC 0010043C */  lui        $a0, (0x10009000 >> 16)
    /* 3B7C0 0023A7C0 000043AC */  sw         $v1, 0x0($v0)
    /* 3B7C4 0023A7C4 00908434 */  ori        $a0, $a0, (0x10009000 & 0xFFFF)
  .L0023A7C8:
    /* 3B7C8 0023A7C8 0000828C */  lw         $v0, 0x0($a0)
    /* 3B7CC 0023A7CC 00014230 */  andi       $v0, $v0, 0x100
    /* 3B7D0 0023A7D0 00000000 */  nop
    /* 3B7D4 0023A7D4 00000000 */  nop
    /* 3B7D8 0023A7D8 00000000 */  nop
    /* 3B7DC 0023A7DC FAFF4014 */  bnez       $v0, .L0023A7C8
    /* 3B7E0 0023A7E0 00000000 */   nop
    /* 3B7E4 0023A7E4 0000BFDF */  ld         $ra, 0x0($sp)
    /* 3B7E8 0023A7E8 2D100000 */  daddu      $v0, $zero, $zero
    /* 3B7EC 0023A7EC 0800E003 */  jr         $ra
    /* 3B7F0 0023A7F0 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_0023A708
