.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00249728, 0x58

glabel func_00249728
    /* 4A728 00249728 02000824 */  addiu      $t0, $zero, 0x2
    /* 4A72C 0024972C 04000324 */  addiu      $v1, $zero, 0x4
    /* 4A730 00249730 B88C83AF */  sw         $v1, %gp_rel(D_00370628)($gp)
    /* 4A734 00249734 08008228 */  slti       $v0, $a0, 0x8
    /* 4A738 00249738 948C88AF */  sw         $t0, %gp_rel(D_00370604)($gp)
    /* 4A73C 0024973C 03004014 */  bnez       $v0, .L0024974C
    /* 4A740 00249740 BC8C84AF */   sw        $a0, %gp_rel(D_0037062C)($gp)
    /* 4A744 00249744 07000010 */  b          .L00249764
    /* 4A748 00249748 C48C88AF */   sw        $t0, %gp_rel(D_00370634)($gp)
  .L0024974C:
    /* 4A74C 0024974C 2C00023C */  lui        $v0, %hi(D_002BB938)
    /* 4A750 00249750 80200400 */  sll        $a0, $a0, 2
    /* 4A754 00249754 38B94224 */  addiu      $v0, $v0, %lo(D_002BB938)
    /* 4A758 00249758 21104400 */  addu       $v0, $v0, $a0
    /* 4A75C 0024975C 2C04438C */  lw         $v1, 0x42C($v0)
    /* 4A760 00249760 C48C83AF */  sw         $v1, %gp_rel(D_00370634)($gp)
  .L00249764:
    /* 4A764 00249764 C001A224 */  addiu      $v0, $a1, 0x1C0
    /* 4A768 00249768 D08C87AF */  sw         $a3, %gp_rel(D_00370640)($gp)
    /* 4A76C 0024976C D48C82AF */  sw         $v0, %gp_rel(D_00370644)($gp)
    /* 4A770 00249770 149286AF */  sw         $a2, %gp_rel(D_00370B84)($gp)
    /* 4A774 00249774 E08C85AF */  sw         $a1, %gp_rel(D_00370650)($gp)
    /* 4A778 00249778 0800E003 */  jr         $ra
    /* 4A77C 0024977C E48C80A3 */   sb        $zero, %gp_rel(D_00370654)($gp)
endlabel func_00249728
