.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0025D608, 0xAC

glabel func_0025D608
    /* 5E608 0025D608 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 5E60C 0025D60C 2D408000 */  daddu      $t0, $a0, $zero
    /* 5E610 0025D610 5000BFFF */  sd         $ra, 0x50($sp)
    /* 5E614 0025D614 4000B0FF */  sd         $s0, 0x40($sp)
    /* 5E618 0025D618 2F000224 */  addiu      $v0, $zero, 0x2F
    /* 5E61C 0025D61C 01000391 */  lbu        $v1, 0x1($t0)
    /* 5E620 0025D620 11006210 */  beq        $v1, $v0, .L0025D668
    /* 5E624 0025D624 2D300000 */   daddu     $a2, $zero, $zero
    /* 5E628 0025D628 2D100001 */  daddu      $v0, $t0, $zero
    /* 5E62C 0025D62C 4E00103C */  lui        $s0, %hi(D_004DC480)
    /* 5E630 0025D630 3600053C */  lui        $a1, %hi(aPatHdd0SS)
    /* 5E634 0025D634 01004490 */  lbu        $a0, 0x1($v0)
  .L0025D638:
    /* 5E638 0025D638 2118A603 */  addu       $v1, $sp, $a2
    /* 5E63C 0025D63C 0100C624 */  addiu      $a2, $a2, 0x1
    /* 5E640 0025D640 2000C228 */  slti       $v0, $a2, 0x20
    /* 5E644 0025D644 0A004010 */  beqz       $v0, .L0025D670
    /* 5E648 0025D648 000064A0 */   sb        $a0, 0x0($v1)
    /* 5E64C 0025D64C 2110C800 */  addu       $v0, $a2, $t0
    /* 5E650 0025D650 2F000424 */  addiu      $a0, $zero, 0x2F
    /* 5E654 0025D654 01004390 */  lbu        $v1, 0x1($v0)
    /* 5E658 0025D658 F7FF6454 */  bnel       $v1, $a0, .L0025D638
    /* 5E65C 0025D65C 01004490 */   lbu       $a0, 0x1($v0)
    /* 5E660 0025D660 04000010 */  b          .L0025D674
    /* 5E664 0025D664 80C41026 */   addiu     $s0, $s0, %lo(D_004DC480)
  .L0025D668:
    /* 5E668 0025D668 4E00103C */  lui        $s0, %hi(D_004DC480)
    /* 5E66C 0025D66C 3600053C */  lui        $a1, %hi(aPatHdd0SS)
  .L0025D670:
    /* 5E670 0025D670 80C41026 */  addiu      $s0, $s0, %lo(D_004DC480)
  .L0025D674:
    /* 5E674 0025D674 0200C724 */  addiu      $a3, $a2, 0x2
    /* 5E678 0025D678 2110A603 */  addu       $v0, $sp, $a2
    /* 5E67C 0025D67C 2D200002 */  daddu      $a0, $s0, $zero
    /* 5E680 0025D680 21380701 */  addu       $a3, $t0, $a3
    /* 5E684 0025D684 000040A0 */  sb         $zero, 0x0($v0)
    /* 5E688 0025D688 3867A524 */  addiu      $a1, $a1, %lo(aPatHdd0SS)
    /* 5E68C 0025D68C EC720A0C */  jal        sprintf
    /* 5E690 0025D690 2D30A003 */   daddu     $a2, $sp, $zero
    /* 5E694 0025D694 0093858F */  lw         $a1, %gp_rel(D_00370C70)($gp)
    /* 5E698 0025D698 2D200002 */  daddu      $a0, $s0, $zero
    /* 5E69C 0025D69C A43A080C */  jal        fileops_cmd_open
    /* 5E6A0 0025D6A0 FF010624 */   addiu     $a2, $zero, 0x1FF
    /* 5E6A4 0025D6A4 5000BFDF */  ld         $ra, 0x50($sp)
    /* 5E6A8 0025D6A8 4000B0DF */  ld         $s0, 0x40($sp)
    /* 5E6AC 0025D6AC 0800E003 */  jr         $ra
    /* 5E6B0 0025D6B0 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel func_0025D608
