.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002544A8, 0x30

glabel func_002544A8
    /* 554A8 002544A8 6C8E80AF */  sw         $zero, %gp_rel(D_003707DC)($gp)
    /* 554AC 002544AC 708E80AF */  sw         $zero, %gp_rel(D_003707E0)($gp)
    /* 554B0 002544B0 6C8E80C7 */  lwc1       $f0, %gp_rel(D_003707DC)($gp)
    /* 554B4 002544B4 7C8E80AF */  sw         $zero, %gp_rel(D_003707EC)($gp)
    /* 554B8 002544B8 788E80AF */  sw         $zero, %gp_rel(D_003707E8)($gp)
    /* 554BC 002544BC 748E80AF */  sw         $zero, %gp_rel(D_003707E4)($gp)
    /* 554C0 002544C0 488E80AF */  sw         $zero, %gp_rel(D_003707B8)($gp)
    /* 554C4 002544C4 4C8E80AF */  sw         $zero, %gp_rel(D_003707BC)($gp)
    /* 554C8 002544C8 000180E4 */  swc1       $f0, 0x100($a0)
    /* 554CC 002544CC 080180E4 */  swc1       $f0, 0x108($a0)
    /* 554D0 002544D0 0800E003 */  jr         $ra
    /* 554D4 002544D4 040180E4 */   swc1      $f0, 0x104($a0)
endlabel func_002544A8
