.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00260BD8, 0x48

glabel func_00260BD8
    /* 61BD8 00260BD8 449085AF */  sw         $a1, %gp_rel(D_003709B4)($gp)
    /* 61BDC 00260BDC 409080AF */  sw         $zero, %gp_rel(D_003709B0)($gp)
    /* 61BE0 00260BE0 2D280000 */  daddu      $a1, $zero, $zero
    /* 61BE4 00260BE4 3C9080AF */  sw         $zero, %gp_rel(D_003709AC)($gp)
    /* 61BE8 00260BE8 0B008018 */  blez       $a0, .L00260C18
    /* 61BEC 00260BEC 489084AF */   sw        $a0, %gp_rel(D_003709B8)($gp)
    /* 61BF0 00260BF0 3100063C */  lui        $a2, %hi(D_00310CB8)
    /* 61BF4 00260BF4 00000000 */  nop
  .L00260BF8:
    /* 61BF8 00260BF8 80100500 */  sll        $v0, $a1, 2
    /* 61BFC 00260BFC B80CC324 */  addiu      $v1, $a2, %lo(D_00310CB8)
    /* 61C00 00260C00 21104300 */  addu       $v0, $v0, $v1
    /* 61C04 00260C04 0100A524 */  addiu      $a1, $a1, 0x1
    /* 61C08 00260C08 000040AC */  sw         $zero, 0x0($v0)
    /* 61C0C 00260C0C 2A18A400 */  slt        $v1, $a1, $a0
    /* 61C10 00260C10 F9FF6014 */  bnez       $v1, .L00260BF8
    /* 61C14 00260C14 00000000 */   nop
  .L00260C18:
    /* 61C18 00260C18 0800E003 */  jr         $ra
    /* 61C1C 00260C1C 00000000 */   nop
endlabel func_00260BD8
