.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0023E368, 0x11C

glabel func_0023E368
    /* 3F368 0023E368 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 3F36C 0023E36C 01000624 */  addiu      $a2, $zero, 0x1
    /* 3F370 0023E370 4000B4FF */  sd         $s4, 0x40($sp)
    /* 3F374 0023E374 0B010224 */  addiu      $v0, $zero, 0x10B
    /* 3F378 0023E378 2000B2FF */  sd         $s2, 0x20($sp)
    /* 3F37C 0023E37C 4700143C */  lui        $s4, %hi(D_00470EE0)
    /* 3F380 0023E380 1000B1FF */  sd         $s1, 0x10($sp)
    /* 3F384 0023E384 E00E8726 */  addiu      $a3, $s4, %lo(D_00470EE0)
    /* 3F388 0023E388 5000BFFF */  sd         $ra, 0x50($sp)
    /* 3F38C 0023E38C 2D908000 */  daddu      $s2, $a0, $zero
    /* 3F390 0023E390 3000B3FF */  sd         $s3, 0x30($sp)
    /* 3F394 0023E394 0000B0FF */  sd         $s0, 0x0($sp)
    /* 3F398 0023E398 1C00E6AC */  sw         $a2, 0x1C($a3)
    /* 3F39C 0023E39C 1000E38C */  lw         $v1, 0x10($a3)
    /* 3F3A0 0023E3A0 0B006214 */  bne        $v1, $v0, .L0023E3D0
    /* 3F3A4 0023E3A4 2D88A000 */   daddu     $s1, $a1, $zero
    /* 3F3A8 0023E3A8 1400E68C */  lw         $a2, 0x14($a3)
    /* 3F3AC 0023E3AC 4700103C */  lui        $s0, %hi(D_0046FAF8)
    /* 3F3B0 0023E3B0 3700053C */  lui        $a1, %hi(aMcDS_0)
    /* 3F3B4 0023E3B4 2000E724 */  addiu      $a3, $a3, 0x20
    /* 3F3B8 0023E3B8 9803A524 */  addiu      $a1, $a1, %lo(aMcDS_0)
    /* 3F3BC 0023E3BC EC720A0C */  jal        sprintf
    /* 3F3C0 0023E3C0 F8FA0426 */   addiu     $a0, $s0, %lo(D_0046FAF8)
    /* 3F3C4 0023E3C4 02000324 */  addiu      $v1, $zero, 0x2
    /* 3F3C8 0023E3C8 09000010 */  b          .L0023E3F0
    /* 3F3CC 0023E3CC 080023AE */   sw        $v1, 0x8($s1)
  .L0023E3D0:
    /* 3F3D0 0023E3D0 1400E68C */  lw         $a2, 0x14($a3)
    /* 3F3D4 0023E3D4 4700103C */  lui        $s0, %hi(D_0046FAF8)
    /* 3F3D8 0023E3D8 3700053C */  lui        $a1, %hi(aMcDS_0)
    /* 3F3DC 0023E3DC F8FA0426 */  addiu      $a0, $s0, %lo(D_0046FAF8)
    /* 3F3E0 0023E3E0 9803A524 */  addiu      $a1, $a1, %lo(aMcDS_0)
    /* 3F3E4 0023E3E4 EC720A0C */  jal        sprintf
    /* 3F3E8 0023E3E8 2D384002 */   daddu     $a3, $s2, $zero
    /* 3F3EC 0023E3EC 080020AE */  sw         $zero, 0x8($s1)
  .L0023E3F0:
    /* 3F3F0 0023E3F0 F8FA1326 */  addiu      $s3, $s0, %lo(D_0046FAF8)
    /* 3F3F4 0023E3F4 AC918527 */  addiu      $a1, $gp, %gp_rel(D_00370B1C)
    /* 3F3F8 0023E3F8 426C090C */  jal        func_0025B108
    /* 3F3FC 0023E3FC 2D206002 */   daddu     $a0, $s3, $zero
    /* 3F400 0023E400 2D804000 */  daddu      $s0, $v0, $zero
    /* 3F404 0023E404 AC91828F */  lw         $v0, %gp_rel(D_00370B1C)($gp)
    /* 3F408 0023E408 0B004010 */  beqz       $v0, .L0023E438
    /* 3F40C 0023E40C 100030AE */   sw        $s0, 0x10($s1)
    /* 3F410 0023E410 2D200002 */  daddu      $a0, $s0, $zero
    /* 3F414 0023E414 5000BFDF */  ld         $ra, 0x50($sp)
    /* 3F418 0023E418 4000B4DF */  ld         $s4, 0x40($sp)
    /* 3F41C 0023E41C 01000524 */  addiu      $a1, $zero, 0x1
    /* 3F420 0023E420 3000B3DF */  ld         $s3, 0x30($sp)
    /* 3F424 0023E424 2000B2DF */  ld         $s2, 0x20($sp)
    /* 3F428 0023E428 1000B1DF */  ld         $s1, 0x10($sp)
    /* 3F42C 0023E42C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 3F430 0023E430 D66A0908 */  j          func_0025AB58
    /* 3F434 0023E434 6000BD27 */   addiu     $sp, $sp, 0x60
  .L0023E438:
    /* 3F438 0023E438 E00E8226 */  addiu      $v0, $s4, %lo(D_00470EE0)
    /* 3F43C 0023E43C 2D284002 */  daddu      $a1, $s2, $zero
    /* 3F440 0023E440 1000448C */  lw         $a0, 0x10($v0)
    /* 3F444 0023E444 7C01063C */  lui        $a2, (0x17C0000 >> 16)
    /* 3F448 0023E448 20F2080C */  jal        func_0023C880
    /* 3F44C 0023E44C 040050AC */   sw        $s0, 0x4($v0)
    /* 3F450 0023E450 80121000 */  sll        $v0, $s0, 10
    /* 3F454 0023E454 2D286002 */  daddu      $a1, $s3, $zero
    /* 3F458 0023E458 2E00043C */  lui        $a0, %hi(D_002DA620)
    /* 3F45C 0023E45C 5000BFDF */  ld         $ra, 0x50($sp)
    /* 3F460 0023E460 20A68424 */  addiu      $a0, $a0, %lo(D_002DA620)
    /* 3F464 0023E464 4000B4DF */  ld         $s4, 0x40($sp)
    /* 3F468 0023E468 3000B3DF */  ld         $s3, 0x30($sp)
    /* 3F46C 0023E46C 21204400 */  addu       $a0, $v0, $a0
    /* 3F470 0023E470 2000B2DF */  ld         $s2, 0x20($sp)
    /* 3F474 0023E474 1000B1DF */  ld         $s1, 0x10($sp)
    /* 3F478 0023E478 0000B0DF */  ld         $s0, 0x0($sp)
    /* 3F47C 0023E47C 64740A08 */  j          strcpy
    /* 3F480 0023E480 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel func_0023E368
