.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00265588, 0x2C

glabel func_00265588
    /* 66588 00265588 3700033C */  lui        $v1, %hi(D_003706B0)
    /* 6658C 0026558C B006628C */  lw         $v0, %lo(D_003706B0)($v1)
    /* 66590 00265590 06004010 */  beqz       $v0, .L002655AC
    /* 66594 00265594 00000000 */   nop
    /* 66598 00265598 933F013C */  lui        $at, (0x3F933333 >> 16)
    /* 6659C 0026559C 33332134 */  ori        $at, $at, (0x3F933333 & 0xFFFF)
    /* 665A0 002655A0 00008144 */  mtc1       $at, $f0
    /* 665A4 002655A4 0800E003 */  jr         $ra
    /* 665A8 002655A8 02600046 */   mul.s     $f0, $f12, $f0
  .L002655AC:
    /* 665AC 002655AC 0800E003 */  jr         $ra
    /* 665B0 002655B0 06600046 */   mov.s     $f0, $f12
endlabel func_00265588
