.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0026BF10, 0x2C

glabel func_0026BF10
    /* 6CF10 0026BF10 2D38A000 */  daddu      $a3, $a1, $zero
    /* 6CF14 0026BF14 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 6CF18 0026BF18 3100023C */  lui        $v0, %hi(D_00311C00)
    /* 6CF1C 0026BF1C 2D288000 */  daddu      $a1, $a0, $zero
    /* 6CF20 0026BF20 0000BFFF */  sd         $ra, 0x0($sp)
    /* 6CF24 0026BF24 001C4424 */  addiu      $a0, $v0, %lo(D_00311C00)
    /* 6CF28 0026BF28 7EC5090C */  jal        func_002715F8
    /* 6CF2C 0026BF2C 08000624 */   addiu     $a2, $zero, 0x8
    /* 6CF30 0026BF30 0000BFDF */  ld         $ra, 0x0($sp)
    /* 6CF34 0026BF34 0800E003 */  jr         $ra
    /* 6CF38 0026BF38 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_0026BF10
    /* 6CF3C 0026BF3C 00000000 */  nop
