.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00255838, 0x14

glabel func_00255838
    /* 56838 00255838 01000224 */  addiu      $v0, $zero, 0x1
    /* 5683C 0025583C B48E84AF */  sw         $a0, %gp_rel(D_00370824)($gp)
    /* 56840 00255840 B08E82AF */  sw         $v0, %gp_rel(D_00370820)($gp)
    /* 56844 00255844 0800E003 */  jr         $ra
    /* 56848 00255848 509282AF */   sw        $v0, %gp_rel(D_00370BC0)($gp)
endlabel func_00255838
