.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002414B0, 0x48

glabel func_002414B0
    /* 424B0 002414B0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 424B4 002414B4 E48A828F */  lw         $v0, %gp_rel(D_00370454)($gp)
    /* 424B8 002414B8 0000B0FF */  sd         $s0, 0x0($sp)
    /* 424BC 002414BC 1000BFFF */  sd         $ra, 0x10($sp)
    /* 424C0 002414C0 08004014 */  bnez       $v0, .L002414E4
    /* 424C4 002414C4 2D808000 */   daddu     $s0, $a0, $zero
    /* 424C8 002414C8 E434090C */  jal        func_0024D390
    /* 424CC 002414CC 00000000 */   nop
    /* 424D0 002414D0 2D200002 */  daddu      $a0, $s0, $zero
    /* 424D4 002414D4 1000BFDF */  ld         $ra, 0x10($sp)
    /* 424D8 002414D8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 424DC 002414DC 68880908 */  j          browser_cdplayer_playoptions
    /* 424E0 002414E0 2000BD27 */   addiu     $sp, $sp, 0x20
  .L002414E4:
    /* 424E4 002414E4 2D200002 */  daddu      $a0, $s0, $zero
    /* 424E8 002414E8 1000BFDF */  ld         $ra, 0x10($sp)
    /* 424EC 002414EC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 424F0 002414F0 E6020908 */  j          func_00240B98
    /* 424F4 002414F4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_002414B0
