.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00260E08, 0x284

glabel func_00260E08
    /* 61E08 00260E08 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 61E0C 00260E0C EC8F828F */  lw         $v0, %gp_rel(D_0037095C)($gp)
    /* 61E10 00260E10 1000BFFF */  sd         $ra, 0x10($sp)
    /* 61E14 00260E14 0A004010 */  beqz       $v0, .L00260E40
    /* 61E18 00260E18 0000B0FF */   sd        $s0, 0x0($sp)
    /* 61E1C 00260E1C 5082090C */  jal        func_00260940
    /* 61E20 00260E20 3090848F */   lw        $a0, %gp_rel(D_003709A0)($gp)
    /* 61E24 00260E24 EC8F828F */  lw         $v0, %gp_rel(D_0037095C)($gp)
    /* 61E28 00260E28 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 61E2C 00260E2C FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 61E30 00260E30 2A186200 */  slt        $v1, $v1, $v0
    /* 61E34 00260E34 0A100300 */  movz       $v0, $zero, $v1
    /* 61E38 00260E38 90000010 */  b          .L0026107C
    /* 61E3C 00260E3C EC8F82AF */   sw        $v0, %gp_rel(D_0037095C)($gp)
  .L00260E40:
    /* 61E40 00260E40 4090828F */  lw         $v0, %gp_rel(D_003709B0)($gp)
    /* 61E44 00260E44 8E004014 */  bnez       $v0, .L00261080
    /* 61E48 00260E48 1000BFDF */   ld        $ra, 0x10($sp)
    /* 61E4C 00260E4C 4C90838F */  lw         $v1, %gp_rel(D_003709BC)($gp)
    /* 61E50 00260E50 20000224 */  addiu      $v0, $zero, 0x20
    /* 61E54 00260E54 0E006210 */  beq        $v1, $v0, .L00260E90
    /* 61E58 00260E58 21006228 */   slti      $v0, $v1, 0x21
    /* 61E5C 00260E5C 05004010 */  beqz       $v0, .L00260E74
    /* 61E60 00260E60 1F000224 */   addiu     $v0, $zero, 0x1F
    /* 61E64 00260E64 0F006210 */  beq        $v1, $v0, .L00260EA4
    /* 61E68 00260E68 0000B0DF */   ld        $s0, 0x0($sp)
    /* 61E6C 00260E6C 85000010 */  b          .L00261084
    /* 61E70 00260E70 00000000 */   nop
  .L00260E74:
    /* 61E74 00260E74 25000224 */  addiu      $v0, $zero, 0x25
    /* 61E78 00260E78 42006210 */  beq        $v1, $v0, .L00260F84
    /* 61E7C 00260E7C 26000224 */   addiu     $v0, $zero, 0x26
    /* 61E80 00260E80 55006210 */  beq        $v1, $v0, .L00260FD8
    /* 61E84 00260E84 1000BFDF */   ld        $ra, 0x10($sp)
    /* 61E88 00260E88 7E000010 */  b          .L00261084
    /* 61E8C 00260E8C 0000B0DF */   ld        $s0, 0x0($sp)
  .L00260E90:
    /* 61E90 00260E90 0090838F */  lw         $v1, %gp_rel(D_00370970)($gp)
    /* 61E94 00260E94 1F000224 */  addiu      $v0, $zero, 0x1F
    /* 61E98 00260E98 4C9082AF */  sw         $v0, %gp_rel(D_003709BC)($gp)
    /* 61E9C 00260E9C 77000010 */  b          .L0026107C
    /* 61EA0 00260EA0 089083AF */   sw        $v1, %gp_rel(D_00370978)($gp)
  .L00260EA4:
    /* 61EA4 00260EA4 2A47090C */  jal        func_00251CA8
    /* 61EA8 00260EA8 03000424 */   addiu     $a0, $zero, 0x3
    /* 61EAC 00260EAC 1047090C */  jal        func_00251C40
    /* 61EB0 00260EB0 02000424 */   addiu     $a0, $zero, 0x2
    /* 61EB4 00260EB4 028E8293 */  lbu        $v0, %gp_rel(D_00370772)($gp)
    /* 61EB8 00260EB8 07004010 */  beqz       $v0, .L00260ED8
    /* 61EBC 00260EBC 348E838F */   lw        $v1, %gp_rel(D_003707A4)($gp)
    /* 61EC0 00260EC0 20006230 */  andi       $v0, $v1, 0x20
    /* 61EC4 00260EC4 04004010 */  beqz       $v0, .L00260ED8
    /* 61EC8 00260EC8 25000224 */   addiu     $v0, $zero, 0x25
    /* 61ECC 00260ECC 0890838F */  lw         $v1, %gp_rel(D_00370978)($gp)
    /* 61ED0 00260ED0 2A000010 */  b          .L00260F7C
    /* 61ED4 00260ED4 4C9082AF */   sw        $v0, %gp_rel(D_003709BC)($gp)
  .L00260ED8:
    /* 61ED8 00260ED8 00806230 */  andi       $v0, $v1, 0x8000
    /* 61EDC 00260EDC 0D004010 */  beqz       $v0, .L00260F14
    /* 61EE0 00260EE0 00630424 */   addiu     $a0, $zero, 0x6300
    /* 61EE4 00260EE4 01000524 */  addiu      $a1, $zero, 0x1
    /* 61EE8 00260EE8 2438090C */  jal        sound_handle_queue_cmd_auto
    /* 61EEC 00260EEC 06000624 */   addiu     $a2, $zero, 0x6
    /* 61EF0 00260EF0 0890838F */  lw         $v1, %gp_rel(D_00370978)($gp)
    /* 61EF4 00260EF4 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 61EF8 00260EF8 03006104 */  bgez       $v1, .L00260F08
    /* 61EFC 00260EFC 089083AF */   sw        $v1, %gp_rel(D_00370978)($gp)
    /* 61F00 00260F00 02000324 */  addiu      $v1, $zero, 0x2
    /* 61F04 00260F04 089083AF */  sw         $v1, %gp_rel(D_00370978)($gp)
  .L00260F08:
    /* 61F08 00260F08 01000224 */  addiu      $v0, $zero, 0x1
    /* 61F0C 00260F0C 1B000010 */  b          .L00260F7C
    /* 61F10 00260F10 3C9082AF */   sw        $v0, %gp_rel(D_003709AC)($gp)
  .L00260F14:
    /* 61F14 00260F14 00206230 */  andi       $v0, $v1, 0x2000
    /* 61F18 00260F18 0D004010 */  beqz       $v0, .L00260F50
    /* 61F1C 00260F1C 01000524 */   addiu     $a1, $zero, 0x1
    /* 61F20 00260F20 2438090C */  jal        sound_handle_queue_cmd_auto
    /* 61F24 00260F24 06000624 */   addiu     $a2, $zero, 0x6
    /* 61F28 00260F28 0890838F */  lw         $v1, %gp_rel(D_00370978)($gp)
    /* 61F2C 00260F2C 01006324 */  addiu      $v1, $v1, 0x1
    /* 61F30 00260F30 03006228 */  slti       $v0, $v1, 0x3
    /* 61F34 00260F34 03004014 */  bnez       $v0, .L00260F44
    /* 61F38 00260F38 089083AF */   sw        $v1, %gp_rel(D_00370978)($gp)
    /* 61F3C 00260F3C 089080AF */  sw         $zero, %gp_rel(D_00370978)($gp)
    /* 61F40 00260F40 2D180000 */  daddu      $v1, $zero, $zero
  .L00260F44:
    /* 61F44 00260F44 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 61F48 00260F48 0C000010 */  b          .L00260F7C
    /* 61F4C 00260F4C 3C9082AF */   sw        $v0, %gp_rel(D_003709AC)($gp)
  .L00260F50:
    /* 61F50 00260F50 40006230 */  andi       $v0, $v1, 0x40
    /* 61F54 00260F54 08004010 */  beqz       $v0, .L00260F78
    /* 61F58 00260F58 00630424 */   addiu     $a0, $zero, 0x6300
    /* 61F5C 00260F5C 01000524 */  addiu      $a1, $zero, 0x1
    /* 61F60 00260F60 2438090C */  jal        sound_handle_queue_cmd_auto
    /* 61F64 00260F64 0A000624 */   addiu     $a2, $zero, 0xA
    /* 61F68 00260F68 FE81090C */  jal        func_002607F8
    /* 61F6C 00260F6C 00000000 */   nop
    /* 61F70 00260F70 7C83090C */  jal        func_00260DF0
    /* 61F74 00260F74 00000000 */   nop
  .L00260F78:
    /* 61F78 00260F78 0890838F */  lw         $v1, %gp_rel(D_00370978)($gp)
  .L00260F7C:
    /* 61F7C 00260F7C 3F000010 */  b          .L0026107C
    /* 61F80 00260F80 449083AF */   sw        $v1, %gp_rel(D_003709B4)($gp)
  .L00260F84:
    /* 61F84 00260F84 0890838F */  lw         $v1, %gp_rel(D_00370978)($gp)
    /* 61F88 00260F88 01000224 */  addiu      $v0, $zero, 0x1
    /* 61F8C 00260F8C 06006210 */  beq        $v1, $v0, .L00260FA8
    /* 61F90 00260F90 00630424 */   addiu     $a0, $zero, 0x6300
    /* 61F94 00260F94 01000524 */  addiu      $a1, $zero, 0x1
    /* 61F98 00260F98 2438090C */  jal        sound_handle_queue_cmd_auto
    /* 61F9C 00260F9C 04000624 */   addiu     $a2, $zero, 0x4
    /* 61FA0 00260FA0 08000010 */  b          .L00260FC4
    /* 61FA4 00260FA4 00000000 */   nop
  .L00260FA8:
    /* 61FA8 00260FA8 01000524 */  addiu      $a1, $zero, 0x1
    /* 61FAC 00260FAC 2438090C */  jal        sound_handle_queue_cmd_auto
    /* 61FB0 00260FB0 07000624 */   addiu     $a2, $zero, 0x7
    /* 61FB4 00260FB4 00630424 */  addiu      $a0, $zero, 0x6300
    /* 61FB8 00260FB8 01000524 */  addiu      $a1, $zero, 0x1
    /* 61FBC 00260FBC 2438090C */  jal        sound_handle_queue_cmd_auto
    /* 61FC0 00260FC0 08000624 */   addiu     $a2, $zero, 0x8
  .L00260FC4:
    /* 61FC4 00260FC4 3E47090C */  jal        func_00251CF8
    /* 61FC8 00260FC8 00000000 */   nop
    /* 61FCC 00260FCC 26000224 */  addiu      $v0, $zero, 0x26
    /* 61FD0 00260FD0 2A000010 */  b          .L0026107C
    /* 61FD4 00260FD4 4C9082AF */   sw        $v0, %gp_rel(D_003709BC)($gp)
  .L00260FD8:
    /* 61FD8 00260FD8 0090828F */  lw         $v0, %gp_rel(D_00370970)($gp)
    /* 61FDC 00260FDC 02000424 */  addiu      $a0, $zero, 0x2
    /* 61FE0 00260FE0 07004410 */  beq        $v0, $a0, .L00261000
    /* 61FE4 00260FE4 0890838F */   lw        $v1, %gp_rel(D_00370978)($gp)
    /* 61FE8 00260FE8 06006450 */  beql       $v1, $a0, .L00261004
    /* 61FEC 00260FEC 01000224 */   addiu     $v0, $zero, 0x1
    /* 61FF0 00260FF0 05004310 */  beq        $v0, $v1, .L00261008
    /* 61FF4 00260FF4 01000224 */   addiu     $v0, $zero, 0x1
    /* 61FF8 00260FF8 04000010 */  b          .L0026100C
    /* 61FFC 00260FFC F88F82AF */   sw        $v0, %gp_rel(D_00370968)($gp)
  .L00261000:
    /* 62000 00261000 01000224 */  addiu      $v0, $zero, 0x1
  .L00261004:
    /* 62004 00261004 F88F82AF */  sw         $v0, %gp_rel(D_00370968)($gp)
  .L00261008:
    /* 62008 00261008 01000224 */  addiu      $v0, $zero, 0x1
  .L0026100C:
    /* 6200C 0026100C 19006214 */  bne        $v1, $v0, .L00261074
    /* 62010 00261010 009083AF */   sw        $v1, %gp_rel(D_00370970)($gp)
    /* 62014 00261014 00008044 */  mtc1       $zero, $f0
    /* 62018 00261018 03000224 */  addiu      $v0, $zero, 0x3
    /* 6201C 0026101C FEFF1024 */  addiu      $s0, $zero, -0x2
    /* 62020 00261020 E08A848F */  lw         $a0, %gp_rel(D_00370450)($gp)
    /* 62024 00261024 888D82AF */  sw         $v0, %gp_rel(D_003706F8)($gp)
    /* 62028 00261028 788D80E7 */  swc1       $f0, %gp_rel(D_003706E8)($gp)
    /* 6202C 0026102C 808D80E7 */  swc1       $f0, %gp_rel(D_003706F0)($gp)
    /* 62030 00261030 DA4A090C */  jal        func_00252B68
    /* 62034 00261034 C88D90AF */   sw        $s0, %gp_rel(D_00370738)($gp)
    /* 62038 00261038 F08A838F */  lw         $v1, %gp_rel(D_00370460)($gp)
    /* 6203C 0026103C 02000224 */  addiu      $v0, $zero, 0x2
    /* 62040 00261040 09006214 */  bne        $v1, $v0, .L00261068
    /* 62044 00261044 E08A848F */   lw        $a0, %gp_rel(D_00370450)($gp)
    /* 62048 00261048 6E4A090C */  jal        func_002529B8
    /* 6204C 0026104C B88D858F */   lw        $a1, %gp_rel(D_00370728)($gp)
    /* 62050 00261050 E08A848F */  lw         $a0, %gp_rel(D_00370450)($gp)
    /* 62054 00261054 FFFF033C */  lui        $v1, (0xFFFFFBFF >> 16)
    /* 62058 00261058 FFFB6334 */  ori        $v1, $v1, (0xFFFFFBFF & 0xFFFF)
    /* 6205C 0026105C 9000828C */  lw         $v0, 0x90($a0)
    /* 62060 00261060 24104300 */  and        $v0, $v0, $v1
    /* 62064 00261064 900082AC */  sw         $v0, 0x90($a0)
  .L00261068:
    /* 62068 00261068 7282090C */  jal        func_002609C8
    /* 6206C 0026106C 00000000 */   nop
    /* 62070 00261070 C48D90AF */  sw         $s0, %gp_rel(D_00370734)($gp)
  .L00261074:
    /* 62074 00261074 7C83090C */  jal        func_00260DF0
    /* 62078 00261078 00000000 */   nop
  .L0026107C:
    /* 6207C 0026107C 1000BFDF */  ld         $ra, 0x10($sp)
  .L00261080:
    /* 62080 00261080 0000B0DF */  ld         $s0, 0x0($sp)
  .L00261084:
    /* 62084 00261084 0800E003 */  jr         $ra
    /* 62088 00261088 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00260E08
