.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0023A580, 0x184

glabel func_0023A580
    /* 3B580 0023A580 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 3B584 0023A584 2D308000 */  daddu      $a2, $a0, $zero
    /* 3B588 0023A588 0000BFFF */  sd         $ra, 0x0($sp)
    /* 3B58C 0023A58C 2A00033C */  lui        $v1, %hi(D_002A7FD0)
    /* 3B590 0023A590 D07F6224 */  addiu      $v0, $v1, %lo(D_002A7FD0)
    /* 3B594 0023A594 803F013C */  lui        $at, (0x3F800000 >> 16)
    /* 3B598 0023A598 00108144 */  mtc1       $at, $f2
    /* 3B59C 0023A59C 0000C0C4 */  lwc1       $f0, 0x0($a2)
    /* 3B5A0 0023A5A0 2A000B3C */  lui        $t3, %hi(D_002A7F88)
    /* 3B5A4 0023A5A4 887F6725 */  addiu      $a3, $t3, %lo(D_002A7F88)
    /* 3B5A8 0023A5A8 2A00083C */  lui        $t0, %hi(D_002A5A60)
    /* 3B5AC 0023A5AC D07F60E4 */  swc1       $f0, %lo(D_002A7FD0)($v1)
    /* 3B5B0 0023A5B0 605A0825 */  addiu      $t0, $t0, %lo(D_002A5A60)
    /* 3B5B4 0023A5B4 FF0F033C */  lui        $v1, (0xFFFFFFF >> 16)
    /* 3B5B8 0023A5B8 00100A3C */  lui        $t2, (0x10009020 >> 16)
    /* 3B5BC 0023A5BC 0400C0C4 */  lwc1       $f0, 0x4($a2)
    /* 3B5C0 0023A5C0 FFFF6334 */  ori        $v1, $v1, (0xFFFFFFF & 0xFFFF)
    /* 3B5C4 0023A5C4 24400301 */  and        $t0, $t0, $v1
    /* 3B5C8 0023A5C8 20904A35 */  ori        $t2, $t2, (0x10009020 & 0xFFFF)
    /* 3B5CC 0023A5CC 040040E4 */  swc1       $f0, 0x4($v0)
    /* 3B5D0 0023A5D0 0010093C */  lui        $t1, (0x10009030 >> 16)
    /* 3B5D4 0023A5D4 30902935 */  ori        $t1, $t1, (0x10009030 & 0xFFFF)
    /* 3B5D8 0023A5D8 0010033C */  lui        $v1, (0x1000E010 >> 16)
    /* 3B5DC 0023A5DC 0800C0C4 */  lwc1       $f0, 0x8($a2)
    /* 3B5E0 0023A5E0 10E06334 */  ori        $v1, $v1, (0x1000E010 & 0xFFFF)
    /* 3B5E4 0023A5E4 02000C24 */  addiu      $t4, $zero, 0x2
    /* 3B5E8 0023A5E8 2D200000 */  daddu      $a0, $zero, $zero
    /* 3B5EC 0023A5EC 080040E4 */  swc1       $f0, 0x8($v0)
    /* 3B5F0 0023A5F0 0C00C0C4 */  lwc1       $f0, 0xC($a2)
    /* 3B5F4 0023A5F4 0C0040E4 */  swc1       $f0, 0xC($v0)
    /* 3B5F8 0023A5F8 1000C1C4 */  lwc1       $f1, 0x10($a2)
    /* 3B5FC 0023A5FC 100041E4 */  swc1       $f1, 0x10($v0)
    /* 3B600 0023A600 1400C0C4 */  lwc1       $f0, 0x14($a2)
    /* 3B604 0023A604 140040E4 */  swc1       $f0, 0x14($v0)
    /* 3B608 0023A608 1800C1C4 */  lwc1       $f1, 0x18($a2)
    /* 3B60C 0023A60C 180041E4 */  swc1       $f1, 0x18($v0)
    /* 3B610 0023A610 1C00C0C4 */  lwc1       $f0, 0x1C($a2)
    /* 3B614 0023A614 1C0040E4 */  swc1       $f0, 0x1C($v0)
    /* 3B618 0023A618 2000C1C4 */  lwc1       $f1, 0x20($a2)
    /* 3B61C 0023A61C 200041E4 */  swc1       $f1, 0x20($v0)
    /* 3B620 0023A620 2400C0C4 */  lwc1       $f0, 0x24($a2)
    /* 3B624 0023A624 240040E4 */  swc1       $f0, 0x24($v0)
    /* 3B628 0023A628 2800C1C4 */  lwc1       $f1, 0x28($a2)
    /* 3B62C 0023A62C 280041E4 */  swc1       $f1, 0x28($v0)
    /* 3B630 0023A630 2C00C0C4 */  lwc1       $f0, 0x2C($a2)
    /* 3B634 0023A634 3C0042E4 */  swc1       $f2, 0x3C($v0)
    /* 3B638 0023A638 2C0040E4 */  swc1       $f0, 0x2C($v0)
    /* 3B63C 0023A63C 300040AC */  sw         $zero, 0x30($v0)
    /* 3B640 0023A640 340040AC */  sw         $zero, 0x34($v0)
    /* 3B644 0023A644 380040AC */  sw         $zero, 0x38($v0)
    /* 3B648 0023A648 0000A0C4 */  lwc1       $f0, 0x0($a1)
    /* 3B64C 0023A64C 887F60E5 */  swc1       $f0, %lo(D_002A7F88)($t3)
    /* 3B650 0023A650 0400A1C4 */  lwc1       $f1, 0x4($a1)
    /* 3B654 0023A654 0400E1E4 */  swc1       $f1, 0x4($a3)
    /* 3B658 0023A658 0800A0C4 */  lwc1       $f0, 0x8($a1)
    /* 3B65C 0023A65C 0800E0E4 */  swc1       $f0, 0x8($a3)
    /* 3B660 0023A660 0C00A1C4 */  lwc1       $f1, 0xC($a1)
    /* 3B664 0023A664 000040AD */  sw         $zero, 0x0($t2)
    /* 3B668 0023A668 0C00E1E4 */  swc1       $f1, 0xC($a3)
    /* 3B66C 0023A66C 000028AD */  sw         $t0, 0x0($t1)
    /* 3B670 0023A670 1000A1C4 */  lwc1       $f1, 0x10($a1)
    /* 3B674 0023A674 00006CAC */  sw         $t4, 0x0($v1)
    /* 3B678 0023A678 1000E1E4 */  swc1       $f1, 0x10($a3)
    /* 3B67C 0023A67C 1400A0C4 */  lwc1       $f0, 0x14($a1)
    /* 3B680 0023A680 1400E0E4 */  swc1       $f0, 0x14($a3)
    /* 3B684 0023A684 1800A1C4 */  lwc1       $f1, 0x18($a1)
    /* 3B688 0023A688 1800E1E4 */  swc1       $f1, 0x18($a3)
    /* 3B68C 0023A68C 1C00A0C4 */  lwc1       $f0, 0x1C($a1)
    /* 3B690 0023A690 1C00E0E4 */  swc1       $f0, 0x1C($a3)
    /* 3B694 0023A694 2000A1C4 */  lwc1       $f1, 0x20($a1)
    /* 3B698 0023A698 2000E1E4 */  swc1       $f1, 0x20($a3)
    /* 3B69C 0023A69C 2400A0C4 */  lwc1       $f0, 0x24($a1)
    /* 3B6A0 0023A6A0 2400E0E4 */  swc1       $f0, 0x24($a3)
    /* 3B6A4 0023A6A4 2800A1C4 */  lwc1       $f1, 0x28($a1)
    /* 3B6A8 0023A6A8 2800E1E4 */  swc1       $f1, 0x28($a3)
    /* 3B6AC 0023A6AC 2C00A0C4 */  lwc1       $f0, 0x2C($a1)
    /* 3B6B0 0023A6B0 2C00E0E4 */  swc1       $f0, 0x2C($a3)
    /* 3B6B4 0023A6B4 3000A1C4 */  lwc1       $f1, 0x30($a1)
    /* 3B6B8 0023A6B8 3000E1E4 */  swc1       $f1, 0x30($a3)
    /* 3B6BC 0023A6BC 3400A0C4 */  lwc1       $f0, 0x34($a1)
    /* 3B6C0 0023A6C0 3400E0E4 */  swc1       $f0, 0x34($a3)
    /* 3B6C4 0023A6C4 3800A1C4 */  lwc1       $f1, 0x38($a1)
    /* 3B6C8 0023A6C8 3800E1E4 */  swc1       $f1, 0x38($a3)
    /* 3B6CC 0023A6CC 3C00A0C4 */  lwc1       $f0, 0x3C($a1)
    /* 3B6D0 0023A6D0 E4FE090C */  jal        FlushCache
    /* 3B6D4 0023A6D4 3C00E0E4 */   swc1      $f0, 0x3C($a3)
    /* 3B6D8 0023A6D8 0010023C */  lui        $v0, (0x10009000 >> 16)
    /* 3B6DC 0023A6DC 45010324 */  addiu      $v1, $zero, 0x145
    /* 3B6E0 0023A6E0 00904234 */  ori        $v0, $v0, (0x10009000 & 0xFFFF)
    /* 3B6E4 0023A6E4 2D200000 */  daddu      $a0, $zero, $zero
    /* 3B6E8 0023A6E8 000043AC */  sw         $v1, 0x0($v0)
    /* 3B6EC 0023A6EC EA240A0C */  jal        sceGsSyncPath
    /* 3B6F0 0023A6F0 2D280000 */   daddu     $a1, $zero, $zero
    /* 3B6F4 0023A6F4 0000BFDF */  ld         $ra, 0x0($sp)
    /* 3B6F8 0023A6F8 2D100000 */  daddu      $v0, $zero, $zero
    /* 3B6FC 0023A6FC 0800E003 */  jr         $ra
    /* 3B700 0023A700 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_0023A580
