.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002497B8, 0x90

glabel func_002497B8
    /* 4A7B8 002497B8 2D408000 */  daddu      $t0, $a0, $zero
    /* 4A7BC 002497BC 08000229 */  slti       $v0, $t0, 0x8
    /* 4A7C0 002497C0 11004014 */  bnez       $v0, .L00249808
    /* 4A7C4 002497C4 2D38A000 */   daddu     $a3, $a1, $zero
    /* 4A7C8 002497C8 08010224 */  addiu      $v0, $zero, 0x108
    /* 4A7CC 002497CC 05000255 */  bnel       $t0, $v0, .L002497E4
    /* 4A7D0 002497D0 B000E38C */   lw        $v1, 0xB0($a3)
    /* 4A7D4 002497D4 3801E28C */  lw         $v0, 0x138($a3)
    /* 4A7D8 002497D8 1400438C */  lw         $v1, 0x14($v0)
    /* 4A7DC 002497DC 0800E003 */  jr         $ra
    /* 4A7E0 002497E0 B800E3AC */   sw        $v1, 0xB8($a3)
  .L002497E4:
    /* 4A7E4 002497E4 0F000224 */  addiu      $v0, $zero, 0xF
    /* 4A7E8 002497E8 08006214 */  bne        $v1, $v0, .L0024980C
    /* 4A7EC 002497EC 2C00023C */   lui       $v0, %hi(D_002BB938)
    /* 4A7F0 002497F0 3801E38C */  lw         $v1, 0x138($a3)
    /* 4A7F4 002497F4 1400628C */  lw         $v0, 0x14($v1)
    /* 4A7F8 002497F8 FF034224 */  addiu      $v0, $v0, 0x3FF
    /* 4A7FC 002497FC 82120200 */  srl        $v0, $v0, 10
    /* 4A800 00249800 0800E003 */  jr         $ra
    /* 4A804 00249804 B800E2AC */   sw        $v0, 0xB8($a3)
  .L00249808:
    /* 4A808 00249808 2C00023C */  lui        $v0, %hi(D_002BB938)
  .L0024980C:
    /* 4A80C 0024980C 80180800 */  sll        $v1, $t0, 2
    /* 4A810 00249810 38B94224 */  addiu      $v0, $v0, %lo(D_002BB938)
    /* 4A814 00249814 02000624 */  addiu      $a2, $zero, 0x2
    /* 4A818 00249818 21104300 */  addu       $v0, $v0, $v1
    /* 4A81C 0024981C 09000424 */  addiu      $a0, $zero, 0x9
    /* 4A820 00249820 2C04438C */  lw         $v1, 0x42C($v0)
    /* 4A824 00249824 C001E524 */  addiu      $a1, $a3, 0x1C0
    /* 4A828 00249828 948C86AF */  sw         $a2, %gp_rel(D_00370604)($gp)
    /* 4A82C 0024982C B88C84AF */  sw         $a0, %gp_rel(D_00370628)($gp)
    /* 4A830 00249830 C48C83AF */  sw         $v1, %gp_rel(D_00370634)($gp)
    /* 4A834 00249834 D48C85AF */  sw         $a1, %gp_rel(D_00370644)($gp)
    /* 4A838 00249838 E08C87AF */  sw         $a3, %gp_rel(D_00370650)($gp)
    /* 4A83C 0024983C BC8C88AF */  sw         $t0, %gp_rel(D_0037062C)($gp)
    /* 4A840 00249840 0800E003 */  jr         $ra
    /* 4A844 00249844 E58C80A3 */   sb        $zero, %gp_rel(D_00370655)($gp)
endlabel func_002497B8
