.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0026BE78, 0x58

glabel func_0026BE78
    /* 6CE78 0026BE78 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 6CE7C 0026BE7C FFFF8330 */  andi       $v1, $a0, 0xFFFF
    /* 6CE80 0026BE80 FFFFA530 */  andi       $a1, $a1, 0xFFFF
    /* 6CE84 0026BE84 FFFFC630 */  andi       $a2, $a2, 0xFFFF
    /* 6CE88 0026BE88 FFFFE730 */  andi       $a3, $a3, 0xFFFF
    /* 6CE8C 0026BE8C FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 6CE90 0026BE90 02000224 */  addiu      $v0, $zero, 0x2
    /* 6CE94 0026BE94 3100043C */  lui        $a0, %hi(D_003113EC)
    /* 6CE98 0026BE98 0400A5A7 */  sh         $a1, 0x4($sp)
    /* 6CE9C 0026BE9C EC138424 */  addiu      $a0, $a0, %lo(D_003113EC)
    /* 6CEA0 0026BEA0 0600A6A7 */  sh         $a2, 0x6($sp)
    /* 6CEA4 0026BEA4 2D28A003 */  daddu      $a1, $sp, $zero
    /* 6CEA8 0026BEA8 1000BFFF */  sd         $ra, 0x10($sp)
    /* 6CEAC 0026BEAC 10000624 */  addiu      $a2, $zero, 0x10
    /* 6CEB0 0026BEB0 0000A2A3 */  sb         $v0, 0x0($sp)
    /* 6CEB4 0026BEB4 0200A3A7 */  sh         $v1, 0x2($sp)
    /* 6CEB8 0026BEB8 0800A7AF */  sw         $a3, 0x8($sp)
    /* 6CEBC 0026BEBC C4C4090C */  jal        func_00271310
    /* 6CEC0 0026BEC0 0C00A8AF */   sw        $t0, 0xC($sp)
    /* 6CEC4 0026BEC4 1000BFDF */  ld         $ra, 0x10($sp)
    /* 6CEC8 0026BEC8 0800E003 */  jr         $ra
    /* 6CECC 0026BECC 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0026BE78
