.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0023C1F8, 0x5C

glabel func_0023C1F8
    /* 3D1F8 0023C1F8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 3D1FC 0023C1FC 2D188000 */  daddu      $v1, $a0, $zero
    /* 3D200 0023C200 08006228 */  slti       $v0, $v1, 0x8
    /* 3D204 0023C204 06004014 */  bnez       $v0, .L0023C220
    /* 3D208 0023C208 0000BFFF */   sd        $ra, 0x0($sp)
    /* 3D20C 0023C20C 01000224 */  addiu      $v0, $zero, 0x1
    /* 3D210 0023C210 DE76090C */  jal        func_0025DB78
    /* 3D214 0023C214 A49182AF */   sw        $v0, %gp_rel(D_00370B14)($gp)
    /* 3D218 0023C218 0C000010 */  b          .L0023C24C
    /* 3D21C 0023C21C 0000BFDF */   ld        $ra, 0x0($sp)
  .L0023C220:
    /* 3D220 0023C220 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 3D224 0023C224 03006424 */  addiu      $a0, $v1, 0x3
    /* 3D228 0023C228 2A104300 */  slt        $v0, $v0, $v1
    /* 3D22C 0023C22C 2D30A000 */  daddu      $a2, $a1, $zero
    /* 3D230 0023C230 0B206200 */  movn       $a0, $v1, $v0
    /* 3D234 0023C234 A49180AF */  sw         $zero, %gp_rel(D_00370B14)($gp)
    /* 3D238 0023C238 83200400 */  sra        $a0, $a0, 2
    /* 3D23C 0023C23C 80280400 */  sll        $a1, $a0, 2
    /* 3D240 0023C240 3A3A0A0C */  jal        sceMcDelete
    /* 3D244 0023C244 23286500 */   subu      $a1, $v1, $a1
    /* 3D248 0023C248 0000BFDF */  ld         $ra, 0x0($sp)
  .L0023C24C:
    /* 3D24C 0023C24C 0800E003 */  jr         $ra
    /* 3D250 0023C250 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_0023C1F8
