.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching module_browser_23A450, 0x24

glabel module_browser_23A450
    /* 3B450 0023A450 000084D8 */  lqc2       $vf4, 0x0($a0)
    /* 3B454 0023A454 0000A5D8 */  lqc2       $vf5, 0x0($a1)
    /* 3B458 0023A458 0000C6D8 */  lqc2       $vf6, 0x0($a2)
    /* 3B45C 0023A45C 2F21E64B */  vmini.xyzw $vf4, $vf4, $vf6
    /* 3B460 0023A460 6B29E64B */  vmax.xyzw  $vf5, $vf5, $vf6
    /* 3B464 0023A464 000084F8 */  sqc2       $vf4, 0x0($a0)
    /* 3B468 0023A468 0000A5F8 */  sqc2       $vf5, 0x0($a1)
    /* 3B46C 0023A46C 0800E003 */  jr         $ra
    /* 3B470 0023A470 00000000 */   nop
endlabel module_browser_23A450
