.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceAtokGetCandidateList, 0x78

glabel sceAtokGetCandidateList
    /* 79760 00278760 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 79764 00278764 00800734 */  ori        $a3, $zero, 0x8000
    /* 79768 00278768 0000B0FF */  sd         $s0, 0x0($sp)
    /* 7976C 0027876C 2000B2FF */  sd         $s2, 0x20($sp)
    /* 79770 00278770 2D808000 */  daddu      $s0, $a0, $zero
    /* 79774 00278774 1000B1FF */  sd         $s1, 0x10($sp)
    /* 79778 00278778 2D90A000 */  daddu      $s2, $a1, $zero
    /* 7977C 0027877C 3000BFFF */  sd         $ra, 0x30($sp)
    /* 79780 00278780 2D88C000 */  daddu      $s1, $a2, $zero
    /* 79784 00278784 B00100AE */  sw         $zero, 0x1B0($s0)
    /* 79788 00278788 60010524 */  addiu      $a1, $zero, 0x160
    /* 7978C 0027878C ECDF090C */  jal        sceAtokCmd
    /* 79790 00278790 1D010624 */   addiu     $a2, $zero, 0x11D
    /* 79794 00278794 AC010386 */  lh         $v1, 0x1AC($s0)
    /* 79798 00278798 2A182302 */  slt        $v1, $s1, $v1
    /* 7979C 0027879C 08006014 */  bnez       $v1, .L002787C0
    /* 797A0 002787A0 2D100000 */   daddu     $v0, $zero, $zero
    /* 797A4 002787A4 B00112AE */  sw         $s2, 0x1B0($s0)
    /* 797A8 002787A8 00802736 */  ori        $a3, $s1, 0x8000
    /* 797AC 002787AC 2D200002 */  daddu      $a0, $s0, $zero
    /* 797B0 002787B0 60010524 */  addiu      $a1, $zero, 0x160
    /* 797B4 002787B4 ECDF090C */  jal        sceAtokCmd
    /* 797B8 002787B8 1D010624 */   addiu     $a2, $zero, 0x11D
    /* 797BC 002787BC AC010286 */  lh         $v0, 0x1AC($s0)
  .L002787C0:
    /* 797C0 002787C0 3000BFDF */  ld         $ra, 0x30($sp)
    /* 797C4 002787C4 2000B2DF */  ld         $s2, 0x20($sp)
    /* 797C8 002787C8 1000B1DF */  ld         $s1, 0x10($sp)
    /* 797CC 002787CC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 797D0 002787D0 0800E003 */  jr         $ra
    /* 797D4 002787D4 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel sceAtokGetCandidateList
