.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceAtokInit, 0x2A8

glabel sceAtokInit
    /* 784F8 002774F8 60FFBD27 */  addiu      $sp, $sp, -0xA0
    /* 784FC 002774FC 7000B7FF */  sd         $s7, 0x70($sp)
    /* 78500 00277500 8000BEFF */  sd         $fp, 0x80($sp)
    /* 78504 00277504 2DB80001 */  daddu      $s7, $t0, $zero
    /* 78508 00277508 6000B6FF */  sd         $s6, 0x60($sp)
    /* 7850C 0027750C 2DF0E000 */  daddu      $fp, $a3, $zero
    /* 78510 00277510 5000B5FF */  sd         $s5, 0x50($sp)
    /* 78514 00277514 2DB0C000 */  daddu      $s6, $a2, $zero
    /* 78518 00277518 0000B0FF */  sd         $s0, 0x0($sp)
    /* 7851C 0027751C 2DA88000 */  daddu      $s5, $a0, $zero
    /* 78520 00277520 9000BFFF */  sd         $ra, 0x90($sp)
    /* 78524 00277524 2D80A000 */  daddu      $s0, $a1, $zero
    /* 78528 00277528 4000B4FF */  sd         $s4, 0x40($sp)
    /* 7852C 0027752C 0F00E232 */  andi       $v0, $s7, 0xF
    /* 78530 00277530 3000B3FF */  sd         $s3, 0x30($sp)
    /* 78534 00277534 2000B2FF */  sd         $s2, 0x20($sp)
    /* 78538 00277538 07004010 */  beqz       $v0, .L00277558
    /* 7853C 0027753C 1000B1FF */   sd        $s1, 0x10($sp)
    /* 78540 00277540 3700043C */  lui        $a0, %hi(aAtokwrapC)
    /* 78544 00277544 3700063C */  lui        $a2, %hi(aIntLoadaddr0xf)
    /* 78548 00277548 B09B8424 */  addiu      $a0, $a0, %lo(aAtokwrapC)
    /* 7854C 0027754C C09BC624 */  addiu      $a2, $a2, %lo(aIntLoadaddr0xf)
    /* 78550 00277550 5C6D0A0C */  jal        __assert
    /* 78554 00277554 F5010524 */   addiu     $a1, $zero, 0x1F5
  .L00277558:
    /* 78558 00277558 500AB426 */  addiu      $s4, $s5, 0xA50
    /* 7855C 0027755C 2D280002 */  daddu      $a1, $s0, $zero
    /* 78560 00277560 2D208002 */  daddu      $a0, $s4, $zero
    /* 78564 00277564 64740A0C */  jal        strcpy
    /* 78568 00277568 FFFF1124 */   addiu     $s1, $zero, -0x1
    /* 7856C 0027756C FFFF1224 */  addiu      $s2, $zero, -0x1
    /* 78570 00277570 F80AB326 */  addiu      $s3, $s5, 0xAF8
    /* 78574 00277574 D00AB1AE */  sw         $s1, 0xAD0($s5)
    /* 78578 00277578 E80AA0FE */  sd         $zero, 0xAE8($s5)
    /* 7857C 0027757C 2D28C002 */  daddu      $a1, $s6, $zero
    /* 78580 00277580 F00AA0FE */  sd         $zero, 0xAF0($s5)
    /* 78584 00277584 2D206002 */  daddu      $a0, $s3, $zero
    /* 78588 00277588 D40AA0AE */  sw         $zero, 0xAD4($s5)
    /* 7858C 0027758C 6401B026 */  addiu      $s0, $s5, 0x164
    /* 78590 00277590 D80AA0AE */  sw         $zero, 0xAD8($s5)
    /* 78594 00277594 5000163C */  lui        $s6, (0x5022B0 >> 16)
    /* 78598 00277598 64740A0C */  jal        strcpy
    /* 7859C 0027759C E00AB2FE */   sd        $s2, 0xAE0($s5)
    /* 785A0 002775A0 780BB1AE */  sw         $s1, 0xB78($s5)
    /* 785A4 002775A4 2D200002 */  daddu      $a0, $s0, $zero
    /* 785A8 002775A8 880BB2FE */  sd         $s2, 0xB88($s5)
    /* 785AC 002775AC 2D280000 */  daddu      $a1, $zero, $zero
    /* 785B0 002775B0 900BA0FE */  sd         $zero, 0xB90($s5)
    /* 785B4 002775B4 68000624 */  addiu      $a2, $zero, 0x68
    /* 785B8 002775B8 980BA0FE */  sd         $zero, 0xB98($s5)
    /* 785BC 002775BC 7C0BA0AE */  sw         $zero, 0xB7C($s5)
    /* 785C0 002775C0 5E710A0C */  jal        memset
    /* 785C4 002775C4 800BA0AE */   sw        $zero, 0xB80($s5)
    /* 785C8 002775C8 CC01A0A2 */  sb         $zero, 0x1CC($s5)
    /* 785CC 002775CC CC01AF26 */  addiu      $t7, $s5, 0x1CC
    /* 785D0 002775D0 CC02A0A2 */  sb         $zero, 0x2CC($s5)
    /* 785D4 002775D4 CC02AE26 */  addiu      $t6, $s5, 0x2CC
    /* 785D8 002775D8 CC03A0A2 */  sb         $zero, 0x3CC($s5)
    /* 785DC 002775DC CC03AD26 */  addiu      $t5, $s5, 0x3CC
    /* 785E0 002775E0 CC04A0A2 */  sb         $zero, 0x4CC($s5)
    /* 785E4 002775E4 CC04AC26 */  addiu      $t4, $s5, 0x4CC
    /* 785E8 002775E8 CC05A0A2 */  sb         $zero, 0x5CC($s5)
    /* 785EC 002775EC CC05AB26 */  addiu      $t3, $s5, 0x5CC
    /* 785F0 002775F0 CC06A0A2 */  sb         $zero, 0x6CC($s5)
    /* 785F4 002775F4 CC06AA26 */  addiu      $t2, $s5, 0x6CC
    /* 785F8 002775F8 CC07A0A2 */  sb         $zero, 0x7CC($s5)
    /* 785FC 002775FC CC07A926 */  addiu      $t1, $s5, 0x7CC
    /* 78600 00277600 4C08A0A2 */  sb         $zero, 0x84C($s5)
    /* 78604 00277604 4C08A826 */  addiu      $t0, $s5, 0x84C
    /* 78608 00277608 CC08A0A2 */  sb         $zero, 0x8CC($s5)
    /* 7860C 0027760C CC08A726 */  addiu      $a3, $s5, 0x8CC
    /* 78610 00277610 4C09A0A2 */  sb         $zero, 0x94C($s5)
    /* 78614 00277614 4C09A326 */  addiu      $v1, $s5, 0x94C
    /* 78618 00277618 CC09A0A2 */  sb         $zero, 0x9CC($s5)
    /* 7861C 0027761C CC09A226 */  addiu      $v0, $s5, 0x9CC
    /* 78620 00277620 0E0000A6 */  sh         $zero, 0xE($s0)
    /* 78624 00277624 2D20A002 */  daddu      $a0, $s5, $zero
    /* 78628 00277628 500000A6 */  sh         $zero, 0x50($s0)
    /* 7862C 0027762C FF000524 */  addiu      $a1, $zero, 0xFF
    /* 78630 00277630 520000A6 */  sh         $zero, 0x52($s0)
    /* 78634 00277634 64010624 */  addiu      $a2, $zero, 0x164
    /* 78638 00277638 14000FAE */  sw         $t7, 0x14($s0)
    /* 7863C 0027763C 18000EAE */  sw         $t6, 0x18($s0)
    /* 78640 00277640 1C000DAE */  sw         $t5, 0x1C($s0)
    /* 78644 00277644 20000CAE */  sw         $t4, 0x20($s0)
    /* 78648 00277648 24000BAE */  sw         $t3, 0x24($s0)
    /* 7864C 0027764C 28000AAE */  sw         $t2, 0x28($s0)
    /* 78650 00277650 2C0009AE */  sw         $t1, 0x2C($s0)
    /* 78654 00277654 340008AE */  sw         $t0, 0x34($s0)
    /* 78658 00277658 380007AE */  sw         $a3, 0x38($s0)
    /* 7865C 0027765C 400003AE */  sw         $v1, 0x40($s0)
    /* 78660 00277660 5E710A0C */  jal        memset
    /* 78664 00277664 440002AE */   sw        $v0, 0x44($s0)
    /* 78668 00277668 2700033C */  lui        $v1, %hi(sceAtok_INITFIXME1)
    /* 7866C 0027766C 2700023C */  lui        $v0, %hi(sceAtok_INITFIXME2)
    /* 78670 00277670 2700063C */  lui        $a2, %hi(sceAtok_INITFIXME3)
    /* 78674 00277674 2700073C */  lui        $a3, %hi(sceAtok_INITFIXME4)
    /* 78678 00277678 2700083C */  lui        $t0, %hi(sceAtok_INITFIXME5)
    /* 7867C 0027767C 2700093C */  lui        $t1, %hi(sceAtok_INITFIXME6)
    /* 78680 00277680 78716324 */  addiu      $v1, $v1, %lo(sceAtok_INITFIXME1)
    /* 78684 00277684 38724224 */  addiu      $v0, $v0, %lo(sceAtok_INITFIXME2)
    /* 78688 00277688 7072C624 */  addiu      $a2, $a2, %lo(sceAtok_INITFIXME3)
    /* 7868C 0027768C E072E724 */  addiu      $a3, $a3, %lo(sceAtok_INITFIXME4)
    /* 78690 00277690 88730825 */  addiu      $t0, $t0, %lo(sceAtok_INITFIXME5)
    /* 78694 00277694 70742925 */  addiu      $t1, $t1, %lo(sceAtok_INITFIXME6)
    /* 78698 00277698 1E000B24 */  addiu      $t3, $zero, 0x1E
    /* 7869C 0027769C 03000A24 */  addiu      $t2, $zero, 0x3
    /* 786A0 002776A0 0000B4AE */  sw         $s4, 0x0($s5)
    /* 786A4 002776A4 2D20C003 */  daddu      $a0, $fp, $zero
    /* 786A8 002776A8 A000B3AE */  sw         $s3, 0xA0($s5)
    /* 786AC 002776AC 2D28E002 */  daddu      $a1, $s7, $zero
    /* 786B0 002776B0 5D01A0A2 */  sb         $zero, 0x15D($s5)
    /* 786B4 002776B4 4001A3AE */  sw         $v1, 0x140($s5)
    /* 786B8 002776B8 4401A2AE */  sw         $v0, 0x144($s5)
    /* 786BC 002776BC 4801A6AE */  sw         $a2, 0x148($s5)
    /* 786C0 002776C0 4C01A7AE */  sw         $a3, 0x14C($s5)
    /* 786C4 002776C4 5001A8AE */  sw         $t0, 0x150($s5)
    /* 786C8 002776C8 5401A9AE */  sw         $t1, 0x154($s5)
    /* 786CC 002776CC 5A01ABA6 */  sh         $t3, 0x15A($s5)
    /* 786D0 002776D0 AEE4090C */  jal        sceAtokLoadErx
    /* 786D4 002776D4 6101AAA2 */   sb        $t2, 0x161($s5)
    /* 786D8 002776D8 03004014 */  bnez       $v0, .L002776E8
    /* 786DC 002776DC B022C2AE */   sw        $v0, (0x5022B0 & 0xFFFF)($s6)
    /* 786E0 002776E0 23000010 */  b          .L00277770
    /* 786E4 002776E4 F0D80224 */   addiu     $v0, $zero, -0x2710
  .L002776E8:
    /* 786E8 002776E8 2D200000 */  daddu      $a0, $zero, $zero
    /* 786EC 002776EC E4FE090C */  jal        FlushCache
    /* 786F0 002776F0 5000113C */   lui       $s1, (0x5022A0 >> 16)
    /* 786F4 002776F4 5000133C */  lui        $s3, (0x5022A4 >> 16)
    /* 786F8 002776F8 02000424 */  addiu      $a0, $zero, 0x2
    /* 786FC 002776FC E4FE090C */  jal        FlushCache
    /* 78700 00277700 5000103C */   lui       $s0, (0x5022A8 >> 16)
    /* 78704 00277704 5000123C */  lui        $s2, (0x5022AC >> 16)
    /* 78708 00277708 B022C28E */  lw         $v0, (0x5022B0 & 0xFFFF)($s6)
    /* 7870C 0027770C 09F84000 */  jalr       $v0
    /* 78710 00277710 01000424 */   addiu     $a0, $zero, 0x1
    /* 78714 00277714 B022C38E */  lw         $v1, (0x5022B0 & 0xFFFF)($s6)
    /* 78718 00277718 02000424 */  addiu      $a0, $zero, 0x2
    /* 7871C 0027771C 09F86000 */  jalr       $v1
    /* 78720 00277720 A02222AE */   sw        $v0, (0x5022A0 & 0xFFFF)($s1)
    /* 78724 00277724 B022C58E */  lw         $a1, (0x5022B0 & 0xFFFF)($s6)
    /* 78728 00277728 03000424 */  addiu      $a0, $zero, 0x3
    /* 7872C 0027772C 09F8A000 */  jalr       $a1
    /* 78730 00277730 A42262AE */   sw        $v0, (0x5022A4 & 0xFFFF)($s3)
    /* 78734 00277734 B022C38E */  lw         $v1, (0x5022B0 & 0xFFFF)($s6)
    /* 78738 00277738 04000424 */  addiu      $a0, $zero, 0x4
    /* 7873C 0027773C 09F86000 */  jalr       $v1
    /* 78740 00277740 A82202AE */   sw        $v0, (0x5022A8 & 0xFFFF)($s0)
    /* 78744 00277744 A022248E */  lw         $a0, (0x5022A0 & 0xFFFF)($s1)
    /* 78748 00277748 3700103C */  lui        $s0, %hi(aS_0)
    /* 7874C 0027774C E09B1026 */  addiu      $s0, $s0, %lo(aS_0)
    /* 78750 00277750 09F88000 */  jalr       $a0
    /* 78754 00277754 AC2242AE */   sw        $v0, (0x5022AC & 0xFFFF)($s2)
    /* 78758 00277758 2D200002 */  daddu      $a0, $s0, $zero
    /* 7875C 0027775C A2710A0C */  jal        printf
    /* 78760 00277760 2D284000 */   daddu     $a1, $v0, $zero
    /* 78764 00277764 A422628E */  lw         $v0, (0x5022A4 & 0xFFFF)($s3)
    /* 78768 00277768 09F84000 */  jalr       $v0
    /* 7876C 0027776C 2D20A002 */   daddu     $a0, $s5, $zero
  .L00277770:
    /* 78770 00277770 9000BFDF */  ld         $ra, 0x90($sp)
    /* 78774 00277774 8000BEDF */  ld         $fp, 0x80($sp)
    /* 78778 00277778 7000B7DF */  ld         $s7, 0x70($sp)
    /* 7877C 0027777C 6000B6DF */  ld         $s6, 0x60($sp)
    /* 78780 00277780 5000B5DF */  ld         $s5, 0x50($sp)
    /* 78784 00277784 4000B4DF */  ld         $s4, 0x40($sp)
    /* 78788 00277788 3000B3DF */  ld         $s3, 0x30($sp)
    /* 7878C 0027778C 2000B2DF */  ld         $s2, 0x20($sp)
    /* 78790 00277790 1000B1DF */  ld         $s1, 0x10($sp)
    /* 78794 00277794 0000B0DF */  ld         $s0, 0x0($sp)
    /* 78798 00277798 0800E003 */  jr         $ra
    /* 7879C 0027779C A000BD27 */   addiu     $sp, $sp, 0xA0
endlabel sceAtokInit
