.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching module_opening_prepare, 0x6C

glabel module_opening_prepare
    /* 1BAC8 0021AAC8 2200023C */  lui        $v0, %hi(module_opening_thread_proc)
    /* 1BACC 0021AACC 3B00033C */  lui        $v1, %hi(D_003B7FE0)
    /* 1BAD0 0021AAD0 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 1BAD4 0021AAD4 D0AB4224 */  addiu      $v0, $v0, %lo(module_opening_thread_proc)
    /* 1BAD8 0021AAD8 E07F6324 */  addiu      $v1, $v1, %lo(D_003B7FE0)
    /* 1BADC 0021AADC 0200053C */  lui        $a1, (0x20000 >> 16)
    /* 1BAE0 0021AAE0 06000624 */  addiu      $a2, $zero, 0x6
    /* 1BAE4 0021AAE4 3700073C */  lui        $a3, %hi(module_gp_area)
    /* 1BAE8 0021AAE8 7079E724 */  addiu      $a3, $a3, %lo(module_gp_area)
    /* 1BAEC 0021AAEC 3000B0FF */  sd         $s0, 0x30($sp)
    /* 1BAF0 0021AAF0 2D20A003 */  daddu      $a0, $sp, $zero
    /* 1BAF4 0021AAF4 4000BFFF */  sd         $ra, 0x40($sp)
    /* 1BAF8 0021AAF8 0400A2AF */  sw         $v0, 0x4($sp)
    /* 1BAFC 0021AAFC 0800A3AF */  sw         $v1, 0x8($sp)
    /* 1BB00 0021AB00 0C00A5AF */  sw         $a1, 0xC($sp)
    /* 1BB04 0021AB04 1400A6AF */  sw         $a2, 0x14($sp)
    /* 1BB08 0021AB08 8CFE090C */  jal        CreateThread
    /* 1BB0C 0021AB0C 1000A7AF */   sw        $a3, 0x10($sp)
    /* 1BB10 0021AB10 2D804000 */  daddu      $s0, $v0, $zero
    /* 1BB14 0021AB14 2D280000 */  daddu      $a1, $zero, $zero
    /* 1BB18 0021AB18 94FE090C */  jal        StartThread
    /* 1BB1C 0021AB1C 2D200002 */   daddu     $a0, $s0, $zero
    /* 1BB20 0021AB20 2D100002 */  daddu      $v0, $s0, $zero
    /* 1BB24 0021AB24 4000BFDF */  ld         $ra, 0x40($sp)
    /* 1BB28 0021AB28 3000B0DF */  ld         $s0, 0x30($sp)
    /* 1BB2C 0021AB2C 0800E003 */  jr         $ra
    /* 1BB30 0021AB30 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel module_opening_prepare
