.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching module_opening_thread_proc, 0x80

glabel module_opening_thread_proc
    /* 1BBD0 0021ABD0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1BBD4 0021ABD4 0000B0FF */  sd         $s0, 0x0($sp)
    /* 1BBD8 0021ABD8 1000BFFF */  sd         $ra, 0x10($sp)
    /* 1BBDC 0021ABDC 2B00103C */  lui        $s0, %hi(threadid_2AE5D8)
  .L0021ABE0:
    /* 1BBE0 0021ABE0 A8FE090C */  jal        SleepThread
    /* 1BBE4 0021ABE4 00000000 */   nop
    /* 1BBE8 0021ABE8 8C6B080C */  jal        opening_thread_set_vars
    /* 1BBEC 0021ABEC 00000000 */   nop
    /* 1BBF0 0021ABF0 9E6B080C */  jal        opening_thread_set_vars_2
    /* 1BBF4 0021ABF4 00000000 */   nop
    /* 1BBF8 0021ABF8 146B080C */  jal        OpeningInit
    /* 1BBFC 0021ABFC 00000000 */   nop
    /* 1BC00 0021AC00 9486828F */  lw         $v0, %gp_rel(D_00370004)($gp)
    /* 1BC04 0021AC04 05004014 */  bnez       $v0, .L0021AC1C
    /* 1BC08 0021AC08 2D200000 */   daddu     $a0, $zero, $zero
    /* 1BC0C 0021AC0C 3846080C */  jal        func_002118E0
    /* 1BC10 0021AC10 00000000 */   nop
    /* 1BC14 0021AC14 03000010 */  b          .L0021AC24
    /* 1BC18 0021AC18 00000000 */   nop
  .L0021AC1C:
    /* 1BC1C 0021AC1C 3846080C */  jal        func_002118E0
    /* 1BC20 0021AC20 01000424 */   addiu     $a0, $zero, 0x1
  .L0021AC24:
    /* 1BC24 0021AC24 686B080C */  jal        OpeningDoOpeningIllegal
    /* 1BC28 0021AC28 00000000 */   nop
    /* 1BC2C 0021AC2C B86B080C */  jal        opening_transition_to_clock
    /* 1BC30 0021AC30 00000000 */   nop
    /* 1BC34 0021AC34 3846080C */  jal        func_002118E0
    /* 1BC38 0021AC38 01000424 */   addiu     $a0, $zero, 0x1
    /* 1BC3C 0021AC3C D8E50326 */  addiu      $v1, $s0, %lo(threadid_2AE5D8)
    /* 1BC40 0021AC40 BCFE090C */  jal        SignalSema
    /* 1BC44 0021AC44 1400648C */   lw        $a0, 0x14($v1)
    /* 1BC48 0021AC48 E5FF0010 */  b          .L0021ABE0
    /* 1BC4C 0021AC4C 00000000 */   nop
endlabel module_opening_thread_proc
