.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching OpeningDoOpeningIllegal, 0x8C

glabel OpeningDoOpeningIllegal
    /* 1BDA0 0021ADA0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 1BDA4 0021ADA4 9486838F */  lw         $v1, %gp_rel(D_00370004)($gp)
    /* 1BDA8 0021ADA8 2000BFFF */  sd         $ra, 0x20($sp)
    /* 1BDAC 0021ADAC 02000224 */  addiu      $v0, $zero, 0x2
    /* 1BDB0 0021ADB0 1000B1FF */  sd         $s1, 0x10($sp)
    /* 1BDB4 0021ADB4 0000B0FF */  sd         $s0, 0x0($sp)
    /* 1BDB8 0021ADB8 17006210 */  beq        $v1, $v0, .L0021AE18
    /* 1BDBC 0021ADBC A08680AF */   sw        $zero, %gp_rel(D_00370010)($gp)
    /* 1BDC0 0021ADC0 01001124 */  addiu      $s1, $zero, 0x1
    /* 1BDC4 0021ADC4 02001024 */  addiu      $s0, $zero, 0x2
  .L0021ADC8:
    /* 1BDC8 0021ADC8 366B080C */  jal        OpeningProcess
    /* 1BDCC 0021ADCC 00000000 */   nop
    /* 1BDD0 0021ADD0 9486828F */  lw         $v0, %gp_rel(D_00370004)($gp)
    /* 1BDD4 0021ADD4 05004010 */  beqz       $v0, .L0021ADEC
    /* 1BDD8 0021ADD8 00000000 */   nop
    /* 1BDDC 0021ADDC 07005110 */  beq        $v0, $s1, .L0021ADFC
    /* 1BDE0 0021ADE0 00000000 */   nop
    /* 1BDE4 0021ADE4 07000010 */  b          .L0021AE04
    /* 1BDE8 0021ADE8 00000000 */   nop
  .L0021ADEC:
    /* 1BDEC 0021ADEC 6088080C */  jal        OpeningDoOpening
    /* 1BDF0 0021ADF0 00000000 */   nop
    /* 1BDF4 0021ADF4 03000010 */  b          .L0021AE04
    /* 1BDF8 0021ADF8 00000000 */   nop
  .L0021ADFC:
    /* 1BDFC 0021ADFC 9C8B080C */  jal        OpeningDoIllegalDisc
    /* 1BE00 0021AE00 00000000 */   nop
  .L0021AE04:
    /* 1BE04 0021AE04 566B080C */  jal        OpeningDrawEnd
    /* 1BE08 0021AE08 00000000 */   nop
    /* 1BE0C 0021AE0C 9886828F */  lw         $v0, %gp_rel(D_00370008)($gp)
    /* 1BE10 0021AE10 EDFF5014 */  bne        $v0, $s0, .L0021ADC8
    /* 1BE14 0021AE14 948682AF */   sw        $v0, %gp_rel(D_00370004)($gp)
  .L0021AE18:
    /* 1BE18 0021AE18 2000BFDF */  ld         $ra, 0x20($sp)
    /* 1BE1C 0021AE1C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1BE20 0021AE20 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1BE24 0021AE24 0800E003 */  jr         $ra
    /* 1BE28 0021AE28 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel OpeningDoOpeningIllegal
