.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching module_dvdplayer_prepare, 0x2C0

glabel module_dvdplayer_prepare
    /* AE40 00209E40 40FBBD27 */  addiu      $sp, $sp, -0x4C0
    /* AE44 00209E44 3800023C */  lui        $v0, %hi(dvdplayer_ver_rom)
    /* AE48 00209E48 A004BEFF */  sd         $fp, 0x4A0($sp)
    /* AE4C 00209E4C 2D280000 */  daddu      $a1, $zero, $zero
    /* AE50 00209E50 9004B7FF */  sd         $s7, 0x490($sp)
    /* AE54 00209E54 58674424 */  addiu      $a0, $v0, %lo(dvdplayer_ver_rom)
    /* AE58 00209E58 8004B6FF */  sd         $s6, 0x480($sp)
    /* AE5C 00209E5C 20000624 */  addiu      $a2, $zero, 0x20
    /* AE60 00209E60 7004B5FF */  sd         $s5, 0x470($sp)
    /* AE64 00209E64 38001E3C */  lui        $fp, %hi(dvdplayer_ver_int_minor_rom)
    /* AE68 00209E68 6004B4FF */  sd         $s4, 0x460($sp)
    /* AE6C 00209E6C 3800153C */  lui        $s5, %hi(dvdplayer_ver_int_major_hdd)
    /* AE70 00209E70 5004B3FF */  sd         $s3, 0x450($sp)
    /* AE74 00209E74 3800143C */  lui        $s4, %hi(dvdplayer_ver_int_major_rom)
    /* AE78 00209E78 4004B2FF */  sd         $s2, 0x440($sp)
    /* AE7C 00209E7C 3800163C */  lui        $s6, %hi(dvdplayer_ver_int_minor_hdd)
    /* AE80 00209E80 3004B1FF */  sd         $s1, 0x430($sp)
    /* AE84 00209E84 3800123C */  lui        $s2, %hi(D_00386780)
    /* AE88 00209E88 B004BFFF */  sd         $ra, 0x4B0($sp)
    /* AE8C 00209E8C 7C67D727 */  addiu      $s7, $fp, %lo(dvdplayer_ver_int_minor_rom)
    /* AE90 00209E90 2004B0FF */  sd         $s0, 0x420($sp)
    /* AE94 00209E94 5E710A0C */  jal        memset
    /* AE98 00209E98 80675326 */   addiu     $s3, $s2, %lo(D_00386780)
    /* AE9C 00209E9C 3800033C */  lui        $v1, %hi(dvdplayer_ver_hdd)
    /* AEA0 00209EA0 2D280000 */  daddu      $a1, $zero, $zero
    /* AEA4 00209EA4 88676424 */  addiu      $a0, $v1, %lo(dvdplayer_ver_hdd)
    /* AEA8 00209EA8 5E710A0C */  jal        memset
    /* AEAC 00209EAC 20000624 */   addiu     $a2, $zero, 0x20
    /* AEB0 00209EB0 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* AEB4 00209EB4 3400043C */  lui        $a0, %hi(aRom1Dvdid)
    /* AEB8 00209EB8 AC67C2AE */  sw         $v0, %lo(dvdplayer_ver_int_minor_hdd)($s6)
    /* AEBC 00209EBC 087F8424 */  addiu      $a0, $a0, %lo(aRom1Dvdid)
    /* AEC0 00209EC0 786782AE */  sw         $v0, %lo(dvdplayer_ver_int_major_rom)($s4)
    /* AEC4 00209EC4 01000524 */  addiu      $a1, $zero, 0x1
    /* AEC8 00209EC8 7C67C2AF */  sw         $v0, %lo(dvdplayer_ver_int_minor_rom)($fp)
    /* AECC 00209ECC 806742AE */  sw         $v0, %lo(D_00386780)($s2)
    /* AED0 00209ED0 CA0D0A0C */  jal        sceOpen
    /* AED4 00209ED4 A867A2AE */   sw        $v0, %lo(dvdplayer_ver_int_major_hdd)($s5)
    /* AED8 00209ED8 2D884000 */  daddu      $s1, $v0, $zero
    /* AEDC 00209EDC 48002006 */  bltz       $s1, .L0020A000
    /* AEE0 00209EE0 2D202002 */   daddu     $a0, $s1, $zero
    /* AEE4 00209EE4 2D28A003 */  daddu      $a1, $sp, $zero
    /* AEE8 00209EE8 5A0F0A0C */  jal        sceRead
    /* AEEC 00209EEC 20000624 */   addiu     $a2, $zero, 0x20
    /* AEF0 00209EF0 6C0E0A0C */  jal        sceClose
    /* AEF4 00209EF4 2D202002 */   daddu     $a0, $s1, $zero
    /* AEF8 00209EF8 2D80A003 */  daddu      $s0, $sp, $zero
    /* AEFC 00209EFC 726D0A0C */  jal        atoi
    /* AF00 00209F00 2D20A003 */   daddu     $a0, $sp, $zero
    /* AF04 00209F04 0000A393 */  lbu        $v1, 0x0($sp)
    /* AF08 00209F08 786782AE */  sw         $v0, %lo(dvdplayer_ver_int_major_rom)($s4)
    /* AF0C 00209F0C D0FF6224 */  addiu      $v0, $v1, -0x30
    /* AF10 00209F10 0A00422C */  sltiu      $v0, $v0, 0xA
    /* AF14 00209F14 0B004010 */  beqz       $v0, .L00209F44
    /* AF18 00209F18 2000B227 */   addiu     $s2, $sp, 0x20
    /* AF1C 00209F1C 00000000 */  nop
  .L00209F20:
    /* AF20 00209F20 01001026 */  addiu      $s0, $s0, 0x1
    /* AF24 00209F24 00000392 */  lbu        $v1, 0x0($s0)
    /* AF28 00209F28 D0FF6224 */  addiu      $v0, $v1, -0x30
    /* AF2C 00209F2C 0A00422C */  sltiu      $v0, $v0, 0xA
    /* AF30 00209F30 00000000 */  nop
    /* AF34 00209F34 FAFF4014 */  bnez       $v0, .L00209F20
    /* AF38 00209F38 00000000 */   nop
    /* AF3C 00209F3C 02000010 */  b          .L00209F48
    /* AF40 00209F40 00160300 */   sll       $v0, $v1, 24
  .L00209F44:
    /* AF44 00209F44 00160300 */  sll        $v0, $v1, 24
  .L00209F48:
    /* AF48 00209F48 2E000324 */  addiu      $v1, $zero, 0x2E
    /* AF4C 00209F4C 03160200 */  sra        $v0, $v0, 24
    /* AF50 00209F50 07004310 */  beq        $v0, $v1, .L00209F70
    /* AF54 00209F54 3800033C */   lui       $v1, %hi(dvdplayer_ver_int_major_rom)
    /* AF58 00209F58 000060AE */  sw         $zero, 0x0($s3)
    /* AF5C 00209F5C 0000E0AE */  sw         $zero, 0x0($s7)
    /* AF60 00209F60 78676324 */  addiu      $v1, $v1, %lo(dvdplayer_ver_int_major_rom)
    /* AF64 00209F64 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* AF68 00209F68 13000010 */  b          .L00209FB8
    /* AF6C 00209F6C 000060AC */   sw        $zero, 0x0($v1)
  .L00209F70:
    /* AF70 00209F70 01001026 */  addiu      $s0, $s0, 0x1
    /* AF74 00209F74 726D0A0C */  jal        atoi
    /* AF78 00209F78 2D200002 */   daddu     $a0, $s0, $zero
    /* AF7C 00209F7C 00000392 */  lbu        $v1, 0x0($s0)
    /* AF80 00209F80 03000010 */  b          .L00209F90
    /* AF84 00209F84 0000E2AE */   sw        $v0, 0x0($s7)
  .L00209F88:
    /* AF88 00209F88 01001026 */  addiu      $s0, $s0, 0x1
    /* AF8C 00209F8C 00000392 */  lbu        $v1, 0x0($s0)
  .L00209F90:
    /* AF90 00209F90 D0FF6224 */  addiu      $v0, $v1, -0x30
    /* AF94 00209F94 0A00422C */  sltiu      $v0, $v0, 0xA
    /* AF98 00209F98 00000000 */  nop
    /* AF9C 00209F9C FAFF4014 */  bnez       $v0, .L00209F88
    /* AFA0 00209FA0 00000000 */   nop
    /* AFA4 00209FA4 03006012 */  beqz       $s3, .L00209FB4
    /* AFA8 00209FA8 00160300 */   sll       $v0, $v1, 24
    /* AFAC 00209FAC 03160200 */  sra        $v0, $v0, 24
    /* AFB0 00209FB0 000062AE */  sw         $v0, 0x0($s3)
  .L00209FB4:
    /* AFB4 00209FB4 2D100000 */  daddu      $v0, $zero, $zero
  .L00209FB8:
    /* AFB8 00209FB8 27004014 */  bnez       $v0, .L0020A058
    /* AFBC 00209FBC 3400033C */   lui       $v1, %hi(aDvdplayer)
    /* AFC0 00209FC0 3400043C */  lui        $a0, %hi(aRom1Dvdver)
    /* AFC4 00209FC4 01000524 */  addiu      $a1, $zero, 0x1
    /* AFC8 00209FC8 CA0D0A0C */  jal        sceOpen
    /* AFCC 00209FCC 187F8424 */   addiu     $a0, $a0, %lo(aRom1Dvdver)
    /* AFD0 00209FD0 2D884000 */  daddu      $s1, $v0, $zero
    /* AFD4 00209FD4 1F002006 */  bltz       $s1, .L0020A054
    /* AFD8 00209FD8 3800023C */   lui       $v0, %hi(dvdplayer_ver_rom)
    /* AFDC 00209FDC 2D202002 */  daddu      $a0, $s1, $zero
    /* AFE0 00209FE0 58675024 */  addiu      $s0, $v0, %lo(dvdplayer_ver_rom)
    /* AFE4 00209FE4 20000624 */  addiu      $a2, $zero, 0x20
    /* AFE8 00209FE8 5A0F0A0C */  jal        sceRead
    /* AFEC 00209FEC 2D280002 */   daddu     $a1, $s0, $zero
    /* AFF0 00209FF0 6C0E0A0C */  jal        sceClose
    /* AFF4 00209FF4 2D202002 */   daddu     $a0, $s1, $zero
    /* AFF8 00209FF8 16000010 */  b          .L0020A054
    /* AFFC 00209FFC 1F0000A2 */   sb        $zero, 0x1F($s0)
  .L0020A000:
    /* B000 0020A000 3800023C */  lui        $v0, %hi(romver_bytes)
    /* B004 0020A004 30000324 */  addiu      $v1, $zero, 0x30
    /* B008 0020A008 C0364590 */  lbu        $a1, %lo(romver_bytes)($v0)
    /* B00C 0020A00C 1000A314 */  bne        $a1, $v1, .L0020A050
    /* B010 0020A010 C0364424 */   addiu     $a0, $v0, %lo(romver_bytes)
    /* B014 0020A014 01008390 */  lbu        $v1, 0x1($a0)
    /* B018 0020A018 31000224 */  addiu      $v0, $zero, 0x31
    /* B01C 0020A01C 0D006254 */  bnel       $v1, $v0, .L0020A054
    /* B020 0020A020 2000B227 */   addiu     $s2, $sp, 0x20
    /* B024 0020A024 02008290 */  lbu        $v0, 0x2($a0)
    /* B028 0020A028 0A004554 */  bnel       $v0, $a1, .L0020A054
    /* B02C 0020A02C 2000B227 */   addiu     $s2, $sp, 0x20
    /* B030 0020A030 03008290 */  lbu        $v0, 0x3($a0)
    /* B034 0020A034 D0FF4224 */  addiu      $v0, $v0, -0x30
    /* B038 0020A038 0200422C */  sltiu      $v0, $v0, 0x2
    /* B03C 0020A03C 04004010 */  beqz       $v0, .L0020A050
    /* B040 0020A040 4A000224 */   addiu     $v0, $zero, 0x4A
    /* B044 0020A044 04008390 */  lbu        $v1, 0x4($a0)
    /* B048 0020A048 01006250 */  beql       $v1, $v0, .L0020A050
    /* B04C 0020A04C 806743AE */   sw        $v1, 0x6780($s2)
  .L0020A050:
    /* B050 0020A050 2000B227 */  addiu      $s2, $sp, 0x20
  .L0020A054:
    /* B054 0020A054 3400033C */  lui        $v1, %hi(aDvdplayer)
  .L0020A058:
    /* B058 0020A058 3800023C */  lui        $v0, %hi(dvdplayer_ver_hdd)
    /* B05C 0020A05C 287F6424 */  addiu      $a0, $v1, %lo(aDvdplayer)
    /* B060 0020A060 88674624 */  addiu      $a2, $v0, %lo(dvdplayer_ver_hdd)
    /* B064 0020A064 3800033C */  lui        $v1, %hi(dvdplayer_ver_int_major_hdd)
    /* B068 0020A068 3800023C */  lui        $v0, %hi(dvdplayer_ver_int_minor_hdd)
    /* B06C 0020A06C A8676724 */  addiu      $a3, $v1, %lo(dvdplayer_ver_int_major_hdd)
    /* B070 0020A070 AC674824 */  addiu      $t0, $v0, %lo(dvdplayer_ver_int_minor_hdd)
    /* B074 0020A074 9E23080C */  jal        get_pathconf_key
    /* B078 0020A078 2D284002 */   daddu     $a1, $s2, $zero
    /* B07C 0020A07C 01000324 */  addiu      $v1, $zero, 0x1
    /* B080 0020A080 13004314 */  bne        $v0, $v1, .L0020A0D0
    /* B084 0020A084 B004BFDF */   ld        $ra, 0x4B0($sp)
    /* B088 0020A088 A867A48E */  lw         $a0, %lo(dvdplayer_ver_int_major_hdd)($s5)
    /* B08C 0020A08C 7867838E */  lw         $v1, %lo(dvdplayer_ver_int_major_rom)($s4)
    /* B090 0020A090 2A106400 */  slt        $v0, $v1, $a0
    /* B094 0020A094 08004054 */  bnel       $v0, $zero, .L0020A0B8
    /* B098 0020A098 3800043C */   lui       $a0, %hi(dvdplayer_path)
    /* B09C 0020A09C 0D008314 */  bne        $a0, $v1, .L0020A0D4
    /* B0A0 0020A0A0 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* B0A4 0020A0A4 AC67C38E */  lw         $v1, %lo(dvdplayer_ver_int_minor_hdd)($s6)
    /* B0A8 0020A0A8 7C67C28F */  lw         $v0, %lo(dvdplayer_ver_int_minor_rom)($fp)
    /* B0AC 0020A0AC 2A104300 */  slt        $v0, $v0, $v1
    /* B0B0 0020A0B0 07004010 */  beqz       $v0, .L0020A0D0
    /* B0B4 0020A0B4 3800043C */   lui       $a0, %hi(dvdplayer_path)
  .L0020A0B8:
    /* B0B8 0020A0B8 3400053C */  lui        $a1, %hi(aSdvdplayerElf)
    /* B0BC 0020A0BC B0678424 */  addiu      $a0, $a0, %lo(dvdplayer_path)
    /* B0C0 0020A0C0 387FA524 */  addiu      $a1, $a1, %lo(aSdvdplayerElf)
    /* B0C4 0020A0C4 EC720A0C */  jal        sprintf
    /* B0C8 0020A0C8 2D304002 */   daddu     $a2, $s2, $zero
    /* B0CC 0020A0CC B004BFDF */  ld         $ra, 0x4B0($sp)
  .L0020A0D0:
    /* B0D0 0020A0D0 FFFF0224 */  addiu      $v0, $zero, -0x1
  .L0020A0D4:
    /* B0D4 0020A0D4 A004BEDF */  ld         $fp, 0x4A0($sp)
    /* B0D8 0020A0D8 9004B7DF */  ld         $s7, 0x490($sp)
    /* B0DC 0020A0DC 8004B6DF */  ld         $s6, 0x480($sp)
    /* B0E0 0020A0E0 7004B5DF */  ld         $s5, 0x470($sp)
    /* B0E4 0020A0E4 6004B4DF */  ld         $s4, 0x460($sp)
    /* B0E8 0020A0E8 5004B3DF */  ld         $s3, 0x450($sp)
    /* B0EC 0020A0EC 4004B2DF */  ld         $s2, 0x440($sp)
    /* B0F0 0020A0F0 3004B1DF */  ld         $s1, 0x430($sp)
    /* B0F4 0020A0F4 2004B0DF */  ld         $s0, 0x420($sp)
    /* B0F8 0020A0F8 0800E003 */  jr         $ra
    /* B0FC 0020A0FC C004BD27 */   addiu     $sp, $sp, 0x4C0
endlabel module_dvdplayer_prepare
