.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching __fixsfdi, 0x3C

glabel __fixsfdi
    /* 99700 00298700 00008044 */  mtc1       $zero, $f0
    /* 99704 00298704 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 99708 00298708 34600046 */  c.lt.s     $f12, $f0
    /* 9970C 0029870C 00000000 */  nop
    /* 99710 00298710 05000045 */  bc1f       .L00298728
    /* 99714 00298714 0000BFFF */   sd        $ra, 0x0($sp)
    /* 99718 00298718 0C620A0C */  jal        __fixunssfdi
    /* 9971C 0029871C 07630046 */   neg.s     $f12, $f12
    /* 99720 00298720 03000010 */  b          .L00298730
    /* 99724 00298724 2F100200 */   dsubu     $v0, $zero, $v0
  .L00298728:
    /* 99728 00298728 0C620A0C */  jal        __fixunssfdi
    /* 9972C 0029872C 00000000 */   nop
  .L00298730:
    /* 99730 00298730 0000BFDF */  ld         $ra, 0x0($sp)
    /* 99734 00298734 0800E003 */  jr         $ra
    /* 99738 00298738 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel __fixsfdi
