.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching __malloc_unlock, 0x8

glabel __malloc_unlock
    /* 9D640 0029C640 0800E003 */  jr         $ra
    /* 9D644 0029C644 00000000 */   nop
endlabel __malloc_unlock
