.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching _DisableDmac, 0x10

glabel _DisableDmac
    /* 88D90 00287D90 17000324 */  addiu      $v1, $zero, 0x17
    /* 88D94 00287D94 0C000000 */  syscall    0 /* handwritten instruction */
    /* 88D98 00287D98 0800E003 */  jr         $ra
    /* 88D9C 00287D9C 00000000 */   nop
endlabel _DisableDmac
