.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching _EnableDmac, 0x10

glabel _EnableDmac
    /* 88D80 00287D80 16000324 */  addiu      $v1, $zero, 0x16
    /* 88D84 00287D84 0C000000 */  syscall    0 /* handwritten instruction */
    /* 88D88 00287D88 0800E003 */  jr         $ra
    /* 88D8C 00287D8C 00000000 */   nop
endlabel _EnableDmac
