.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching _free_r, 0x31C

glabel _free_r
    /* A38B0 002A28B0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* A38B4 002A28B4 1000B1FF */  sd         $s1, 0x10($sp)
    /* A38B8 002A28B8 0000B0FF */  sd         $s0, 0x0($sp)
    /* A38BC 002A28BC 2D888000 */  daddu      $s1, $a0, $zero
    /* A38C0 002A28C0 2D80A000 */  daddu      $s0, $a1, $zero
    /* A38C4 002A28C4 BC000012 */  beqz       $s0, .L002A2BB8
    /* A38C8 002A28C8 2000BFFF */   sd        $ra, 0x20($sp)
    /* A38CC 002A28CC 8E710A0C */  jal        __malloc_lock
    /* A38D0 002A28D0 00000000 */   nop
    /* A38D4 002A28D4 F8FF0A26 */  addiu      $t2, $s0, -0x8
    /* A38D8 002A28D8 FFFF023C */  lui        $v0, (0xFFFFFFFE >> 16)
    /* A38DC 002A28DC 0400478D */  lw         $a3, 0x4($t2)
    /* A38E0 002A28E0 FEFF4234 */  ori        $v0, $v0, (0xFFFFFFFE & 0xFFFF)
    /* A38E4 002A28E4 34000D3C */  lui        $t5, %hi(__malloc_av_)
    /* A38E8 002A28E8 FFFF033C */  lui        $v1, (0xFFFFFFFC >> 16)
    /* A38EC 002A28EC 2448E200 */  and        $t1, $a3, $v0
    /* A38F0 002A28F0 8873AC25 */  addiu      $t4, $t5, %lo(__malloc_av_)
    /* A38F4 002A28F4 21304901 */  addu       $a2, $t2, $t1
    /* A38F8 002A28F8 FCFF6334 */  ori        $v1, $v1, (0xFFFFFFFC & 0xFFFF)
    /* A38FC 002A28FC 0400C28C */  lw         $v0, 0x4($a2)
    /* A3900 002A2900 0800848D */  lw         $a0, 0x8($t4)
    /* A3904 002A2904 1E00C414 */  bne        $a2, $a0, .L002A2980
    /* A3908 002A2908 24584300 */   and       $t3, $v0, $v1
    /* A390C 002A290C 0100E230 */  andi       $v0, $a3, 0x1
    /* A3910 002A2910 08004014 */  bnez       $v0, .L002A2934
    /* A3914 002A2914 21482B01 */   addu      $t1, $t1, $t3
    /* A3918 002A2918 F8FF058E */  lw         $a1, -0x8($s0)
    /* A391C 002A291C 23504501 */  subu       $t2, $t2, $a1
    /* A3920 002A2920 21482501 */  addu       $t1, $t1, $a1
    /* A3924 002A2924 0C00488D */  lw         $t0, 0xC($t2)
    /* A3928 002A2928 0800478D */  lw         $a3, 0x8($t2)
    /* A392C 002A292C 0C00E8AC */  sw         $t0, 0xC($a3)
    /* A3930 002A2930 080007AD */  sw         $a3, 0x8($t0)
  .L002A2934:
    /* A3934 002A2934 3400033C */  lui        $v1, %hi(__malloc_trim_threshold)
    /* A3938 002A2938 3C100900 */  dsll32     $v0, $t1, 0
    /* A393C 002A293C 907764DC */  ld         $a0, %lo(__malloc_trim_threshold)($v1)
    /* A3940 002A2940 3E100200 */  dsrl32     $v0, $v0, 0
    /* A3944 002A2944 01002335 */  ori        $v1, $t1, 0x1
    /* A3948 002A2948 08008AAD */  sw         $t2, 0x8($t4)
    /* A394C 002A294C 2B104400 */  sltu       $v0, $v0, $a0
    /* A3950 002A2950 05004014 */  bnez       $v0, .L002A2968
    /* A3954 002A2954 040043AD */   sw        $v1, 0x4($t2)
    /* A3958 002A2958 3400023C */  lui        $v0, %hi(__malloc_top_pad)
    /* A395C 002A295C 2D202002 */  daddu      $a0, $s1, $zero
    /* A3960 002A2960 F48A0A0C */  jal        _malloc_trim_r
    /* A3964 002A2964 9877458C */   lw        $a1, %lo(__malloc_top_pad)($v0)
  .L002A2968:
    /* A3968 002A2968 2D202002 */  daddu      $a0, $s1, $zero
    /* A396C 002A296C 2000BFDF */  ld         $ra, 0x20($sp)
    /* A3970 002A2970 1000B1DF */  ld         $s1, 0x10($sp)
    /* A3974 002A2974 0000B0DF */  ld         $s0, 0x0($sp)
    /* A3978 002A2978 90710A08 */  j          __malloc_unlock
    /* A397C 002A297C 3000BD27 */   addiu     $sp, $sp, 0x30
  .L002A2980:
    /* A3980 002A2980 0100E230 */  andi       $v0, $a3, 0x1
    /* A3984 002A2984 0400CBAC */  sw         $t3, 0x4($a2)
    /* A3988 002A2988 0D004014 */  bnez       $v0, .L002A29C0
    /* A398C 002A298C 2D200000 */   daddu     $a0, $zero, $zero
    /* A3990 002A2990 F8FF058E */  lw         $a1, -0x8($s0)
    /* A3994 002A2994 08008225 */  addiu      $v0, $t4, 0x8
    /* A3998 002A2998 23504501 */  subu       $t2, $t2, $a1
    /* A399C 002A299C 0800438D */  lw         $v1, 0x8($t2)
    /* A39A0 002A29A0 03006214 */  bne        $v1, $v0, .L002A29B0
    /* A39A4 002A29A4 21482501 */   addu      $t1, $t1, $a1
    /* A39A8 002A29A8 05000010 */  b          .L002A29C0
    /* A39AC 002A29AC 01000424 */   addiu     $a0, $zero, 0x1
  .L002A29B0:
    /* A39B0 002A29B0 0C00488D */  lw         $t0, 0xC($t2)
    /* A39B4 002A29B4 2D386000 */  daddu      $a3, $v1, $zero
    /* A39B8 002A29B8 0C00E8AC */  sw         $t0, 0xC($a3)
    /* A39BC 002A29BC 080007AD */  sw         $a3, 0x8($t0)
  .L002A29C0:
    /* A39C0 002A29C0 2118CB00 */  addu       $v1, $a2, $t3
    /* A39C4 002A29C4 0400628C */  lw         $v0, 0x4($v1)
    /* A39C8 002A29C8 01004230 */  andi       $v0, $v0, 0x1
    /* A39CC 002A29CC 14004014 */  bnez       $v0, .L002A2A20
    /* A39D0 002A29D0 01002235 */   ori       $v0, $t1, 0x1
    /* A39D4 002A29D4 0C008014 */  bnez       $a0, .L002A2A08
    /* A39D8 002A29D8 21482B01 */   addu      $t1, $t1, $t3
    /* A39DC 002A29DC 3400023C */  lui        $v0, %hi(D_00347390)
    /* A39E0 002A29E0 0800C38C */  lw         $v1, 0x8($a2)
    /* A39E4 002A29E4 90734224 */  addiu      $v0, $v0, %lo(D_00347390)
    /* A39E8 002A29E8 09006254 */  bnel       $v1, $v0, .L002A2A10
    /* A39EC 002A29EC 0C00C88C */   lw        $t0, 0xC($a2)
    /* A39F0 002A29F0 0C006AAC */  sw         $t2, 0xC($v1)
    /* A39F4 002A29F4 01000424 */  addiu      $a0, $zero, 0x1
    /* A39F8 002A29F8 08006AAC */  sw         $t2, 0x8($v1)
    /* A39FC 002A29FC 080043AD */  sw         $v1, 0x8($t2)
    /* A3A00 002A2A00 06000010 */  b          .L002A2A1C
    /* A3A04 002A2A04 0C0043AD */   sw        $v1, 0xC($t2)
  .L002A2A08:
    /* A3A08 002A2A08 0800C38C */  lw         $v1, 0x8($a2)
    /* A3A0C 002A2A0C 0C00C88C */  lw         $t0, 0xC($a2)
  .L002A2A10:
    /* A3A10 002A2A10 2D386000 */  daddu      $a3, $v1, $zero
    /* A3A14 002A2A14 0C00E8AC */  sw         $t0, 0xC($a3)
    /* A3A18 002A2A18 080007AD */  sw         $a3, 0x8($t0)
  .L002A2A1C:
    /* A3A1C 002A2A1C 01002235 */  ori        $v0, $t1, 0x1
  .L002A2A20:
    /* A3A20 002A2A20 21184901 */  addu       $v1, $t2, $t1
    /* A3A24 002A2A24 040042AD */  sw         $v0, 0x4($t2)
    /* A3A28 002A2A28 5D008014 */  bnez       $a0, .L002A2BA0
    /* A3A2C 002A2A2C 000069AC */   sw        $t1, 0x0($v1)
    /* A3A30 002A2A30 0002222D */  sltiu      $v0, $t1, 0x200
    /* A3A34 002A2A34 16004010 */  beqz       $v0, .L002A2A90
    /* A3A38 002A2A38 C2300900 */   srl       $a2, $t1, 3
    /* A3A3C 002A2A3C FFFF0224 */  addiu      $v0, $zero, -0x1
    /* A3A40 002A2A40 8873A525 */  addiu      $a1, $t5, %lo(__malloc_av_)
    /* A3A44 002A2A44 2A104600 */  slt        $v0, $v0, $a2
    /* A3A48 002A2A48 C0200600 */  sll        $a0, $a2, 3
    /* A3A4C 002A2A4C 0300C324 */  addiu      $v1, $a2, 0x3
    /* A3A50 002A2A50 21408500 */  addu       $t0, $a0, $a1
    /* A3A54 002A2A54 0B18C200 */  movn       $v1, $a2, $v0
    /* A3A58 002A2A58 0800078D */  lw         $a3, 0x8($t0)
    /* A3A5C 002A2A5C 83180300 */  sra        $v1, $v1, 2
    /* A3A60 002A2A60 01000224 */  addiu      $v0, $zero, 0x1
    /* A3A64 002A2A64 0400A48C */  lw         $a0, 0x4($a1)
    /* A3A68 002A2A68 14106200 */  dsllv      $v0, $v0, $v1
    /* A3A6C 002A2A6C 0C0048AD */  sw         $t0, 0xC($t2)
    /* A3A70 002A2A70 080047AD */  sw         $a3, 0x8($t2)
    /* A3A74 002A2A74 3C100200 */  dsll32     $v0, $v0, 0
    /* A3A78 002A2A78 3F100200 */  dsra32     $v0, $v0, 0
    /* A3A7C 002A2A7C 25208200 */  or         $a0, $a0, $v0
    /* A3A80 002A2A80 08000AAD */  sw         $t2, 0x8($t0)
    /* A3A84 002A2A84 0C00EAAC */  sw         $t2, 0xC($a3)
    /* A3A88 002A2A88 45000010 */  b          .L002A2BA0
    /* A3A8C 002A2A8C 0400A4AC */   sw        $a0, 0x4($a1)
  .L002A2A90:
    /* A3A90 002A2A90 421A0900 */  srl        $v1, $t1, 9
    /* A3A94 002A2A94 03006014 */  bnez       $v1, .L002A2AA4
    /* A3A98 002A2A98 0500622C */   sltiu     $v0, $v1, 0x5
    /* A3A9C 002A2A9C 18000010 */  b          .L002A2B00
    /* A3AA0 002A2AA0 C2300900 */   srl       $a2, $t1, 3
  .L002A2AA4:
    /* A3AA4 002A2AA4 03004010 */  beqz       $v0, .L002A2AB4
    /* A3AA8 002A2AA8 82110900 */   srl       $v0, $t1, 6
    /* A3AAC 002A2AAC 14000010 */  b          .L002A2B00
    /* A3AB0 002A2AB0 38004624 */   addiu     $a2, $v0, 0x38
  .L002A2AB4:
    /* A3AB4 002A2AB4 1500622C */  sltiu      $v0, $v1, 0x15
    /* A3AB8 002A2AB8 11004014 */  bnez       $v0, .L002A2B00
    /* A3ABC 002A2ABC 5B006624 */   addiu     $a2, $v1, 0x5B
    /* A3AC0 002A2AC0 5500622C */  sltiu      $v0, $v1, 0x55
    /* A3AC4 002A2AC4 03004010 */  beqz       $v0, .L002A2AD4
    /* A3AC8 002A2AC8 02130900 */   srl       $v0, $t1, 12
    /* A3ACC 002A2ACC 0C000010 */  b          .L002A2B00
    /* A3AD0 002A2AD0 6E004624 */   addiu     $a2, $v0, 0x6E
  .L002A2AD4:
    /* A3AD4 002A2AD4 5501622C */  sltiu      $v0, $v1, 0x155
    /* A3AD8 002A2AD8 03004010 */  beqz       $v0, .L002A2AE8
    /* A3ADC 002A2ADC C2130900 */   srl       $v0, $t1, 15
    /* A3AE0 002A2AE0 07000010 */  b          .L002A2B00
    /* A3AE4 002A2AE4 77004624 */   addiu     $a2, $v0, 0x77
  .L002A2AE8:
    /* A3AE8 002A2AE8 5505622C */  sltiu      $v0, $v1, 0x555
    /* A3AEC 002A2AEC 03004010 */  beqz       $v0, .L002A2AFC
    /* A3AF0 002A2AF0 82140900 */   srl       $v0, $t1, 18
    /* A3AF4 002A2AF4 02000010 */  b          .L002A2B00
    /* A3AF8 002A2AF8 7C004624 */   addiu     $a2, $v0, 0x7C
  .L002A2AFC:
    /* A3AFC 002A2AFC 7E000624 */  addiu      $a2, $zero, 0x7E
  .L002A2B00:
    /* A3B00 002A2B00 8873AB25 */  addiu      $t3, $t5, %lo(__malloc_av_)
    /* A3B04 002A2B04 C0100600 */  sll        $v0, $a2, 3
    /* A3B08 002A2B08 21404B00 */  addu       $t0, $v0, $t3
    /* A3B0C 002A2B0C 0800078D */  lw         $a3, 0x8($t0)
    /* A3B10 002A2B10 0E00E854 */  bnel       $a3, $t0, .L002A2B4C
    /* A3B14 002A2B14 0400E38C */   lw        $v1, 0x4($a3)
    /* A3B18 002A2B18 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* A3B1C 002A2B1C 0300C324 */  addiu      $v1, $a2, 0x3
    /* A3B20 002A2B20 2A104600 */  slt        $v0, $v0, $a2
    /* A3B24 002A2B24 01000424 */  addiu      $a0, $zero, 0x1
    /* A3B28 002A2B28 0B18C200 */  movn       $v1, $a2, $v0
    /* A3B2C 002A2B2C 0400658D */  lw         $a1, 0x4($t3)
    /* A3B30 002A2B30 83180300 */  sra        $v1, $v1, 2
    /* A3B34 002A2B34 14206400 */  dsllv      $a0, $a0, $v1
    /* A3B38 002A2B38 3C200400 */  dsll32     $a0, $a0, 0
    /* A3B3C 002A2B3C 3F200400 */  dsra32     $a0, $a0, 0
    /* A3B40 002A2B40 2528A400 */  or         $a1, $a1, $a0
    /* A3B44 002A2B44 12000010 */  b          .L002A2B90
    /* A3B48 002A2B48 040065AD */   sw        $a1, 0x4($t3)
  .L002A2B4C:
    /* A3B4C 002A2B4C FFFF023C */  lui        $v0, (0xFFFFFFFC >> 16)
    /* A3B50 002A2B50 FCFF4234 */  ori        $v0, $v0, (0xFFFFFFFC & 0xFFFF)
    /* A3B54 002A2B54 24186200 */  and        $v1, $v1, $v0
    /* A3B58 002A2B58 2B182301 */  sltu       $v1, $t1, $v1
    /* A3B5C 002A2B5C 0C006050 */  beql       $v1, $zero, .L002A2B90
    /* A3B60 002A2B60 0C00E88C */   lw        $t0, 0xC($a3)
    /* A3B64 002A2B64 FFFF033C */  lui        $v1, (0xFFFFFFFC >> 16)
    /* A3B68 002A2B68 FCFF6334 */  ori        $v1, $v1, (0xFFFFFFFC & 0xFFFF)
    /* A3B6C 002A2B6C 0800E78C */  lw         $a3, 0x8($a3)
  .L002A2B70:
    /* A3B70 002A2B70 0700E850 */  beql       $a3, $t0, .L002A2B90
    /* A3B74 002A2B74 0C00E88C */   lw        $t0, 0xC($a3)
    /* A3B78 002A2B78 0400E28C */  lw         $v0, 0x4($a3)
    /* A3B7C 002A2B7C 24104300 */  and        $v0, $v0, $v1
    /* A3B80 002A2B80 2B102201 */  sltu       $v0, $t1, $v0
    /* A3B84 002A2B84 FAFF4054 */  bnel       $v0, $zero, .L002A2B70
    /* A3B88 002A2B88 0800E78C */   lw        $a3, 0x8($a3)
    /* A3B8C 002A2B8C 0C00E88C */  lw         $t0, 0xC($a3)
  .L002A2B90:
    /* A3B90 002A2B90 0C0048AD */  sw         $t0, 0xC($t2)
    /* A3B94 002A2B94 080047AD */  sw         $a3, 0x8($t2)
    /* A3B98 002A2B98 08000AAD */  sw         $t2, 0x8($t0)
    /* A3B9C 002A2B9C 0C00EAAC */  sw         $t2, 0xC($a3)
  .L002A2BA0:
    /* A3BA0 002A2BA0 2D202002 */  daddu      $a0, $s1, $zero
    /* A3BA4 002A2BA4 2000BFDF */  ld         $ra, 0x20($sp)
    /* A3BA8 002A2BA8 1000B1DF */  ld         $s1, 0x10($sp)
    /* A3BAC 002A2BAC 0000B0DF */  ld         $s0, 0x0($sp)
    /* A3BB0 002A2BB0 90710A08 */  j          __malloc_unlock
    /* A3BB4 002A2BB4 3000BD27 */   addiu     $sp, $sp, 0x30
  .L002A2BB8:
    /* A3BB8 002A2BB8 2000BFDF */  ld         $ra, 0x20($sp)
    /* A3BBC 002A2BBC 1000B1DF */  ld         $s1, 0x10($sp)
    /* A3BC0 002A2BC0 0000B0DF */  ld         $s0, 0x0($sp)
    /* A3BC4 002A2BC4 0800E003 */  jr         $ra
    /* A3BC8 002A2BC8 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel _free_r
