.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching _init_signal_r, 0x70

glabel _init_signal_r
    /* 9D778 0029C778 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 9D77C 0029C77C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 9D780 0029C780 1000BFFF */  sd         $ra, 0x10($sp)
    /* 9D784 0029C784 2D808000 */  daddu      $s0, $a0, $zero
    /* 9D788 0029C788 D401028E */  lw         $v0, 0x1D4($s0)
    /* 9D78C 0029C78C 12004014 */  bnez       $v0, .L0029C7D8
    /* 9D790 0029C790 2D100000 */   daddu     $v0, $zero, $zero
    /* 9D794 0029C794 EE6E0A0C */  jal        _malloc_r
    /* 9D798 0029C798 80000524 */   addiu     $a1, $zero, 0x80
    /* 9D79C 0029C79C 03004014 */  bnez       $v0, .L0029C7AC
    /* 9D7A0 0029C7A0 D40102AE */   sw        $v0, 0x1D4($s0)
    /* 9D7A4 0029C7A4 0C000010 */  b          .L0029C7D8
    /* 9D7A8 0029C7A8 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L0029C7AC:
    /* 9D7AC 0029C7AC 7C004224 */  addiu      $v0, $v0, 0x7C
    /* 9D7B0 0029C7B0 1F000324 */  addiu      $v1, $zero, 0x1F
    /* 9D7B4 0029C7B4 00000000 */  nop
  .L0029C7B8:
    /* 9D7B8 0029C7B8 000040AC */  sw         $zero, 0x0($v0)
    /* 9D7BC 0029C7BC FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 9D7C0 0029C7C0 FCFF4224 */  addiu      $v0, $v0, -0x4
    /* 9D7C4 0029C7C4 00000000 */  nop
    /* 9D7C8 0029C7C8 00000000 */  nop
    /* 9D7CC 0029C7CC FAFF6104 */  bgez       $v1, .L0029C7B8
    /* 9D7D0 0029C7D0 00000000 */   nop
    /* 9D7D4 0029C7D4 2D100000 */  daddu      $v0, $zero, $zero
  .L0029C7D8:
    /* 9D7D8 0029C7D8 1000BFDF */  ld         $ra, 0x10($sp)
    /* 9D7DC 0029C7DC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 9D7E0 0029C7E0 0800E003 */  jr         $ra
    /* 9D7E4 0029C7E4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel _init_signal_r
