.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching _mprec_log10, 0x6C

glabel _mprec_log10
    /* A5488 002A4488 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* A548C 002A448C 0000B0FF */  sd         $s0, 0x0($sp)
    /* A5490 002A4490 2D808000 */  daddu      $s0, $a0, $zero
    /* A5494 002A4494 C0FF0434 */  ori        $a0, $zero, 0xFFC0
    /* A5498 002A4498 BC230400 */  dsll32     $a0, $a0, 14
    /* A549C 002A449C 1800022A */  slti       $v0, $s0, 0x18
    /* A54A0 002A44A0 07004010 */  beqz       $v0, .L002A44C0
    /* A54A4 002A44A4 1000BFFF */   sd        $ra, 0x10($sp)
    /* A54A8 002A44A8 3700023C */  lui        $v0, %hi(__mprec_tens)
    /* A54AC 002A44AC C0181000 */  sll        $v1, $s0, 3
    /* A54B0 002A44B0 50F84224 */  addiu      $v0, $v0, %lo(__mprec_tens)
    /* A54B4 002A44B4 21186200 */  addu       $v1, $v1, $v0
    /* A54B8 002A44B8 0A000010 */  b          .L002A44E4
    /* A54BC 002A44BC 000062DC */   ld        $v0, 0x0($v1)
  .L002A44C0:
    /* A54C0 002A44C0 0800001A */  blez       $s0, .L002A44E4
    /* A54C4 002A44C4 2D108000 */   daddu     $v0, $a0, $zero
  .L002A44C8:
    /* A54C8 002A44C8 48800534 */  ori        $a1, $zero, 0x8048
    /* A54CC 002A44CC FC2B0500 */  dsll32     $a1, $a1, 15
    /* A54D0 002A44D0 52680A0C */  jal        dpmul
    /* A54D4 002A44D4 FFFF1026 */   addiu     $s0, $s0, -0x1
    /* A54D8 002A44D8 FBFF001E */  bgtz       $s0, .L002A44C8
    /* A54DC 002A44DC 2D204000 */   daddu     $a0, $v0, $zero
    /* A54E0 002A44E0 2D108000 */  daddu      $v0, $a0, $zero
  .L002A44E4:
    /* A54E4 002A44E4 1000BFDF */  ld         $ra, 0x10($sp)
    /* A54E8 002A44E8 0000B0DF */  ld         $s0, 0x0($sp)
    /* A54EC 002A44EC 0800E003 */  jr         $ra
    /* A54F0 002A44F0 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel _mprec_log10
