.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching _sceFreeLoadFileRpc, 0x24

glabel _sceFreeLoadFileRpc
    /* 93F80 00292F80 5100023C */  lui        $v0, (0x510000 >> 16)
    /* 93F84 00292F84 FFFF033C */  lui        $v1, (0xFFFFFFFE >> 16)
    /* 93F88 00292F88 D0A1448C */  lw         $a0, -0x5E30($v0)
    /* 93F8C 00292F8C FEFF6334 */  ori        $v1, $v1, (0xFFFFFFFE & 0xFFFF)
    /* 93F90 00292F90 1000828C */  lw         $v0, 0x10($a0)
    /* 93F94 00292F94 180080AC */  sw         $zero, 0x18($a0)
    /* 93F98 00292F98 24104300 */  and        $v0, $v0, $v1
    /* 93F9C 00292F9C 0800E003 */  jr         $ra
    /* 93FA0 00292FA0 100082AC */   sw        $v0, 0x10($a0)
endlabel _sceFreeLoadFileRpc
