.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_002643EC, 0x4

glabel D_002643EC
    /* 653EC 002643EC 00000000 */  nop
endlabel D_002643EC
