.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00235138, 0x38

glabel func_00235138
    /* 36138 00235138 0A000324 */  addiu      $v1, $zero, 0xA
    /* 3613C 0023513C F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 36140 00235140 1A008300 */  div        $zero, $a0, $v1
    /* 36144 00235144 0000A2AF */  sw         $v0, 0x0($sp)
    /* 36148 00235148 01006050 */  beql       $v1, $zero, .L00235150
    /* 3614C 0023514C CD010000 */   break     0, 7
  .L00235150:
    /* 36150 00235150 0A000424 */  addiu      $a0, $zero, 0xA
    /* 36154 00235154 12100000 */  mflo       $v0
    /* 36158 00235158 10280000 */  mfhi       $a1
    /* 3615C 0023515C 00110200 */  sll        $v0, $v0, 4
    /* 36160 00235160 21104500 */  addu       $v0, $v0, $a1
    /* 36164 00235164 FF004230 */  andi       $v0, $v0, 0xFF
    /* 36168 00235168 0800E003 */  jr         $ra
    /* 3616C 0023516C 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_00235138
