.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0029B2C4, 0x4

glabel D_0029B2C4
    /* 9C2C4 0029B2C4 00000000 */  nop
endlabel D_0029B2C4
