.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0029025C, 0x4

glabel D_0029025C
    /* 9125C 0029025C 00000000 */  nop
endlabel D_0029025C
