.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0021810C, 0x4

glabel D_0021810C
    /* 1910C 0021810C 00000000 */  nop
endlabel D_0021810C
