.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0024F4EC, 0x4

glabel D_0024F4EC
    /* 504EC 0024F4EC 00000000 */  nop
endlabel D_0024F4EC
