.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0027C254, 0x4

glabel D_0027C254
    /* 7D254 0027C254 00000000 */  nop
endlabel D_0027C254
