.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00266AEC, 0x4

glabel D_00266AEC
    /* 67AEC 00266AEC 00000000 */  nop
endlabel D_00266AEC
