.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00235514, 0x4

glabel D_00235514
    /* 36514 00235514 00000000 */  nop
endlabel D_00235514

nonmatching func_00235518, 0x54

glabel func_00235518
    /* 36518 00235518 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 3651C 0023551C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 36520 00235520 12D5080C */  jal        func_00235448
    /* 36524 00235524 00000000 */   nop
    /* 36528 00235528 B4D4080C */  jal        config_save_clock_osd
    /* 3652C 0023552C 00000000 */   nop
    /* 36530 00235530 9C89858F */  lw         $a1, %gp_rel(var_config_writeinprogress)($gp)
    /* 36534 00235534 0500A010 */  beqz       $a1, .L0023554C
    /* 36538 00235538 01000424 */   addiu     $a0, $zero, 0x1
    /* 3653C 0023553C 1249080C */  jal        func_00212448
    /* 36540 00235540 2D300000 */   daddu     $a2, $zero, $zero
    /* 36544 00235544 01004054 */  bnel       $v0, $zero, .L0023554C
    /* 36548 00235548 9C8980AF */   sw        $zero, %gp_rel(var_config_writeinprogress)($gp)
  .L0023554C:
    /* 3654C 0023554C 3AD5080C */  jal        is_config_dirty
    /* 36550 00235550 00000000 */   nop
    /* 36554 00235554 03004014 */  bnez       $v0, .L00235564
    /* 36558 00235558 0000BFDF */   ld        $ra, 0x0($sp)
    /* 3655C 0023555C E2D30808 */  j          config_load_clock_osd
    /* 36560 00235560 1000BD27 */   addiu     $sp, $sp, 0x10
  .L00235564:
    /* 36564 00235564 0800E003 */  jr         $ra
    /* 36568 00235568 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_00235518
    /* 3656C 0023556C 00000000 */  nop

nonmatching func_00235570, 0x2C

glabel func_00235570
    /* 36570 00235570 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 36574 00235574 9C89858F */  lw         $a1, %gp_rel(var_config_writeinprogress)($gp)
    /* 36578 00235578 0500A010 */  beqz       $a1, .L00235590
    /* 3657C 0023557C 0000BFFF */   sd        $ra, 0x0($sp)
    /* 36580 00235580 2D200000 */  daddu      $a0, $zero, $zero
    /* 36584 00235584 1249080C */  jal        func_00212448
    /* 36588 00235588 2D300000 */   daddu     $a2, $zero, $zero
    /* 3658C 0023558C 9C8980AF */  sw         $zero, %gp_rel(var_config_writeinprogress)($gp)
  .L00235590:
    /* 36590 00235590 0000BFDF */  ld         $ra, 0x0($sp)
    /* 36594 00235594 0800E003 */  jr         $ra
    /* 36598 00235598 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_00235570
    /* 3659C 0023559C 00000000 */  nop

nonmatching func_002355A0, 0x58

glabel func_002355A0
    /* 365A0 002355A0 4100043C */  lui        $a0, %hi(D_00409230)
    /* 365A4 002355A4 30928224 */  addiu      $v0, $a0, %lo(D_00409230)
    /* 365A8 002355A8 0400428C */  lw         $v0, 0x4($v0)
    /* 365AC 002355AC 05004004 */  bltz       $v0, .L002355C4
    /* 365B0 002355B0 42180200 */   srl       $v1, $v0, 1
    /* 365B4 002355B4 00108244 */  mtc1       $v0, $f2
    /* 365B8 002355B8 A0108046 */  cvt.s.w    $f2, $f2
    /* 365BC 002355BC 07000010 */  b          .L002355DC
    /* 365C0 002355C0 309280C4 */   lwc1      $f0, -0x6DD0($a0)
  .L002355C4:
    /* 365C4 002355C4 01004230 */  andi       $v0, $v0, 0x1
    /* 365C8 002355C8 25104300 */  or         $v0, $v0, $v1
    /* 365CC 002355CC 00108244 */  mtc1       $v0, $f2
    /* 365D0 002355D0 A0108046 */  cvt.s.w    $f2, $f2
    /* 365D4 002355D4 80100246 */  add.s      $f2, $f2, $f2
    /* 365D8 002355D8 309280C4 */  lwc1       $f0, -0x6DD0($a0)
  .L002355DC:
    /* 365DC 002355DC 7A44013C */  lui        $at, (0x447A0000 >> 16)
    /* 365E0 002355E0 00088144 */  mtc1       $at, $f1
    /* 365E4 002355E4 00000000 */  nop
    /* 365E8 002355E8 00000000 */  nop
    /* 365EC 002355EC 03000146 */  div.s      $f0, $f0, $f1
    /* 365F0 002355F0 0800E003 */  jr         $ra
    /* 365F4 002355F4 00100046 */   add.s     $f0, $f2, $f0
endlabel func_002355A0
