.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00252B5C, 0x4

glabel D_00252B5C
    /* 53B5C 00252B5C 00000000 */  nop
endlabel D_00252B5C
