.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0025B6E4, 0x4

glabel D_0025B6E4
    /* 5C6E4 0025B6E4 00000000 */  nop
endlabel D_0025B6E4
