.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_002455EC, 0x4

glabel D_002455EC
    /* 465EC 002455EC 00000000 */  nop
endlabel D_002455EC
