.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0029A6BC, 0x4

glabel D_0029A6BC
    /* 9B6BC 0029A6BC 00000000 */  nop
endlabel D_0029A6BC
