.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00241B2C, 0x4

glabel D_00241B2C
    /* 42B2C 00241B2C 00000000 */  nop
endlabel D_00241B2C
