.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00229858, 0x120

glabel func_00229858
    /* 2A858 00229858 70FFBD27 */  addiu      $sp, $sp, -0x90
    /* 2A85C 0022985C 0B000224 */  addiu      $v0, $zero, 0xB
    /* 2A860 00229860 5000B5FF */  sd         $s5, 0x50($sp)
    /* 2A864 00229864 4000B4FF */  sd         $s4, 0x40($sp)
    /* 2A868 00229868 2DA8A000 */  daddu      $s5, $a1, $zero
    /* 2A86C 0022986C 3000B3FF */  sd         $s3, 0x30($sp)
    /* 2A870 00229870 2DA0E000 */  daddu      $s4, $a3, $zero
    /* 2A874 00229874 8000BFFF */  sd         $ra, 0x80($sp)
    /* 2A878 00229878 2D988000 */  daddu      $s3, $a0, $zero
    /* 2A87C 0022987C 7000B7FF */  sd         $s7, 0x70($sp)
    /* 2A880 00229880 6000B6FF */  sd         $s6, 0x60($sp)
    /* 2A884 00229884 2000B2FF */  sd         $s2, 0x20($sp)
    /* 2A888 00229888 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2A88C 0022988C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2A890 00229890 0400648E */  lw         $a0, 0x4($s3)
    /* 2A894 00229894 18188200 */  mult       $v1, $a0, $v0
    /* 2A898 00229898 21106600 */  addu       $v0, $v1, $a2
    /* 2A89C 0022989C B8004228 */  slti       $v0, $v0, 0xB8
    /* 2A8A0 002298A0 0C004014 */  bnez       $v0, .L002298D4
    /* 2A8A4 002298A4 2D288000 */   daddu     $a1, $a0, $zero
    /* 2A8A8 002298A8 1000638E */  lw         $v1, 0x10($s3)
    /* 2A8AC 002298AC 00000000 */  nop
  .L002298B0:
    /* 2A8B0 002298B0 0B000224 */  addiu      $v0, $zero, 0xB
    /* 2A8B4 002298B4 F5FFC624 */  addiu      $a2, $a2, -0xB
    /* 2A8B8 002298B8 1810A200 */  mult       $v0, $a1, $v0
    /* 2A8BC 002298BC 2110C200 */  addu       $v0, $a2, $v0
    /* 2A8C0 002298C0 B8004228 */  slti       $v0, $v0, 0xB8
    /* 2A8C4 002298C4 FAFF4010 */  beqz       $v0, .L002298B0
    /* 2A8C8 002298C8 00000000 */   nop
    /* 2A8CC 002298CC 03000010 */  b          .L002298DC
    /* 2A8D0 002298D0 2D906000 */   daddu     $s2, $v1, $zero
  .L002298D4:
    /* 2A8D4 002298D4 1000638E */  lw         $v1, 0x10($s3)
    /* 2A8D8 002298D8 2D906000 */  daddu      $s2, $v1, $zero
  .L002298DC:
    /* 2A8DC 002298DC 1B008018 */  blez       $a0, .L0022994C
    /* 2A8E0 002298E0 2D880000 */   daddu     $s1, $zero, $zero
    /* 2A8E4 002298E4 2D80C000 */  daddu      $s0, $a2, $zero
    /* 2A8E8 002298E8 2B00173C */  lui        $s7, %hi(D_002B2540)
    /* 2A8EC 002298EC 2B00163C */  lui        $s6, %hi(D_002B2550)
  .L002298F0:
    /* 2A8F0 002298F0 CED3080C */  jal        module_clock_get_config_item
    /* 2A8F4 002298F4 0C00648E */   lw        $a0, 0xC($s3)
    /* 2A8F8 002298F8 0000438C */  lw         $v1, 0x0($v0)
    /* 2A8FC 002298FC 08002316 */  bne        $s1, $v1, .L00229920
    /* 2A900 00229900 0400488E */   lw        $t0, 0x4($s2)
    /* 2A904 00229904 2D20A002 */  daddu      $a0, $s5, $zero
    /* 2A908 00229908 2D280002 */  daddu      $a1, $s0, $zero
    /* 2A90C 0022990C 4025E626 */  addiu      $a2, $s7, %lo(D_002B2540)
    /* 2A910 00229910 E69A080C */  jal        DrawNonSelectableItem
    /* 2A914 00229914 2D388002 */   daddu     $a3, $s4, $zero
    /* 2A918 00229918 07000010 */  b          .L00229938
    /* 2A91C 0022991C 0400628E */   lw        $v0, 0x4($s3)
  .L00229920:
    /* 2A920 00229920 2D20A002 */  daddu      $a0, $s5, $zero
    /* 2A924 00229924 2D280002 */  daddu      $a1, $s0, $zero
    /* 2A928 00229928 5025C626 */  addiu      $a2, $s6, %lo(D_002B2550)
    /* 2A92C 0022992C E69A080C */  jal        DrawNonSelectableItem
    /* 2A930 00229930 2D388002 */   daddu     $a3, $s4, $zero
    /* 2A934 00229934 0400628E */  lw         $v0, 0x4($s3)
  .L00229938:
    /* 2A938 00229938 01003126 */  addiu      $s1, $s1, 0x1
    /* 2A93C 0022993C 0B001026 */  addiu      $s0, $s0, 0xB
    /* 2A940 00229940 2A102202 */  slt        $v0, $s1, $v0
    /* 2A944 00229944 EAFF4014 */  bnez       $v0, .L002298F0
    /* 2A948 00229948 20005226 */   addiu     $s2, $s2, 0x20
  .L0022994C:
    /* 2A94C 0022994C 8000BFDF */  ld         $ra, 0x80($sp)
    /* 2A950 00229950 7000B7DF */  ld         $s7, 0x70($sp)
    /* 2A954 00229954 6000B6DF */  ld         $s6, 0x60($sp)
    /* 2A958 00229958 5000B5DF */  ld         $s5, 0x50($sp)
    /* 2A95C 0022995C 4000B4DF */  ld         $s4, 0x40($sp)
    /* 2A960 00229960 3000B3DF */  ld         $s3, 0x30($sp)
    /* 2A964 00229964 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2A968 00229968 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2A96C 0022996C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2A970 00229970 0800E003 */  jr         $ra
    /* 2A974 00229974 9000BD27 */   addiu     $sp, $sp, 0x90
endlabel func_00229858

nonmatching D_00229978, 0xA0

glabel D_00229978
    /* 2A978 00229978 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 2A97C 0022997C 2000B2FF */  sd         $s2, 0x20($sp)
    /* 2A980 00229980 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2A984 00229984 2D908000 */  daddu      $s2, $a0, $zero
    /* 2A988 00229988 5000BFFF */  sd         $ra, 0x50($sp)
    /* 2A98C 0022998C 2D880000 */  daddu      $s1, $zero, $zero
    /* 2A990 00229990 4000B4FF */  sd         $s4, 0x40($sp)
    /* 2A994 00229994 3000B3FF */  sd         $s3, 0x30($sp)
    /* 2A998 00229998 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2A99C 0022999C 0400428E */  lw         $v0, 0x4($s2)
    /* 2A9A0 002299A0 15004018 */  blez       $v0, .L002299F8
    /* 2A9A4 002299A4 1000508E */   lw        $s0, 0x10($s2)
    /* 2A9A8 002299A8 2B00023C */  lui        $v0, %hi(D_002B2540)
    /* 2A9AC 002299AC 2B00033C */  lui        $v1, %hi(D_002B2550)
    /* 2A9B0 002299B0 40255424 */  addiu      $s4, $v0, %lo(D_002B2540)
    /* 2A9B4 002299B4 50257324 */  addiu      $s3, $v1, %lo(D_002B2550)
  .L002299B8:
    /* 2A9B8 002299B8 CED3080C */  jal        module_clock_get_config_item
    /* 2A9BC 002299BC 0C00448E */   lw        $a0, 0xC($s2)
    /* 2A9C0 002299C0 0000438C */  lw         $v1, 0x0($v0)
    /* 2A9C4 002299C4 05002316 */  bne        $s1, $v1, .L002299DC
    /* 2A9C8 002299C8 10000226 */   addiu     $v0, $s0, 0x10
    /* 2A9CC 002299CC 0000867A */  lq         $a2, 0x0($s4)
    /* 2A9D0 002299D0 0000467C */  sq         $a2, 0x0($v0)
    /* 2A9D4 002299D4 04000010 */  b          .L002299E8
    /* 2A9D8 002299D8 0400428E */   lw        $v0, 0x4($s2)
  .L002299DC:
    /* 2A9DC 002299DC 0000667A */  lq         $a2, 0x0($s3)
    /* 2A9E0 002299E0 0000467C */  sq         $a2, 0x0($v0)
    /* 2A9E4 002299E4 0400428E */  lw         $v0, 0x4($s2)
  .L002299E8:
    /* 2A9E8 002299E8 01003126 */  addiu      $s1, $s1, 0x1
    /* 2A9EC 002299EC 2A102202 */  slt        $v0, $s1, $v0
    /* 2A9F0 002299F0 F1FF4014 */  bnez       $v0, .L002299B8
    /* 2A9F4 002299F4 20001026 */   addiu     $s0, $s0, 0x20
  .L002299F8:
    /* 2A9F8 002299F8 5000BFDF */  ld         $ra, 0x50($sp)
    /* 2A9FC 002299FC 4000B4DF */  ld         $s4, 0x40($sp)
    /* 2AA00 00229A00 3000B3DF */  ld         $s3, 0x30($sp)
    /* 2AA04 00229A04 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2AA08 00229A08 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2AA0C 00229A0C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2AA10 00229A10 0800E003 */  jr         $ra
    /* 2AA14 00229A14 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel D_00229978

nonmatching D_00229A18, 0x74

glabel D_00229A18
    /* 2AA18 00229A18 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 2AA1C 00229A1C 3000B3FF */  sd         $s3, 0x30($sp)
    /* 2AA20 00229A20 2000B2FF */  sd         $s2, 0x20($sp)
    /* 2AA24 00229A24 2D98E000 */  daddu      $s3, $a3, $zero
    /* 2AA28 00229A28 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2AA2C 00229A2C 2D90C000 */  daddu      $s2, $a2, $zero
    /* 2AA30 00229A30 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2AA34 00229A34 2D88A000 */  daddu      $s1, $a1, $zero
    /* 2AA38 00229A38 4000BFFF */  sd         $ra, 0x40($sp)
    /* 2AA3C 00229A3C 2D808000 */  daddu      $s0, $a0, $zero
    /* 2AA40 00229A40 CED3080C */  jal        module_clock_get_config_item
    /* 2AA44 00229A44 0C00048E */   lw        $a0, 0xC($s0)
    /* 2AA48 00229A48 0000438C */  lw         $v1, 0x0($v0)
    /* 2AA4C 00229A4C 2D202002 */  daddu      $a0, $s1, $zero
    /* 2AA50 00229A50 1000028E */  lw         $v0, 0x10($s0)
    /* 2AA54 00229A54 2D284002 */  daddu      $a1, $s2, $zero
    /* 2AA58 00229A58 40190300 */  sll        $v1, $v1, 5
    /* 2AA5C 00229A5C 2D386002 */  daddu      $a3, $s3, $zero
    /* 2AA60 00229A60 21186200 */  addu       $v1, $v1, $v0
    /* 2AA64 00229A64 2B00063C */  lui        $a2, %hi(D_002B2560)
    /* 2AA68 00229A68 0400688C */  lw         $t0, 0x4($v1)
    /* 2AA6C 00229A6C 6025C624 */  addiu      $a2, $a2, %lo(D_002B2560)
    /* 2AA70 00229A70 4000BFDF */  ld         $ra, 0x40($sp)
    /* 2AA74 00229A74 3000B3DF */  ld         $s3, 0x30($sp)
    /* 2AA78 00229A78 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2AA7C 00229A7C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2AA80 00229A80 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2AA84 00229A84 E69A0808 */  j          DrawNonSelectableItem
    /* 2AA88 00229A88 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel D_00229A18
    /* 2AA8C 00229A8C 00000000 */  nop

nonmatching D_00229A90, 0x110

glabel D_00229A90
    /* 2AA90 00229A90 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 2AA94 00229A94 4000B4FF */  sd         $s4, 0x40($sp)
    /* 2AA98 00229A98 3000B3FF */  sd         $s3, 0x30($sp)
    /* 2AA9C 00229A9C 2DA08000 */  daddu      $s4, $a0, $zero
    /* 2AAA0 00229AA0 2000B2FF */  sd         $s2, 0x20($sp)
    /* 2AAA4 00229AA4 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2AAA8 00229AA8 2D90A000 */  daddu      $s2, $a1, $zero
    /* 2AAAC 00229AAC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2AAB0 00229AB0 2D88C000 */  daddu      $s1, $a2, $zero
    /* 2AAB4 00229AB4 5000BFFF */  sd         $ra, 0x50($sp)
    /* 2AAB8 00229AB8 2D80E000 */  daddu      $s0, $a3, $zero
    /* 2AABC 00229ABC CED3080C */  jal        module_clock_get_config_item
    /* 2AAC0 00229AC0 0C00848E */   lw        $a0, 0xC($s4)
    /* 2AAC4 00229AC4 2D984000 */  daddu      $s3, $v0, $zero
    /* 2AAC8 00229AC8 2D380002 */  daddu      $a3, $s0, $zero
    /* 2AACC 00229ACC 2D284002 */  daddu      $a1, $s2, $zero
    /* 2AAD0 00229AD0 2D302002 */  daddu      $a2, $s1, $zero
    /* 2AAD4 00229AD4 16A6080C */  jal        func_00229858
    /* 2AAD8 00229AD8 2D208002 */   daddu     $a0, $s4, $zero
    /* 2AADC 00229ADC 2B00043C */  lui        $a0, %hi(D_002B5780)
    /* 2AAE0 00229AE0 2D280000 */  daddu      $a1, $zero, $zero
    /* 2AAE4 00229AE4 A6D2080C */  jal        func_00234A98
    /* 2AAE8 00229AE8 80578424 */   addiu     $a0, $a0, %lo(D_002B5780)
    /* 2AAEC 00229AEC 24004010 */  beqz       $v0, .L00229B80
    /* 2AAF0 00229AF0 C489838F */   lw        $v1, %gp_rel(D_00370334)($gp)
    /* 2AAF4 00229AF4 00106230 */  andi       $v0, $v1, 0x1000
    /* 2AAF8 00229AF8 0E004010 */  beqz       $v0, .L00229B34
    /* 2AAFC 00229AFC 00406230 */   andi      $v0, $v1, 0x4000
    /* 2AB00 00229B00 0000628E */  lw         $v0, 0x0($s3)
    /* 2AB04 00229B04 FFFF4324 */  addiu      $v1, $v0, -0x1
    /* 2AB08 00229B08 04006104 */  bgez       $v1, .L00229B1C
    /* 2AB0C 00229B0C 000063AE */   sw        $v1, 0x0($s3)
    /* 2AB10 00229B10 0400828E */  lw         $v0, 0x4($s4)
    /* 2AB14 00229B14 21106200 */  addu       $v0, $v1, $v0
    /* 2AB18 00229B18 000062AE */  sw         $v0, 0x0($s3)
  .L00229B1C:
    /* 2AB1C 00229B1C 00630424 */  addiu      $a0, $zero, 0x6300
    /* 2AB20 00229B20 01000524 */  addiu      $a1, $zero, 0x1
    /* 2AB24 00229B24 BAAA080C */  jal        j_sound_handler_queue_command_0
    /* 2AB28 00229B28 06000624 */   addiu     $a2, $zero, 0x6
    /* 2AB2C 00229B2C C489838F */  lw         $v1, %gp_rel(D_00370334)($gp)
    /* 2AB30 00229B30 00406230 */  andi       $v0, $v1, 0x4000
  .L00229B34:
    /* 2AB34 00229B34 13004010 */  beqz       $v0, .L00229B84
    /* 2AB38 00229B38 5000BFDF */   ld        $ra, 0x50($sp)
    /* 2AB3C 00229B3C 0000628E */  lw         $v0, 0x0($s3)
    /* 2AB40 00229B40 01004224 */  addiu      $v0, $v0, 0x1
    /* 2AB44 00229B44 000062AE */  sw         $v0, 0x0($s3)
    /* 2AB48 00229B48 0400838E */  lw         $v1, 0x4($s4)
    /* 2AB4C 00229B4C 02004350 */  beql       $v0, $v1, .L00229B58
    /* 2AB50 00229B50 000060AE */   sw        $zero, 0x0($s3)
    /* 2AB54 00229B54 5000BFDF */  ld         $ra, 0x50($sp)
  .L00229B58:
    /* 2AB58 00229B58 00630424 */  addiu      $a0, $zero, 0x6300
    /* 2AB5C 00229B5C 4000B4DF */  ld         $s4, 0x40($sp)
    /* 2AB60 00229B60 01000524 */  addiu      $a1, $zero, 0x1
    /* 2AB64 00229B64 3000B3DF */  ld         $s3, 0x30($sp)
    /* 2AB68 00229B68 06000624 */  addiu      $a2, $zero, 0x6
    /* 2AB6C 00229B6C 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2AB70 00229B70 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2AB74 00229B74 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2AB78 00229B78 BAAA0808 */  j          j_sound_handler_queue_command_0
    /* 2AB7C 00229B7C 6000BD27 */   addiu     $sp, $sp, 0x60
  .L00229B80:
    /* 2AB80 00229B80 5000BFDF */  ld         $ra, 0x50($sp)
  .L00229B84:
    /* 2AB84 00229B84 4000B4DF */  ld         $s4, 0x40($sp)
    /* 2AB88 00229B88 3000B3DF */  ld         $s3, 0x30($sp)
    /* 2AB8C 00229B8C 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2AB90 00229B90 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2AB94 00229B94 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2AB98 00229B98 0800E003 */  jr         $ra
    /* 2AB9C 00229B9C 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel D_00229A90
