.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00209C3C, 0x4

glabel D_00209C3C
    /* AC3C 00209C3C 00000000 */  nop
endlabel D_00209C3C
