.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0022D5D4, 0x4

glabel D_0022D5D4
    /* 2E5D4 0022D5D4 00000000 */  nop
endlabel D_0022D5D4
