.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_002743D4, 0x4

glabel D_002743D4
    /* 753D4 002743D4 00000000 */  nop
endlabel D_002743D4
