.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_002682F4, 0x4

glabel D_002682F4
    /* 692F4 002682F4 00000000 */  nop
endlabel D_002682F4
