.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0021A52C, 0x4

glabel D_0021A52C
    /* 1B52C 0021A52C 00000000 */  nop
endlabel D_0021A52C
