.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0020C784, 0x4

glabel D_0020C784
    /* D784 0020C784 00000000 */  nop
endlabel D_0020C784
