.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0027639C, 0x4

glabel D_0027639C
    /* 7739C 0027639C 00000000 */  nop
endlabel D_0027639C
