.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00288174, 0x4

glabel D_00288174
    /* 89174 00288174 00000000 */  nop
endlabel D_00288174
