.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0022D3DC, 0x4

glabel D_0022D3DC
    /* 2E3DC 0022D3DC 00000000 */  nop
endlabel D_0022D3DC
