.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0029CB24, 0x4

glabel D_0029CB24
    /* 9DB24 0029CB24 00000000 */  nop
endlabel D_0029CB24
