.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00234A5C, 0x4

glabel D_00234A5C
    /* 35A5C 00234A5C 00000000 */  nop
endlabel D_00234A5C
