.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00292444, 0x4

glabel D_00292444
    /* 93444 00292444 00000000 */  nop
endlabel D_00292444
