.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0026BF0C, 0x4

glabel D_0026BF0C
    /* 6CF0C 0026BF0C 00000000 */  nop
endlabel D_0026BF0C
