.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_002445E4, 0x4

glabel D_002445E4
    /* 455E4 002445E4 00000000 */  nop
endlabel D_002445E4
