.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00263804, 0x4

glabel D_00263804
    /* 64804 00263804 00000000 */  nop
endlabel D_00263804
