.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00264124, 0x4

glabel D_00264124
    /* 65124 00264124 00000000 */  nop
endlabel D_00264124
