.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_002083D4, 0x4

glabel D_002083D4
    /* 93D4 002083D4 00000000 */  nop
endlabel D_002083D4
