.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_002638B8, 0x24

glabel D_002638B8
    /* 648B8 002638B8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 648BC 002638BC FF008430 */  andi       $a0, $a0, 0xFF
    /* 648C0 002638C0 0000BFFF */  sd         $ra, 0x0($sp)
    /* 648C4 002638C4 FFFFA530 */  andi       $a1, $a1, 0xFFFF
    /* 648C8 002638C8 C8C2090C */  jal        func_00270B20
    /* 648CC 002638CC FFFFC630 */   andi      $a2, $a2, 0xFFFF
    /* 648D0 002638D0 0000BFDF */  ld         $ra, 0x0($sp)
    /* 648D4 002638D4 0800E003 */  jr         $ra
    /* 648D8 002638D8 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel D_002638B8
    /* 648DC 002638DC 00000000 */  nop
