.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00264AB0, 0x10

glabel D_00264AB0
    /* 65AB0 00264AB0 4E00033C */  lui        $v1, (0x4E7FB4 >> 16)
    /* 65AB4 00264AB4 B47F628C */  lw         $v0, (0x4E7FB4 & 0xFFFF)($v1)
    /* 65AB8 00264AB8 0800E003 */  jr         $ra
    /* 65ABC 00264ABC 0100422C */   sltiu     $v0, $v0, 0x1
endlabel D_00264AB0
