.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching DPRINT, 0x28

glabel DPRINT
    /* 7F000 0027E000 80FFBD27 */  addiu      $sp, $sp, -0x80
    /* 7F004 0027E004 4800A5FF */  sd         $a1, 0x48($sp)
    /* 7F008 0027E008 5000A6FF */  sd         $a2, 0x50($sp)
    /* 7F00C 0027E00C 5800A7FF */  sd         $a3, 0x58($sp)
    /* 7F010 0027E010 6000A8FF */  sd         $t0, 0x60($sp)
    /* 7F014 0027E014 6800A9FF */  sd         $t1, 0x68($sp)
    /* 7F018 0027E018 7000AAFF */  sd         $t2, 0x70($sp)
    /* 7F01C 0027E01C 7800ABFF */  sd         $t3, 0x78($sp)
    /* 7F020 0027E020 0800E003 */  jr         $ra
    /* 7F024 0027E024 8000BD27 */   addiu     $sp, $sp, 0x80
endlabel DPRINT
