.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching EIntr, 0x18

glabel EIntr
    /* 88888 00287888 00600240 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 8888C 0028788C 0100033C */  lui        $v1, (0x10000 >> 16)
    /* 88890 00287890 24104300 */  and        $v0, $v0, $v1
    /* 88894 00287894 38000042 */  ei /* handwritten instruction */
    /* 88898 00287898 0800E003 */  jr         $ra
    /* 8889C 0028789C 2B100200 */   sltu      $v0, $zero, $v0
endlabel EIntr
