.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching ExpandInit, 0x1C

glabel ExpandInit
    /* 1D10 00200D10 3700033C */  lui        $v1, %hi(D_00370E48)
    /* 1D14 00200D14 0000858C */  lw         $a1, 0x0($a0)
    /* 1D18 00200D18 04008424 */  addiu      $a0, $a0, 0x4
    /* 1D1C 00200D1C 480E6224 */  addiu      $v0, $v1, %lo(D_00370E48)
    /* 1D20 00200D20 480E65AC */  sw         $a1, %lo(D_00370E48)($v1)
    /* 1D24 00200D24 0800E003 */  jr         $ra
    /* 1D28 00200D28 140044AC */   sw        $a0, 0x14($v0)
endlabel ExpandInit
