.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching fileops_cmd_zonesz_pfs, 0x2C

glabel fileops_cmd_zonesz_pfs
    /* 112B8 002102B8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 112BC 002102BC 01500524 */  addiu      $a1, $zero, 0x5001
    /* 112C0 002102C0 0000BFFF */  sd         $ra, 0x0($sp)
    /* 112C4 002102C4 2D300000 */  daddu      $a2, $zero, $zero
    /* 112C8 002102C8 2D380000 */  daddu      $a3, $zero, $zero
    /* 112CC 002102CC 2D400000 */  daddu      $t0, $zero, $zero
    /* 112D0 002102D0 BA3D080C */  jal        fileops_cmd_devctl
    /* 112D4 002102D4 2D480000 */   daddu     $t1, $zero, $zero
    /* 112D8 002102D8 0000BFDF */  ld         $ra, 0x0($sp)
    /* 112DC 002102DC 0800E003 */  jr         $ra
    /* 112E0 002102E0 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel fileops_cmd_zonesz_pfs
