.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching fileops_cmd_sync, 0x68

glabel fileops_cmd_sync
    /* 10470 0020F470 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 10474 0020F474 1000B1FF */  sd         $s1, 0x10($sp)
    /* 10478 0020F478 2D888000 */  daddu      $s1, $a0, $zero
    /* 1047C 0020F47C 2000B2FF */  sd         $s2, 0x20($sp)
    /* 10480 0020F480 2D90A000 */  daddu      $s2, $a1, $zero
    /* 10484 0020F484 13000424 */  addiu      $a0, $zero, 0x13
    /* 10488 0020F488 3000BFFF */  sd         $ra, 0x30($sp)
    /* 1048C 0020F48C 1441080C */  jal        fileops_send_cmd
    /* 10490 0020F490 0000B0FF */   sd        $s0, 0x0($sp)
    /* 10494 0020F494 0A004004 */  bltz       $v0, .L0020F4C0
    /* 10498 0020F498 3900103C */   lui       $s0, %hi(D_0038E7C0)
    /* 1049C 0020F49C 2D282002 */  daddu      $a1, $s1, $zero
    /* 104A0 0020F4A0 C0E71026 */  addiu      $s0, $s0, %lo(D_0038E7C0)
    /* 104A4 0020F4A4 64740A0C */  jal        strcpy
    /* 104A8 0020F4A8 2D200002 */   daddu     $a0, $s0, $zero
    /* 104AC 0020F4AC 3900033C */  lui        $v1, %hi(fileops_sema1)
    /* 104B0 0020F4B0 041C12AE */  sw         $s2, 0x1C04($s0)
    /* 104B4 0020F4B4 BCFE090C */  jal        SignalSema
    /* 104B8 0020F4B8 84E7648C */   lw        $a0, %lo(fileops_sema1)($v1)
    /* 104BC 0020F4BC 2D100000 */  daddu      $v0, $zero, $zero
  .L0020F4C0:
    /* 104C0 0020F4C0 3000BFDF */  ld         $ra, 0x30($sp)
    /* 104C4 0020F4C4 2000B2DF */  ld         $s2, 0x20($sp)
    /* 104C8 0020F4C8 1000B1DF */  ld         $s1, 0x10($sp)
    /* 104CC 0020F4CC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 104D0 0020F4D0 0800E003 */  jr         $ra
    /* 104D4 0020F4D4 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel fileops_cmd_sync
