.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching fileops_cmd_del_subpartition, 0x2C

glabel fileops_cmd_del_subpartition
    /* 10EC0 0020FEC0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 10EC4 0020FEC4 02680524 */  addiu      $a1, $zero, 0x6802
    /* 10EC8 0020FEC8 0000BFFF */  sd         $ra, 0x0($sp)
    /* 10ECC 0020FECC 2D300000 */  daddu      $a2, $zero, $zero
    /* 10ED0 0020FED0 2D380000 */  daddu      $a3, $zero, $zero
    /* 10ED4 0020FED4 2D400000 */  daddu      $t0, $zero, $zero
    /* 10ED8 0020FED8 1C3E080C */  jal        fileops_cmd_ioctl2
    /* 10EDC 0020FEDC 2D480000 */   daddu     $t1, $zero, $zero
    /* 10EE0 0020FEE0 0000BFDF */  ld         $ra, 0x0($sp)
    /* 10EE4 0020FEE4 0800E003 */  jr         $ra
    /* 10EE8 0020FEE8 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel fileops_cmd_del_subpartition
