.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching fileops_cmd_symlink, 0x16C

glabel fileops_cmd_symlink
    /* 100F0 0020F0F0 00FFBD27 */  addiu      $sp, $sp, -0x100
    /* 100F4 0020F0F4 B000B3FF */  sd         $s3, 0xB0($sp)
    /* 100F8 0020F0F8 C000B4FF */  sd         $s4, 0xC0($sp)
    /* 100FC 0020F0FC 2D988000 */  daddu      $s3, $a0, $zero
    /* 10100 0020F100 A000B2FF */  sd         $s2, 0xA0($sp)
    /* 10104 0020F104 2DA0A000 */  daddu      $s4, $a1, $zero
    /* 10108 0020F108 F000BFFF */  sd         $ra, 0xF0($sp)
    /* 1010C 0020F10C 0C000424 */  addiu      $a0, $zero, 0xC
    /* 10110 0020F110 E000B6FF */  sd         $s6, 0xE0($sp)
    /* 10114 0020F114 D000B5FF */  sd         $s5, 0xD0($sp)
    /* 10118 0020F118 9000B1FF */  sd         $s1, 0x90($sp)
    /* 1011C 0020F11C 1441080C */  jal        fileops_send_cmd
    /* 10120 0020F120 8000B0FF */   sd        $s0, 0x80($sp)
    /* 10124 0020F124 2D904000 */  daddu      $s2, $v0, $zero
    /* 10128 0020F128 42004006 */  bltz       $s2, .L0020F234
    /* 1012C 0020F12C 2D28A003 */   daddu     $a1, $sp, $zero
    /* 10130 0020F130 3900023C */  lui        $v0, %hi(D_0038BD80)
    /* 10134 0020F134 2D206002 */  daddu      $a0, $s3, $zero
    /* 10138 0020F138 80BD5524 */  addiu      $s5, $v0, %lo(D_0038BD80)
    /* 1013C 0020F13C 2D30A002 */  daddu      $a2, $s5, $zero
    /* 10140 0020F140 3A41080C */  jal        fileops_handle_cmd_path
    /* 10144 0020F144 EDFF1124 */   addiu     $s1, $zero, -0x13
    /* 10148 0020F148 05005114 */  bne        $v0, $s1, .L0020F160
    /* 1014C 0020F14C 3900023C */   lui       $v0, %hi(D_0038C180)
    /* 10150 0020F150 0C41080C */  jal        fileops_cmd_handle_error
    /* 10154 0020F154 EDFF0424 */   addiu     $a0, $zero, -0x13
    /* 10158 0020F158 36000010 */  b          .L0020F234
    /* 1015C 0020F15C 2D100000 */   daddu     $v0, $zero, $zero
  .L0020F160:
    /* 10160 0020F160 4000B027 */  addiu      $s0, $sp, 0x40
    /* 10164 0020F164 80C15624 */  addiu      $s6, $v0, %lo(D_0038C180)
    /* 10168 0020F168 2D208002 */  daddu      $a0, $s4, $zero
    /* 1016C 0020F16C 2D280002 */  daddu      $a1, $s0, $zero
    /* 10170 0020F170 3A41080C */  jal        fileops_handle_cmd_path
    /* 10174 0020F174 2D30C002 */   daddu     $a2, $s6, $zero
    /* 10178 0020F178 2D904000 */  daddu      $s2, $v0, $zero
    /* 1017C 0020F17C 05005116 */  bne        $s2, $s1, .L0020F194
    /* 10180 0020F180 2D280002 */   daddu     $a1, $s0, $zero
    /* 10184 0020F184 0C41080C */  jal        fileops_cmd_handle_error
    /* 10188 0020F188 EDFF0424 */   addiu     $a0, $zero, -0x13
    /* 1018C 0020F18C 29000010 */  b          .L0020F234
    /* 10190 0020F190 2D100000 */   daddu     $v0, $zero, $zero
  .L0020F194:
    /* 10194 0020F194 13740A0C */  jal        strcmp
    /* 10198 0020F198 2D20A003 */   daddu     $a0, $sp, $zero
    /* 1019C 0020F19C 05004010 */  beqz       $v0, .L0020F1B4
    /* 101A0 0020F1A0 FEFF0224 */   addiu     $v0, $zero, -0x2
    /* 101A4 0020F1A4 0C41080C */  jal        fileops_cmd_handle_error
    /* 101A8 0020F1A8 EEFF0424 */   addiu     $a0, $zero, -0x12
    /* 101AC 0020F1AC 21000010 */  b          .L0020F234
    /* 101B0 0020F1B0 2D100000 */   daddu     $v0, $zero, $zero
  .L0020F1B4:
    /* 101B4 0020F1B4 14004216 */  bne        $s2, $v0, .L0020F208
    /* 101B8 0020F1B8 3900103C */   lui       $s0, %hi(D_0038E7C0)
    /* 101BC 0020F1BC 3E42080C */  jal        func_002108F8
    /* 101C0 0020F1C0 2D20A003 */   daddu     $a0, $sp, $zero
    /* 101C4 0020F1C4 3900103C */  lui        $s0, %hi(D_0038E7C0)
    /* 101C8 0020F1C8 3500113C */  lui        $s1, %hi(aPfsDS)
    /* 101CC 0020F1CC 2D904000 */  daddu      $s2, $v0, $zero
    /* 101D0 0020F1D0 C0E71026 */  addiu      $s0, $s0, %lo(D_0038E7C0)
    /* 101D4 0020F1D4 C0893126 */  addiu      $s1, $s1, %lo(aPfsDS)
    /* 101D8 0020F1D8 2D38A002 */  daddu      $a3, $s5, $zero
    /* 101DC 0020F1DC 2D200002 */  daddu      $a0, $s0, $zero
    /* 101E0 0020F1E0 2D282002 */  daddu      $a1, $s1, $zero
    /* 101E4 0020F1E4 EC720A0C */  jal        sprintf
    /* 101E8 0020F1E8 2D304002 */   daddu     $a2, $s2, $zero
    /* 101EC 0020F1EC 00040426 */  addiu      $a0, $s0, 0x400
    /* 101F0 0020F1F0 2D282002 */  daddu      $a1, $s1, $zero
    /* 101F4 0020F1F4 2D304002 */  daddu      $a2, $s2, $zero
    /* 101F8 0020F1F8 EC720A0C */  jal        sprintf
    /* 101FC 0020F1FC 2D38C002 */   daddu     $a3, $s6, $zero
    /* 10200 0020F200 09000010 */  b          .L0020F228
    /* 10204 0020F204 3900023C */   lui       $v0, %hi(fileops_sema1)
  .L0020F208:
    /* 10208 0020F208 2D286002 */  daddu      $a1, $s3, $zero
    /* 1020C 0020F20C C0E71026 */  addiu      $s0, $s0, %lo(D_0038E7C0)
    /* 10210 0020F210 64740A0C */  jal        strcpy
    /* 10214 0020F214 2D200002 */   daddu     $a0, $s0, $zero
    /* 10218 0020F218 00040426 */  addiu      $a0, $s0, 0x400
    /* 1021C 0020F21C 64740A0C */  jal        strcpy
    /* 10220 0020F220 2D288002 */   daddu     $a1, $s4, $zero
    /* 10224 0020F224 3900023C */  lui        $v0, %hi(fileops_sema1)
  .L0020F228:
    /* 10228 0020F228 BCFE090C */  jal        SignalSema
    /* 1022C 0020F22C 84E7448C */   lw        $a0, %lo(fileops_sema1)($v0)
    /* 10230 0020F230 2D100000 */  daddu      $v0, $zero, $zero
  .L0020F234:
    /* 10234 0020F234 F000BFDF */  ld         $ra, 0xF0($sp)
    /* 10238 0020F238 E000B6DF */  ld         $s6, 0xE0($sp)
    /* 1023C 0020F23C D000B5DF */  ld         $s5, 0xD0($sp)
    /* 10240 0020F240 C000B4DF */  ld         $s4, 0xC0($sp)
    /* 10244 0020F244 B000B3DF */  ld         $s3, 0xB0($sp)
    /* 10248 0020F248 A000B2DF */  ld         $s2, 0xA0($sp)
    /* 1024C 0020F24C 9000B1DF */  ld         $s1, 0x90($sp)
    /* 10250 0020F250 8000B0DF */  ld         $s0, 0x80($sp)
    /* 10254 0020F254 0800E003 */  jr         $ra
    /* 10258 0020F258 0001BD27 */   addiu     $sp, $sp, 0x100
endlabel fileops_cmd_symlink
