.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching fileops_cmd_set_osd_mbr, 0x34

glabel fileops_cmd_set_osd_mbr
    /* 11100 00210100 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 11104 00210104 08000724 */  addiu      $a3, $zero, 0x8
    /* 11108 00210108 0000A5AF */  sw         $a1, 0x0($sp)
    /* 1110C 0021010C 2D400000 */  daddu      $t0, $zero, $zero
    /* 11110 00210110 0400A6AF */  sw         $a2, 0x4($sp)
    /* 11114 00210114 33680524 */  addiu      $a1, $zero, 0x6833
    /* 11118 00210118 1000BFFF */  sd         $ra, 0x10($sp)
    /* 1111C 0021011C 2D30A003 */  daddu      $a2, $sp, $zero
    /* 11120 00210120 BA3D080C */  jal        fileops_cmd_devctl
    /* 11124 00210124 2D480000 */   daddu     $t1, $zero, $zero
    /* 11128 00210128 1000BFDF */  ld         $ra, 0x10($sp)
    /* 1112C 0021012C 0800E003 */  jr         $ra
    /* 11130 00210130 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel fileops_cmd_set_osd_mbr
