.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching ftoi, 0x90

glabel ftoi
    /* 81F30 00280F30 2D288000 */  daddu      $a1, $a0, $zero
    /* 81F34 00280F34 78100500 */  dsll       $v0, $a1, 1
    /* 81F38 00280F38 7E350200 */  dsrl32     $a2, $v0, 21
    /* 81F3C 00280F3C CDFBC664 */  daddiu     $a2, $a2, -0x433
    /* 81F40 00280F40 CBFFC228 */  slti       $v0, $a2, -0x35
    /* 81F44 00280F44 03004010 */  beqz       $v0, .L00280F54
    /* 81F48 00280F48 0D00C228 */   slti      $v0, $a2, 0xD
    /* 81F4C 00280F4C 0800E003 */  jr         $ra
    /* 81F50 00280F50 2D100000 */   daddu     $v0, $zero, $zero
  .L00280F54:
    /* 81F54 00280F54 03004014 */  bnez       $v0, .L00280F64
    /* 81F58 00280F58 38130500 */   dsll      $v0, $a1, 12
    /* 81F5C 00280F5C 0800E003 */  jr         $ra
    /* 81F60 00280F60 0F270224 */   addiu     $v0, $zero, 0x270F
  .L00280F64:
    /* 81F64 00280F64 00800334 */  ori        $v1, $zero, 0x8000
    /* 81F68 00280F68 7C190300 */  dsll32     $v1, $v1, 5
    /* 81F6C 00280F6C 3A2B0200 */  dsrl       $a1, $v0, 12
    /* 81F70 00280F70 0D00C104 */  bgez       $a2, .L00280FA8
    /* 81F74 00280F74 2528A300 */   or        $a1, $a1, $v1
    /* 81F78 00280F78 2F300600 */  dsubu      $a2, $zero, $a2
    /* 81F7C 00280F7C 03000224 */  addiu      $v0, $zero, 0x3
    /* 81F80 00280F80 FEFFC364 */  daddiu     $v1, $a2, -0x2
    /* 81F84 00280F84 3C180300 */  dsll32     $v1, $v1, 0
    /* 81F88 00280F88 3F180300 */  dsra32     $v1, $v1, 0
    /* 81F8C 00280F8C 16286500 */  dsrlv      $a1, $a1, $v1
    /* 81F90 00280F90 0300A430 */  andi       $a0, $a1, 0x3
    /* 81F94 00280F94 07008254 */  bnel       $a0, $v0, .L00280FB4
    /* 81F98 00280F98 BA280500 */   dsrl      $a1, $a1, 2
    /* 81F9C 00280F9C BA100500 */  dsrl       $v0, $a1, 2
    /* 81FA0 00280FA0 04000010 */  b          .L00280FB4
    /* 81FA4 00280FA4 01004564 */   daddiu    $a1, $v0, 0x1
  .L00280FA8:
    /* 81FA8 00280FA8 3C100600 */  dsll32     $v0, $a2, 0
    /* 81FAC 00280FAC 3F100200 */  dsra32     $v0, $v0, 0
    /* 81FB0 00280FB0 14284500 */  dsllv      $a1, $a1, $v0
  .L00280FB4:
    /* 81FB4 00280FB4 3C100500 */  dsll32     $v0, $a1, 0
    /* 81FB8 00280FB8 0800E003 */  jr         $ra
    /* 81FBC 00280FBC 3F100200 */   dsra32    $v0, $v0, 0
endlabel ftoi
