.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00271148, 0x100

glabel func_00271148
    /* 72148 00271148 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 7214C 0027114C 2000B2FF */  sd         $s2, 0x20($sp)
    /* 72150 00271150 1000B1FF */  sd         $s1, 0x10($sp)
    /* 72154 00271154 1E001224 */  addiu      $s2, $zero, 0x1E
    /* 72158 00271158 3000BFFF */  sd         $ra, 0x30($sp)
    /* 7215C 0027115C 03001124 */  addiu      $s1, $zero, 0x3
    /* 72160 00271160 3810080C */  jal        config_get_keyboard_repeatw
    /* 72164 00271164 0000B0FF */   sd        $s0, 0x0($sp)
    /* 72168 00271168 2D184000 */  daddu      $v1, $v0, $zero
    /* 7216C 0027116C 01000224 */  addiu      $v0, $zero, 0x1
    /* 72170 00271170 08006210 */  beq        $v1, $v0, .L00271194
    /* 72174 00271174 00000000 */   nop
    /* 72178 00271178 05006010 */  beqz       $v1, .L00271190
    /* 7217C 0027117C 02000224 */   addiu     $v0, $zero, 0x2
    /* 72180 00271180 04006250 */  beql       $v1, $v0, .L00271194
    /* 72184 00271184 2D001224 */   addiu     $s2, $zero, 0x2D
    /* 72188 00271188 02000010 */  b          .L00271194
    /* 7218C 0027118C 00000000 */   nop
  .L00271190:
    /* 72190 00271190 14001224 */  addiu      $s2, $zero, 0x14
  .L00271194:
    /* 72194 00271194 4010080C */  jal        config_get_keyboard_repeats
    /* 72198 00271198 00000000 */   nop
    /* 7219C 0027119C 2D184000 */  daddu      $v1, $v0, $zero
    /* 721A0 002711A0 01000224 */  addiu      $v0, $zero, 0x1
    /* 721A4 002711A4 0A006250 */  beql       $v1, $v0, .L002711D0
    /* 721A8 002711A8 03001124 */   addiu     $s1, $zero, 0x3
    /* 721AC 002711AC 05006010 */  beqz       $v1, .L002711C4
    /* 721B0 002711B0 02000224 */   addiu     $v0, $zero, 0x2
    /* 721B4 002711B4 05006210 */  beq        $v1, $v0, .L002711CC
    /* 721B8 002711B8 5000103C */   lui       $s0, (0x502294 >> 16)
    /* 721BC 002711BC 06000010 */  b          .L002711D8
    /* 721C0 002711C0 2D284002 */   daddu     $a1, $s2, $zero
  .L002711C4:
    /* 721C4 002711C4 02000010 */  b          .L002711D0
    /* 721C8 002711C8 02001124 */   addiu     $s1, $zero, 0x2
  .L002711CC:
    /* 721CC 002711CC 05001124 */  addiu      $s1, $zero, 0x5
  .L002711D0:
    /* 721D0 002711D0 5000103C */  lui        $s0, (0x502294 >> 16)
    /* 721D4 002711D4 2D284002 */  daddu      $a1, $s2, $zero
  .L002711D8:
    /* 721D8 002711D8 9422048E */  lw         $a0, (0x502294 & 0xFFFF)($s0)
    /* 721DC 002711DC 22E7090C */  jal        sceUsbKbSetRepeat
    /* 721E0 002711E0 2D302002 */   daddu     $a2, $s1, $zero
    /* 721E4 002711E4 9422048E */  lw         $a0, (0x502294 & 0xFFFF)($s0)
    /* 721E8 002711E8 34E7090C */  jal        sceUsbKbSetCodeType
    /* 721EC 002711EC 2D280000 */   daddu     $a1, $zero, $zero
    /* 721F0 002711F0 3010080C */  jal        config_get_keyboard_type
    /* 721F4 002711F4 00000000 */   nop
    /* 721F8 002711F8 2D184000 */  daddu      $v1, $v0, $zero
    /* 721FC 002711FC 0A006010 */  beqz       $v1, .L00271228
    /* 72200 00271200 01000224 */   addiu     $v0, $zero, 0x1
    /* 72204 00271204 09006214 */  bne        $v1, $v0, .L0027122C
    /* 72208 00271208 9422048E */   lw        $a0, (0x502294 & 0xFFFF)($s0)
    /* 7220C 0027120C 2D280000 */  daddu      $a1, $zero, $zero
    /* 72210 00271210 3000BFDF */  ld         $ra, 0x30($sp)
    /* 72214 00271214 2000B2DF */  ld         $s2, 0x20($sp)
    /* 72218 00271218 1000B1DF */  ld         $s1, 0x10($sp)
    /* 7221C 0027121C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 72220 00271220 48E70908 */  j          sceUsbKbSetArrangement
    /* 72224 00271224 4000BD27 */   addiu     $sp, $sp, 0x40
  .L00271228:
    /* 72228 00271228 9422048E */  lw         $a0, (0x502294 & 0xFFFF)($s0)
  .L0027122C:
    /* 7222C 0027122C 01000524 */  addiu      $a1, $zero, 0x1
    /* 72230 00271230 3000BFDF */  ld         $ra, 0x30($sp)
    /* 72234 00271234 2000B2DF */  ld         $s2, 0x20($sp)
    /* 72238 00271238 1000B1DF */  ld         $s1, 0x10($sp)
    /* 7223C 0027123C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 72240 00271240 48E70908 */  j          sceUsbKbSetArrangement
    /* 72244 00271244 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_00271148
