.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0022BE58, 0x74

glabel func_0022BE58
    /* 2CE58 0022BE58 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 2CE5C 0022BE5C 3000B3FF */  sd         $s3, 0x30($sp)
    /* 2CE60 0022BE60 2000B2FF */  sd         $s2, 0x20($sp)
    /* 2CE64 0022BE64 2D98A000 */  daddu      $s3, $a1, $zero
    /* 2CE68 0022BE68 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2CE6C 0022BE6C 2D90E000 */  daddu      $s2, $a3, $zero
    /* 2CE70 0022BE70 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2CE74 0022BE74 2D88C000 */  daddu      $s1, $a2, $zero
    /* 2CE78 0022BE78 4000BFFF */  sd         $ra, 0x40($sp)
    /* 2CE7C 0022BE7C 2B00103C */  lui        $s0, %hi(D_002B2560)
    /* 2CE80 0022BE80 60251026 */  addiu      $s0, $s0, %lo(D_002B2560)
    /* 2CE84 0022BE84 0800828C */  lw         $v0, 0x8($a0)
    /* 2CE88 0022BE88 1000838C */  lw         $v1, 0x10($a0)
    /* 2CE8C 0022BE8C 40110200 */  sll        $v0, $v0, 5
    /* 2CE90 0022BE90 21104300 */  addu       $v0, $v0, $v1
    /* 2CE94 0022BE94 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2CE98 0022BE98 0400448C */   lw        $a0, 0x4($v0)
    /* 2CE9C 0022BE9C 2D206002 */  daddu      $a0, $s3, $zero
    /* 2CEA0 0022BEA0 2D282002 */  daddu      $a1, $s1, $zero
    /* 2CEA4 0022BEA4 2D300002 */  daddu      $a2, $s0, $zero
    /* 2CEA8 0022BEA8 2D384002 */  daddu      $a3, $s2, $zero
    /* 2CEAC 0022BEAC 4000BFDF */  ld         $ra, 0x40($sp)
    /* 2CEB0 0022BEB0 2D404000 */  daddu      $t0, $v0, $zero
    /* 2CEB4 0022BEB4 3000B3DF */  ld         $s3, 0x30($sp)
    /* 2CEB8 0022BEB8 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2CEBC 0022BEBC 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2CEC0 0022BEC0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2CEC4 0022BEC4 009B0808 */  j          draw_menu_item
    /* 2CEC8 0022BEC8 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_0022BE58
