.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00264538, 0x44

glabel func_00264538
    /* 65538 00264538 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 6553C 0026453C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 65540 00264540 9E8E090C */  jal        func_00263A78
    /* 65544 00264544 00000000 */   nop
    /* 65548 00264548 09004014 */  bnez       $v0, .L00264570
    /* 6554C 0026454C 01000224 */   addiu     $v0, $zero, 0x1
    /* 65550 00264550 3100043C */  lui        $a0, %hi(D_00310CEC)
    /* 65554 00264554 EC0C838C */  lw         $v1, %lo(D_00310CEC)($a0)
    /* 65558 00264558 04006018 */  blez       $v1, .L0026456C
    /* 6555C 0026455C FFFF6324 */   addiu     $v1, $v1, -0x1
    /* 65560 00264560 01000224 */  addiu      $v0, $zero, 0x1
    /* 65564 00264564 02000010 */  b          .L00264570
    /* 65568 00264568 EC0C83AC */   sw        $v1, %lo(D_00310CEC)($a0)
  .L0026456C:
    /* 6556C 0026456C 2D100000 */  daddu      $v0, $zero, $zero
  .L00264570:
    /* 65570 00264570 0000BFDF */  ld         $ra, 0x0($sp)
    /* 65574 00264574 0800E003 */  jr         $ra
    /* 65578 00264578 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_00264538
