.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002328D8, 0x60

glabel func_002328D8
    /* 338D8 002328D8 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 338DC 002328DC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 338E0 002328E0 2D80A000 */  daddu      $s0, $a1, $zero
    /* 338E4 002328E4 2000B4E7 */  swc1       $f20, 0x20($sp)
    /* 338E8 002328E8 2D288000 */  daddu      $a1, $a0, $zero
    /* 338EC 002328EC 1000BFFF */  sd         $ra, 0x10($sp)
    /* 338F0 002328F0 86EB090C */  jal        sceVu0ApplyMatrix
    /* 338F4 002328F4 2D200002 */   daddu     $a0, $s0, $zero
    /* 338F8 002328F8 0C0000C6 */  lwc1       $f0, 0xC($s0)
    /* 338FC 002328FC 2D200002 */  daddu      $a0, $s0, $zero
    /* 33900 00232900 803F013C */  lui        $at, (0x3F800000 >> 16)
    /* 33904 00232904 00A08144 */  mtc1       $at, $f20
    /* 33908 00232908 2D288000 */  daddu      $a1, $a0, $zero
    /* 3390C 0023290C 00000000 */  nop
    /* 33910 00232910 00000000 */  nop
    /* 33914 00232914 03A50046 */  div.s      $f20, $f20, $f0
    /* 33918 00232918 20EC090C */  jal        sceVu0ScaleVector
    /* 3391C 0023291C 06A30046 */   mov.s     $f12, $f20
    /* 33920 00232920 06A00046 */  mov.s      $f0, $f20
    /* 33924 00232924 1000BFDF */  ld         $ra, 0x10($sp)
    /* 33928 00232928 0000B0DF */  ld         $s0, 0x0($sp)
    /* 3392C 0023292C 2000B4C7 */  lwc1       $f20, 0x20($sp)
    /* 33930 00232930 0800E003 */  jr         $ra
    /* 33934 00232934 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_002328D8
