.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00232878, 0x10

glabel func_00232878
    /* 33878 00232878 6489828F */  lw         $v0, %gp_rel(D_003702D4)($gp)
    /* 3387C 0023287C 01004224 */  addiu      $v0, $v0, 0x1
    /* 33880 00232880 0800E003 */  jr         $ra
    /* 33884 00232884 648982AF */   sw        $v0, %gp_rel(D_003702D4)($gp)
endlabel func_00232878
