.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00271C38, 0x18

glabel func_00271C38
    /* 72C38 00271C38 2D108000 */  daddu      $v0, $a0, $zero
    /* 72C3C 00271C3C 3800478C */  lw         $a3, 0x38($v0)
    /* 72C40 00271C40 40004424 */  addiu      $a0, $v0, 0x40
    /* 72C44 00271C44 3C00458C */  lw         $a1, 0x3C($v0)
    /* 72C48 00271C48 E0990908 */  j          func_00266780
    /* 72C4C 00271C4C 3400468C */   lw        $a2, 0x34($v0)
endlabel func_00271C38
