.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0022BAE0, 0x40

glabel func_0022BAE0
    /* 2CAE0 0022BAE0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 2CAE4 0022BAE4 6088838F */  lw         $v1, %gp_rel(D_003701D0)($gp)
    /* 2CAE8 0022BAE8 0000BFFF */  sd         $ra, 0x0($sp)
    /* 2CAEC 0022BAEC 38000524 */  addiu      $a1, $zero, 0x38
    /* 2CAF0 0022BAF0 1000628C */  lw         $v0, 0x10($v1)
    /* 2CAF4 0022BAF4 0400648C */  lw         $a0, 0x4($v1)
    /* 2CAF8 0022BAF8 18104500 */  mult       $v0, $v0, $a1
    /* 2CAFC 0022BAFC 21208200 */  addu       $a0, $a0, $v0
    /* 2CB00 0022BB00 3000828C */  lw         $v0, 0x30($a0)
    /* 2CB04 0022BB04 04004010 */  beqz       $v0, .L0022BB18
    /* 2CB08 0022BB08 0000BFDF */   ld        $ra, 0x0($sp)
    /* 2CB0C 0022BB0C 09F84000 */  jalr       $v0
    /* 2CB10 0022BB10 2091858F */   lw        $a1, %gp_rel(D_00370A90)($gp)
    /* 2CB14 0022BB14 0000BFDF */  ld         $ra, 0x0($sp)
  .L0022BB18:
    /* 2CB18 0022BB18 0800E003 */  jr         $ra
    /* 2CB1C 0022BB1C 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_0022BAE0
