.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00269F48, 0x80

glabel func_00269F48
    /* 6AF48 00269F48 4F00023C */  lui        $v0, %hi(D_004E8070)
    /* 6AF4C 00269F4C C0200400 */  sll        $a0, $a0, 3
    /* 6AF50 00269F50 70804724 */  addiu      $a3, $v0, %lo(D_004E8070)
    /* 6AF54 00269F54 0080053C */  lui        $a1, (0x80000006 >> 16)
    /* 6AF58 00269F58 4400E38C */  lw         $v1, 0x44($a3)
    /* 6AF5C 00269F5C 0600A534 */  ori        $a1, $a1, (0x80000006 & 0xFFFF)
    /* 6AF60 00269F60 21208300 */  addu       $a0, $a0, $v1
    /* 6AF64 00269F64 0400828C */  lw         $v0, 0x4($a0)
    /* 6AF68 00269F68 0000438C */  lw         $v1, 0x0($v0)
    /* 6AF6C 00269F6C 09006510 */  beq        $v1, $a1, .L00269F94
    /* 6AF70 00269F70 2B10A300 */   sltu      $v0, $a1, $v1
    /* 6AF74 00269F74 12004010 */  beqz       $v0, .L00269FC0
    /* 6AF78 00269F78 00000000 */   nop
    /* 6AF7C 00269F7C 0080023C */  lui        $v0, (0x80000007 >> 16)
    /* 6AF80 00269F80 07004234 */  ori        $v0, $v0, (0x80000007 & 0xFFFF)
    /* 6AF84 00269F84 09006210 */  beq        $v1, $v0, .L00269FAC
    /* 6AF88 00269F88 2D20E000 */   daddu     $a0, $a3, $zero
    /* 6AF8C 00269F8C 0800E003 */  jr         $ra
    /* 6AF90 00269F90 00000000 */   nop
  .L00269F94:
    /* 6AF94 00269F94 0080053C */  lui        $a1, (0x80000006 >> 16)
    /* 6AF98 00269F98 FFFF063C */  lui        $a2, (0xFFFFFFFD >> 16)
    /* 6AF9C 00269F9C 2D20E000 */  daddu      $a0, $a3, $zero
    /* 6AFA0 00269FA0 0600A534 */  ori        $a1, $a1, (0x80000006 & 0xFFFF)
    /* 6AFA4 00269FA4 18CF0908 */  j          func_00273C60
    /* 6AFA8 00269FA8 FDFFC634 */   ori       $a2, $a2, (0xFFFFFFFD & 0xFFFF)
  .L00269FAC:
    /* 6AFAC 00269FAC 0080053C */  lui        $a1, (0x80000007 >> 16)
    /* 6AFB0 00269FB0 FFFF063C */  lui        $a2, (0xFFFFFFFD >> 16)
    /* 6AFB4 00269FB4 0700A534 */  ori        $a1, $a1, (0x80000007 & 0xFFFF)
    /* 6AFB8 00269FB8 18CF0908 */  j          func_00273C60
    /* 6AFBC 00269FBC FDFFC634 */   ori       $a2, $a2, (0xFFFFFFFD & 0xFFFF)
  .L00269FC0:
    /* 6AFC0 00269FC0 0800E003 */  jr         $ra
    /* 6AFC4 00269FC4 00000000 */   nop
endlabel func_00269F48
