.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00236230, 0x94

glabel func_00236230
    /* 37230 00236230 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 37234 00236234 1F00063C */  lui        $a2, (0x1F0CB8 >> 16)
    /* 37238 00236238 1000B1FF */  sd         $s1, 0x10($sp)
    /* 3723C 0023623C 0020033C */  lui        $v1, (0x20000034 >> 16)
    /* 37240 00236240 0000B0FF */  sd         $s0, 0x0($sp)
    /* 37244 00236244 2D888000 */  daddu      $s1, $a0, $zero
    /* 37248 00236248 2000BFFF */  sd         $ra, 0x20($sp)
    /* 3724C 0023624C 2B00103C */  lui        $s0, %hi(D_002B6060)
    /* 37250 00236250 60601026 */  addiu      $s0, $s0, %lo(D_002B6060)
    /* 37254 00236254 01000424 */  addiu      $a0, $zero, 0x1
    /* 37258 00236258 B40CC28C */  lw         $v0, (0x1F0CB4 & 0xFFFF)($a2)
    /* 3725C 0023625C 25800302 */  or         $s0, $s0, $v1
    /* 37260 00236260 01000524 */  addiu      $a1, $zero, 0x1
    /* 37264 00236264 00110200 */  sll        $v0, $v0, 4
    /* 37268 00236268 200002AE */  sw         $v0, (0x20000020 & 0xFFFF)($s0)
    /* 3726C 0023626C B80CC28C */  lw         $v0, (0x1F0CB8 & 0xFFFF)($a2)
    /* 37270 00236270 00110200 */  sll        $v0, $v0, 4
    /* 37274 00236274 240002AE */  sw         $v0, (0x20000024 & 0xFFFF)($s0)
    /* 37278 00236278 B40CC38C */  lw         $v1, (0x1F0CB4 & 0xFFFF)($a2)
    /* 3727C 0023627C 00190300 */  sll        $v1, $v1, 4
    /* 37280 00236280 08006324 */  addiu      $v1, $v1, 0x8
    /* 37284 00236284 280003AE */  sw         $v1, (0x20000028 & 0xFFFF)($s0)
    /* 37288 00236288 B80CC28C */  lw         $v0, (0x1F0CB8 & 0xFFFF)($a2)
    /* 3728C 0023628C 00110200 */  sll        $v0, $v0, 4
    /* 37290 00236290 08004224 */  addiu      $v0, $v0, 0x8
    /* 37294 00236294 9CCF080C */  jal        func_00233E70
    /* 37298 00236298 2C0002AE */   sw        $v0, (0x2000002C & 0xFFFF)($s0)
    /* 3729C 0023629C 340011AE */  sw         $s1, (0x20000034 & 0xFFFF)($s0)
    /* 372A0 002362A0 DCCD080C */  jal        func_00233770
    /* 372A4 002362A4 2D200002 */   daddu     $a0, $s0, $zero
    /* 372A8 002362A8 2000BFDF */  ld         $ra, 0x20($sp)
    /* 372AC 002362AC 2D200000 */  daddu      $a0, $zero, $zero
    /* 372B0 002362B0 1000B1DF */  ld         $s1, 0x10($sp)
    /* 372B4 002362B4 2D280000 */  daddu      $a1, $zero, $zero
    /* 372B8 002362B8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 372BC 002362BC EA240A08 */  j          sceGsSyncPath
    /* 372C0 002362C0 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00236230
