.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0022E9C8, 0x104

glabel func_0022E9C8
    /* 2F9C8 0022E9C8 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 2F9CC 0022E9CC 2000B2FF */  sd         $s2, 0x20($sp)
    /* 2F9D0 0022E9D0 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2F9D4 0022E9D4 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2F9D8 0022E9D8 0C001124 */  addiu      $s1, $zero, 0xC
    /* 2F9DC 0022E9DC 4800B5E7 */  swc1       $f21, 0x48($sp)
    /* 2F9E0 0022E9E0 4000103C */  lui        $s0, (0x404F70 >> 16)
    /* 2F9E4 0022E9E4 4000B4E7 */  swc1       $f20, 0x40($sp)
    /* 2F9E8 0022E9E8 3000BFFF */  sd         $ra, 0x30($sp)
    /* 2F9EC 0022E9EC CCD5080C */  jal        func_00235730
    /* 2F9F0 0022E9F0 704F1226 */   addiu     $s2, $s0, %lo(D_00404F70)
    /* 2F9F4 0022E9F4 8047013C */  lui        $at, (0x47800000 >> 16)
    /* 2F9F8 0022E9F8 00A08144 */  mtc1       $at, $f20
    /* 2F9FC 0022E9FC 64000046 */  .word      0x46000064                    # cvt.w.s    $f1, $f0 # 00000000 <InstrIdType: CPU_COP1_FPUS>
    /* 2FA00 0022EA00 00080344 */  mfc1       $v1, $f1
    /* 2FA04 0022EA04 01002052 */  beql       $s1, $zero, .L0022EA0C
    /* 2FA08 0022EA08 CD010000 */   break     0, 7
  .L0022EA0C:
    /* 2FA0C 0022EA0C 7042013C */  lui        $at, (0x42700000 >> 16)
    /* 2FA10 0022EA10 00A88144 */  mtc1       $at, $f21
    /* 2FA14 0022EA14 1A007100 */  div        $zero, $v1, $s1
    /* 2FA18 0022EA18 10100000 */  mfhi       $v0
    /* 2FA1C 0022EA1C CCD5080C */  jal        func_00235730
    /* 2FA20 0022EA20 704F02AE */   sw        $v0, (0x404F70 & 0xFFFF)($s0)
    /* 2FA24 0022EA24 02001446 */  mul.s      $f0, $f0, $f20
    /* 2FA28 0022EA28 4041013C */  lui        $at, (0x41400000 >> 16)
    /* 2FA2C 0022EA2C 00088144 */  mtc1       $at, $f1
    /* 2FA30 0022EA30 00000000 */  nop
    /* 2FA34 0022EA34 00000000 */  nop
    /* 2FA38 0022EA38 03000146 */  div.s      $f0, $f0, $f1
    /* 2FA3C 0022EA3C 64000046 */  .word      0x46000064                    # cvt.w.s    $f1, $f0 # 00000000 <InstrIdType: CPU_COP1_FPUS>
    /* 2FA40 0022EA40 00080244 */  mfc1       $v0, $f1
    /* 2FA44 0022EA44 2A9182A7 */  sh         $v0, %gp_rel(D_00370A9A)($gp)
    /* 2FA48 0022EA48 68D5080C */  jal        func_002355A0
    /* 2FA4C 0022EA4C 00000000 */   nop
    /* 2FA50 0022EA50 704F038E */  lw         $v1, (0x404F70 & 0xFFFF)($s0)
    /* 2FA54 0022EA54 02001446 */  mul.s      $f0, $f0, $f20
    /* 2FA58 0022EA58 0C000424 */  addiu      $a0, $zero, 0xC
    /* 2FA5C 0022EA5C 001C0300 */  sll        $v1, $v1, 16
    /* 2FA60 0022EA60 1B007100 */  divu       $zero, $v1, $s1
    /* 2FA64 0022EA64 00000000 */  nop
    /* 2FA68 0022EA68 00000000 */  nop
    /* 2FA6C 0022EA6C 03001546 */  div.s      $f0, $f0, $f21
    /* 2FA70 0022EA70 64000046 */  .word      0x46000064                    # cvt.w.s    $f1, $f0 # 00000000 <InstrIdType: CPU_COP1_FPUS>
    /* 2FA74 0022EA74 00080244 */  mfc1       $v0, $f1
    /* 2FA78 0022EA78 289182A7 */  sh         $v0, %gp_rel(D_00370A98)($gp)
    /* 2FA7C 0022EA7C 01008050 */  beql       $a0, $zero, .L0022EA84
    /* 2FA80 0022EA80 CD010000 */   break     0, 7
  .L0022EA84:
    /* 2FA84 0022EA84 12180000 */  mflo       $v1
    /* 2FA88 0022EA88 68D5080C */  jal        func_002355A0
    /* 2FA8C 0022EA8C 060043A6 */   sh        $v1, 0x6($s2)
    /* 2FA90 0022EA90 02001446 */  mul.s      $f0, $f0, $f20
    /* 2FA94 0022EA94 3000BFDF */  ld         $ra, 0x30($sp)
    /* 2FA98 0022EA98 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2FA9C 0022EA9C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2FAA0 0022EAA0 00000000 */  nop
    /* 2FAA4 0022EAA4 00000000 */  nop
    /* 2FAA8 0022EAA8 03001546 */  div.s      $f0, $f0, $f21
    /* 2FAAC 0022EAAC 4000B4C7 */  lwc1       $f20, 0x40($sp)
    /* 2FAB0 0022EAB0 4800B5C7 */  lwc1       $f21, 0x48($sp)
    /* 2FAB4 0022EAB4 64000046 */  .word      0x46000064                    # cvt.w.s    $f1, $f0 # 00000000 <InstrIdType: CPU_COP1_FPUS>
    /* 2FAB8 0022EAB8 00080244 */  mfc1       $v0, $f1
    /* 2FABC 0022EABC 040042A6 */  sh         $v0, 0x4($s2)
    /* 2FAC0 0022EAC0 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2FAC4 0022EAC4 0800E003 */  jr         $ra
    /* 2FAC8 0022EAC8 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_0022E9C8
