.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002738F8, 0x10

glabel func_002738F8
    /* 748F8 002738F8 72008290 */  lbu        $v0, 0x72($a0)
    /* 748FC 002738FC FD004230 */  andi       $v0, $v0, 0xFD
    /* 74900 00273900 0800E003 */  jr         $ra
    /* 74904 00273904 720082A0 */   sb        $v0, 0x72($a0)
endlabel func_002738F8
