.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0022D5A0, 0x34

glabel func_0022D5A0
    /* 2E5A0 0022D5A0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 2E5A4 0022D5A4 2B00043C */  lui        $a0, %hi(D_002B46B8)
    /* 2E5A8 0022D5A8 0000BFFF */  sd         $ra, 0x0($sp)
    /* 2E5AC 0022D5AC B8D2080C */  jal        func_00234AE0
    /* 2E5B0 0022D5B0 B8468424 */   addiu     $a0, $a0, %lo(D_002B46B8)
    /* 2E5B4 0022D5B4 D2C3080C */  jal        func_00230F48
    /* 2E5B8 0022D5B8 00000000 */   nop
    /* 2E5BC 0022D5BC 0000BFDF */  ld         $ra, 0x0($sp)
    /* 2E5C0 0022D5C0 00630424 */  addiu      $a0, $zero, 0x6300
    /* 2E5C4 0022D5C4 01000524 */  addiu      $a1, $zero, 0x1
    /* 2E5C8 0022D5C8 0A000624 */  addiu      $a2, $zero, 0xA
    /* 2E5CC 0022D5CC AEB50808 */  j          j_sound_handler_queue_cmd_0
    /* 2E5D0 0022D5D0 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_0022D5A0
