.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002685A0, 0x30

glabel func_002685A0
    /* 695A0 002685A0 3100033C */  lui        $v1, %hi(D_00310EC8)
    /* 695A4 002685A4 C80E6824 */  addiu      $t0, $v1, %lo(D_00310EC8)
    /* 695A8 002685A8 07000569 */  ldl        $a1, 0x7($t0)
    /* 695AC 002685AC 0000056D */  ldr        $a1, 0x0($t0)
    /* 695B0 002685B0 0F000669 */  ldl        $a2, 0xF($t0)
    /* 695B4 002685B4 0800066D */  ldr        $a2, 0x8($t0)
    /* 695B8 002685B8 070085B0 */  sdl        $a1, 0x7($a0)
    /* 695BC 002685BC 000085B4 */  sdr        $a1, 0x0($a0)
    /* 695C0 002685C0 0F0086B0 */  sdl        $a2, 0xF($a0)
    /* 695C4 002685C4 080086B4 */  sdr        $a2, 0x8($a0)
    /* 695C8 002685C8 0800E003 */  jr         $ra
    /* 695CC 002685CC 2D108000 */   daddu     $v0, $a0, $zero
endlabel func_002685A0
