.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00268AC8, 0x3B8

glabel func_00268AC8
    /* 69AC8 00268AC8 40FFBD27 */  addiu      $sp, $sp, -0xC0
    /* 69ACC 00268ACC 4F00023C */  lui        $v0, (0x4F0000 >> 16)
    /* 69AD0 00268AD0 3000B1FF */  sd         $s1, 0x30($sp)
    /* 69AD4 00268AD4 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 69AD8 00268AD8 C080458C */  lw         $a1, -0x7F40($v0)
    /* 69ADC 00268ADC 3100113C */  lui        $s1, %hi(D_00311028)
    /* 69AE0 00268AE0 2810228E */  lw         $v0, %lo(D_00311028)($s1)
    /* 69AE4 00268AE4 2000B0FF */  sd         $s0, 0x20($sp)
    /* 69AE8 00268AE8 B000BFFF */  sd         $ra, 0xB0($sp)
    /* 69AEC 00268AEC 2380A200 */  subu       $s0, $a1, $v0
    /* 69AF0 00268AF0 A000BEFF */  sd         $fp, 0xA0($sp)
    /* 69AF4 00268AF4 9000B7FF */  sd         $s7, 0x90($sp)
    /* 69AF8 00268AF8 8000B6FF */  sd         $s6, 0x80($sp)
    /* 69AFC 00268AFC 7000B5FF */  sd         $s5, 0x70($sp)
    /* 69B00 00268B00 6000B4FF */  sd         $s4, 0x60($sp)
    /* 69B04 00268B04 5000B3FF */  sd         $s3, 0x50($sp)
    /* 69B08 00268B08 4000B2FF */  sd         $s2, 0x40($sp)
    /* 69B0C 00268B0C 07004314 */  bne        $v0, $v1, .L00268B2C
    /* 69B10 00268B10 1000A4AF */   sw        $a0, 0x10($sp)
    /* 69B14 00268B14 281025AE */  sw         $a1, %lo(D_00311028)($s1)
    /* 69B18 00268B18 2D20A000 */  daddu      $a0, $a1, $zero
    /* 69B1C 00268B1C F4A1090C */  jal        func_002687D0
    /* 69B20 00268B20 08000524 */   addiu     $a1, $zero, 0x8
    /* 69B24 00268B24 18000010 */  b          .L00268B88
    /* 69B28 00268B28 3100063C */   lui       $a2, %hi(D_00310EC8)
  .L00268B2C:
    /* 69B2C 00268B2C 0C00001A */  blez       $s0, .L00268B60
    /* 69B30 00268B30 00000000 */   nop
    /* 69B34 00268B34 38A2090C */  jal        func_002688E0
    /* 69B38 00268B38 2D200002 */   daddu     $a0, $s0, $zero
    /* 69B3C 00268B3C 4F00033C */  lui        $v1, (0x4F0000 >> 16)
    /* 69B40 00268B40 F8FF0426 */  addiu      $a0, $s0, -0x8
    /* 69B44 00268B44 C080628C */  lw         $v0, -0x7F40($v1)
    /* 69B48 00268B48 2D280002 */  daddu      $a1, $s0, $zero
    /* 69B4C 00268B4C 23204400 */  subu       $a0, $v0, $a0
    /* 69B50 00268B50 F4A1090C */  jal        func_002687D0
    /* 69B54 00268B54 281022AE */   sw        $v0, %lo(D_00311028)($s1)
    /* 69B58 00268B58 0B000010 */  b          .L00268B88
    /* 69B5C 00268B5C 3100063C */   lui       $a2, %hi(D_00310EC8)
  .L00268B60:
    /* 69B60 00268B60 09000306 */  bgezl      $s0, .L00268B88
    /* 69B64 00268B64 3100063C */   lui       $a2, %hi(D_00310EC8)
    /* 69B68 00268B68 38A2090C */  jal        func_002688E0
    /* 69B6C 00268B6C 2D200002 */   daddu     $a0, $s0, $zero
    /* 69B70 00268B70 4F00053C */  lui        $a1, (0x4F0000 >> 16)
    /* 69B74 00268B74 C080A48C */  lw         $a0, -0x7F40($a1)
    /* 69B78 00268B78 23281000 */  negu       $a1, $s0
    /* 69B7C 00268B7C F4A1090C */  jal        func_002687D0
    /* 69B80 00268B80 281024AE */   sw        $a0, %lo(D_00311028)($s1)
    /* 69B84 00268B84 3100063C */  lui        $a2, %hi(D_00310EC8)
  .L00268B88:
    /* 69B88 00268B88 4C3F013C */  lui        $at, (0x3F4CCCCD >> 16)
    /* 69B8C 00268B8C CDCC2134 */  ori        $at, $at, (0x3F4CCCCD & 0xFFFF)
    /* 69B90 00268B90 00608144 */  mtc1       $at, $f12
    /* 69B94 00268B94 C80EDE24 */  addiu      $fp, $a2, %lo(D_00310EC8)
    /* 69B98 00268B98 EE49080C */  jal        Font_SetRatio
    /* 69B9C 00268B9C 2DB00000 */   daddu     $s6, $zero, $zero
    /* 69BA0 00268BA0 16001724 */  addiu      $s7, $zero, 0x16
    /* 69BA4 00268BA4 DE49080C */  jal        Font_SetPitch
    /* 69BA8 00268BA8 2D200000 */   daddu     $a0, $zero, $zero
    /* 69BAC 00268BAC F449080C */  jal        Font_SetRetHeight
    /* 69BB0 00268BB0 2D200000 */   daddu     $a0, $zero, $zero
    /* 69BB4 00268BB4 EA49080C */  jal        Font_SetProp
    /* 69BB8 00268BB8 2D200000 */   daddu     $a0, $zero, $zero
    /* 69BBC 00268BBC 803F013C */  lui        $at, (0x3F800000 >> 16)
    /* 69BC0 00268BC0 00608144 */  mtc1       $at, $f12
    /* 69BC4 00268BC4 F849080C */  jal        Font_SetTvFontRatio
    /* 69BC8 00268BC8 00000000 */   nop
    /* 69BCC 00268BCC 1000A78F */  lw         $a3, 0x10($sp)
    /* 69BD0 00268BD0 3C000424 */  addiu      $a0, $zero, 0x3C
    /* 69BD4 00268BD4 3C000524 */  addiu      $a1, $zero, 0x3C
    /* 69BD8 00268BD8 1C4A080C */  jal        Font_SetColor
    /* 69BDC 00268BDC 3C000624 */   addiu     $a2, $zero, 0x3C
    /* 69BE0 00268BE0 1838D702 */  mult       $a3, $s6, $s7
    /* 69BE4 00268BE4 00000000 */  nop
  .L00268BE8:
    /* 69BE8 00268BE8 4F00033C */  lui        $v1, %hi(D_004E8A78)
    /* 69BEC 00268BEC 0100C426 */  addiu      $a0, $s6, 0x1
    /* 69BF0 00268BF0 C0111600 */  sll        $v0, $s6, 7
    /* 69BF4 00268BF4 788A6324 */  addiu      $v1, $v1, %lo(D_004E8A78)
    /* 69BF8 00268BF8 1800A4AF */  sw         $a0, 0x18($sp)
    /* 69BFC 00268BFC 21904300 */  addu       $s2, $v0, $v1
    /* 69C00 00268C00 2DA00000 */  daddu      $s4, $zero, $zero
    /* 69C04 00268C04 1400A7AF */  sw         $a3, 0x14($sp)
    /* 69C08 00268C08 2DA80000 */  daddu      $s5, $zero, $zero
    /* 69C0C 00268C0C 00000000 */  nop
  .L00268C10:
    /* 69C10 00268C10 3100053C */  lui        $a1, %hi(D_00310EE0)
    /* 69C14 00268C14 1400A78F */  lw         $a3, 0x14($sp)
    /* 69C18 00268C18 E00EA28C */  lw         $v0, %lo(D_00310EE0)($a1)
    /* 69C1C 00268C1C 3100063C */  lui        $a2, %hi(D_00310EDC)
    /* 69C20 00268C20 4F00053C */  lui        $a1, (0x4F0000 >> 16)
    /* 69C24 00268C24 DC0EC38C */  lw         $v1, %lo(D_00310EDC)($a2)
    /* 69C28 00268C28 2110E200 */  addu       $v0, $a3, $v0
    /* 69C2C 00268C2C C080A48C */  lw         $a0, -0x7F40($a1)
    /* 69C30 00268C30 07005124 */  addiu      $s1, $v0, 0x7
    /* 69C34 00268C34 2118A302 */  addu       $v1, $s5, $v1
    /* 69C38 00268C38 C2171100 */  srl        $v0, $s1, 31
    /* 69C3C 00268C3C 4F00063C */  lui        $a2, (0x4F0000 >> 16)
    /* 69C40 00268C40 21102202 */  addu       $v0, $s1, $v0
    /* 69C44 00268C44 2128C402 */  addu       $a1, $s6, $a0
    /* 69C48 00268C48 0A007324 */  addiu      $s3, $v1, 0xA
    /* 69C4C 00268C4C C480C48C */  lw         $a0, -0x7F3C($a2)
    /* 69C50 00268C50 43880200 */  sra        $s1, $v0, 1
    /* 69C54 00268C54 0300478A */  lwl        $a3, 0x3($s2)
    /* 69C58 00268C58 0000479A */  lwr        $a3, 0x0($s2)
    /* 69C5C 00268C5C 0300A7AB */  swl        $a3, 0x3($sp)
    /* 69C60 00268C60 1A008416 */  bne        $s4, $a0, .L00268CCC
    /* 69C64 00268C64 0000A7BB */   swr       $a3, 0x0($sp)
    /* 69C68 00268C68 4F00073C */  lui        $a3, (0x4F0000 >> 16)
    /* 69C6C 00268C6C C880E28C */  lw         $v0, -0x7F38($a3)
    /* 69C70 00268C70 1700A214 */  bne        $a1, $v0, .L00268CD0
    /* 69C74 00268C74 0400508E */   lw        $s0, 0x4($s2)
    /* 69C78 00268C78 50000424 */  addiu      $a0, $zero, 0x50
    /* 69C7C 00268C7C 1000A78F */  lw         $a3, 0x10($sp)
    /* 69C80 00268C80 50000524 */  addiu      $a1, $zero, 0x50
    /* 69C84 00268C84 2380F002 */  subu       $s0, $s7, $s0
    /* 69C88 00268C88 C8000624 */  addiu      $a2, $zero, 0xC8
    /* 69C8C 00268C8C 1C4A080C */  jal        Font_SetColor
    /* 69C90 00268C90 43801000 */   sra       $s0, $s0, 1
    /* 69C94 00268C94 21207002 */  addu       $a0, $s3, $s0
    /* 69C98 00268C98 A449080C */  jal        Font_SetLocate
    /* 69C9C 00268C9C 02002526 */   addiu     $a1, $s1, 0x2
    /* 69CA0 00268CA0 904F080C */  jal        j_Font_PutsPackets
    /* 69CA4 00268CA4 2D20A003 */   daddu     $a0, $sp, $zero
    /* 69CA8 00268CA8 3100043C */  lui        $a0, %hi(D_00310EC8)
    /* 69CAC 00268CAC 01002226 */  addiu      $v0, $s1, 0x1
    /* 69CB0 00268CB0 C80E93AC */  sw         $s3, %lo(D_00310EC8)($a0)
    /* 69CB4 00268CB4 0B000324 */  addiu      $v1, $zero, 0xB
    /* 69CB8 00268CB8 0400C2AF */  sw         $v0, 0x4($fp)
    /* 69CBC 00268CBC 0E00C3A7 */  sh         $v1, 0xE($fp)
    /* 69CC0 00268CC0 0800C0AF */  sw         $zero, 0x8($fp)
    /* 69CC4 00268CC4 0E000010 */  b          .L00268D00
    /* 69CC8 00268CC8 0C00D7A7 */   sh        $s7, 0xC($fp)
  .L00268CCC:
    /* 69CCC 00268CCC 0400508E */  lw         $s0, 0x4($s2)
  .L00268CD0:
    /* 69CD0 00268CD0 3C000424 */  addiu      $a0, $zero, 0x3C
    /* 69CD4 00268CD4 1000A78F */  lw         $a3, 0x10($sp)
    /* 69CD8 00268CD8 3C000524 */  addiu      $a1, $zero, 0x3C
    /* 69CDC 00268CDC 2380F002 */  subu       $s0, $s7, $s0
    /* 69CE0 00268CE0 3C000624 */  addiu      $a2, $zero, 0x3C
    /* 69CE4 00268CE4 1C4A080C */  jal        Font_SetColor
    /* 69CE8 00268CE8 43801000 */   sra       $s0, $s0, 1
    /* 69CEC 00268CEC 21207002 */  addu       $a0, $s3, $s0
    /* 69CF0 00268CF0 A449080C */  jal        Font_SetLocate
    /* 69CF4 00268CF4 02002526 */   addiu     $a1, $s1, 0x2
    /* 69CF8 00268CF8 904F080C */  jal        j_Font_PutsPackets
    /* 69CFC 00268CFC 2D20A003 */   daddu     $a0, $sp, $zero
  .L00268D00:
    /* 69D00 00268D00 01009426 */  addiu      $s4, $s4, 0x1
    /* 69D04 00268D04 08005226 */  addiu      $s2, $s2, 0x8
    /* 69D08 00268D08 1000822A */  slti       $v0, $s4, 0x10
    /* 69D0C 00268D0C C0FF4014 */  bnez       $v0, .L00268C10
    /* 69D10 00268D10 1600B526 */   addiu     $s5, $s5, 0x16
    /* 69D14 00268D14 1800B68F */  lw         $s6, 0x18($sp)
    /* 69D18 00268D18 0800C22A */  slti       $v0, $s6, 0x8
    /* 69D1C 00268D1C B2FF4014 */  bnez       $v0, .L00268BE8
    /* 69D20 00268D20 1838D702 */   mult      $a3, $s6, $s7
    /* 69D24 00268D24 4F00053C */  lui        $a1, (0x4F0000 >> 16)
    /* 69D28 00268D28 10000224 */  addiu      $v0, $zero, 0x10
    /* 69D2C 00268D2C C480A38C */  lw         $v1, -0x7F3C($a1)
    /* 69D30 00268D30 21006214 */  bne        $v1, $v0, .L00268DB8
    /* 69D34 00268D34 11000224 */   addiu     $v0, $zero, 0x11
    /* 69D38 00268D38 4F00033C */  lui        $v1, (0x4F0000 >> 16)
    /* 69D3C 00268D3C 4F00063C */  lui        $a2, (0x4F0000 >> 16)
    /* 69D40 00268D40 C080C58C */  lw         $a1, -0x7F40($a2)
    /* 69D44 00268D44 4F00073C */  lui        $a3, %hi(D_004E8070)
    /* 69D48 00268D48 C880628C */  lw         $v0, -0x7F38($v1)
    /* 69D4C 00268D4C 7080E424 */  addiu      $a0, $a3, %lo(D_004E8070)
    /* 69D50 00268D50 02000624 */  addiu      $a2, $zero, 0x2
    /* 69D54 00268D54 4400878C */  lw         $a3, 0x44($a0)
    /* 69D58 00268D58 23104500 */  subu       $v0, $v0, $a1
    /* 69D5C 00268D5C 3400888C */  lw         $t0, 0x34($a0)
    /* 69D60 00268D60 03004328 */  slti       $v1, $v0, 0x3
    /* 69D64 00268D64 180080AC */  sw         $zero, 0x18($a0)
    /* 69D68 00268D68 0A10C300 */  movz       $v0, $a2, $v1
    /* 69D6C 00268D6C 3100053C */  lui        $a1, %hi(D_00310EC8)
    /* 69D70 00268D70 C0180200 */  sll        $v1, $v0, 3
    /* 69D74 00268D74 1C0082AC */  sw         $v0, 0x1C($a0)
    /* 69D78 00268D78 21186700 */  addu       $v1, $v1, $a3
    /* 69D7C 00268D7C 0400648C */  lw         $a0, 0x4($v1)
    /* 69D80 00268D80 60008294 */  lhu        $v0, 0x60($a0)
    /* 69D84 00268D84 00110200 */  sll        $v0, $v0, 4
    /* 69D88 00268D88 21104800 */  addu       $v0, $v0, $t0
    /* 69D8C 00268D8C C80EA724 */  addiu      $a3, $a1, %lo(D_00310EC8)
    /* 69D90 00268D90 07004368 */  ldl        $v1, 0x7($v0)
    /* 69D94 00268D94 0000436C */  ldr        $v1, 0x0($v0)
    /* 69D98 00268D98 0F004468 */  ldl        $a0, 0xF($v0)
    /* 69D9C 00268D9C 0800446C */  ldr        $a0, 0x8($v0)
    /* 69DA0 00268DA0 0700E3B0 */  sdl        $v1, 0x7($a3)
    /* 69DA4 00268DA4 0000E3B4 */  sdr        $v1, 0x0($a3)
    /* 69DA8 00268DA8 0F00E4B0 */  sdl        $a0, 0xF($a3)
    /* 69DAC 00268DAC 0800E4B4 */  sdr        $a0, 0x8($a3)
    /* 69DB0 00268DB0 28000010 */  b          .L00268E54
    /* 69DB4 00268DB4 B000BFDF */   ld        $ra, 0xB0($sp)
  .L00268DB8:
    /* 69DB8 00268DB8 21006214 */  bne        $v1, $v0, .L00268E40
    /* 69DBC 00268DBC 4F00043C */   lui       $a0, %hi(D_004E8070)
    /* 69DC0 00268DC0 4F00023C */  lui        $v0, (0x4F0000 >> 16)
    /* 69DC4 00268DC4 4F00033C */  lui        $v1, (0x4F0000 >> 16)
    /* 69DC8 00268DC8 C080468C */  lw         $a2, -0x7F40($v0)
    /* 69DCC 00268DCC 01000524 */  addiu      $a1, $zero, 0x1
    /* 69DD0 00268DD0 C880628C */  lw         $v0, -0x7F38($v1)
    /* 69DD4 00268DD4 4F00033C */  lui        $v1, %hi(D_004E8070)
    /* 69DD8 00268DD8 70806424 */  addiu      $a0, $v1, %lo(D_004E8070)
    /* 69DDC 00268DDC 23104600 */  subu       $v0, $v0, $a2
    /* 69DE0 00268DE0 01004328 */  slti       $v1, $v0, 0x1
    /* 69DE4 00268DE4 4400878C */  lw         $a3, 0x44($a0)
    /* 69DE8 00268DE8 0A100300 */  movz       $v0, $zero, $v1
    /* 69DEC 00268DEC 3400888C */  lw         $t0, 0x34($a0)
    /* 69DF0 00268DF0 C0180200 */  sll        $v1, $v0, 3
    /* 69DF4 00268DF4 180085AC */  sw         $a1, 0x18($a0)
    /* 69DF8 00268DF8 1C0082AC */  sw         $v0, 0x1C($a0)
    /* 69DFC 00268DFC 21186700 */  addu       $v1, $v1, $a3
    /* 69E00 00268E00 0400648C */  lw         $a0, 0x4($v1)
    /* 69E04 00268E04 3100053C */  lui        $a1, %hi(D_00310EC8)
    /* 69E08 00268E08 E4008294 */  lhu        $v0, 0xE4($a0)
    /* 69E0C 00268E0C 00110200 */  sll        $v0, $v0, 4
    /* 69E10 00268E10 21104800 */  addu       $v0, $v0, $t0
    /* 69E14 00268E14 C80EA324 */  addiu      $v1, $a1, %lo(D_00310EC8)
    /* 69E18 00268E18 07004468 */  ldl        $a0, 0x7($v0)
    /* 69E1C 00268E1C 0000446C */  ldr        $a0, 0x0($v0)
    /* 69E20 00268E20 0F004668 */  ldl        $a2, 0xF($v0)
    /* 69E24 00268E24 0800466C */  ldr        $a2, 0x8($v0)
    /* 69E28 00268E28 070064B0 */  sdl        $a0, 0x7($v1)
    /* 69E2C 00268E2C 000064B4 */  sdr        $a0, 0x0($v1)
    /* 69E30 00268E30 0F0066B0 */  sdl        $a2, 0xF($v1)
    /* 69E34 00268E34 080066B4 */  sdr        $a2, 0x8($v1)
    /* 69E38 00268E38 06000010 */  b          .L00268E54
    /* 69E3C 00268E3C B000BFDF */   ld        $ra, 0xB0($sp)
  .L00268E40:
    /* 69E40 00268E40 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 69E44 00268E44 70808324 */  addiu      $v1, $a0, %lo(D_004E8070)
    /* 69E48 00268E48 1C0062AC */  sw         $v0, 0x1C($v1)
    /* 69E4C 00268E4C 180062AC */  sw         $v0, 0x18($v1)
    /* 69E50 00268E50 B000BFDF */  ld         $ra, 0xB0($sp)
  .L00268E54:
    /* 69E54 00268E54 A000BEDF */  ld         $fp, 0xA0($sp)
    /* 69E58 00268E58 9000B7DF */  ld         $s7, 0x90($sp)
    /* 69E5C 00268E5C 8000B6DF */  ld         $s6, 0x80($sp)
    /* 69E60 00268E60 7000B5DF */  ld         $s5, 0x70($sp)
    /* 69E64 00268E64 6000B4DF */  ld         $s4, 0x60($sp)
    /* 69E68 00268E68 5000B3DF */  ld         $s3, 0x50($sp)
    /* 69E6C 00268E6C 4000B2DF */  ld         $s2, 0x40($sp)
    /* 69E70 00268E70 3000B1DF */  ld         $s1, 0x30($sp)
    /* 69E74 00268E74 2000B0DF */  ld         $s0, 0x20($sp)
    /* 69E78 00268E78 0800E003 */  jr         $ra
    /* 69E7C 00268E7C C000BD27 */   addiu     $sp, $sp, 0xC0
endlabel func_00268AC8
