.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0022E2FC, 0x4

glabel D_0022E2FC
    /* 2F2FC 0022E2FC 00000000 */  nop
endlabel D_0022E2FC

nonmatching func_0022E300, 0xC

glabel func_0022E300
    /* 2F300 0022E300 2B00023C */  lui        $v0, %hi(D_002B46D0)
    /* 2F304 0022E304 0800E003 */  jr         $ra
    /* 2F308 0022E308 D0464224 */   addiu     $v0, $v0, %lo(D_002B46D0)
endlabel func_0022E300
    /* 2F30C 0022E30C 00000000 */  nop

nonmatching D_0022E310, 0xA8

glabel D_0022E310
    /* 2F310 0022E310 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 2F314 0022E314 CC88828F */  lw         $v0, %gp_rel(D_0037023C)($gp)
    /* 2F318 0022E318 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2F31C 0022E31C 3000BFFF */  sd         $ra, 0x30($sp)
    /* 2F320 0022E320 2D888000 */  daddu      $s1, $a0, $zero
    /* 2F324 0022E324 2000B2FF */  sd         $s2, 0x20($sp)
    /* 2F328 0022E328 18004010 */  beqz       $v0, .L0022E38C
    /* 2F32C 0022E32C 0000B0FF */   sd        $s0, 0x0($sp)
    /* 2F330 0022E330 0400228E */  lw         $v0, 0x4($s1)
    /* 2F334 0022E334 2D900000 */  daddu      $s2, $zero, $zero
    /* 2F338 0022E338 14004018 */  blez       $v0, .L0022E38C
    /* 2F33C 0022E33C CC8880AF */   sw        $zero, %gp_rel(D_0037023C)($gp)
    /* 2F340 0022E340 1000248E */  lw         $a0, 0x10($s1)
    /* 2F344 0022E344 40811200 */  sll        $s0, $s2, 5
  .L0022E348:
    /* 2F348 0022E348 21100402 */  addu       $v0, $s0, $a0
    /* 2F34C 0022E34C 01005226 */  addiu      $s2, $s2, 0x1
    /* 2F350 0022E350 5C20080C */  jal        config_set_langtbl
    /* 2F354 0022E354 0000448C */   lw        $a0, 0x0($v0)
    /* 2F358 0022E358 1000238E */  lw         $v1, 0x10($s1)
    /* 2F35C 0022E35C 21180302 */  addu       $v1, $s0, $v1
    /* 2F360 0022E360 6E20080C */  jal        get_lang_string_GetOSDString_hkdosd_p2_tgt
    /* 2F364 0022E364 0400648C */   lw        $a0, 0x4($v1)
    /* 2F368 0022E368 1000248E */  lw         $a0, 0x10($s1)
    /* 2F36C 0022E36C 21800402 */  addu       $s0, $s0, $a0
    /* 2F370 0022E370 040002AE */  sw         $v0, 0x4($s0)
    /* 2F374 0022E374 0400228E */  lw         $v0, 0x4($s1)
    /* 2F378 0022E378 2A104202 */  slt        $v0, $s2, $v0
    /* 2F37C 0022E37C F2FF4014 */  bnez       $v0, .L0022E348
    /* 2F380 0022E380 40811200 */   sll       $s0, $s2, 5
    /* 2F384 0022E384 03000010 */  b          .L0022E394
    /* 2F388 0022E388 0800228E */   lw        $v0, 0x8($s1)
  .L0022E38C:
    /* 2F38C 0022E38C 1000248E */  lw         $a0, 0x10($s1)
    /* 2F390 0022E390 0800228E */  lw         $v0, 0x8($s1)
  .L0022E394:
    /* 2F394 0022E394 3000BFDF */  ld         $ra, 0x30($sp)
    /* 2F398 0022E398 40110200 */  sll        $v0, $v0, 5
    /* 2F39C 0022E39C 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2F3A0 0022E3A0 21104400 */  addu       $v0, $v0, $a0
    /* 2F3A4 0022E3A4 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2F3A8 0022E3A8 0000448C */  lw         $a0, 0x0($v0)
    /* 2F3AC 0022E3AC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2F3B0 0022E3B0 5C200808 */  j          config_set_langtbl
    /* 2F3B4 0022E3B4 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel D_0022E310

nonmatching D_0022E3B8, 0x3C

glabel D_0022E3B8
    /* 2F3B8 0022E3B8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2F3BC 0022E3BC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2F3C0 0022E3C0 1000BFFF */  sd         $ra, 0x10($sp)
    /* 2F3C4 0022E3C4 2D808000 */  daddu      $s0, $a0, $zero
    /* 2F3C8 0022E3C8 0800028E */  lw         $v0, 0x8($s0)
    /* 2F3CC 0022E3CC 1000038E */  lw         $v1, 0x10($s0)
    /* 2F3D0 0022E3D0 40110200 */  sll        $v0, $v0, 5
    /* 2F3D4 0022E3D4 21104300 */  addu       $v0, $v0, $v1
    /* 2F3D8 0022E3D8 5C20080C */  jal        config_set_langtbl
    /* 2F3DC 0022E3DC 0000448C */   lw        $a0, 0x0($v0)
    /* 2F3E0 0022E3E0 38000426 */  addiu      $a0, $s0, 0x38
    /* 2F3E4 0022E3E4 1000BFDF */  ld         $ra, 0x10($sp)
    /* 2F3E8 0022E3E8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2F3EC 0022E3EC A0B20808 */  j          func_0022CA80
    /* 2F3F0 0022E3F0 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel D_0022E3B8
    /* 2F3F4 0022E3F4 00000000 */  nop

nonmatching D_0022E3F8, 0x2C

glabel D_0022E3F8
    /* 2F3F8 0022E3F8 2D188000 */  daddu      $v1, $a0, $zero
    /* 2F3FC 0022E3FC 2B00093C */  lui        $t1, %hi(D_002B2560)
    /* 2F400 0022E400 0800628C */  lw         $v0, 0x8($v1)
    /* 2F404 0022E404 2D20A000 */  daddu      $a0, $a1, $zero
    /* 2F408 0022E408 1000688C */  lw         $t0, 0x10($v1)
    /* 2F40C 0022E40C 2D28C000 */  daddu      $a1, $a2, $zero
    /* 2F410 0022E410 40110200 */  sll        $v0, $v0, 5
    /* 2F414 0022E414 60252625 */  addiu      $a2, $t1, %lo(D_002B2560)
    /* 2F418 0022E418 21104800 */  addu       $v0, $v0, $t0
    /* 2F41C 0022E41C 009B0808 */  j          draw_menu_item
    /* 2F420 0022E420 0400488C */   lw        $t0, 0x4($v0)
endlabel D_0022E3F8
    /* 2F424 0022E424 00000000 */  nop

nonmatching D_0022E428, 0x170

glabel D_0022E428
    /* 2F428 0022E428 50FFBD27 */  addiu      $sp, $sp, -0xB0
    /* 2F42C 0022E42C 9000BEFF */  sd         $fp, 0x90($sp)
    /* 2F430 0022E430 8000B7FF */  sd         $s7, 0x80($sp)
    /* 2F434 0022E434 2DF0E000 */  daddu      $fp, $a3, $zero
    /* 2F438 0022E438 7000B6FF */  sd         $s6, 0x70($sp)
    /* 2F43C 0022E43C 2DB8C000 */  daddu      $s7, $a2, $zero
    /* 2F440 0022E440 5000B4FF */  sd         $s4, 0x50($sp)
    /* 2F444 0022E444 2DB0A000 */  daddu      $s6, $a1, $zero
    /* 2F448 0022E448 3000B2FF */  sd         $s2, 0x30($sp)
    /* 2F44C 0022E44C 2DA00000 */  daddu      $s4, $zero, $zero
    /* 2F450 0022E450 2000B1FF */  sd         $s1, 0x20($sp)
    /* 2F454 0022E454 A000BFFF */  sd         $ra, 0xA0($sp)
    /* 2F458 0022E458 2D888000 */  daddu      $s1, $a0, $zero
    /* 2F45C 0022E45C 6000B5FF */  sd         $s5, 0x60($sp)
    /* 2F460 0022E460 1000B0FF */  sd         $s0, 0x10($sp)
    /* 2F464 0022E464 4000B3FF */  sd         $s3, 0x40($sp)
    /* 2F468 0022E468 BCAA080C */  jal        func_0022AAF0
    /* 2F46C 0022E46C 0800338E */   lw        $s3, 0x8($s1)
    /* 2F470 0022E470 2D904000 */  daddu      $s2, $v0, $zero
    /* 2F474 0022E474 3800428E */  lw         $v0, 0x38($s2)
    /* 2F478 0022E478 15004050 */  beql       $v0, $zero, .L0022E4D0
    /* 2F47C 0022E47C F08893AF */   sw        $s3, %gp_rel(D_00370260)($gp)
    /* 2F480 0022E480 D420080C */  jal        is_pal_vmode_p9_tgt
    /* 2F484 0022E484 00000000 */   nop
    /* 2F488 0022E488 01000324 */  addiu      $v1, $zero, 0x1
    /* 2F48C 0022E48C 06004314 */  bne        $v0, $v1, .L0022E4A8
    /* 2F490 0022E490 3800428E */   lw        $v0, 0x38($s2)
    /* 2F494 0022E494 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 2F498 0022E498 2A208200 */  slt        $a0, $a0, $v0
    /* 2F49C 0022E49C FAFF4324 */  addiu      $v1, $v0, -0x6
    /* 2F4A0 0022E4A0 05000010 */  b          .L0022E4B8
    /* 2F4A4 0022E4A4 06004224 */   addiu     $v0, $v0, 0x6
  .L0022E4A8:
    /* 2F4A8 0022E4A8 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 2F4AC 0022E4AC 2A208200 */  slt        $a0, $a0, $v0
    /* 2F4B0 0022E4B0 FBFF4324 */  addiu      $v1, $v0, -0x5
    /* 2F4B4 0022E4B4 05004224 */  addiu      $v0, $v0, 0x5
  .L0022E4B8:
    /* 2F4B8 0022E4B8 0A184400 */  movz       $v1, $v0, $a0
    /* 2F4BC 0022E4BC 380043AE */  sw         $v1, 0x38($s2)
    /* 2F4C0 0022E4C0 3800428E */  lw         $v0, 0x38($s2)
    /* 2F4C4 0022E4C4 03004054 */  bnel       $v0, $zero, .L0022E4D4
    /* 2F4C8 0022E4C8 0400228E */   lw        $v0, 0x4($s1)
    /* 2F4CC 0022E4CC F08893AF */  sw         $s3, %gp_rel(D_00370260)($gp)
  .L0022E4D0:
    /* 2F4D0 0022E4D0 0400228E */  lw         $v0, 0x4($s1)
  .L0022E4D4:
    /* 2F4D4 0022E4D4 11004018 */  blez       $v0, .L0022E51C
    /* 2F4D8 0022E4D8 2D800000 */   daddu     $s0, $zero, $zero
    /* 2F4DC 0022E4DC 40991300 */  sll        $s3, $s3, 5
    /* 2F4E0 0022E4E0 2B00153C */  lui        $s5, %hi(D_002B2540)
    /* 2F4E4 0022E4E4 00000000 */  nop
  .L0022E4E8:
    /* 2F4E8 0022E4E8 1000238E */  lw         $v1, 0x10($s1)
    /* 2F4EC 0022E4EC 40111000 */  sll        $v0, $s0, 5
    /* 2F4F0 0022E4F0 01001026 */  addiu      $s0, $s0, 0x1
    /* 2F4F4 0022E4F4 21104300 */  addu       $v0, $v0, $v1
    /* 2F4F8 0022E4F8 BA4F080C */  jal        func_00213EE8
    /* 2F4FC 0022E4FC 0400448C */   lw        $a0, 0x4($v0)
    /* 2F500 0022E500 0400248E */  lw         $a0, 0x4($s1)
    /* 2F504 0022E504 2A188202 */  slt        $v1, $s4, $v0
    /* 2F508 0022E508 2A200402 */  slt        $a0, $s0, $a0
    /* 2F50C 0022E50C F6FF8014 */  bnez       $a0, .L0022E4E8
    /* 2F510 0022E510 0BA04300 */   movn      $s4, $v0, $v1
    /* 2F514 0022E514 04000010 */  b          .L0022E528
    /* 2F518 0022E518 F088838F */   lw        $v1, %gp_rel(D_00370260)($gp)
  .L0022E51C:
    /* 2F51C 0022E51C 40991300 */  sll        $s3, $s3, 5
    /* 2F520 0022E520 2B00153C */  lui        $s5, %hi(D_002B2540)
    /* 2F524 0022E524 F088838F */  lw         $v1, %gp_rel(D_00370260)($gp)
  .L0022E528:
    /* 2F528 0022E528 4025AA26 */  addiu      $t2, $s5, %lo(D_002B2540)
    /* 2F52C 0022E52C 1000228E */  lw         $v0, 0x10($s1)
    /* 2F530 0022E530 3D000724 */  addiu      $a3, $zero, 0x3D
    /* 2F534 0022E534 40190300 */  sll        $v1, $v1, 5
    /* 2F538 0022E538 2D20C002 */  daddu      $a0, $s6, $zero
    /* 2F53C 0022E53C 21186200 */  addu       $v1, $v1, $v0
    /* 2F540 0022E540 2D28E002 */  daddu      $a1, $s7, $zero
    /* 2F544 0022E544 21106202 */  addu       $v0, $s3, $v0
    /* 2F548 0022E548 04006B8C */  lw         $t3, 0x4($v1)
    /* 2F54C 0022E54C 0400498C */  lw         $t1, 0x4($v0)
    /* 2F550 0022E550 2D308002 */  daddu      $a2, $s4, $zero
    /* 2F554 0022E554 0800A7AF */  sw         $a3, 0x8($sp)
    /* 2F558 0022E558 0000AAAF */  sw         $t2, 0x0($sp)
    /* 2F55C 0022E55C 2D38C003 */  daddu      $a3, $fp, $zero
    /* 2F560 0022E560 14B1080C */  jal        func_0022C450
    /* 2F564 0022E564 3800488E */   lw        $t0, 0x38($s2)
    /* 2F568 0022E568 A000BFDF */  ld         $ra, 0xA0($sp)
    /* 2F56C 0022E56C 9000BEDF */  ld         $fp, 0x90($sp)
    /* 2F570 0022E570 8000B7DF */  ld         $s7, 0x80($sp)
    /* 2F574 0022E574 7000B6DF */  ld         $s6, 0x70($sp)
    /* 2F578 0022E578 6000B5DF */  ld         $s5, 0x60($sp)
    /* 2F57C 0022E57C 5000B4DF */  ld         $s4, 0x50($sp)
    /* 2F580 0022E580 4000B3DF */  ld         $s3, 0x40($sp)
    /* 2F584 0022E584 3000B2DF */  ld         $s2, 0x30($sp)
    /* 2F588 0022E588 2000B1DF */  ld         $s1, 0x20($sp)
    /* 2F58C 0022E58C 1000B0DF */  ld         $s0, 0x10($sp)
    /* 2F590 0022E590 0800E003 */  jr         $ra
    /* 2F594 0022E594 B000BD27 */   addiu     $sp, $sp, 0xB0
endlabel D_0022E428

nonmatching D_0022E598, 0x40

glabel D_0022E598
    /* 2F598 0022E598 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2F59C 0022E59C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2F5A0 0022E5A0 1000BFFF */  sd         $ra, 0x10($sp)
    /* 2F5A4 0022E5A4 2D808000 */  daddu      $s0, $a0, $zero
    /* 2F5A8 0022E5A8 CED3080C */  jal        module_clock_get_config_item
    /* 2F5AC 0022E5AC 0C00048E */   lw        $a0, 0xC($s0)
    /* 2F5B0 0022E5B0 0800038E */  lw         $v1, 0x8($s0)
    /* 2F5B4 0022E5B4 1000058E */  lw         $a1, 0x10($s0)
    /* 2F5B8 0022E5B8 40190300 */  sll        $v1, $v1, 5
    /* 2F5BC 0022E5BC 1000BFDF */  ld         $ra, 0x10($sp)
    /* 2F5C0 0022E5C0 21186500 */  addu       $v1, $v1, $a1
    /* 2F5C4 0022E5C4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2F5C8 0022E5C8 0000648C */  lw         $a0, 0x0($v1)
    /* 2F5CC 0022E5CC 000044AC */  sw         $a0, 0x0($v0)
    /* 2F5D0 0022E5D0 0800E003 */  jr         $ra
    /* 2F5D4 0022E5D4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel D_0022E598
