.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0022588C, 0x4

glabel D_0022588C
    /* 2688C 0022588C 00000000 */  nop
endlabel D_0022588C
