.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00278574, 0x4

glabel D_00278574
    /* 79574 00278574 00000000 */  nop
endlabel D_00278574
