.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00280994, 0x4

glabel D_00280994
    /* 81994 00280994 00000000 */  nop
endlabel D_00280994
