.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00282B3C, 0x4

glabel D_00282B3C
    /* 83B3C 00282B3C 00000000 */  nop
endlabel D_00282B3C
