.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0028FE6C, 0x4

glabel D_0028FE6C
    /* 90E6C 0028FE6C 00000000 */  nop
endlabel D_0028FE6C
