.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00275944, 0x4

glabel D_00275944
    /* 76944 00275944 00000000 */  nop
endlabel D_00275944

nonmatching func_00275948, 0x1A4

glabel func_00275948
    /* 76948 00275948 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 7694C 0027594C 84000724 */  addiu      $a3, $zero, 0x84
    /* 76950 00275950 4000B4FF */  sd         $s4, 0x40($sp)
    /* 76954 00275954 0C000624 */  addiu      $a2, $zero, 0xC
    /* 76958 00275958 3000B3FF */  sd         $s3, 0x30($sp)
    /* 7695C 0027595C 2000B2FF */  sd         $s2, 0x20($sp)
    /* 76960 00275960 2D980000 */  daddu      $s3, $zero, $zero
    /* 76964 00275964 0000B0FF */  sd         $s0, 0x0($sp)
    /* 76968 00275968 2D90A000 */  daddu      $s2, $a1, $zero
    /* 7696C 0027596C 5000BFFF */  sd         $ra, 0x50($sp)
    /* 76970 00275970 2D808000 */  daddu      $s0, $a0, $zero
    /* 76974 00275974 1000B1FF */  sd         $s1, 0x10($sp)
    /* 76978 00275978 20004392 */  lbu        $v1, 0x20($s2)
    /* 7697C 0027597C 1C00458E */  lw         $a1, 0x1C($s2)
    /* 76980 00275980 1800448E */  lw         $a0, 0x18($s2)
    /* 76984 00275984 07006330 */  andi       $v1, $v1, 0x7
    /* 76988 00275988 4400428E */  lw         $v0, 0x44($s2)
    /* 7698C 0027598C C0280500 */  sll        $a1, $a1, 3
    /* 76990 00275990 18208700 */  mult       $a0, $a0, $a3
    /* 76994 00275994 18186670 */  mult1      $v1, $v1, $a2
    /* 76998 00275998 2128A200 */  addu       $a1, $a1, $v0
    /* 7699C 0027599C 0400A28C */  lw         $v0, 0x4($a1)
    /* 769A0 002759A0 21A04400 */  addu       $s4, $v0, $a0
    /* 769A4 002759A4 21188302 */  addu       $v1, $s4, $v1
    /* 769A8 002759A8 0000718C */  lw         $s1, 0x0($v1)
    /* 769AC 002759AC 3A002106 */  bgez       $s1, .L00275A98
    /* 769B0 002759B0 04006524 */   addiu     $a1, $v1, 0x4
    /* 769B4 002759B4 16E1090C */  jal        sceAtokGetInputState
    /* 769B8 002759B8 2D200002 */   daddu     $a0, $s0, $zero
    /* 769BC 002759BC 2D184000 */  daddu      $v1, $v0, $zero
    /* 769C0 002759C0 0900622C */  sltiu      $v0, $v1, 0x9
    /* 769C4 002759C4 2A004010 */  beqz       $v0, .L00275A70
    /* 769C8 002759C8 3700023C */   lui       $v0, %hi(jtbl_00369860)
    /* 769CC 002759CC 80180300 */  sll        $v1, $v1, 2
    /* 769D0 002759D0 60984224 */  addiu      $v0, $v0, %lo(jtbl_00369860)
    /* 769D4 002759D4 21186200 */  addu       $v1, $v1, $v0
    /* 769D8 002759D8 0000648C */  lw         $a0, 0x0($v1)
    /* 769DC 002759DC 08008000 */  jr         $a0
    /* 769E0 002759E0 00000000 */   nop
    /* 769E4 002759E4 2D200002 */  daddu      $a0, $s0, $zero
    /* 769E8 002759E8 2D284002 */  daddu      $a1, $s2, $zero
    /* 769EC 002759EC 58D3090C */  jal        func_00274D60
    /* 769F0 002759F0 2D302002 */   daddu     $a2, $s1, $zero
    /* 769F4 002759F4 1E000010 */  b          .L00275A70
    /* 769F8 002759F8 2D984000 */   daddu     $s3, $v0, $zero
    /* 769FC 002759FC 2D200002 */  daddu      $a0, $s0, $zero
    /* 76A00 00275A00 2D284002 */  daddu      $a1, $s2, $zero
    /* 76A04 00275A04 0AD4090C */  jal        func_00275028
    /* 76A08 00275A08 2D302002 */   daddu     $a2, $s1, $zero
    /* 76A0C 00275A0C 18000010 */  b          .L00275A70
    /* 76A10 00275A10 2D984000 */   daddu     $s3, $v0, $zero
    /* 76A14 00275A14 2D200002 */  daddu      $a0, $s0, $zero
    /* 76A18 00275A18 2D284002 */  daddu      $a1, $s2, $zero
    /* 76A1C 00275A1C 9ED4090C */  jal        func_00275278
    /* 76A20 00275A20 2D302002 */   daddu     $a2, $s1, $zero
    /* 76A24 00275A24 12000010 */  b          .L00275A70
    /* 76A28 00275A28 2D984000 */   daddu     $s3, $v0, $zero
    /* 76A2C 00275A2C 2D200002 */  daddu      $a0, $s0, $zero
    /* 76A30 00275A30 2D284002 */  daddu      $a1, $s2, $zero
    /* 76A34 00275A34 EAD4090C */  jal        func_002753A8
    /* 76A38 00275A38 2D302002 */   daddu     $a2, $s1, $zero
    /* 76A3C 00275A3C 0C000010 */  b          .L00275A70
    /* 76A40 00275A40 2D984000 */   daddu     $s3, $v0, $zero
    /* 76A44 00275A44 2D200002 */  daddu      $a0, $s0, $zero
    /* 76A48 00275A48 2D284002 */  daddu      $a1, $s2, $zero
    /* 76A4C 00275A4C 42D5090C */  jal        func_00275508
    /* 76A50 00275A50 2D302002 */   daddu     $a2, $s1, $zero
    /* 76A54 00275A54 06000010 */  b          .L00275A70
    /* 76A58 00275A58 2D984000 */   daddu     $s3, $v0, $zero
    /* 76A5C 00275A5C 2D200002 */  daddu      $a0, $s0, $zero
    /* 76A60 00275A60 2D284002 */  daddu      $a1, $s2, $zero
    /* 76A64 00275A64 9AD5090C */  jal        func_00275668
    /* 76A68 00275A68 2D302002 */   daddu     $a2, $s1, $zero
    /* 76A6C 00275A6C 2D984000 */  daddu      $s3, $v0, $zero
  .L00275A70:
    /* 76A70 00275A70 17006012 */  beqz       $s3, .L00275AD0
    /* 76A74 00275A74 5000BFDF */   ld        $ra, 0x50($sp)
    /* 76A78 00275A78 2D208002 */  daddu      $a0, $s4, $zero
    /* 76A7C 00275A7C 4000B4DF */  ld         $s4, 0x40($sp)
    /* 76A80 00275A80 3000B3DF */  ld         $s3, 0x30($sp)
    /* 76A84 00275A84 2000B2DF */  ld         $s2, 0x20($sp)
    /* 76A88 00275A88 1000B1DF */  ld         $s1, 0x10($sp)
    /* 76A8C 00275A8C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 76A90 00275A90 3ACE0908 */  j          func_002738E8
    /* 76A94 00275A94 6000BD27 */   addiu     $sp, $sp, 0x60
  .L00275A98:
    /* 76A98 00275A98 F2D5090C */  jal        sendKeyAtok
    /* 76A9C 00275A9C 2D200002 */   daddu     $a0, $s0, $zero
    /* 76AA0 00275AA0 00630424 */  addiu      $a0, $zero, 0x6300
    /* 76AA4 00275AA4 01000524 */  addiu      $a1, $zero, 0x1
    /* 76AA8 00275AA8 2438090C */  jal        sound_handle_queue_cmd_auto
    /* 76AAC 00275AAC 12000624 */   addiu     $a2, $zero, 0x12
    /* 76AB0 00275AB0 3ACE090C */  jal        func_002738E8
    /* 76AB4 00275AB4 2D208002 */   daddu     $a0, $s4, $zero
    /* 76AB8 00275AB8 20004392 */  lbu        $v1, 0x20($s2)
    /* 76ABC 00275ABC 80006230 */  andi       $v0, $v1, 0x80
    /* 76AC0 00275AC0 02004010 */  beqz       $v0, .L00275ACC
    /* 76AC4 00275AC4 7E006230 */   andi      $v0, $v1, 0x7E
    /* 76AC8 00275AC8 200042A2 */  sb         $v0, 0x20($s2)
  .L00275ACC:
    /* 76ACC 00275ACC 5000BFDF */  ld         $ra, 0x50($sp)
  .L00275AD0:
    /* 76AD0 00275AD0 4000B4DF */  ld         $s4, 0x40($sp)
    /* 76AD4 00275AD4 3000B3DF */  ld         $s3, 0x30($sp)
    /* 76AD8 00275AD8 2000B2DF */  ld         $s2, 0x20($sp)
    /* 76ADC 00275ADC 1000B1DF */  ld         $s1, 0x10($sp)
    /* 76AE0 00275AE0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 76AE4 00275AE4 0800E003 */  jr         $ra
    /* 76AE8 00275AE8 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel func_00275948
    /* 76AEC 00275AEC 00000000 */  nop
