.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00208374, 0x4

glabel D_00208374
    /* 9374 00208374 00000000 */  nop
endlabel D_00208374
