.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0021C104, 0x4

glabel D_0021C104
    /* 1D104 0021C104 00000000 */  nop
endlabel D_0021C104
