.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_002780A4, 0x4

glabel D_002780A4
    /* 790A4 002780A4 00000000 */  nop
endlabel D_002780A4
