.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_0023F4B8, 0x84

glabel D_0023F4B8
    /* 404B8 0023F4B8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 404BC 0023F4BC 4700023C */  lui        $v0, %hi(D_00470EE0)
    /* 404C0 0023F4C0 0000BFFF */  sd         $ra, 0x0($sp)
    /* 404C4 0023F4C4 E00E4224 */  addiu      $v0, $v0, %lo(D_00470EE0)
    /* 404C8 0023F4C8 08010424 */  addiu      $a0, $zero, 0x108
    /* 404CC 0023F4CC 1000438C */  lw         $v1, 0x10($v0)
    /* 404D0 0023F4D0 06006454 */  bnel       $v1, $a0, .L0023F4EC
    /* 404D4 0023F4D4 0800428C */   lw        $v0, 0x8($v0)
    /* 404D8 0023F4D8 B091858F */  lw         $a1, %gp_rel(D_00370B20)($gp)
    /* 404DC 0023F4DC 8CFB080C */  jal        browser_handle_icon_sys_text
    /* 404E0 0023F4E0 7C01043C */   lui       $a0, (0x17C0000 >> 16)
    /* 404E4 0023F4E4 13000010 */  b          .L0023F534
    /* 404E8 0023F4E8 0000BFDF */   ld        $ra, 0x0($sp)
  .L0023F4EC:
    /* 404EC 0023F4EC 20004230 */  andi       $v0, $v0, 0x20
    /* 404F0 0023F4F0 06004014 */  bnez       $v0, .L0023F50C
    /* 404F4 0023F4F4 B091828F */   lw        $v0, %gp_rel(D_00370B20)($gp)
    /* 404F8 0023F4F8 B091858F */  lw         $a1, %gp_rel(D_00370B20)($gp)
    /* 404FC 0023F4FC CAFC080C */  jal        browser_handle_ps2file
    /* 40500 0023F500 7C01043C */   lui       $a0, (0x17C0000 >> 16)
    /* 40504 0023F504 0B000010 */  b          .L0023F534
    /* 40508 0023F508 0000BFDF */   ld        $ra, 0x0($sp)
  .L0023F50C:
    /* 4050C 0023F50C C4034228 */  slti       $v0, $v0, 0x3C4
    /* 40510 0023F510 05004010 */  beqz       $v0, .L0023F528
    /* 40514 0023F514 00000000 */   nop
    /* 40518 0023F518 D0F9080C */  jal        func_0023E740
    /* 4051C 0023F51C 00000000 */   nop
    /* 40520 0023F520 04000010 */  b          .L0023F534
    /* 40524 0023F524 0000BFDF */   ld        $ra, 0x0($sp)
  .L0023F528:
    /* 40528 0023F528 DAF9080C */  jal        browser_handle_icon_sys_binary
    /* 4052C 0023F52C 7C01043C */   lui       $a0, (0x17C0000 >> 16)
    /* 40530 0023F530 0000BFDF */  ld         $ra, 0x0($sp)
  .L0023F534:
    /* 40534 0023F534 0800E003 */  jr         $ra
    /* 40538 0023F538 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel D_0023F4B8
    /* 4053C 0023F53C 00000000 */  nop
