.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00266C24, 0x4

glabel D_00266C24
    /* 67C24 00266C24 00000000 */  nop
endlabel D_00266C24
