.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching get_pathconf_key, 0x278

glabel get_pathconf_key
    /* 9E78 00208E78 90FEBD27 */  addiu      $sp, $sp, -0x170
    /* 9E7C 00208E7C 5001BEFF */  sd         $fp, 0x150($sp)
    /* 9E80 00208E80 4001B7FF */  sd         $s7, 0x140($sp)
    /* 9E84 00208E84 2DF0E000 */  daddu      $fp, $a3, $zero
    /* 9E88 00208E88 3001B6FF */  sd         $s6, 0x130($sp)
    /* 9E8C 00208E8C 2DB88000 */  daddu      $s7, $a0, $zero
    /* 9E90 00208E90 2001B5FF */  sd         $s5, 0x120($sp)
    /* 9E94 00208E94 2DB0A000 */  daddu      $s6, $a1, $zero
    /* 9E98 00208E98 6001BFFF */  sd         $ra, 0x160($sp)
    /* 9E9C 00208E9C 2DA8C000 */  daddu      $s5, $a2, $zero
    /* 9EA0 00208EA0 1001B4FF */  sd         $s4, 0x110($sp)
    /* 9EA4 00208EA4 0001B3FF */  sd         $s3, 0x100($sp)
    /* 9EA8 00208EA8 F000B2FF */  sd         $s2, 0xF0($sp)
    /* 9EAC 00208EAC E000B1FF */  sd         $s1, 0xE0($sp)
    /* 9EB0 00208EB0 D000B0FF */  sd         $s0, 0xD0($sp)
    /* 9EB4 00208EB4 0200C012 */  beqz       $s6, .L00208EC0
    /* 9EB8 00208EB8 C800A8AF */   sw        $t0, 0xC8($sp)
    /* 9EBC 00208EBC 0000C0A2 */  sb         $zero, 0x0($s6)
  .L00208EC0:
    /* 9EC0 00208EC0 0100A056 */  bnel       $s5, $zero, .L00208EC8
    /* 9EC4 00208EC4 0000A0A2 */   sb        $zero, 0x0($s5)
  .L00208EC8:
    /* 9EC8 00208EC8 0100C057 */  bnel       $fp, $zero, .L00208ED0
    /* 9ECC 00208ECC 0000C0AF */   sw        $zero, 0x0($fp)
  .L00208ED0:
    /* 9ED0 00208ED0 C800A28F */  lw         $v0, 0xC8($sp)
    /* 9ED4 00208ED4 01004054 */  bnel       $v0, $zero, .L00208EDC
    /* 9ED8 00208ED8 000040AC */   sw        $zero, 0x0($v0)
  .L00208EDC:
    /* 9EDC 00208EDC 8000B227 */  addiu      $s2, $sp, 0x80
    /* 9EE0 00208EE0 2D280000 */  daddu      $a1, $zero, $zero
    /* 9EE4 00208EE4 2D204002 */  daddu      $a0, $s2, $zero
    /* 9EE8 00208EE8 5E710A0C */  jal        memset
    /* 9EEC 00208EEC 20000624 */   addiu     $a2, $zero, 0x20
    /* 9EF0 00208EF0 A000B427 */  addiu      $s4, $sp, 0xA0
    /* 9EF4 00208EF4 2D280000 */  daddu      $a1, $zero, $zero
    /* 9EF8 00208EF8 2D208002 */  daddu      $a0, $s4, $zero
    /* 9EFC 00208EFC 5E710A0C */  jal        memset
    /* 9F00 00208F00 20000624 */   addiu     $a2, $zero, 0x20
    /* 9F04 00208F04 4000B327 */  addiu      $s3, $sp, 0x40
    /* 9F08 00208F08 3800043C */  lui        $a0, %hi(path_conf_bytes)
    /* 9F0C 00208F0C 3400063C */  lui        $a2, %hi(aPath)
    /* 9F10 00208F10 00378424 */  addiu      $a0, $a0, %lo(path_conf_bytes)
    /* 9F14 00208F14 F07DC624 */  addiu      $a2, $a2, %lo(aPath)
    /* 9F18 00208F18 2D28E002 */  daddu      $a1, $s7, $zero
    /* 9F1C 00208F1C 2D386002 */  daddu      $a3, $s3, $zero
    /* 9F20 00208F20 3A22080C */  jal        parse_path_conf
    /* 9F24 00208F24 40000824 */   addiu     $t0, $zero, 0x40
    /* 9F28 00208F28 52004004 */  bltz       $v0, .L00209074
    /* 9F2C 00208F2C 3400053C */   lui       $a1, %hi(aPfs0SSId)
    /* 9F30 00208F30 2D20A003 */  daddu      $a0, $sp, $zero
    /* 9F34 00208F34 F87DA524 */  addiu      $a1, $a1, %lo(aPfs0SSId)
    /* 9F38 00208F38 2D306002 */  daddu      $a2, $s3, $zero
    /* 9F3C 00208F3C EC720A0C */  jal        sprintf
    /* 9F40 00208F40 2D38E002 */   daddu     $a3, $s7, $zero
    /* 9F44 00208F44 2D20A003 */  daddu      $a0, $sp, $zero
    /* 9F48 00208F48 CA0D0A0C */  jal        sceOpen
    /* 9F4C 00208F4C 01000524 */   addiu     $a1, $zero, 0x1
    /* 9F50 00208F50 2D884000 */  daddu      $s1, $v0, $zero
    /* 9F54 00208F54 47002006 */  bltz       $s1, .L00209074
    /* 9F58 00208F58 2D202002 */   daddu     $a0, $s1, $zero
    /* 9F5C 00208F5C 2D284002 */  daddu      $a1, $s2, $zero
    /* 9F60 00208F60 5A0F0A0C */  jal        sceRead
    /* 9F64 00208F64 1F000624 */   addiu     $a2, $zero, 0x1F
    /* 9F68 00208F68 2D804000 */  daddu      $s0, $v0, $zero
    /* 9F6C 00208F6C 6C0E0A0C */  jal        sceClose
    /* 9F70 00208F70 2D202002 */   daddu     $a0, $s1, $zero
    /* 9F74 00208F74 52000006 */  bltz       $s0, .L002090C0
    /* 9F78 00208F78 2D100000 */   daddu     $v0, $zero, $zero
    /* 9F7C 00208F7C 21105002 */  addu       $v0, $s2, $s0
    /* 9F80 00208F80 C400B127 */  addiu      $s1, $sp, 0xC4
    /* 9F84 00208F84 2D804002 */  daddu      $s0, $s2, $zero
    /* 9F88 00208F88 000040A0 */  sb         $zero, 0x0($v0)
    /* 9F8C 00208F8C C000B227 */  addiu      $s2, $sp, 0xC0
    /* 9F90 00208F90 726D0A0C */  jal        atoi
    /* 9F94 00208F94 2D200002 */   daddu     $a0, $s0, $zero
    /* 9F98 00208F98 8000A393 */  lbu        $v1, 0x80($sp)
    /* 9F9C 00208F9C 04000010 */  b          .L00208FB0
    /* 9FA0 00208FA0 C000A2AF */   sw        $v0, 0xC0($sp)
    /* 9FA4 00208FA4 00000000 */  nop
  .L00208FA8:
    /* 9FA8 00208FA8 01001026 */  addiu      $s0, $s0, 0x1
    /* 9FAC 00208FAC 00000392 */  lbu        $v1, 0x0($s0)
  .L00208FB0:
    /* 9FB0 00208FB0 D0FF6224 */  addiu      $v0, $v1, -0x30
    /* 9FB4 00208FB4 0A00422C */  sltiu      $v0, $v0, 0xA
    /* 9FB8 00208FB8 00000000 */  nop
    /* 9FBC 00208FBC FAFF4014 */  bnez       $v0, .L00208FA8
    /* 9FC0 00208FC0 00000000 */   nop
    /* 9FC4 00208FC4 00160300 */  sll        $v0, $v1, 24
    /* 9FC8 00208FC8 2E000324 */  addiu      $v1, $zero, 0x2E
    /* 9FCC 00208FCC 03160200 */  sra        $v0, $v0, 24
    /* 9FD0 00208FD0 06004310 */  beq        $v0, $v1, .L00208FEC
    /* 9FD4 00208FD4 01001026 */   addiu     $s0, $s0, 0x1
    /* 9FD8 00208FD8 000000AC */  sw         $zero, 0x0($zero)
    /* 9FDC 00208FDC FFFF1024 */  addiu      $s0, $zero, -0x1
    /* 9FE0 00208FE0 000020AE */  sw         $zero, 0x0($s1)
    /* 9FE4 00208FE4 0E000010 */  b          .L00209020
    /* 9FE8 00208FE8 000040AE */   sw        $zero, 0x0($s2)
  .L00208FEC:
    /* 9FEC 00208FEC 726D0A0C */  jal        atoi
    /* 9FF0 00208FF0 2D200002 */   daddu     $a0, $s0, $zero
    /* 9FF4 00208FF4 03000010 */  b          .L00209004
    /* 9FF8 00208FF8 000022AE */   sw        $v0, 0x0($s1)
    /* 9FFC 00208FFC 00000000 */  nop
  .L00209000:
    /* A000 00209000 01001026 */  addiu      $s0, $s0, 0x1
  .L00209004:
    /* A004 00209004 00000292 */  lbu        $v0, 0x0($s0)
    /* A008 00209008 D0FF4224 */  addiu      $v0, $v0, -0x30
    /* A00C 0020900C 0A00422C */  sltiu      $v0, $v0, 0xA
    /* A010 00209010 00000000 */  nop
    /* A014 00209014 FAFF4014 */  bnez       $v0, .L00209000
    /* A018 00209018 00000000 */   nop
    /* A01C 0020901C 2D800000 */  daddu      $s0, $zero, $zero
  .L00209020:
    /* A020 00209020 14000006 */  bltz       $s0, .L00209074
    /* A024 00209024 3400053C */   lui       $a1, %hi(aPfs0SSVer)
    /* A028 00209028 4000A627 */  addiu      $a2, $sp, 0x40
    /* A02C 0020902C 087EA524 */  addiu      $a1, $a1, %lo(aPfs0SSVer)
    /* A030 00209030 2D38E002 */  daddu      $a3, $s7, $zero
    /* A034 00209034 EC720A0C */  jal        sprintf
    /* A038 00209038 2D20A003 */   daddu     $a0, $sp, $zero
    /* A03C 0020903C 2D20A003 */  daddu      $a0, $sp, $zero
    /* A040 00209040 CA0D0A0C */  jal        sceOpen
    /* A044 00209044 01000524 */   addiu     $a1, $zero, 0x1
    /* A048 00209048 2D884000 */  daddu      $s1, $v0, $zero
    /* A04C 0020904C 09002006 */  bltz       $s1, .L00209074
    /* A050 00209050 A000A527 */   addiu     $a1, $sp, 0xA0
    /* A054 00209054 2D202002 */  daddu      $a0, $s1, $zero
    /* A058 00209058 5A0F0A0C */  jal        sceRead
    /* A05C 0020905C 1F000624 */   addiu     $a2, $zero, 0x1F
    /* A060 00209060 2D804000 */  daddu      $s0, $v0, $zero
    /* A064 00209064 6C0E0A0C */  jal        sceClose
    /* A068 00209068 2D202002 */   daddu     $a0, $s1, $zero
    /* A06C 0020906C 03000106 */  bgez       $s0, .L0020907C
    /* A070 00209070 21109002 */   addu      $v0, $s4, $s0
  .L00209074:
    /* A074 00209074 12000010 */  b          .L002090C0
    /* A078 00209078 2D100000 */   daddu     $v0, $zero, $zero
  .L0020907C:
    /* A07C 0020907C 0400A012 */  beqz       $s5, .L00209090
    /* A080 00209080 000040A0 */   sb        $zero, 0x0($v0)
    /* A084 00209084 2D20A002 */  daddu      $a0, $s5, $zero
    /* A088 00209088 64740A0C */  jal        strcpy
    /* A08C 0020908C 2D288002 */   daddu     $a1, $s4, $zero
  .L00209090:
    /* A090 00209090 0300C012 */  beqz       $s6, .L002090A0
    /* A094 00209094 2D20C002 */   daddu     $a0, $s6, $zero
    /* A098 00209098 64740A0C */  jal        strcpy
    /* A09C 0020909C 2D286002 */   daddu     $a1, $s3, $zero
  .L002090A0:
    /* A0A0 002090A0 0200C013 */  beqz       $fp, .L002090AC
    /* A0A4 002090A4 C000A28F */   lw        $v0, 0xC0($sp)
    /* A0A8 002090A8 0000C2AF */  sw         $v0, 0x0($fp)
  .L002090AC:
    /* A0AC 002090AC C800A38F */  lw         $v1, 0xC8($sp)
    /* A0B0 002090B0 02006010 */  beqz       $v1, .L002090BC
    /* A0B4 002090B4 C400A28F */   lw        $v0, 0xC4($sp)
    /* A0B8 002090B8 000062AC */  sw         $v0, 0x0($v1)
  .L002090BC:
    /* A0BC 002090BC 01000224 */  addiu      $v0, $zero, 0x1
  .L002090C0:
    /* A0C0 002090C0 6001BFDF */  ld         $ra, 0x160($sp)
    /* A0C4 002090C4 5001BEDF */  ld         $fp, 0x150($sp)
    /* A0C8 002090C8 4001B7DF */  ld         $s7, 0x140($sp)
    /* A0CC 002090CC 3001B6DF */  ld         $s6, 0x130($sp)
    /* A0D0 002090D0 2001B5DF */  ld         $s5, 0x120($sp)
    /* A0D4 002090D4 1001B4DF */  ld         $s4, 0x110($sp)
    /* A0D8 002090D8 0001B3DF */  ld         $s3, 0x100($sp)
    /* A0DC 002090DC F000B2DF */  ld         $s2, 0xF0($sp)
    /* A0E0 002090E0 E000B1DF */  ld         $s1, 0xE0($sp)
    /* A0E4 002090E4 D000B0DF */  ld         $s0, 0xD0($sp)
    /* A0E8 002090E8 0800E003 */  jr         $ra
    /* A0EC 002090EC 7001BD27 */   addiu     $sp, $sp, 0x170
endlabel get_pathconf_key
