.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching handle_version_info, 0x14C

glabel handle_version_info
    /* B988 0020A988 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* B98C 0020A98C 3800023C */  lui        $v0, %hi(romver_bytes)
    /* B990 0020A990 1000B1FF */  sd         $s1, 0x10($sp)
    /* B994 0020A994 2D280000 */  daddu      $a1, $zero, $zero
    /* B998 0020A998 C0365124 */  addiu      $s1, $v0, %lo(romver_bytes)
    /* B99C 0020A99C 0000B0FF */  sd         $s0, 0x0($sp)
    /* B9A0 0020A9A0 4000BFFF */  sd         $ra, 0x40($sp)
    /* B9A4 0020A9A4 10000624 */  addiu      $a2, $zero, 0x10
    /* B9A8 0020A9A8 3000B3FF */  sd         $s3, 0x30($sp)
    /* B9AC 0020A9AC 2D202002 */  daddu      $a0, $s1, $zero
    /* B9B0 0020A9B0 5E710A0C */  jal        memset
    /* B9B4 0020A9B4 2000B2FF */   sd        $s2, 0x20($sp)
    /* B9B8 0020A9B8 3400043C */  lui        $a0, %hi(aRom0Romver_0)
    /* B9BC 0020A9BC 01000524 */  addiu      $a1, $zero, 0x1
    /* B9C0 0020A9C0 CA0D0A0C */  jal        sceOpen
    /* B9C4 0020A9C4 B07F8424 */   addiu     $a0, $a0, %lo(aRom0Romver_0)
    /* B9C8 0020A9C8 2D804000 */  daddu      $s0, $v0, $zero
    /* B9CC 0020A9CC 06000006 */  bltz       $s0, .L0020A9E8
    /* B9D0 0020A9D0 2D282002 */   daddu     $a1, $s1, $zero
    /* B9D4 0020A9D4 2D200002 */  daddu      $a0, $s0, $zero
    /* B9D8 0020A9D8 5A0F0A0C */  jal        sceRead
    /* B9DC 0020A9DC 10000624 */   addiu     $a2, $zero, 0x10
    /* B9E0 0020A9E0 6C0E0A0C */  jal        sceClose
    /* B9E4 0020A9E4 2D200002 */   daddu     $a0, $s0, $zero
  .L0020A9E8:
    /* B9E8 0020A9E8 3800133C */  lui        $s3, %hi(path_conf_bytes)
    /* B9EC 0020A9EC 2D280000 */  daddu      $a1, $zero, $zero
    /* B9F0 0020A9F0 00377226 */  addiu      $s2, $s3, %lo(path_conf_bytes)
    /* B9F4 0020A9F4 00080624 */  addiu      $a2, $zero, 0x800
    /* B9F8 0020A9F8 5E710A0C */  jal        memset
    /* B9FC 0020A9FC 2D204002 */   daddu     $a0, $s2, $zero
    /* BA00 0020AA00 3400043C */  lui        $a0, %hi(aPfs0ModulesCnf)
    /* BA04 0020AA04 01000524 */  addiu      $a1, $zero, 0x1
    /* BA08 0020AA08 CA0D0A0C */  jal        sceOpen
    /* BA0C 0020AA0C C07F8424 */   addiu     $a0, $a0, %lo(aPfs0ModulesCnf)
    /* BA10 0020AA10 2D804000 */  daddu      $s0, $v0, $zero
    /* BA14 0020AA14 15000006 */  bltz       $s0, .L0020AA6C
    /* BA18 0020AA18 2D200002 */   daddu     $a0, $s0, $zero
    /* BA1C 0020AA1C 2D284002 */  daddu      $a1, $s2, $zero
    /* BA20 0020AA20 5A0F0A0C */  jal        sceRead
    /* BA24 0020AA24 FF070624 */   addiu     $a2, $zero, 0x7FF
    /* BA28 0020AA28 2D884000 */  daddu      $s1, $v0, $zero
    /* BA2C 0020AA2C 6C0E0A0C */  jal        sceClose
    /* BA30 0020AA30 2D200002 */   daddu     $a0, $s0, $zero
    /* BA34 0020AA34 03002106 */  bgez       $s1, .L0020AA44
    /* BA38 0020AA38 2D204002 */   daddu     $a0, $s2, $zero
    /* BA3C 0020AA3C 0B000010 */  b          .L0020AA6C
    /* BA40 0020AA40 003760A2 */   sb        $zero, %lo(path_conf_bytes)($s3)
  .L0020AA44:
    /* BA44 0020AA44 91B6063C */  lui        $a2, (0xB6913225 >> 16)
    /* BA48 0020AA48 2532C634 */  ori        $a2, $a2, (0xB6913225 & 0xFFFF)
    /* BA4C 0020AA4C 38340600 */  dsll       $a2, $a2, 16
    /* BA50 0020AA50 8E77C634 */  ori        $a2, $a2, 0x778E
    /* BA54 0020AA54 38340600 */  dsll       $a2, $a2, 16
    /* BA58 0020AA58 D26AC634 */  ori        $a2, $a2, 0x6AD2
    /* BA5C 0020AA5C E021080C */  jal        decryption_forconfigfile
    /* BA60 0020AA60 2D282002 */   daddu     $a1, $s1, $zero
    /* BA64 0020AA64 21103202 */  addu       $v0, $s1, $s2
    /* BA68 0020AA68 000040A0 */  sb         $zero, 0x0($v0)
  .L0020AA6C:
    /* BA6C 0020AA6C 0E25080C */  jal        module_machine_setup
    /* BA70 0020AA70 00000000 */   nop
    /* BA74 0020AA74 CE6A080C */  jal        module_opening_setup
    /* BA78 0020AA78 00000000 */   nop
    /* BA7C 0020AA7C 4096080C */  jal        module_clock_setup
    /* BA80 0020AA80 00000000 */   nop
    /* BA84 0020AA84 103A090C */  jal        module_browser_setup
    /* BA88 0020AA88 00000000 */   nop
    /* BA8C 0020AA8C E26A080C */  jal        module_dummy_setup
    /* BA90 0020AA90 00000000 */   nop
    /* BA94 0020AA94 E425080C */  jal        module_cdplayer_setup
    /* BA98 0020AA98 00000000 */   nop
    /* BA9C 0020AA9C 7827080C */  jal        module_ps1drv_setup
    /* BAA0 0020AAA0 00000000 */   nop
    /* BAA4 0020AAA4 E029080C */  jal        module_dvdplayer_setup
    /* BAA8 0020AAA8 00000000 */   nop
    /* BAAC 0020AAAC 4E2A080C */  jal        module_smap_setup
    /* BAB0 0020AAB0 00000000 */   nop
    /* BAB4 0020AAB4 4000BFDF */  ld         $ra, 0x40($sp)
    /* BAB8 0020AAB8 2D100000 */  daddu      $v0, $zero, $zero
    /* BABC 0020AABC 3000B3DF */  ld         $s3, 0x30($sp)
    /* BAC0 0020AAC0 2000B2DF */  ld         $s2, 0x20($sp)
    /* BAC4 0020AAC4 1000B1DF */  ld         $s1, 0x10($sp)
    /* BAC8 0020AAC8 0000B0DF */  ld         $s0, 0x0($sp)
    /* BACC 0020AACC 0800E003 */  jr         $ra
    /* BAD0 0020AAD0 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel handle_version_info
