.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching handle_get_vidmode, 0xDC

glabel handle_get_vidmode
    /* 9238 00208238 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 923C 0020823C 2000B1FF */  sd         $s1, 0x20($sp)
    /* 9240 00208240 2B00113C */  lui        $s1, %hi(var_curvidmode)
    /* 9244 00208244 3000BFFF */  sd         $ra, 0x30($sp)
    /* 9248 00208248 28D2228E */  lw         $v0, %lo(var_curvidmode)($s1)
    /* 924C 0020824C 2C004104 */  bgez       $v0, .L00208300
    /* 9250 00208250 1000B0FF */   sd        $s0, 0x10($sp)
    /* 9254 00208254 3400043C */  lui        $a0, %hi(aRom0Romver)
    /* 9258 00208258 01000524 */  addiu      $a1, $zero, 0x1
    /* 925C 0020825C CA0D0A0C */  jal        sceOpen
    /* 9260 00208260 807D8424 */   addiu     $a0, $a0, %lo(aRom0Romver)
    /* 9264 00208264 2D804000 */  daddu      $s0, $v0, $zero
    /* 9268 00208268 03000106 */  bgez       $s0, .L00208278
    /* 926C 0020826C 2D200002 */   daddu     $a0, $s0, $zero
    /* 9270 00208270 23000010 */  b          .L00208300
    /* 9274 00208274 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L00208278:
    /* 9278 00208278 2D28A003 */  daddu      $a1, $sp, $zero
    /* 927C 0020827C 5A0F0A0C */  jal        sceRead
    /* 9280 00208280 10000624 */   addiu     $a2, $zero, 0x10
    /* 9284 00208284 6C0E0A0C */  jal        sceClose
    /* 9288 00208288 2D200002 */   daddu     $a0, $s0, $zero
    /* 928C 0020828C 0400A393 */  lbu        $v1, 0x4($sp)
    /* 9290 00208290 45000224 */  addiu      $v0, $zero, 0x45
    /* 9294 00208294 001E0300 */  sll        $v1, $v1, 24
    /* 9298 00208298 031E0300 */  sra        $v1, $v1, 24
    /* 929C 0020829C 10006210 */  beq        $v1, $v0, .L002082E0
    /* 92A0 002082A0 46006228 */   slti      $v0, $v1, 0x46
    /* 92A4 002082A4 05004010 */  beqz       $v0, .L002082BC
    /* 92A8 002082A8 41000224 */   addiu     $v0, $zero, 0x41
    /* 92AC 002082AC 0A006210 */  beq        $v1, $v0, .L002082D8
    /* 92B0 002082B0 0500A393 */   lbu       $v1, 0x5($sp)
    /* 92B4 002082B4 0E000010 */  b          .L002082F0
    /* 92B8 002082B8 2B00043C */   lui       $a0, %hi(var_curlang)
  .L002082BC:
    /* 92BC 002082BC 48000224 */  addiu      $v0, $zero, 0x48
    /* 92C0 002082C0 05006210 */  beq        $v1, $v0, .L002082D8
    /* 92C4 002082C4 4A000224 */   addiu     $v0, $zero, 0x4A
    /* 92C8 002082C8 07006250 */  beql       $v1, $v0, .L002082E8
    /* 92CC 002082CC 28D220AE */   sw        $zero, %lo(var_curvidmode)($s1)
    /* 92D0 002082D0 06000010 */  b          .L002082EC
    /* 92D4 002082D4 0500A393 */   lbu       $v1, 0x5($sp)
  .L002082D8:
    /* 92D8 002082D8 02000010 */  b          .L002082E4
    /* 92DC 002082DC 01000224 */   addiu     $v0, $zero, 0x1
  .L002082E0:
    /* 92E0 002082E0 02000224 */  addiu      $v0, $zero, 0x2
  .L002082E4:
    /* 92E4 002082E4 28D222AE */  sw         $v0, %lo(var_curvidmode)($s1)
  .L002082E8:
    /* 92E8 002082E8 0500A393 */  lbu        $v1, 0x5($sp)
  .L002082EC:
    /* 92EC 002082EC 2B00043C */  lui        $a0, %hi(var_curlang)
  .L002082F0:
    /* 92F0 002082F0 28D2228E */  lw         $v0, %lo(var_curvidmode)($s1)
    /* 92F4 002082F4 001E0300 */  sll        $v1, $v1, 24
    /* 92F8 002082F8 031E0300 */  sra        $v1, $v1, 24
    /* 92FC 002082FC 24D283AC */  sw         $v1, %lo(var_curlang)($a0)
  .L00208300:
    /* 9300 00208300 3000BFDF */  ld         $ra, 0x30($sp)
    /* 9304 00208304 2000B1DF */  ld         $s1, 0x20($sp)
    /* 9308 00208308 1000B0DF */  ld         $s0, 0x10($sp)
    /* 930C 0020830C 0800E003 */  jr         $ra
    /* 9310 00208310 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel handle_get_vidmode
