.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching iopbtconf_modify_code, 0x1C0

glabel iopbtconf_modify_code
    /* 93BF0 00292BF0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 93BF4 00292BF4 5345023C */  lui        $v0, (0x45534552 >> 16)
    /* 93BF8 00292BF8 2000B2FF */  sd         $s2, 0x20($sp)
    /* 93BFC 00292BFC 52454234 */  ori        $v0, $v0, (0x45534552 & 0xFFFF)
    /* 93C00 00292C00 3000BFFF */  sd         $ra, 0x30($sp)
    /* 93C04 00292C04 1000B1FF */  sd         $s1, 0x10($sp)
    /* 93C08 00292C08 0000B0FF */  sd         $s0, 0x0($sp)
    /* 93C0C 00292C0C 0000A38C */  lw         $v1, 0x0($a1)
    /* 93C10 00292C10 0E006214 */  bne        $v1, $v0, .L00292C4C
    /* 93C14 00292C14 2D908000 */   daddu     $s2, $a0, $zero
    /* 93C18 00292C18 0400A38C */  lw         $v1, 0x4($a1)
    /* 93C1C 00292C1C 54000224 */  addiu      $v0, $zero, 0x54
    /* 93C20 00292C20 5D006214 */  bne        $v1, $v0, .L00292D98
    /* 93C24 00292C24 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 93C28 00292C28 4D44023C */  lui        $v0, (0x444D4F52 >> 16)
    /* 93C2C 00292C2C 1000A38C */  lw         $v1, 0x10($a1)
    /* 93C30 00292C30 524F4234 */  ori        $v0, $v0, (0x444D4F52 & 0xFFFF)
    /* 93C34 00292C34 58006214 */  bne        $v1, $v0, .L00292D98
    /* 93C38 00292C38 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 93C3C 00292C3C 1400A38C */  lw         $v1, 0x14($a1)
    /* 93C40 00292C40 49520224 */  addiu      $v0, $zero, 0x5249
    /* 93C44 00292C44 03006210 */  beq        $v1, $v0, .L00292C54
    /* 93C48 00292C48 5042073C */   lui       $a3, (0x42504F49 >> 16)
  .L00292C4C:
    /* 93C4C 00292C4C 52000010 */  b          .L00292D98
    /* 93C50 00292C50 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L00292C54:
    /* 93C54 00292C54 4F4E063C */  lui        $a2, (0x4E4F4354 >> 16)
    /* 93C58 00292C58 2D180000 */  daddu      $v1, $zero, $zero
    /* 93C5C 00292C5C 494FE734 */  ori        $a3, $a3, (0x42504F49 & 0xFFFF)
    /* 93C60 00292C60 5443C634 */  ori        $a2, $a2, (0x4E4F4354 & 0xFFFF)
    /* 93C64 00292C64 46000A24 */  addiu      $t2, $zero, 0x46
    /* 93C68 00292C68 58000B24 */  addiu      $t3, $zero, 0x58
    /* 93C6C 00292C6C 3700093C */  lui        $t1, %hi(aReset_1)
    /* 93C70 00292C70 F0FF0824 */  addiu      $t0, $zero, -0x10
    /* 93C74 00292C74 2D20A000 */  daddu      $a0, $a1, $zero
  .L00292C78:
    /* 93C78 00292C78 00008290 */  lbu        $v0, 0x0($a0)
    /* 93C7C 00292C7C 46004010 */  beqz       $v0, .L00292D98
    /* 93C80 00292C80 2D100000 */   daddu     $v0, $zero, $zero
    /* 93C84 00292C84 0000828C */  lw         $v0, 0x0($a0)
    /* 93C88 00292C88 12004714 */  bne        $v0, $a3, .L00292CD4
    /* 93C8C 00292C8C 0C00908C */   lw        $s0, 0xC($a0)
    /* 93C90 00292C90 0400828C */  lw         $v0, 0x4($a0)
    /* 93C94 00292C94 10004614 */  bne        $v0, $a2, .L00292CD8
    /* 93C98 00292C98 0F000226 */   addiu     $v0, $s0, 0xF
    /* 93C9C 00292C9C 08008294 */  lhu        $v0, 0x8($a0)
    /* 93CA0 00292CA0 0D004A14 */  bne        $v0, $t2, .L00292CD8
    /* 93CA4 00292CA4 0F000226 */   addiu     $v0, $s0, 0xF
    /* 93CA8 00292CA8 A8D82725 */  addiu      $a3, $t1, %lo(aReset_1)
    /* 93CAC 00292CAC 00008BA0 */  sb         $t3, 0x0($a0)
    /* 93CB0 00292CB0 25104702 */  or         $v0, $s2, $a3
    /* 93CB4 00292CB4 07004230 */  andi       $v0, $v0, 0x7
    /* 93CB8 00292CB8 22004010 */  beqz       $v0, .L00292D44
    /* 93CBC 00292CBC 2D304002 */   daddu     $a2, $s2, $zero
    /* 93CC0 00292CC0 2128A300 */  addu       $a1, $a1, $v1
    /* 93CC4 00292CC4 6000E224 */  addiu      $v0, $a3, 0x60
    /* 93CC8 00292CC8 60004426 */  addiu      $a0, $s2, 0x60
    /* 93CCC 00292CCC 06000010 */  b          .L00292CE8
    /* 93CD0 00292CD0 60001126 */   addiu     $s1, $s0, 0x60
  .L00292CD4:
    /* 93CD4 00292CD4 0F000226 */  addiu      $v0, $s0, 0xF
  .L00292CD8:
    /* 93CD8 00292CD8 10008424 */  addiu      $a0, $a0, 0x10
    /* 93CDC 00292CDC 24104800 */  and        $v0, $v0, $t0
    /* 93CE0 00292CE0 E5FF0010 */  b          .L00292C78
    /* 93CE4 00292CE4 21186200 */   addu      $v1, $v1, $v0
  .L00292CE8:
    /* 93CE8 00292CE8 0700E368 */  ldl        $v1, 0x7($a3)
    /* 93CEC 00292CEC 0000E36C */  ldr        $v1, 0x0($a3)
    /* 93CF0 00292CF0 0F00E868 */  ldl        $t0, 0xF($a3)
    /* 93CF4 00292CF4 0800E86C */  ldr        $t0, 0x8($a3)
    /* 93CF8 00292CF8 1700E968 */  ldl        $t1, 0x17($a3)
    /* 93CFC 00292CFC 1000E96C */  ldr        $t1, 0x10($a3)
    /* 93D00 00292D00 1F00EA68 */  ldl        $t2, 0x1F($a3)
    /* 93D04 00292D04 1800EA6C */  ldr        $t2, 0x18($a3)
    /* 93D08 00292D08 0700C3B0 */  sdl        $v1, 0x7($a2)
    /* 93D0C 00292D0C 0000C3B4 */  sdr        $v1, 0x0($a2)
    /* 93D10 00292D10 0F00C8B0 */  sdl        $t0, 0xF($a2)
    /* 93D14 00292D14 0800C8B4 */  sdr        $t0, 0x8($a2)
    /* 93D18 00292D18 1700C9B0 */  sdl        $t1, 0x17($a2)
    /* 93D1C 00292D1C 1000C9B4 */  sdr        $t1, 0x10($a2)
    /* 93D20 00292D20 1F00CAB0 */  sdl        $t2, 0x1F($a2)
    /* 93D24 00292D24 1800CAB4 */  sdr        $t2, 0x18($a2)
    /* 93D28 00292D28 2000E724 */  addiu      $a3, $a3, 0x20
    /* 93D2C 00292D2C 2000C624 */  addiu      $a2, $a2, 0x20
    /* 93D30 00292D30 00000000 */  nop
    /* 93D34 00292D34 ECFFE214 */  bne        $a3, $v0, .L00292CE8
    /* 93D38 00292D38 00000000 */   nop
    /* 93D3C 00292D3C 12000010 */  b          .L00292D88
    /* 93D40 00292D40 00000000 */   nop
  .L00292D44:
    /* 93D44 00292D44 2128A300 */  addu       $a1, $a1, $v1
    /* 93D48 00292D48 6000E224 */  addiu      $v0, $a3, 0x60
    /* 93D4C 00292D4C 60004426 */  addiu      $a0, $s2, 0x60
    /* 93D50 00292D50 60001126 */  addiu      $s1, $s0, 0x60
  .L00292D54:
    /* 93D54 00292D54 0000E3DC */  ld         $v1, 0x0($a3)
    /* 93D58 00292D58 0800E8DC */  ld         $t0, 0x8($a3)
    /* 93D5C 00292D5C 1000E9DC */  ld         $t1, 0x10($a3)
    /* 93D60 00292D60 1800EADC */  ld         $t2, 0x18($a3)
    /* 93D64 00292D64 0000C3FC */  sd         $v1, 0x0($a2)
    /* 93D68 00292D68 0800C8FC */  sd         $t0, 0x8($a2)
    /* 93D6C 00292D6C 1000C9FC */  sd         $t1, 0x10($a2)
    /* 93D70 00292D70 1800CAFC */  sd         $t2, 0x18($a2)
    /* 93D74 00292D74 2000E724 */  addiu      $a3, $a3, 0x20
    /* 93D78 00292D78 2000C624 */  addiu      $a2, $a2, 0x20
    /* 93D7C 00292D7C 00000000 */  nop
    /* 93D80 00292D80 F4FFE214 */  bne        $a3, $v0, .L00292D54
    /* 93D84 00292D84 00000000 */   nop
  .L00292D88:
    /* 93D88 00292D88 F1700A0C */  jal        memcpy
    /* 93D8C 00292D8C 2D300002 */   daddu     $a2, $s0, $zero
    /* 93D90 00292D90 3C0050AE */  sw         $s0, 0x3C($s2)
    /* 93D94 00292D94 2D102002 */  daddu      $v0, $s1, $zero
  .L00292D98:
    /* 93D98 00292D98 3000BFDF */  ld         $ra, 0x30($sp)
    /* 93D9C 00292D9C 2000B2DF */  ld         $s2, 0x20($sp)
    /* 93DA0 00292DA0 1000B1DF */  ld         $s1, 0x10($sp)
    /* 93DA4 00292DA4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 93DA8 00292DA8 0800E003 */  jr         $ra
    /* 93DAC 00292DAC 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel iopbtconf_modify_code
