.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching lseek, 0x8

glabel lseek
    /* 80E58 0027FE58 0800E003 */  jr         $ra
    /* 80E5C 0027FE5C FFFF0224 */   addiu     $v0, $zero, -0x1
endlabel lseek
