.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching mcHearAlarm, 0x24

glabel mcHearAlarm
    /* 8F1C0 0028E1C0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 8F1C4 0028E1C4 0000BFFF */  sd         $ra, 0x0($sp)
    /* 8F1C8 0028E1C8 D0010A0C */  jal        iWakeupThread
    /* 8F1CC 0028E1CC 2D20C000 */   daddu     $a0, $a2, $zero
    /* 8F1D0 0028E1D0 0F000000 */  sync
    /* 8F1D4 0028E1D4 38000042 */  ei /* handwritten instruction */
    /* 8F1D8 0028E1D8 0000BFDF */  ld         $ra, 0x0($sp)
    /* 8F1DC 0028E1DC 0800E003 */  jr         $ra
    /* 8F1E0 0028E1E0 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel mcHearAlarm
