.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching nullsub_14, 0x8

glabel nullsub_14
    /* 2DC48 0022CC48 0800E003 */  jr         $ra
    /* 2DC4C 0022CC4C 00000000 */   nop
endlabel nullsub_14
