.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching nullsub_11, 0x8

glabel nullsub_11
    /* 29740 00228740 0800E003 */  jr         $ra
    /* 29744 00228744 00000000 */   nop
endlabel nullsub_11
