.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching return_to_browser, 0x50

glabel return_to_browser
    /* 2A00 00201A00 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2A04 00201A04 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2A08 00201A08 2D808000 */  daddu      $s0, $a0, $zero
    /* 2A0C 00201A0C 1000BFFF */  sd         $ra, 0x10($sp)
    /* 2A10 00201A10 3400043C */  lui        $a0, %hi(D_00347860)
    /* 2A14 00201A14 BC050A0C */  jal        kprintf
    /* 2A18 00201A18 60788424 */   addiu     $a0, $a0, %lo(D_00347860)
    /* 2A1C 00201A1C 03000012 */  beqz       $s0, .L00201A2C
    /* 2A20 00201A20 00000000 */   nop
    /* 2A24 00201A24 6C06080C */  jal        deinit_2019B0
    /* 2A28 00201A28 01000424 */   addiu     $a0, $zero, 0x1
  .L00201A2C:
    /* 2A2C 00201A2C A0060A0C */  jal        sceSifExitCmd
    /* 2A30 00201A30 00000000 */   nop
    /* 2A34 00201A34 3400053C */  lui        $a1, %hi(bootbrowser_ptr)
    /* 2A38 00201A38 1000BFDF */  ld         $ra, 0x10($sp)
    /* 2A3C 00201A3C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2A40 00201A40 01000424 */  addiu      $a0, $zero, 0x1
    /* 2A44 00201A44 4878A524 */  addiu      $a1, $a1, %lo(bootbrowser_ptr)
    /* 2A48 00201A48 3A1F0A08 */  j          ExecOSD
    /* 2A4C 00201A4C 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel return_to_browser
