.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching Rm2GetConnectionStateString, 0x34

glabel Rm2GetConnectionStateString
    /* 954A0 002944A0 0400822C */  sltiu      $v0, $a0, 0x4
    /* 954A4 002944A4 08004010 */  beqz       $v0, .L002944C8
    /* 954A8 002944A8 3700023C */   lui       $v0, %hi(D_0036E350)
    /* 954AC 002944AC 3400023C */  lui        $v0, %hi(rm2_connection_state_str_tbl)
    /* 954B0 002944B0 80180400 */  sll        $v1, $a0, 2
    /* 954B4 002944B4 30704224 */  addiu      $v0, $v0, %lo(rm2_connection_state_str_tbl)
    /* 954B8 002944B8 2D20A000 */  daddu      $a0, $a1, $zero
    /* 954BC 002944BC 21186200 */  addu       $v1, $v1, $v0
    /* 954C0 002944C0 64740A08 */  j          strcpy
    /* 954C4 002944C4 0000658C */   lw        $a1, 0x0($v1)
  .L002944C8:
    /* 954C8 002944C8 50E34390 */  lbu        $v1, %lo(D_0036E350)($v0)
    /* 954CC 002944CC 0800E003 */  jr         $ra
    /* 954D0 002944D0 0000A3A0 */   sb        $v1, 0x0($a1)
endlabel Rm2GetConnectionStateString
