.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceCdApplyNCmd, 0x210

glabel sceCdApplyNCmd
    /* 8CE50 0028BE50 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 8CE54 0028BE54 3300033C */  lui        $v1, %hi(_sceCd_ncmd_semid)
    /* 8CE58 0028BE58 1800B1FF */  sd         $s1, 0x18($sp)
    /* 8CE5C 0028BE5C 28E26224 */  addiu      $v0, $v1, %lo(_sceCd_ncmd_semid)
    /* 8CE60 0028BE60 2000B2FF */  sd         $s2, 0x20($sp)
    /* 8CE64 0028BE64 3300123C */  lui        $s2, %hi(SCE_CD_debug)
    /* 8CE68 0028BE68 3000B4FF */  sd         $s4, 0x30($sp)
    /* 8CE6C 0028BE6C 2DA0C000 */  daddu      $s4, $a2, $zero
    /* 8CE70 0028BE70 4800B7FF */  sd         $s7, 0x48($sp)
    /* 8CE74 0028BE74 2DB8A000 */  daddu      $s7, $a1, $zero
    /* 8CE78 0028BE78 5000BEFF */  sd         $fp, 0x50($sp)
    /* 8CE7C 0028BE7C FF009E30 */  andi       $fp, $a0, 0xFF
    /* 8CE80 0028BE80 1000B0FF */  sd         $s0, 0x10($sp)
    /* 8CE84 0028BE84 3300033C */  lui        $v1, %hi(D_0032E300)
    /* 8CE88 0028BE88 2800B3FF */  sd         $s3, 0x28($sp)
    /* 8CE8C 0028BE8C 00E37124 */  addiu      $s1, $v1, %lo(D_0032E300)
    /* 8CE90 0028BE90 3800B5FF */  sd         $s5, 0x38($sp)
    /* 8CE94 0028BE94 4000B6FF */  sd         $s6, 0x40($sp)
    /* 8CE98 0028BE98 5800BFFF */  sd         $ra, 0x58($sp)
    /* 8CE9C 0028BE9C C4FE090C */  jal        WaitSema
    /* 8CEA0 0028BEA0 0000448C */   lw        $a0, 0x0($v0)
    /* 8CEA4 0028BEA4 3300033C */  lui        $v1, %hi(D_0032E21C)
    /* 8CEA8 0028BEA8 0E000224 */  addiu      $v0, $zero, 0xE
    /* 8CEAC 0028BEAC 2D200000 */  daddu      $a0, $zero, $zero
    /* 8CEB0 0028BEB0 E82C0A0C */  jal        sceCdSync
    /* 8CEB4 0028BEB4 1CE262AC */   sw        $v0, %lo(D_0032E21C)($v1)
    /* 8CEB8 0028BEB8 10E2438E */  lw         $v1, %lo(SCE_CD_debug)($s2)
    /* 8CEBC 0028BEBC 05006058 */  blezl      $v1, .L0028BED4
    /* 8CEC0 0028BEC0 2D200000 */   daddu     $a0, $zero, $zero
    /* 8CEC4 0028BEC4 3700043C */  lui        $a0, %hi(aApplyNCmd0)
    /* 8CEC8 0028BEC8 CA050A0C */  jal        scePrintf
    /* 8CECC 0028BECC E8D68424 */   addiu     $a0, $a0, %lo(aApplyNCmd0)
    /* 8CED0 0028BED0 2D200000 */  daddu      $a0, $zero, $zero
  .L0028BED4:
    /* 8CED4 0028BED4 B4070A0C */  jal        sceSifInitRpc
    /* 8CED8 0028BED8 3300153C */   lui       $s5, %hi(D_0032E238)
    /* 8CEDC 0028BEDC 38E2A28E */  lw         $v0, %lo(D_0032E238)($s5)
    /* 8CEE0 0028BEE0 2D004104 */  bgez       $v0, .L0028BF98
    /* 8CEE4 0028BEE4 3300163C */   lui       $s6, %hi(_sceCd_cd_ncmd)
    /* 8CEE8 0028BEE8 3700133C */  lui        $s3, %hi(aLibcdvdBindErr_4)
    /* 8CEEC 0028BEEC D0F3D026 */  addiu      $s0, $s6, %lo(_sceCd_cd_ncmd)
  .L0028BEF0:
    /* 8CEF0 0028BEF0 0080053C */  lui        $a1, (0x80000595 >> 16)
    /* 8CEF4 0028BEF4 2D200002 */  daddu      $a0, $s0, $zero
    /* 8CEF8 0028BEF8 9505A534 */  ori        $a1, $a1, (0x80000595 & 0xFFFF)
    /* 8CEFC 0028BEFC 50090A0C */  jal        sceSifBindRpc
    /* 8CF00 0028BF00 2D300000 */   daddu     $a2, $zero, $zero
    /* 8CF04 0028BF04 14004304 */  bgezl      $v0, .L0028BF58
    /* 8CF08 0028BF08 2400028E */   lw        $v0, 0x24($s0)
    /* 8CF0C 0028BF0C 10E2428E */  lw         $v0, %lo(SCE_CD_debug)($s2)
    /* 8CF10 0028BF10 04004018 */  blez       $v0, .L0028BF24
    /* 8CF14 0028BF14 0F00033C */   lui       $v1, (0xFFFFF >> 16)
    /* 8CF18 0028BF18 CA050A0C */  jal        scePrintf
    /* 8CF1C 0028BF1C F8D66426 */   addiu     $a0, $s3, %lo(aLibcdvdBindErr_4)
    /* 8CF20 0028BF20 0F00033C */  lui        $v1, (0xFFFFF >> 16)
  .L0028BF24:
    /* 8CF24 0028BF24 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 8CF28 0028BF28 FFFF6334 */  ori        $v1, $v1, (0xFFFFF & 0xFFFF)
    /* 8CF2C 0028BF2C FCFF6324 */  addiu      $v1, $v1, -0x4
  .L0028BF30:
    /* 8CF30 0028BF30 00000000 */  nop
    /* 8CF34 0028BF34 00000000 */  nop
    /* 8CF38 0028BF38 00000000 */  nop
    /* 8CF3C 0028BF3C 00000000 */  nop
    /* 8CF40 0028BF40 00000000 */  nop
    /* 8CF44 0028BF44 FAFF6254 */  bnel       $v1, $v0, .L0028BF30
    /* 8CF48 0028BF48 FCFF6324 */   addiu     $v1, $v1, -0x4
    /* 8CF4C 0028BF4C E8FF0010 */  b          .L0028BEF0
    /* 8CF50 0028BF50 00000000 */   nop
    /* 8CF54 0028BF54 00000000 */  nop
  .L0028BF58:
    /* 8CF58 0028BF58 0F00033C */  lui        $v1, (0xFFFFF >> 16)
    /* 8CF5C 0028BF5C FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 8CF60 0028BF60 03004010 */  beqz       $v0, .L0028BF70
    /* 8CF64 0028BF64 FFFF6334 */   ori       $v1, $v1, (0xFFFFF & 0xFFFF)
    /* 8CF68 0028BF68 0B000010 */  b          .L0028BF98
    /* 8CF6C 0028BF6C 38E2A0AE */   sw        $zero, %lo(D_0032E238)($s5)
  .L0028BF70:
    /* 8CF70 0028BF70 FCFF6324 */  addiu      $v1, $v1, -0x4
  .L0028BF74:
    /* 8CF74 0028BF74 00000000 */  nop
    /* 8CF78 0028BF78 00000000 */  nop
    /* 8CF7C 0028BF7C 00000000 */  nop
    /* 8CF80 0028BF80 00000000 */  nop
    /* 8CF84 0028BF84 00000000 */  nop
    /* 8CF88 0028BF88 FAFF6454 */  bnel       $v1, $a0, .L0028BF74
    /* 8CF8C 0028BF8C FCFF6324 */   addiu     $v1, $v1, -0x4
    /* 8CF90 0028BF90 D7FF0010 */  b          .L0028BEF0
    /* 8CF94 0028BF94 00000000 */   nop
  .L0028BF98:
    /* 8CF98 0028BF98 2D28E002 */  daddu      $a1, $s7, $zero
    /* 8CF9C 0028BF9C 2D308002 */  daddu      $a2, $s4, $zero
    /* 8CFA0 0028BFA0 04002426 */  addiu      $a0, $s1, 0x4
    /* 8CFA4 0028BFA4 00003EA6 */  sh         $fp, 0x0($s1)
    /* 8CFA8 0028BFA8 F1700A0C */  jal        memcpy
    /* 8CFAC 0028BFAC 020034A6 */   sh        $s4, 0x2($s1)
    /* 8CFB0 0028BFB0 10E2438E */  lw         $v1, %lo(SCE_CD_debug)($s2)
    /* 8CFB4 0028BFB4 05006058 */  blezl      $v1, .L0028BFCC
    /* 8CFB8 0028BFB8 2D202002 */   daddu     $a0, $s1, $zero
    /* 8CFBC 0028BFBC 3700043C */  lui        $a0, %hi(aApplyNCmd1)
    /* 8CFC0 0028BFC0 CA050A0C */  jal        scePrintf
    /* 8CFC4 0028BFC4 10D78424 */   addiu     $a0, $a0, %lo(aApplyNCmd1)
    /* 8CFC8 0028BFC8 2D202002 */  daddu      $a0, $s1, $zero
  .L0028BFCC:
    /* 8CFCC 0028BFCC 88070A0C */  jal        sceSifWriteBackDCache
    /* 8CFD0 0028BFD0 84000524 */   addiu     $a1, $zero, 0x84
    /* 8CFD4 0028BFD4 3300103C */  lui        $s0, %hi(D_0032E280)
  .L0028BFD8:
    /* 8CFD8 0028BFD8 D0F3C426 */  addiu      $a0, $s6, %lo(_sceCd_cd_ncmd)
    /* 8CFDC 0028BFDC 0C000524 */  addiu      $a1, $zero, 0xC
    /* 8CFE0 0028BFE0 2D300000 */  daddu      $a2, $zero, $zero
    /* 8CFE4 0028BFE4 2D382002 */  daddu      $a3, $s1, $zero
    /* 8CFE8 0028BFE8 84000824 */  addiu      $t0, $zero, 0x84
    /* 8CFEC 0028BFEC 80E20926 */  addiu      $t1, $s0, %lo(D_0032E280)
    /* 8CFF0 0028BFF0 04000A24 */  addiu      $t2, $zero, 0x4
    /* 8CFF4 0028BFF4 2D580000 */  daddu      $t3, $zero, $zero
    /* 8CFF8 0028BFF8 C4090A0C */  jal        sceSifCallRpc
    /* 8CFFC 0028BFFC 0000A0AF */   sw        $zero, 0x0($sp)
    /* 8D000 0028C000 F5FF4004 */  bltz       $v0, .L0028BFD8
    /* 8D004 0028C004 10E2428E */   lw        $v0, %lo(SCE_CD_debug)($s2)
    /* 8D008 0028C008 05004018 */  blez       $v0, .L0028C020
    /* 8D00C 0028C00C 3300033C */   lui       $v1, %hi(_sceCd_ncmd_semid)
    /* 8D010 0028C010 3700043C */  lui        $a0, %hi(aApplyNCmd2)
    /* 8D014 0028C014 CA050A0C */  jal        scePrintf
    /* 8D018 0028C018 20D78424 */   addiu     $a0, $a0, %lo(aApplyNCmd2)
    /* 8D01C 0028C01C 3300033C */  lui        $v1, %hi(_sceCd_ncmd_semid)
  .L0028C020:
    /* 8D020 0028C020 28E26224 */  addiu      $v0, $v1, %lo(_sceCd_ncmd_semid)
    /* 8D024 0028C024 BCFE090C */  jal        SignalSema
    /* 8D028 0028C028 0000448C */   lw        $a0, 0x0($v0)
    /* 8D02C 0028C02C 01000224 */  addiu      $v0, $zero, 0x1
    /* 8D030 0028C030 1000B0DF */  ld         $s0, 0x10($sp)
    /* 8D034 0028C034 1800B1DF */  ld         $s1, 0x18($sp)
    /* 8D038 0028C038 2000B2DF */  ld         $s2, 0x20($sp)
    /* 8D03C 0028C03C 2800B3DF */  ld         $s3, 0x28($sp)
    /* 8D040 0028C040 3000B4DF */  ld         $s4, 0x30($sp)
    /* 8D044 0028C044 3800B5DF */  ld         $s5, 0x38($sp)
    /* 8D048 0028C048 4000B6DF */  ld         $s6, 0x40($sp)
    /* 8D04C 0028C04C 4800B7DF */  ld         $s7, 0x48($sp)
    /* 8D050 0028C050 5000BEDF */  ld         $fp, 0x50($sp)
    /* 8D054 0028C054 5800BFDF */  ld         $ra, 0x58($sp)
    /* 8D058 0028C058 0800E003 */  jr         $ra
    /* 8D05C 0028C05C 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel sceCdApplyNCmd
