.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceCdGetError, 0xA8

glabel sceCdGetError
    /* 8D658 0028C658 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 8D65C 0028C65C 1000B0FF */  sd         $s0, 0x10($sp)
    /* 8D660 0028C660 1800BFFF */  sd         $ra, 0x18($sp)
    /* 8D664 0028C664 342D0A0C */  jal        _sceCd_scmd_prechk
    /* 8D668 0028C668 03000424 */   addiu     $a0, $zero, 0x3
    /* 8D66C 0028C66C 3300033C */  lui        $v1, %hi(_sceCd_scmdrdata)
    /* 8D670 0028C670 3300043C */  lui        $a0, %hi(_sceCd_cd_scmd)
    /* 8D674 0028C674 00F47024 */  addiu      $s0, $v1, %lo(_sceCd_scmdrdata)
    /* 8D678 0028C678 48FC8424 */  addiu      $a0, $a0, %lo(_sceCd_cd_scmd)
    /* 8D67C 0028C67C 04000524 */  addiu      $a1, $zero, 0x4
    /* 8D680 0028C680 2D300000 */  daddu      $a2, $zero, $zero
    /* 8D684 0028C684 2D380000 */  daddu      $a3, $zero, $zero
    /* 8D688 0028C688 2D400000 */  daddu      $t0, $zero, $zero
    /* 8D68C 0028C68C 2D480002 */  daddu      $t1, $s0, $zero
    /* 8D690 0028C690 04000A24 */  addiu      $t2, $zero, 0x4
    /* 8D694 0028C694 04004014 */  bnez       $v0, .L0028C6A8
    /* 8D698 0028C698 2D580000 */   daddu     $t3, $zero, $zero
    /* 8D69C 0028C69C 14000010 */  b          .L0028C6F0
    /* 8D6A0 0028C6A0 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 8D6A4 0028C6A4 00000000 */  nop
  .L0028C6A8:
    /* 8D6A8 0028C6A8 C4090A0C */  jal        sceSifCallRpc
    /* 8D6AC 0028C6AC 0000A0AF */   sw        $zero, 0x0($sp)
    /* 8D6B0 0028C6B0 3300043C */  lui        $a0, %hi(_sceCd_scmd_semid)
    /* 8D6B4 0028C6B4 0020033C */  lui        $v1, (0x20000000 >> 16)
    /* 8D6B8 0028C6B8 2CE28624 */  addiu      $a2, $a0, %lo(_sceCd_scmd_semid)
    /* 8D6BC 0028C6BC 25180302 */  or         $v1, $s0, $v1
    /* 8D6C0 0028C6C0 07004104 */  bgez       $v0, .L0028C6E0
    /* 8D6C4 0028C6C4 2D20C000 */   daddu     $a0, $a2, $zero
    /* 8D6C8 0028C6C8 0000C48C */  lw         $a0, 0x0($a2)
    /* 8D6CC 0028C6CC BCFE090C */  jal        SignalSema
    /* 8D6D0 0028C6D0 00000000 */   nop
    /* 8D6D4 0028C6D4 06000010 */  b          .L0028C6F0
    /* 8D6D8 0028C6D8 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 8D6DC 0028C6DC 00000000 */  nop
  .L0028C6E0:
    /* 8D6E0 0028C6E0 0000708C */  lw         $s0, (0x20000000 & 0xFFFF)($v1)
    /* 8D6E4 0028C6E4 BCFE090C */  jal        SignalSema
    /* 8D6E8 0028C6E8 0000848C */   lw        $a0, 0x0($a0)
    /* 8D6EC 0028C6EC 2D100002 */  daddu      $v0, $s0, $zero
  .L0028C6F0:
    /* 8D6F0 0028C6F0 1000B0DF */  ld         $s0, 0x10($sp)
    /* 8D6F4 0028C6F4 1800BFDF */  ld         $ra, 0x18($sp)
    /* 8D6F8 0028C6F8 0800E003 */  jr         $ra
    /* 8D6FC 0028C6FC 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel sceCdGetError
