.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceChdir, 0x1C

glabel sceChdir
    /* 86868 00285868 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 8686C 0028586C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 86870 00285870 F2110A0C */  jal        _sceCallCode
    /* 86874 00285874 12000524 */   addiu     $a1, $zero, 0x12
    /* 86878 00285878 0000BFDF */  ld         $ra, 0x0($sp)
    /* 8687C 0028587C 0800E003 */  jr         $ra
    /* 86880 00285880 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel sceChdir
