.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceCcc_unused3, 0x1C

glabel sceCcc_unused3
    /* 91388 00290388 AC200224 */  addiu      $v0, $zero, 0x20AC
    /* 9138C 0029038C 03008210 */  beq        $a0, $v0, .L0029039C
    /* 91390 00290390 80000224 */   addiu     $v0, $zero, 0x80
    /* 91394 00290394 0800E003 */  jr         $ra
    /* 91398 00290398 FF008230 */   andi      $v0, $a0, 0xFF
  .L0029039C:
    /* 9139C 0029039C 0800E003 */  jr         $ra
    /* 913A0 002903A0 00000000 */   nop
endlabel sceCcc_unused3
