.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceCccSetErrorCharUTF16, 0x10

glabel sceCccSetErrorCharUTF16
    /* 914C0 002904C0 3300033C */  lui        $v1, %hi(__error_char_utf16__)
    /* 914C4 002904C4 90FC628C */  lw         $v0, %lo(__error_char_utf16__)($v1)
    /* 914C8 002904C8 0800E003 */  jr         $ra
    /* 914CC 002904CC 90FC64AC */   sw        $a0, %lo(__error_char_utf16__)($v1)
endlabel sceCccSetErrorCharUTF16
