.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceCdIntToPos, 0xC4

glabel sceCdIntToPos
    /* 8D060 0028C060 4B000224 */  addiu      $v0, $zero, 0x4B
    /* 8D064 0028C064 96008424 */  addiu      $a0, $a0, 0x96
    /* 8D068 0028C068 1A008200 */  div        $zero, $a0, $v0
    /* 8D06C 0028C06C 3C000924 */  addiu      $t1, $zero, 0x3C
    /* 8D070 0028C070 0A000624 */  addiu      $a2, $zero, 0xA
    /* 8D074 0028C074 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 8D078 0028C078 4B000324 */  addiu      $v1, $zero, 0x4B
    /* 8D07C 0028C07C 0A000824 */  addiu      $t0, $zero, 0xA
    /* 8D080 0028C080 0000B0FF */  sd         $s0, 0x0($sp)
    /* 8D084 0028C084 3C001024 */  addiu      $s0, $zero, 0x3C
    /* 8D088 0028C088 0800B1FF */  sd         $s1, 0x8($sp)
    /* 8D08C 0028C08C 0A001124 */  addiu      $s1, $zero, 0xA
    /* 8D090 0028C090 1000B2FF */  sd         $s2, 0x10($sp)
    /* 8D094 0028C094 0A001224 */  addiu      $s2, $zero, 0xA
    /* 8D098 0028C098 01004050 */  beql       $v0, $zero, .L0028C0A0
    /* 8D09C 0028C09C CD010000 */   break     0, 7
  .L0028C0A0:
    /* 8D0A0 0028C0A0 2D10A000 */  daddu      $v0, $a1, $zero
    /* 8D0A4 0028C0A4 4B000C24 */  addiu      $t4, $zero, 0x4B
    /* 8D0A8 0028C0A8 0A000D24 */  addiu      $t5, $zero, 0xA
    /* 8D0AC 0028C0AC 3C000E24 */  addiu      $t6, $zero, 0x3C
    /* 8D0B0 0028C0B0 0A000F24 */  addiu      $t7, $zero, 0xA
    /* 8D0B4 0028C0B4 12200000 */  mflo       $a0
    /* 8D0B8 0028C0B8 10500000 */  mfhi       $t2
    /* 8D0BC 0028C0BC 1A008900 */  div        $zero, $a0, $t1
    /* 8D0C0 0028C0C0 12200000 */  mflo       $a0
    /* 8D0C4 0028C0C4 10380000 */  mfhi       $a3
    /* 8D0C8 0028C0C8 1A004601 */  div        $zero, $t2, $a2
    /* 8D0CC 0028C0CC 10400000 */  mfhi       $t0
    /* 8D0D0 0028C0D0 12180000 */  mflo       $v1
    /* 8D0D4 0028C0D4 1A008600 */  div        $zero, $a0, $a2
    /* 8D0D8 0028C0D8 00190300 */  sll        $v1, $v1, 4
    /* 8D0DC 0028C0DC 21186800 */  addu       $v1, $v1, $t0
    /* 8D0E0 0028C0E0 0200A3A0 */  sb         $v1, 0x2($a1)
    /* 8D0E4 0028C0E4 10580000 */  mfhi       $t3
    /* 8D0E8 0028C0E8 12200000 */  mflo       $a0
    /* 8D0EC 0028C0EC 1A00E600 */  div        $zero, $a3, $a2
    /* 8D0F0 0028C0F0 00210400 */  sll        $a0, $a0, 4
    /* 8D0F4 0028C0F4 21208B00 */  addu       $a0, $a0, $t3
    /* 8D0F8 0028C0F8 12300000 */  mflo       $a2
    /* 8D0FC 0028C0FC 10500000 */  mfhi       $t2
    /* 8D100 0028C100 00310600 */  sll        $a2, $a2, 4
    /* 8D104 0028C104 2130CA00 */  addu       $a2, $a2, $t2
    /* 8D108 0028C108 0100A6A0 */  sb         $a2, 0x1($a1)
    /* 8D10C 0028C10C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 8D110 0028C110 0800B1DF */  ld         $s1, 0x8($sp)
    /* 8D114 0028C114 1000B2DF */  ld         $s2, 0x10($sp)
    /* 8D118 0028C118 0000A4A0 */  sb         $a0, 0x0($a1)
    /* 8D11C 0028C11C 0800E003 */  jr         $ra
    /* 8D120 0028C120 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel sceCdIntToPos
