.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceDmaRecvI, 0xF0

glabel sceDmaRecvI
    /* 7D348 0027C348 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 7D34C 0027C34C 4000B4FF */  sd         $s4, 0x40($sp)
    /* 7D350 0027C350 3000B3FF */  sd         $s3, 0x30($sp)
    /* 7D354 0027C354 2DA0C000 */  daddu      $s4, $a2, $zero
    /* 7D358 0027C358 1000B1FF */  sd         $s1, 0x10($sp)
    /* 7D35C 0027C35C 2D98A000 */  daddu      $s3, $a1, $zero
    /* 7D360 0027C360 0000B0FF */  sd         $s0, 0x0($sp)
    /* 7D364 0027C364 0001113C */  lui        $s1, %hi(D_FFFFFF)
    /* 7D368 0027C368 5000BFFF */  sd         $ra, 0x50($sp)
    /* 7D36C 0027C36C 2D808000 */  daddu      $s0, $a0, $zero
    /* 7D370 0027C370 2000B2FF */  sd         $s2, 0x20($sp)
    /* 7D374 0027C374 0000028E */  lw         $v0, 0x0($s0)
    /* 7D378 0027C378 00014230 */  andi       $v0, $v0, 0x100
    /* 7D37C 0027C37C 18004010 */  beqz       $v0, .L0027C3E0
    /* 7D380 0027C380 3700123C */   lui       $s2, %hi(aLibdmaSyncTime)
    /* 7D384 0027C384 FFFF3126 */  addiu      $s1, $s1, %lo(D_FFFFFF)
  .L0027C388:
    /* 7D388 0027C388 11002106 */  bgez       $s1, .L0027C3D0
    /* 7D38C 0027C38C 00000000 */   nop
    /* 7D390 0027C390 A2710A0C */  jal        printf
    /* 7D394 0027C394 B0C94426 */   addiu     $a0, $s2, %lo(aLibdmaSyncTime)
    /* 7D398 0027C398 0000048E */  lw         $a0, 0x0($s0)
    /* 7D39C 0027C39C 02120400 */  srl        $v0, $a0, 8
    /* 7D3A0 0027C3A0 01004230 */  andi       $v0, $v0, 0x1
    /* 7D3A4 0027C3A4 0A004010 */  beqz       $v0, .L0027C3D0
    /* 7D3A8 0027C3A8 00000000 */   nop
    /* 7D3AC 0027C3AC FFFE0524 */  addiu      $a1, $zero, -0x101
  .L0027C3B0:
    /* 7D3B0 0027C3B0 24188500 */  and        $v1, $a0, $a1
    /* 7D3B4 0027C3B4 2D100000 */  daddu      $v0, $zero, $zero
    /* 7D3B8 0027C3B8 2D206000 */  daddu      $a0, $v1, $zero
    /* 7D3BC 0027C3BC 00000000 */  nop
    /* 7D3C0 0027C3C0 00000000 */  nop
    /* 7D3C4 0027C3C4 FAFF4014 */  bnez       $v0, .L0027C3B0
    /* 7D3C8 0027C3C8 00000000 */   nop
    /* 7D3CC 0027C3CC 000003AE */  sw         $v1, 0x0($s0)
  .L0027C3D0:
    /* 7D3D0 0027C3D0 0000028E */  lw         $v0, 0x0($s0)
    /* 7D3D4 0027C3D4 00014230 */  andi       $v0, $v0, 0x100
    /* 7D3D8 0027C3D8 EBFF4014 */  bnez       $v0, .L0027C388
    /* 7D3DC 0027C3DC FFFF3126 */   addiu     $s1, $s1, -0x1
  .L0027C3E0:
    /* 7D3E0 0027C3E0 FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 7D3E4 0027C3E4 1000038E */  lw         $v1, 0x10($s0)
    /* 7D3E8 0027C3E8 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 7D3EC 0027C3EC 01006254 */  bnel       $v1, $v0, .L0027C3F4
    /* 7D3F0 0027C3F0 100013AE */   sw        $s3, 0x10($s0)
  .L0027C3F4:
    /* 7D3F4 0027C3F4 0000028E */  lw         $v0, 0x0($s0)
    /* 7D3F8 0027C3F8 F3FF0324 */  addiu      $v1, $zero, -0xD
    /* 7D3FC 0027C3FC FEFF0424 */  addiu      $a0, $zero, -0x2
    /* 7D400 0027C400 200014AE */  sw         $s4, 0x20($s0)
    /* 7D404 0027C404 24104300 */  and        $v0, $v0, $v1
    /* 7D408 0027C408 5000BFDF */  ld         $ra, 0x50($sp)
    /* 7D40C 0027C40C 08004234 */  ori        $v0, $v0, 0x8
    /* 7D410 0027C410 4000B4DF */  ld         $s4, 0x40($sp)
    /* 7D414 0027C414 24104400 */  and        $v0, $v0, $a0
    /* 7D418 0027C418 3000B3DF */  ld         $s3, 0x30($sp)
    /* 7D41C 0027C41C 00014234 */  ori        $v0, $v0, 0x100
    /* 7D420 0027C420 2000B2DF */  ld         $s2, 0x20($sp)
    /* 7D424 0027C424 000002AE */  sw         $v0, 0x0($s0)
    /* 7D428 0027C428 1000B1DF */  ld         $s1, 0x10($sp)
    /* 7D42C 0027C42C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 7D430 0027C430 0800E003 */  jr         $ra
    /* 7D434 0027C434 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel sceDmaRecvI
