.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceDevVif0GetErr, 0x10

glabel sceDevVif0GetErr
    /* 7E340 0027D340 0010033C */  lui        $v1, (0x10003820 >> 16)
    /* 7E344 0027D344 20386334 */  ori        $v1, $v1, (0x10003820 & 0xFFFF)
    /* 7E348 0027D348 0800E003 */  jr         $ra
    /* 7E34C 0027D34C 0000628C */   lw        $v0, 0x0($v1)
endlabel sceDevVif0GetErr
