.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceDevGifPutP3msk, 0x68

glabel sceDevGifPutP3msk
    /* 7E080 0027D080 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 7E084 0027D084 0B008014 */  bnez       $a0, .L0027D0B4
    /* 7E088 0027D088 0000BFFF */   sd        $ra, 0x0($sp)
    /* 7E08C 0027D08C 1AF4090C */  jal        sceDevGifGetImtMode
    /* 7E090 0027D090 00000000 */   nop
    /* 7E094 0027D094 FFFF033C */  lui        $v1, (0xFFFFFFFE >> 16)
    /* 7E098 0027D098 0010043C */  lui        $a0, (0x10003010 >> 16)
    /* 7E09C 0027D09C FEFF6334 */  ori        $v1, $v1, (0xFFFFFFFE & 0xFFFF)
    /* 7E0A0 0027D0A0 10308434 */  ori        $a0, $a0, (0x10003010 & 0xFFFF)
    /* 7E0A4 0027D0A4 24104300 */  and        $v0, $v0, $v1
    /* 7E0A8 0027D0A8 000082AC */  sw         $v0, 0x0($a0)
    /* 7E0AC 0027D0AC 0B000010 */  b          .L0027D0DC
    /* 7E0B0 0027D0B0 0000BFDF */   ld        $ra, 0x0($sp)
  .L0027D0B4:
    /* 7E0B4 0027D0B4 01000224 */  addiu      $v0, $zero, 0x1
    /* 7E0B8 0027D0B8 09008214 */  bne        $a0, $v0, .L0027D0E0
    /* 7E0BC 0027D0BC 0000BFDF */   ld        $ra, 0x0($sp)
    /* 7E0C0 0027D0C0 1AF4090C */  jal        sceDevGifGetImtMode
    /* 7E0C4 0027D0C4 00000000 */   nop
    /* 7E0C8 0027D0C8 0010033C */  lui        $v1, (0x10003010 >> 16)
    /* 7E0CC 0027D0CC 01004234 */  ori        $v0, $v0, 0x1
    /* 7E0D0 0027D0D0 10306334 */  ori        $v1, $v1, (0x10003010 & 0xFFFF)
    /* 7E0D4 0027D0D4 000062AC */  sw         $v0, 0x0($v1)
    /* 7E0D8 0027D0D8 0000BFDF */  ld         $ra, 0x0($sp)
  .L0027D0DC:
    /* 7E0DC 0027D0DC 01000224 */  addiu      $v0, $zero, 0x1
  .L0027D0E0:
    /* 7E0E0 0027D0E0 0800E003 */  jr         $ra
    /* 7E0E4 0027D0E4 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel sceDevGifPutP3msk
