.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceDevVu1PutCnd, 0x148

glabel sceDevVu1PutCnd
    /* 7DE50 0027CE50 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 7DE54 0027CE54 3000B2FF */  sd         $s2, 0x30($sp)
    /* 7DE58 0027CE58 5000BFFF */  sd         $ra, 0x50($sp)
    /* 7DE5C 0027CE5C 2D908000 */  daddu      $s2, $a0, $zero
    /* 7DE60 0027CE60 4000B3FF */  sd         $s3, 0x40($sp)
    /* 7DE64 0027CE64 2000B1FF */  sd         $s1, 0x20($sp)
    /* 7DE68 0027CE68 90F2090C */  jal        sceVuCheckBusy
    /* 7DE6C 0027CE6C 1000B0FF */   sd        $s0, 0x10($sp)
    /* 7DE70 0027CE70 42004014 */  bnez       $v0, .L0027CF7C
    /* 7DE74 0027CE74 2D100000 */   daddu     $v0, $zero, $zero
    /* 7DE78 0027CE78 2D880000 */  daddu      $s1, $zero, $zero
    /* 7DE7C 0027CE7C 1C025326 */  addiu      $s3, $s2, 0x21C
    /* 7DE80 0027CE80 2D804002 */  daddu      $s0, $s2, $zero
    /* 7DE84 0027CE84 00000000 */  nop
  .L0027CE88:
    /* 7DE88 0027CE88 0000027A */  lq         $v0, 0x0($s0)
    /* 7DE8C 0027CE8C 00042426 */  addiu      $a0, $s1, 0x400
    /* 7DE90 0027CE90 FFFF8430 */  andi       $a0, $a0, 0xFFFF
    /* 7DE94 0027CE94 2D28A003 */  daddu      $a1, $sp, $zero
    /* 7DE98 0027CE98 0000A27F */  sq         $v0, 0x0($sp)
    /* 7DE9C 0027CE9C 9CF2090C */  jal        sceVu0MemWriteQ
    /* 7DEA0 0027CEA0 01003126 */   addiu     $s1, $s1, 0x1
    /* 7DEA4 0027CEA4 2000222E */  sltiu      $v0, $s1, 0x20
    /* 7DEA8 0027CEA8 F7FF4014 */  bnez       $v0, .L0027CE88
    /* 7DEAC 0027CEAC 10001026 */   addiu     $s0, $s0, 0x10
    /* 7DEB0 0027CEB0 0002429E */  lwu        $v0, 0x200($s2)
    /* 7DEB4 0027CEB4 A91C0070 */  por        $v1, $zero, $zero
    /* 7DEB8 0027CEB8 0000A37F */  sq         $v1, 0x0($sp)
    /* 7DEBC 0027CEBC 30040424 */  addiu      $a0, $zero, 0x430
    /* 7DEC0 0027CEC0 2D28A003 */  daddu      $a1, $sp, $zero
    /* 7DEC4 0027CEC4 9CF2090C */  jal        sceVu0MemWriteQ
    /* 7DEC8 0027CEC8 0000A2FF */   sd        $v0, 0x0($sp)
    /* 7DECC 0027CECC 2D806002 */  daddu      $s0, $s3, $zero
    /* 7DED0 0027CED0 0402429E */  lwu        $v0, 0x204($s2)
    /* 7DED4 0027CED4 31040424 */  addiu      $a0, $zero, 0x431
    /* 7DED8 0027CED8 2D28A003 */  daddu      $a1, $sp, $zero
    /* 7DEDC 0027CEDC 2D880000 */  daddu      $s1, $zero, $zero
    /* 7DEE0 0027CEE0 9CF2090C */  jal        sceVu0MemWriteQ
    /* 7DEE4 0027CEE4 0000A2FF */   sd        $v0, 0x0($sp)
    /* 7DEE8 0027CEE8 0802429E */  lwu        $v0, 0x208($s2)
    /* 7DEEC 0027CEEC 32040424 */  addiu      $a0, $zero, 0x432
    /* 7DEF0 0027CEF0 2D28A003 */  daddu      $a1, $sp, $zero
    /* 7DEF4 0027CEF4 9CF2090C */  jal        sceVu0MemWriteQ
    /* 7DEF8 0027CEF8 0000A2FF */   sd        $v0, 0x0($sp)
    /* 7DEFC 0027CEFC 0C02429E */  lwu        $v0, 0x20C($s2)
    /* 7DF00 0027CF00 34040424 */  addiu      $a0, $zero, 0x434
    /* 7DF04 0027CF04 2D28A003 */  daddu      $a1, $sp, $zero
    /* 7DF08 0027CF08 9CF2090C */  jal        sceVu0MemWriteQ
    /* 7DF0C 0027CF0C 0000A2FF */   sd        $v0, 0x0($sp)
    /* 7DF10 0027CF10 1002429E */  lwu        $v0, 0x210($s2)
    /* 7DF14 0027CF14 35040424 */  addiu      $a0, $zero, 0x435
    /* 7DF18 0027CF18 2D28A003 */  daddu      $a1, $sp, $zero
    /* 7DF1C 0027CF1C 9CF2090C */  jal        sceVu0MemWriteQ
    /* 7DF20 0027CF20 0000A2FF */   sd        $v0, 0x0($sp)
    /* 7DF24 0027CF24 1402429E */  lwu        $v0, 0x214($s2)
    /* 7DF28 0027CF28 36040424 */  addiu      $a0, $zero, 0x436
    /* 7DF2C 0027CF2C 2D28A003 */  daddu      $a1, $sp, $zero
    /* 7DF30 0027CF30 9CF2090C */  jal        sceVu0MemWriteQ
    /* 7DF34 0027CF34 0000A2FF */   sd        $v0, 0x0($sp)
    /* 7DF38 0027CF38 1802429E */  lwu        $v0, 0x218($s2)
    /* 7DF3C 0027CF3C 37040424 */  addiu      $a0, $zero, 0x437
    /* 7DF40 0027CF40 2D28A003 */  daddu      $a1, $sp, $zero
    /* 7DF44 0027CF44 9CF2090C */  jal        sceVu0MemWriteQ
    /* 7DF48 0027CF48 0000A2FF */   sd        $v0, 0x0($sp)
    /* 7DF4C 0027CF4C 00000000 */  nop
  .L0027CF50:
    /* 7DF50 0027CF50 00000296 */  lhu        $v0, 0x0($s0)
    /* 7DF54 0027CF54 20042426 */  addiu      $a0, $s1, 0x420
    /* 7DF58 0027CF58 FFFF8430 */  andi       $a0, $a0, 0xFFFF
    /* 7DF5C 0027CF5C 2D28A003 */  daddu      $a1, $sp, $zero
    /* 7DF60 0027CF60 0000A2FF */  sd         $v0, 0x0($sp)
    /* 7DF64 0027CF64 9CF2090C */  jal        sceVu0MemWriteQ
    /* 7DF68 0027CF68 01003126 */   addiu     $s1, $s1, 0x1
    /* 7DF6C 0027CF6C 1000222E */  sltiu      $v0, $s1, 0x10
    /* 7DF70 0027CF70 F7FF4014 */  bnez       $v0, .L0027CF50
    /* 7DF74 0027CF74 02001026 */   addiu     $s0, $s0, 0x2
    /* 7DF78 0027CF78 01000224 */  addiu      $v0, $zero, 0x1
  .L0027CF7C:
    /* 7DF7C 0027CF7C 5000BFDF */  ld         $ra, 0x50($sp)
    /* 7DF80 0027CF80 4000B3DF */  ld         $s3, 0x40($sp)
    /* 7DF84 0027CF84 3000B2DF */  ld         $s2, 0x30($sp)
    /* 7DF88 0027CF88 2000B1DF */  ld         $s1, 0x20($sp)
    /* 7DF8C 0027CF8C 1000B0DF */  ld         $s0, 0x10($sp)
    /* 7DF90 0027CF90 0800E003 */  jr         $ra
    /* 7DF94 0027CF94 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel sceDevVu1PutCnd
