.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceDevGifGetP3msk, 0x20

glabel sceDevGifGetP3msk
    /* 7E0E8 0027D0E8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 7E0EC 0027D0EC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 7E0F0 0027D0F0 1AF4090C */  jal        sceDevGifGetImtMode
    /* 7E0F4 0027D0F4 00000000 */   nop
    /* 7E0F8 0027D0F8 0000BFDF */  ld         $ra, 0x0($sp)
    /* 7E0FC 0027D0FC 01004230 */  andi       $v0, $v0, 0x1
    /* 7E100 0027D100 0800E003 */  jr         $ra
    /* 7E104 0027D104 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel sceDevGifGetP3msk
