.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceGsSyncV, 0x94

glabel sceGsSyncV
    /* 8A310 00289310 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 8A314 00289314 0000B0FF */  sd         $s0, 0x0($sp)
    /* 8A318 00289318 1000BFFF */  sd         $ra, 0x10($sp)
    /* 8A31C 0028931C F2220A0C */  jal        sceGsGetGParam
    /* 8A320 00289320 00000000 */   nop
    /* 8A324 00289324 2D804000 */  daddu      $s0, $v0, $zero
    /* 8A328 00289328 0800028E */  lw         $v0, 0x8($s0)
    /* 8A32C 0028932C 10004014 */  bnez       $v0, .L00289370
    /* 8A330 00289330 00000000 */   nop
    /* 8A334 00289334 FCFE090C */  jal        VSync_WaitVblankStart
    /* 8A338 00289338 00000000 */   nop
    /* 8A33C 0028933C 00000386 */  lh         $v1, 0x0($s0)
    /* 8A340 00289340 01000224 */  addiu      $v0, $zero, 0x1
    /* 8A344 00289344 14006214 */  bne        $v1, $v0, .L00289398
    /* 8A348 00289348 1000BFDF */   ld        $ra, 0x10($sp)
    /* 8A34C 0028934C 0012033C */  lui        $v1, (0x12001000 >> 16)
    /* 8A350 00289350 00106334 */  ori        $v1, $v1, (0x12001000 & 0xFFFF)
    /* 8A354 00289354 000062DC */  ld         $v0, 0x0($v1)
    /* 8A358 00289358 7A130200 */  dsrl       $v0, $v0, 13
    /* 8A35C 0028935C 01004230 */  andi       $v0, $v0, 0x1
    /* 8A360 00289360 3C100200 */  dsll32     $v0, $v0, 0
    /* 8A364 00289364 3F100200 */  dsra32     $v0, $v0, 0
    /* 8A368 00289368 0C000010 */  b          .L0028939C
    /* 8A36C 0028936C 0000B0DF */   ld        $s0, 0x0($sp)
  .L00289370:
    /* 8A370 00289370 20FF090C */  jal        VSync2
    /* 8A374 00289374 00000000 */   nop
    /* 8A378 00289378 7B130200 */  dsra       $v0, $v0, 13
    /* 8A37C 0028937C 00000386 */  lh         $v1, 0x0($s0)
    /* 8A380 00289380 01004430 */  andi       $a0, $v0, 0x1
    /* 8A384 00289384 01000224 */  addiu      $v0, $zero, 0x1
    /* 8A388 00289388 03006214 */  bne        $v1, $v0, .L00289398
    /* 8A38C 0028938C 1000BFDF */   ld        $ra, 0x10($sp)
    /* 8A390 00289390 3C100400 */  dsll32     $v0, $a0, 0
    /* 8A394 00289394 3F100200 */  dsra32     $v0, $v0, 0
  .L00289398:
    /* 8A398 00289398 0000B0DF */  ld         $s0, 0x0($sp)
  .L0028939C:
    /* 8A39C 0028939C 0800E003 */  jr         $ra
    /* 8A3A0 002893A0 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel sceGsSyncV
