.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceMtapGetConnection, 0x6C

glabel sceMtapGetConnection
    /* 7F388 0027E388 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 7F38C 0027E38C 5000023C */  lui        $v0, (0x5025C0 >> 16)
    /* 7F390 0027E390 1000B0FF */  sd         $s0, 0x10($sp)
    /* 7F394 0027E394 5000033C */  lui        $v1, %hi(D_00502510)
    /* 7F398 0027E398 C0255024 */  addiu      $s0, $v0, %lo(D_005025C0)
    /* 7F39C 0027E39C C02544AC */  sw         $a0, (0x5025C0 & 0xFFFF)($v0)
    /* 7F3A0 0027E3A0 2000BFFF */  sd         $ra, 0x20($sp)
    /* 7F3A4 0027E3A4 10256424 */  addiu      $a0, $v1, %lo(D_00502510)
    /* 7F3A8 0027E3A8 0000A0AF */  sw         $zero, 0x0($sp)
    /* 7F3AC 0027E3AC 01000524 */  addiu      $a1, $zero, 0x1
    /* 7F3B0 0027E3B0 2D300000 */  daddu      $a2, $zero, $zero
    /* 7F3B4 0027E3B4 2D380002 */  daddu      $a3, $s0, $zero
    /* 7F3B8 0027E3B8 80000824 */  addiu      $t0, $zero, 0x80
    /* 7F3BC 0027E3BC 2D480002 */  daddu      $t1, $s0, $zero
    /* 7F3C0 0027E3C0 80000A24 */  addiu      $t2, $zero, 0x80
    /* 7F3C4 0027E3C4 C4090A0C */  jal        sceSifCallRpc
    /* 7F3C8 0027E3C8 2D580000 */   daddu     $t3, $zero, $zero
    /* 7F3CC 0027E3CC 05004304 */  bgezl      $v0, .L0027E3E4
    /* 7F3D0 0027E3D0 0400028E */   lw        $v0, 0x4($s0)
    /* 7F3D4 0027E3D4 3700043C */  lui        $a0, %hi(aScemtapgetconn)
    /* 7F3D8 0027E3D8 00F8090C */  jal        DPRINT
    /* 7F3DC 0027E3DC C8CA8424 */   addiu     $a0, $a0, %lo(aScemtapgetconn)
    /* 7F3E0 0027E3E0 2D100000 */  daddu      $v0, $zero, $zero
  .L0027E3E4:
    /* 7F3E4 0027E3E4 2000BFDF */  ld         $ra, 0x20($sp)
    /* 7F3E8 0027E3E8 1000B0DF */  ld         $s0, 0x10($sp)
    /* 7F3EC 0027E3EC 0800E003 */  jr         $ra
    /* 7F3F0 0027E3F0 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel sceMtapGetConnection
