.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceMcMkdir, 0x34

glabel sceMcMkdir
    /* 8ECC8 0028DCC8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 8ECCC 0028DCCC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 8ECD0 0028DCD0 E4360A0C */  jal        sceMcOpen
    /* 8ECD4 0028DCD4 40000724 */   addiu     $a3, $zero, 0x40
    /* 8ECD8 0028DCD8 2D204000 */  daddu      $a0, $v0, $zero
    /* 8ECDC 0028DCDC 04008014 */  bnez       $a0, .L0028DCF0
    /* 8ECE0 0028DCE0 0000BFDF */   ld        $ra, 0x0($sp)
    /* 8ECE4 0028DCE4 3300033C */  lui        $v1, %hi(mcRunCmdNo)
    /* 8ECE8 0028DCE8 0B000224 */  addiu      $v0, $zero, 0xB
    /* 8ECEC 0028DCEC 80FC62AC */  sw         $v0, %lo(mcRunCmdNo)($v1)
  .L0028DCF0:
    /* 8ECF0 0028DCF0 2D108000 */  daddu      $v0, $a0, $zero
    /* 8ECF4 0028DCF4 0800E003 */  jr         $ra
    /* 8ECF8 0028DCF8 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel sceMcMkdir
