.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching scePFontGetScreenMatrix, 0x10

glabel scePFontGetScreenMatrix
    /* 91778 00290778 2D108000 */  daddu      $v0, $a0, $zero
    /* 9177C 0029077C 2D20A000 */  daddu      $a0, $a1, $zero
    /* 91780 00290780 36EC0908 */  j          sceVu0CopyMatrix
    /* 91784 00290784 2D284000 */   daddu     $a1, $v0, $zero
endlabel scePFontGetScreenMatrix
