.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching scePowerOffHandler, 0x90

glabel scePowerOffHandler
    /* 843D8 002833D8 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 843DC 002833DC 3000B3FF */  sd         $s3, 0x30($sp)
    /* 843E0 002833E0 2000B2FF */  sd         $s2, 0x20($sp)
    /* 843E4 002833E4 2D988000 */  daddu      $s3, $a0, $zero
    /* 843E8 002833E8 4000B4FF */  sd         $s4, 0x40($sp)
    /* 843EC 002833EC 2D90A000 */  daddu      $s2, $a1, $zero
    /* 843F0 002833F0 1000B1FF */  sd         $s1, 0x10($sp)
    /* 843F4 002833F4 1B000424 */  addiu      $a0, $zero, 0x1B
    /* 843F8 002833F8 5000BFFF */  sd         $ra, 0x50($sp)
    /* 843FC 002833FC 5000113C */  lui        $s1, (0x5064C0 >> 16)
    /* 84400 00283400 0000B0FF */  sd         $s0, 0x0($sp)
    /* 84404 00283404 E60C0A0C */  jal        _sceFsWaitS
    /* 84408 00283408 C0643426 */   addiu     $s4, $s1, %lo(D_005064C0)
    /* 8440C 0028340C 3300023C */  lui        $v0, %hi(_fs_init)
    /* 84410 00283410 30D3438C */  lw         $v1, %lo(_fs_init)($v0)
    /* 84414 00283414 03006014 */  bnez       $v1, .L00283424
    /* 84418 00283418 00000000 */   nop
    /* 8441C 0028341C 260D0A0C */  jal        sceFsInit
    /* 84420 00283420 00000000 */   nop
  .L00283424:
    /* 84424 00283424 101E0A0C */  jal        DIntr
    /* 84428 00283428 00000000 */   nop
    /* 8442C 0028342C C064308E */  lw         $s0, (0x5064C0 & 0xFFFF)($s1)
    /* 84430 00283430 040092AE */  sw         $s2, 0x4($s4)
    /* 84434 00283434 221E0A0C */  jal        EIntr
    /* 84438 00283438 C06433AE */   sw        $s3, (0x5064C0 & 0xFFFF)($s1)
    /* 8443C 0028343C F20C0A0C */  jal        _sceFsSigSema
    /* 84440 00283440 00000000 */   nop
    /* 84444 00283444 2D100002 */  daddu      $v0, $s0, $zero
    /* 84448 00283448 5000BFDF */  ld         $ra, 0x50($sp)
    /* 8444C 0028344C 4000B4DF */  ld         $s4, 0x40($sp)
    /* 84450 00283450 3000B3DF */  ld         $s3, 0x30($sp)
    /* 84454 00283454 2000B2DF */  ld         $s2, 0x20($sp)
    /* 84458 00283458 1000B1DF */  ld         $s1, 0x10($sp)
    /* 8445C 0028345C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 84460 00283460 0800E003 */  jr         $ra
    /* 84464 00283464 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel scePowerOffHandler
