.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching scePFontGetBlock, 0x30

glabel scePFontGetBlock
    /* 93558 00292558 8003848C */  lw         $a0, 0x380($a0)
    /* 9355C 0029255C 03008054 */  bnel       $a0, $zero, .L0029256C
    /* 93560 00292560 5800828C */   lw        $v0, 0x58($a0)
  .L00292564:
    /* 93564 00292564 0800E003 */  jr         $ra
    /* 93568 00292568 2D100000 */   daddu     $v0, $zero, $zero
  .L0029256C:
    /* 9356C 0029256C 2A10A200 */  slt        $v0, $a1, $v0
    /* 93570 00292570 FCFF4010 */  beqz       $v0, .L00292564
    /* 93574 00292574 80180500 */   sll       $v1, $a1, 2
    /* 93578 00292578 21188300 */  addu       $v1, $a0, $v1
    /* 9357C 0029257C 5C00628C */  lw         $v0, 0x5C($v1)
    /* 93580 00292580 0800E003 */  jr         $ra
    /* 93584 00292584 21108200 */   addu      $v0, $a0, $v0
endlabel scePFontGetBlock
