.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching scePFontPutc, 0x44

glabel scePFontPutc
    /* 93598 00292598 2D188000 */  daddu      $v1, $a0, $zero
    /* 9359C 0029259C F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 935A0 002925A0 0000BFFF */  sd         $ra, 0x0($sp)
    /* 935A4 002925A4 3300043C */  lui        $a0, %hi(s_scePFontControl)
    /* 935A8 002925A8 01000824 */  addiu      $t0, $zero, 0x1
    /* 935AC 002925AC 880365AC */  sw         $a1, 0x388($v1)
    /* 935B0 002925B0 A0FC828C */  lw         $v0, %lo(s_scePFontControl)($a0)
    /* 935B4 002925B4 2D28E000 */  daddu      $a1, $a3, $zero
    /* 935B8 002925B8 2D206000 */  daddu      $a0, $v1, $zero
    /* 935BC 002925BC 6C0368AC */  sw         $t0, 0x36C($v1)
    /* 935C0 002925C0 840366AC */  sw         $a2, 0x384($v1)
    /* 935C4 002925C4 C80268AC */  sw         $t0, 0x2C8($v1)
    /* 935C8 002925C8 09F84000 */  jalr       $v0
    /* 935CC 002925CC C40260AC */   sw        $zero, 0x2C4($v1)
    /* 935D0 002925D0 0000BFDF */  ld         $ra, 0x0($sp)
    /* 935D4 002925D4 0800E003 */  jr         $ra
    /* 935D8 002925D8 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel scePFontPutc
