.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceSifSearchModuleByAddress, 0x90

glabel sceSifSearchModuleByAddress
    /* 87ED0 00286ED0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 87ED4 00286ED4 2000B1FF */  sd         $s1, 0x20($sp)
    /* 87ED8 00286ED8 3000BFFF */  sd         $ra, 0x30($sp)
    /* 87EDC 00286EDC 2D888000 */  daddu      $s1, $a0, $zero
    /* 87EE0 00286EE0 F2190A0C */  jal        _lf_bind
    /* 87EE4 00286EE4 1000B0FF */   sd        $s0, 0x10($sp)
    /* 87EE8 00286EE8 18004004 */  bltz       $v0, .L00286F4C
    /* 87EEC 00286EEC FFFF023C */   lui       $v0, (0xFFFF0000 >> 16)
    /* 87EF0 00286EF0 321A0A0C */  jal        _lf_version
    /* 87EF4 00286EF4 00000000 */   nop
    /* 87EF8 00286EF8 04004010 */  beqz       $v0, .L00286F0C
    /* 87EFC 00286EFC 5000103C */   lui       $s0, (0x5066C0 >> 16)
    /* 87F00 00286F00 FEFF023C */  lui        $v0, (0xFFFEFFFC >> 16)
    /* 87F04 00286F04 11000010 */  b          .L00286F4C
    /* 87F08 00286F08 FCFF4234 */   ori       $v0, $v0, (0xFFFEFFFC & 0xFFFF)
  .L00286F0C:
    /* 87F0C 00286F0C 5000043C */  lui        $a0, %hi(D_005068C0)
    /* 87F10 00286F10 C0660726 */  addiu      $a3, $s0, %lo(D_005066C0)
    /* 87F14 00286F14 C06611AE */  sw         $s1, (0x5066C0 & 0xFFFF)($s0)
    /* 87F18 00286F18 C0688424 */  addiu      $a0, $a0, %lo(D_005068C0)
    /* 87F1C 00286F1C 0000A0AF */  sw         $zero, 0x0($sp)
    /* 87F20 00286F20 0A000524 */  addiu      $a1, $zero, 0xA
    /* 87F24 00286F24 2D300000 */  daddu      $a2, $zero, $zero
    /* 87F28 00286F28 04000824 */  addiu      $t0, $zero, 0x4
    /* 87F2C 00286F2C 2D48E000 */  daddu      $t1, $a3, $zero
    /* 87F30 00286F30 04000A24 */  addiu      $t2, $zero, 0x4
    /* 87F34 00286F34 C4090A0C */  jal        sceSifCallRpc
    /* 87F38 00286F38 2D580000 */   daddu     $t3, $zero, $zero
    /* 87F3C 00286F3C 03004304 */  bgezl      $v0, .L00286F4C
    /* 87F40 00286F40 C066028E */   lw        $v0, (0x5066C0 & 0xFFFF)($s0)
    /* 87F44 00286F44 FEFF023C */  lui        $v0, (0xFFFEFFFF >> 16)
    /* 87F48 00286F48 FFFF4234 */  ori        $v0, $v0, (0xFFFEFFFF & 0xFFFF)
  .L00286F4C:
    /* 87F4C 00286F4C 3000BFDF */  ld         $ra, 0x30($sp)
    /* 87F50 00286F50 2000B1DF */  ld         $s1, 0x20($sp)
    /* 87F54 00286F54 1000B0DF */  ld         $s0, 0x10($sp)
    /* 87F58 00286F58 0800E003 */  jr         $ra
    /* 87F5C 00286F5C 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel sceSifSearchModuleByAddress
