.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceSifSetCmdBuffer, 0x18

glabel sceSifSetCmdBuffer
    /* 82AB8 00281AB8 5000033C */  lui        $v1, %hi(D_00503758)
    /* 82ABC 00281ABC 58376324 */  addiu      $v1, $v1, %lo(D_00503758)
    /* 82AC0 00281AC0 1400628C */  lw         $v0, 0x14($v1)
    /* 82AC4 00281AC4 180065AC */  sw         $a1, 0x18($v1)
    /* 82AC8 00281AC8 0800E003 */  jr         $ra
    /* 82ACC 00281ACC 140064AC */   sw        $a0, 0x14($v1)
endlabel sceSifSetCmdBuffer
