.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceSifAllocIopHeap, 0x70

glabel sceSifAllocIopHeap
    /* 87550 00286550 3300033C */  lui        $v1, %hi(_bind)
    /* 87554 00286554 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 87558 00286558 44D3628C */  lw         $v0, %lo(_bind)($v1)
    /* 8755C 0028655C 2D288000 */  daddu      $a1, $a0, $zero
    /* 87560 00286560 2000BFFF */  sd         $ra, 0x20($sp)
    /* 87564 00286564 11004004 */  bltz       $v0, .L002865AC
    /* 87568 00286568 1000B0FF */   sd        $s0, 0x10($sp)
    /* 8756C 0028656C 5000073C */  lui        $a3, (0x506580 >> 16)
    /* 87570 00286570 5000043C */  lui        $a0, %hi(D_00506500)
    /* 87574 00286574 8065E5AC */  sw         $a1, (0x506580 & 0xFFFF)($a3)
    /* 87578 00286578 5000103C */  lui        $s0, (0x506540 >> 16)
    /* 8757C 0028657C 00658424 */  addiu      $a0, $a0, %lo(D_00506500)
    /* 87580 00286580 8065E724 */  addiu      $a3, $a3, %lo(D_00506580)
    /* 87584 00286584 0000A0AF */  sw         $zero, 0x0($sp)
    /* 87588 00286588 01000524 */  addiu      $a1, $zero, 0x1
    /* 8758C 0028658C 2D300000 */  daddu      $a2, $zero, $zero
    /* 87590 00286590 04000824 */  addiu      $t0, $zero, 0x4
    /* 87594 00286594 40650926 */  addiu      $t1, $s0, %lo(D_00506540)
    /* 87598 00286598 04000A24 */  addiu      $t2, $zero, 0x4
    /* 8759C 0028659C C4090A0C */  jal        sceSifCallRpc
    /* 875A0 002865A0 2D580000 */   daddu     $t3, $zero, $zero
    /* 875A4 002865A4 02004104 */  bgez       $v0, .L002865B0
    /* 875A8 002865A8 4065028E */   lw        $v0, (0x506540 & 0xFFFF)($s0)
  .L002865AC:
    /* 875AC 002865AC 2D100000 */  daddu      $v0, $zero, $zero
  .L002865B0:
    /* 875B0 002865B0 2000BFDF */  ld         $ra, 0x20($sp)
    /* 875B4 002865B4 1000B0DF */  ld         $s0, 0x10($sp)
    /* 875B8 002865B8 0800E003 */  jr         $ra
    /* 875BC 002865BC 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel sceSifAllocIopHeap
