.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceSifSearchModuleByName, 0xA0

glabel sceSifSearchModuleByName
    /* 87E30 00286E30 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 87E34 00286E34 1000B0FF */  sd         $s0, 0x10($sp)
    /* 87E38 00286E38 2000BFFF */  sd         $ra, 0x20($sp)
    /* 87E3C 00286E3C F2190A0C */  jal        _lf_bind
    /* 87E40 00286E40 2D808000 */   daddu     $s0, $a0, $zero
    /* 87E44 00286E44 1E004004 */  bltz       $v0, .L00286EC0
    /* 87E48 00286E48 FFFF023C */   lui       $v0, (0xFFFF0000 >> 16)
    /* 87E4C 00286E4C 321A0A0C */  jal        _lf_version
    /* 87E50 00286E50 00000000 */   nop
    /* 87E54 00286E54 04004050 */  beql       $v0, $zero, .L00286E68
    /* 87E58 00286E58 5000023C */   lui       $v0, %hi(D_005066C8)
    /* 87E5C 00286E5C FEFF023C */  lui        $v0, (0xFFFEFFFC >> 16)
    /* 87E60 00286E60 17000010 */  b          .L00286EC0
    /* 87E64 00286E64 FCFF4234 */   ori       $v0, $v0, (0xFFFEFFFC & 0xFFFF)
  .L00286E68:
    /* 87E68 00286E68 2D280002 */  daddu      $a1, $s0, $zero
    /* 87E6C 00286E6C C8665024 */  addiu      $s0, $v0, %lo(D_005066C8)
    /* 87E70 00286E70 FC000624 */  addiu      $a2, $zero, 0xFC
    /* 87E74 00286E74 D2750A0C */  jal        strncpy
    /* 87E78 00286E78 2D200002 */   daddu     $a0, $s0, $zero
    /* 87E7C 00286E7C F8FF0326 */  addiu      $v1, $s0, -0x8
    /* 87E80 00286E80 5000043C */  lui        $a0, %hi(D_005068C0)
    /* 87E84 00286E84 2D386000 */  daddu      $a3, $v1, $zero
    /* 87E88 00286E88 030160A0 */  sb         $zero, 0x103($v1)
    /* 87E8C 00286E8C C0688424 */  addiu      $a0, $a0, %lo(D_005068C0)
    /* 87E90 00286E90 09000524 */  addiu      $a1, $zero, 0x9
    /* 87E94 00286E94 0000A0AF */  sw         $zero, 0x0($sp)
    /* 87E98 00286E98 2D300000 */  daddu      $a2, $zero, $zero
    /* 87E9C 00286E9C 00020824 */  addiu      $t0, $zero, 0x200
    /* 87EA0 00286EA0 2D48E000 */  daddu      $t1, $a3, $zero
    /* 87EA4 00286EA4 04000A24 */  addiu      $t2, $zero, 0x4
    /* 87EA8 00286EA8 C4090A0C */  jal        sceSifCallRpc
    /* 87EAC 00286EAC 2D580000 */   daddu     $t3, $zero, $zero
    /* 87EB0 00286EB0 03004304 */  bgezl      $v0, .L00286EC0
    /* 87EB4 00286EB4 F8FF028E */   lw        $v0, -0x8($s0)
    /* 87EB8 00286EB8 FEFF023C */  lui        $v0, (0xFFFEFFFF >> 16)
    /* 87EBC 00286EBC FFFF4234 */  ori        $v0, $v0, (0xFFFEFFFF & 0xFFFF)
  .L00286EC0:
    /* 87EC0 00286EC0 2000BFDF */  ld         $ra, 0x20($sp)
    /* 87EC4 00286EC4 1000B0DF */  ld         $s0, 0x10($sp)
    /* 87EC8 00286EC8 0800E003 */  jr         $ra
    /* 87ECC 00286ECC 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel sceSifSearchModuleByName
