.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching sceSifStopDma, 0x10

glabel sceSifStopDma
    /* 88E30 00287E30 6B000324 */  addiu      $v1, $zero, 0x6B
    /* 88E34 00287E34 0C000000 */  syscall    0 /* handwritten instruction */
    /* 88E38 00287E38 0800E003 */  jr         $ra
    /* 88E3C 00287E3C 00000000 */   nop
endlabel sceSifStopDma
