.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceVu0InterVectorXYZ, 0x2C

glabel sceVu0InterVectorXYZ
    /* 7C980 0027B980 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 7C984 0027B984 0000C5D8 */  lqc2       $vf5, 0x0($a2)
    /* 7C988 0027B988 00600844 */  mfc1       $t0, $f12
    /* 7C98C 0027B98C 0030A848 */  qmtc2.ni   $t0, $vf6
    /* 7C990 0027B990 3C23294A */  vmove.w    $vf9, $vf4
    /* 7C994 0027B994 C301004B */  vaddw.x    $vf7, $vf0, $vf0w
    /* 7C998 0027B998 2C3A064B */  vsub.x     $vf8, $vf7, $vf6
    /* 7C99C 0027B99C BC21C64B */  vmulax.xyz $ACC, $vf4, $vf6x
    /* 7C9A0 0027B9A0 482AC84B */  vmaddx.xyz $vf9, $vf5, $vf8x
    /* 7C9A4 0027B9A4 0800E003 */  jr         $ra
    /* 7C9A8 0027B9A8 000089F8 */   sqc2      $vf9, 0x0($a0)
endlabel sceVu0InterVectorXYZ
