.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceVu0ViewScreenMatrix, 0x104

glabel sceVu0ViewScreenMatrix
    /* 7C628 0027B628 60FFBD27 */  addiu      $sp, $sp, -0xA0
    /* 7C62C 0027B62C 07880046 */  neg.s      $f0, $f17
    /* 7C630 0027B630 6000B4E7 */  swc1       $f20, 0x60($sp)
    /* 7C634 0027B634 07950046 */  neg.s      $f20, $f18
    /* 7C638 0027B638 A000A1C7 */  lwc1       $f1, 0xA0($sp)
    /* 7C63C 0027B63C 6800B5E7 */  swc1       $f21, 0x68($sp)
    /* 7C640 0027B640 00001246 */  add.s      $f0, $f0, $f18
    /* 7C644 0027B644 420D1346 */  mul.s      $f21, $f1, $f19
    /* 7C648 0027B648 4000B0FF */  sd         $s0, 0x40($sp)
    /* 7C64C 0027B64C 02A51346 */  mul.s      $f20, $f20, $f19
    /* 7C650 0027B650 2D808000 */  daddu      $s0, $a0, $zero
    /* 7C654 0027B654 428C0146 */  mul.s      $f17, $f17, $f1
    /* 7C658 0027B658 9000BAE7 */  swc1       $f26, 0x90($sp)
    /* 7C65C 0027B65C C79C0046 */  neg.s      $f19, $f19
    /* 7C660 0027B660 8800B9E7 */  swc1       $f25, 0x88($sp)
    /* 7C664 0027B664 42AD0046 */  mul.s      $f21, $f21, $f0
    /* 7C668 0027B668 8000B8E7 */  swc1       $f24, 0x80($sp)
    /* 7C66C 0027B66C 00A51146 */  add.s      $f20, $f20, $f17
    /* 7C670 0027B670 7800B7E7 */  swc1       $f23, 0x78($sp)
    /* 7C674 0027B674 C09C0146 */  add.s      $f19, $f19, $f1
    /* 7C678 0027B678 7000B6E7 */  swc1       $f22, 0x70($sp)
    /* 7C67C 0027B67C 86650046 */  mov.s      $f22, $f12
    /* 7C680 0027B680 066E0046 */  mov.s      $f24, $f13
    /* 7C684 0027B684 C6750046 */  mov.s      $f23, $f14
    /* 7C688 0027B688 867E0046 */  mov.s      $f26, $f15
    /* 7C68C 0027B68C 00000000 */  nop
    /* 7C690 0027B690 00000000 */  nop
    /* 7C694 0027B694 43AD1346 */  div.s      $f21, $f21, $f19
    /* 7C698 0027B698 00000000 */  nop
    /* 7C69C 0027B69C 00000000 */  nop
    /* 7C6A0 0027B6A0 03A51346 */  div.s      $f20, $f20, $f19
    /* 7C6A4 0027B6A4 5000BFFF */  sd         $ra, 0x50($sp)
    /* 7C6A8 0027B6A8 50EC090C */  jal        sceVu0UnitMatrix
    /* 7C6AC 0027B6AC 46860046 */   mov.s     $f25, $f16
    /* 7C6B0 0027B6B0 803F013C */  lui        $at, (0x3F800000 >> 16)
    /* 7C6B4 0027B6B4 00008144 */  mtc1       $at, $f0
    /* 7C6B8 0027B6B8 2D20A003 */  daddu      $a0, $sp, $zero
    /* 7C6BC 0027B6BC 140016E6 */  swc1       $f22, 0x14($s0)
    /* 7C6C0 0027B6C0 000016E6 */  swc1       $f22, 0x0($s0)
    /* 7C6C4 0027B6C4 280000AE */  sw         $zero, 0x28($s0)
    /* 7C6C8 0027B6C8 3C0000AE */  sw         $zero, 0x3C($s0)
    /* 7C6CC 0027B6CC 2C0000E6 */  swc1       $f0, 0x2C($s0)
    /* 7C6D0 0027B6D0 50EC090C */  jal        sceVu0UnitMatrix
    /* 7C6D4 0027B6D4 380000E6 */   swc1      $f0, 0x38($s0)
    /* 7C6D8 0027B6D8 2D200002 */  daddu      $a0, $s0, $zero
    /* 7C6DC 0027B6DC 0000B8E7 */  swc1       $f24, 0x0($sp)
    /* 7C6E0 0027B6E0 1400B7E7 */  swc1       $f23, 0x14($sp)
    /* 7C6E4 0027B6E4 2D28A003 */  daddu      $a1, $sp, $zero
    /* 7C6E8 0027B6E8 2800B5E7 */  swc1       $f21, 0x28($sp)
    /* 7C6EC 0027B6EC 2D308000 */  daddu      $a2, $a0, $zero
    /* 7C6F0 0027B6F0 3000BAE7 */  swc1       $f26, 0x30($sp)
    /* 7C6F4 0027B6F4 3400B9E7 */  swc1       $f25, 0x34($sp)
    /* 7C6F8 0027B6F8 92EB090C */  jal        sceVu0MulMatrix
    /* 7C6FC 0027B6FC 3800B4E7 */   swc1      $f20, 0x38($sp)
    /* 7C700 0027B700 5000BFDF */  ld         $ra, 0x50($sp)
    /* 7C704 0027B704 4000B0DF */  ld         $s0, 0x40($sp)
    /* 7C708 0027B708 9000BAC7 */  lwc1       $f26, 0x90($sp)
    /* 7C70C 0027B70C 8800B9C7 */  lwc1       $f25, 0x88($sp)
    /* 7C710 0027B710 8000B8C7 */  lwc1       $f24, 0x80($sp)
    /* 7C714 0027B714 7800B7C7 */  lwc1       $f23, 0x78($sp)
    /* 7C718 0027B718 7000B6C7 */  lwc1       $f22, 0x70($sp)
    /* 7C71C 0027B71C 6800B5C7 */  lwc1       $f21, 0x68($sp)
    /* 7C720 0027B720 6000B4C7 */  lwc1       $f20, 0x60($sp)
    /* 7C724 0027B724 0800E003 */  jr         $ra
    /* 7C728 0027B728 A000BD27 */   addiu     $sp, $sp, 0xA0
endlabel sceVu0ViewScreenMatrix
