.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sceVu0DivVector, 0x20

glabel sceVu0DivVector
    /* 7BFD0 0027AFD0 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 7BFD4 0027AFD4 00600844 */  mfc1       $t0, $f12
    /* 7BFD8 0027AFD8 0028A848 */  qmtc2.ni   $t0, $vf5
    /* 7BFDC 0027AFDC BC03654A */  vdiv       $Q, $vf0w, $vf5x
    /* 7BFE0 0027AFE0 BF03004A */  vwaitq
    /* 7BFE4 0027AFE4 1C21E04B */  vmulq.xyzw $vf4, $vf4, $Q
    /* 7BFE8 0027AFE8 0800E003 */  jr         $ra
    /* 7BFEC 0027AFEC 000084F8 */   sqc2      $vf4, 0x0($a0)
endlabel sceVu0DivVector
