.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching setlocale, 0x2C

glabel setlocale
    /* A41B0 002A31B0 2D108000 */  daddu      $v0, $a0, $zero
    /* A41B4 002A31B4 3400033C */  lui        $v1, %hi(_impure_ptr_0)
    /* A41B8 002A31B8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* A41BC 002A31BC 2D30A000 */  daddu      $a2, $a1, $zero
    /* A41C0 002A31C0 8473648C */  lw         $a0, %lo(_impure_ptr_0)($v1)
    /* A41C4 002A31C4 0000BFFF */  sd         $ra, 0x0($sp)
    /* A41C8 002A31C8 468C0A0C */  jal        _setlocale_r
    /* A41CC 002A31CC 2D284000 */   daddu     $a1, $v0, $zero
    /* A41D0 002A31D0 0000BFDF */  ld         $ra, 0x0($sp)
    /* A41D4 002A31D4 0800E003 */  jr         $ra
    /* A41D8 002A31D8 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel setlocale
