.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching SetTLBEntry, 0x30

glabel SetTLBEntry
    /* 892C8 002882C8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 892CC 002882CC F3FF8224 */  addiu      $v0, $a0, -0xD
    /* 892D0 002882D0 2300422C */  sltiu      $v0, $v0, 0x23
    /* 892D4 002882D4 03004014 */  bnez       $v0, .L002882E4
    /* 892D8 002882D8 0000BFFF */   sd        $ra, 0x0($sp)
    /* 892DC 002882DC 03000010 */  b          .L002882EC
    /* 892E0 002882E0 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L002882E4:
    /* 892E4 002882E4 AE200A0C */  jal        _SetTLBEntry
    /* 892E8 002882E8 00000000 */   nop
  .L002882EC:
    /* 892EC 002882EC 0000BFDF */  ld         $ra, 0x0($sp)
    /* 892F0 002882F0 0800E003 */  jr         $ra
    /* 892F4 002882F4 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel SetTLBEntry
