.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002170D8, 0x40

glabel func_002170D8
    /* 180D8 002170D8 0800858C */  lw         $a1, 0x8($a0)
    /* 180DC 002170DC FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 180E0 002170E0 3B00063C */  lui        $a2, (0x3B7BD0 >> 16)
    /* 180E4 002170E4 989080AF */  sw         $zero, %gp_rel(D_00370A08)($gp)
    /* 180E8 002170E8 2A104500 */  slt        $v0, $v0, $a1
    /* 180EC 002170EC 0700A324 */  addiu      $v1, $a1, 0x7
    /* 180F0 002170F0 0B18A200 */  movn       $v1, $a1, $v0
    /* 180F4 002170F4 D07BC424 */  addiu      $a0, $a2, %lo(D_003B7BD0)
    /* 180F8 002170F8 D07BC0AC */  sw         $zero, (0x3B7BD0 & 0xFFFF)($a2)
    /* 180FC 002170FC C3180300 */  sra        $v1, $v1, 3
    /* 18100 00217100 0C0083AC */  sw         $v1, 0xC($a0)
    /* 18104 00217104 040080AC */  sw         $zero, 0x4($a0)
    /* 18108 00217108 080083AC */  sw         $v1, 0x8($a0)
    /* 1810C 0021710C 9C9080AF */  sw         $zero, %gp_rel(D_00370A0C)($gp)
    /* 18110 00217110 0800E003 */  jr         $ra
    /* 18114 00217114 2D100000 */   daddu     $v0, $zero, $zero
endlabel func_002170D8
