.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching config_set_keyboard_type, 0x10

glabel config_set_keyboard_type
    /* 50B0 002040B0 2D108000 */  daddu      $v0, $a0, $zero
    /* 50B4 002040B4 3700033C */  lui        $v1, %hi(var_hddsys_keyboard_type)
    /* 50B8 002040B8 0800E003 */  jr         $ra
    /* 50BC 002040BC 201862AC */   sw        $v0, %lo(var_hddsys_keyboard_type)($v1)
endlabel config_set_keyboard_type
