.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching config_hdd_prepare, 0x22C

glabel config_hdd_prepare
    /* 5598 00204598 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 559C 0020459C 2000BFFF */  sd         $ra, 0x20($sp)
    /* 55A0 002045A0 1000B1FF */  sd         $s1, 0x10($sp)
    /* 55A4 002045A4 7C10080C */  jal        config_hdd_set_uninit
    /* 55A8 002045A8 0000B0FF */   sd        $s0, 0x0($sp)
    /* 55AC 002045AC 3400043C */  lui        $a0, %hi(aPfs1ConfSystem)
    /* 55B0 002045B0 CE13080C */  jal        config_hdd_open_read_ini
    /* 55B4 002045B4 207C8424 */   addiu     $a0, $a0, %lo(aPfs1ConfSystem)
    /* 55B8 002045B8 05004104 */  bgez       $v0, .L002045D0
    /* 55BC 002045BC 2000BFDF */   ld        $ra, 0x20($sp)
    /* 55C0 002045C0 1000B1DF */  ld         $s1, 0x10($sp)
    /* 55C4 002045C4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 55C8 002045C8 06110808 */  j          config_hdd_set_default
    /* 55CC 002045CC 3000BD27 */   addiu     $sp, $sp, 0x30
  .L002045D0:
    /* 55D0 002045D0 2A14080C */  jal        func_002050A8
    /* 55D4 002045D4 00000000 */   nop
    /* 55D8 002045D8 5E19080C */  jal        func_00206578
    /* 55DC 002045DC 2D204000 */   daddu     $a0, $v0, $zero
    /* 55E0 002045E0 3400033C */  lui        $v1, %hi(aKeyboard)
    /* 55E4 002045E4 3700023C */  lui        $v0, %hi(var_hddsys_keyboard_type)
    /* 55E8 002045E8 387C7124 */  addiu      $s1, $v1, %lo(aKeyboard)
    /* 55EC 002045EC 20185024 */  addiu      $s0, $v0, %lo(var_hddsys_keyboard_type)
    /* 55F0 002045F0 3400053C */  lui        $a1, %hi(aType)
    /* 55F4 002045F4 2D202002 */  daddu      $a0, $s1, $zero
    /* 55F8 002045F8 487CA524 */  addiu      $a1, $a1, %lo(aType)
    /* 55FC 002045FC 2D300002 */  daddu      $a2, $s0, $zero
    /* 5600 00204600 8C19080C */  jal        config_hdd_do_get_key
    /* 5604 00204604 2D380000 */   daddu     $a3, $zero, $zero
    /* 5608 00204608 04004104 */  bgez       $v0, .L0020461C
    /* 560C 0020460C 3400053C */   lui       $a1, %hi(aRepeatw)
    /* 5610 00204610 FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 5614 00204614 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 5618 00204618 000002AE */  sw         $v0, 0x0($s0)
  .L0020461C:
    /* 561C 0020461C 2D202002 */  daddu      $a0, $s1, $zero
    /* 5620 00204620 507CA524 */  addiu      $a1, $a1, %lo(aRepeatw)
    /* 5624 00204624 04000626 */  addiu      $a2, $s0, 0x4
    /* 5628 00204628 8C19080C */  jal        config_hdd_do_get_key
    /* 562C 0020462C 2D380000 */   daddu     $a3, $zero, $zero
    /* 5630 00204630 04004104 */  bgez       $v0, .L00204644
    /* 5634 00204634 3400053C */   lui       $a1, %hi(aRepeats)
    /* 5638 00204638 FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 563C 0020463C FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 5640 00204640 040002AE */  sw         $v0, 0x4($s0)
  .L00204644:
    /* 5644 00204644 2D202002 */  daddu      $a0, $s1, $zero
    /* 5648 00204648 587CA524 */  addiu      $a1, $a1, %lo(aRepeats)
    /* 564C 0020464C 08000626 */  addiu      $a2, $s0, 0x8
    /* 5650 00204650 8C19080C */  jal        config_hdd_do_get_key
    /* 5654 00204654 2D380000 */   daddu     $a3, $zero, $zero
    /* 5658 00204658 05004104 */  bgez       $v0, .L00204670
    /* 565C 0020465C 3400023C */   lui       $v0, %hi(aMouse)
    /* 5660 00204660 FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 5664 00204664 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 5668 00204668 080002AE */  sw         $v0, 0x8($s0)
    /* 566C 0020466C 3400023C */  lui        $v0, %hi(aMouse)
  .L00204670:
    /* 5670 00204670 3400053C */  lui        $a1, %hi(aSpeed)
    /* 5674 00204674 607C5124 */  addiu      $s1, $v0, %lo(aMouse)
    /* 5678 00204678 687CA524 */  addiu      $a1, $a1, %lo(aSpeed)
    /* 567C 0020467C 2D202002 */  daddu      $a0, $s1, $zero
    /* 5680 00204680 0C000626 */  addiu      $a2, $s0, 0xC
    /* 5684 00204684 8C19080C */  jal        config_hdd_do_get_key
    /* 5688 00204688 2D380000 */   daddu     $a3, $zero, $zero
    /* 568C 0020468C 04004104 */  bgez       $v0, .L002046A0
    /* 5690 00204690 3400053C */   lui       $a1, %hi(aDblclk)
    /* 5694 00204694 FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 5698 00204698 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 569C 0020469C 0C0002AE */  sw         $v0, 0xC($s0)
  .L002046A0:
    /* 56A0 002046A0 2D202002 */  daddu      $a0, $s1, $zero
    /* 56A4 002046A4 707CA524 */  addiu      $a1, $a1, %lo(aDblclk)
    /* 56A8 002046A8 10000626 */  addiu      $a2, $s0, 0x10
    /* 56AC 002046AC 8C19080C */  jal        config_hdd_do_get_key
    /* 56B0 002046B0 2D380000 */   daddu     $a3, $zero, $zero
    /* 56B4 002046B4 04004104 */  bgez       $v0, .L002046C8
    /* 56B8 002046B8 3400053C */   lui       $a1, %hi(aLr)
    /* 56BC 002046BC FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 56C0 002046C0 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 56C4 002046C4 100002AE */  sw         $v0, 0x10($s0)
  .L002046C8:
    /* 56C8 002046C8 2D202002 */  daddu      $a0, $s1, $zero
    /* 56CC 002046CC 787CA524 */  addiu      $a1, $a1, %lo(aLr)
    /* 56D0 002046D0 14000626 */  addiu      $a2, $s0, 0x14
    /* 56D4 002046D4 8C19080C */  jal        config_hdd_do_get_key
    /* 56D8 002046D8 2D380000 */   daddu     $a3, $zero, $zero
    /* 56DC 002046DC 05004104 */  bgez       $v0, .L002046F4
    /* 56E0 002046E0 3400023C */   lui       $v0, %hi(aAtok)
    /* 56E4 002046E4 FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 56E8 002046E8 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 56EC 002046EC 140002AE */  sw         $v0, 0x14($s0)
    /* 56F0 002046F0 3400023C */  lui        $v0, %hi(aAtok)
  .L002046F4:
    /* 56F4 002046F4 3400053C */  lui        $a1, %hi(aMode)
    /* 56F8 002046F8 807C5124 */  addiu      $s1, $v0, %lo(aAtok)
    /* 56FC 002046FC 887CA524 */  addiu      $a1, $a1, %lo(aMode)
    /* 5700 00204700 2D202002 */  daddu      $a0, $s1, $zero
    /* 5704 00204704 18000626 */  addiu      $a2, $s0, 0x18
    /* 5708 00204708 8C19080C */  jal        config_hdd_do_get_key
    /* 570C 0020470C 2D380000 */   daddu     $a3, $zero, $zero
    /* 5710 00204710 04004104 */  bgez       $v0, .L00204724
    /* 5714 00204714 3400053C */   lui       $a1, %hi(aBind)
    /* 5718 00204718 FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 571C 0020471C FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 5720 00204720 180002AE */  sw         $v0, 0x18($s0)
  .L00204724:
    /* 5724 00204724 2D202002 */  daddu      $a0, $s1, $zero
    /* 5728 00204728 907CA524 */  addiu      $a1, $a1, %lo(aBind)
    /* 572C 0020472C 1C000626 */  addiu      $a2, $s0, 0x1C
    /* 5730 00204730 8C19080C */  jal        config_hdd_do_get_key
    /* 5734 00204734 2D380000 */   daddu     $a3, $zero, $zero
    /* 5738 00204738 05004104 */  bgez       $v0, .L00204750
    /* 573C 0020473C 3400023C */   lui       $v0, %hi(aLaststatus)
    /* 5740 00204740 FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 5744 00204744 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 5748 00204748 1C0002AE */  sw         $v0, 0x1C($s0)
    /* 574C 0020474C 3400023C */  lui        $v0, %hi(aLaststatus)
  .L00204750:
    /* 5750 00204750 3400053C */  lui        $a1, %hi(aSoftkbOnoff)
    /* 5754 00204754 987C5124 */  addiu      $s1, $v0, %lo(aLaststatus)
    /* 5758 00204758 A87CA524 */  addiu      $a1, $a1, %lo(aSoftkbOnoff)
    /* 575C 0020475C 2D202002 */  daddu      $a0, $s1, $zero
    /* 5760 00204760 20000626 */  addiu      $a2, $s0, 0x20
    /* 5764 00204764 8C19080C */  jal        config_hdd_do_get_key
    /* 5768 00204768 2D380000 */   daddu     $a3, $zero, $zero
    /* 576C 0020476C 04004104 */  bgez       $v0, .L00204780
    /* 5770 00204770 3400053C */   lui       $a1, %hi(aSoftkbQwert)
    /* 5774 00204774 FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 5778 00204778 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 577C 0020477C 200002AE */  sw         $v0, 0x20($s0)
  .L00204780:
    /* 5780 00204780 2D202002 */  daddu      $a0, $s1, $zero
    /* 5784 00204784 B87CA524 */  addiu      $a1, $a1, %lo(aSoftkbQwert)
    /* 5788 00204788 24000626 */  addiu      $a2, $s0, 0x24
    /* 578C 0020478C 8C19080C */  jal        config_hdd_do_get_key
    /* 5790 00204790 2D380000 */   daddu     $a3, $zero, $zero
    /* 5794 00204794 04004104 */  bgez       $v0, .L002047A8
    /* 5798 00204798 00000000 */   nop
    /* 579C 0020479C FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 57A0 002047A0 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFFF & 0xFFFF)
    /* 57A4 002047A4 240002AE */  sw         $v0, 0x24($s0)
  .L002047A8:
    /* 57A8 002047A8 FE13080C */  jal        config_hdd_close_ini
    /* 57AC 002047AC 00000000 */   nop
    /* 57B0 002047B0 2000BFDF */  ld         $ra, 0x20($sp)
    /* 57B4 002047B4 1000B1DF */  ld         $s1, 0x10($sp)
    /* 57B8 002047B8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 57BC 002047BC 06110808 */  j          config_hdd_set_default
    /* 57C0 002047C0 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel config_hdd_prepare
