.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching config_get_daylight_saving, 0x14

glabel config_get_daylight_saving
    /* 4FC8 00203FC8 3700033C */  lui        $v1, %hi(var_mechacon_config_param_1)
    /* 4FCC 00203FCC 1818628C */  lw         $v0, %lo(var_mechacon_config_param_1)($v1)
    /* 4FD0 00203FD0 42170200 */  srl        $v0, $v0, 29
    /* 4FD4 00203FD4 0800E003 */  jr         $ra
    /* 4FD8 00203FD8 01004230 */   andi      $v0, $v0, 0x1
endlabel config_get_daylight_saving
