.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_00205DE8, 0xC

glabel D_00205DE8
    /* 6DE8 00205DE8 E0FF8224 */  addiu      $v0, $a0, -0x20
    /* 6DEC 00205DEC 0800E003 */  jr         $ra
    /* 6DF0 00205DF0 5F00422C */   sltiu     $v0, $v0, 0x5F
endlabel D_00205DE8
