.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching D_002050B8, 0xC

glabel D_002050B8
    /* 60B8 002050B8 2B00033C */  lui        $v1, %hi(D_002ACA6C)
    /* 60BC 002050BC 0800E003 */  jr         $ra
    /* 60C0 002050C0 6CCA628C */   lw        $v0, %lo(D_002ACA6C)($v1)
endlabel D_002050B8
