.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_002058A8, 0x48

glabel func_002058A8
    /* 68A8 002058A8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 68AC 002058AC FF008430 */  andi       $a0, $a0, 0xFF
    /* 68B0 002058B0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 68B4 002058B4 3700103C */  lui        $s0, %hi(D_003718E8)
    /* 68B8 002058B8 1000BFFF */  sd         $ra, 0x10($sp)
    /* 68BC 002058BC E818038E */  lw         $v1, %lo(D_003718E8)($s0)
    /* 68C0 002058C0 0C00628C */  lw         $v0, 0xC($v1)
    /* 68C4 002058C4 09F84000 */  jalr       $v0
    /* 68C8 002058C8 E8181026 */   addiu     $s0, $s0, %lo(D_003718E8)
    /* 68CC 002058CC FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 68D0 002058D0 181202AE */  sw         $v0, 0x1218($s0)
    /* 68D4 002058D4 2A206200 */  slt        $a0, $v1, $v0
    /* 68D8 002058D8 1000BFDF */  ld         $ra, 0x10($sp)
    /* 68DC 002058DC 2D106000 */  daddu      $v0, $v1, $zero
    /* 68E0 002058E0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 68E4 002058E4 0B100400 */  movn       $v0, $zero, $a0
    /* 68E8 002058E8 0800E003 */  jr         $ra
    /* 68EC 002058EC 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_002058A8
