.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00205C10, 0x2C

glabel func_00205C10
    /* 6C10 00205C10 D0FF8224 */  addiu      $v0, $a0, -0x30
    /* 6C14 00205C14 0A00422C */  sltiu      $v0, $v0, 0xA
    /* 6C18 00205C18 04004014 */  bnez       $v0, .L00205C2C
    /* 6C1C 00205C1C 9FFF8224 */   addiu     $v0, $a0, -0x61
    /* 6C20 00205C20 0600422C */  sltiu      $v0, $v0, 0x6
    /* 6C24 00205C24 03004010 */  beqz       $v0, .L00205C34
    /* 6C28 00205C28 00000000 */   nop
  .L00205C2C:
    /* 6C2C 00205C2C 0800E003 */  jr         $ra
    /* 6C30 00205C30 01000224 */   addiu     $v0, $zero, 0x1
  .L00205C34:
    /* 6C34 00205C34 0800E003 */  jr         $ra
    /* 6C38 00205C38 2D100000 */   daddu     $v0, $zero, $zero
endlabel func_00205C10
