.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00205DF8, 0x64

glabel func_00205DF8
    /* 6DF8 00205DF8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 6DFC 00205DFC 1000BFFF */  sd         $ra, 0x10($sp)
    /* 6E00 00205E00 0000B0FF */  sd         $s0, 0x0($sp)
    /* 6E04 00205E04 00000000 */  nop
  .L00205E08:
    /* 6E08 00205E08 C815080C */  jal        func_00205720
    /* 6E0C 00205E0C 00000000 */   nop
    /* 6E10 00205E10 2D804000 */  daddu      $s0, $v0, $zero
    /* 6E14 00205E14 2A17080C */  jal        func_00205CA8
    /* 6E18 00205E18 2D200002 */   daddu     $a0, $s0, $zero
    /* 6E1C 00205E1C FAFF4014 */  bnez       $v0, .L00205E08
    /* 6E20 00205E20 00000000 */   nop
    /* 6E24 00205E24 2017080C */  jal        func_00205C80
    /* 6E28 00205E28 2D200002 */   daddu     $a0, $s0, $zero
    /* 6E2C 00205E2C 08004010 */  beqz       $v0, .L00205E50
    /* 6E30 00205E30 1000BFDF */   ld        $ra, 0x10($sp)
    /* 6E34 00205E34 00000000 */  nop
  .L00205E38:
    /* 6E38 00205E38 C815080C */  jal        func_00205720
    /* 6E3C 00205E3C 00000000 */   nop
    /* 6E40 00205E40 1017080C */  jal        func_00205C40
    /* 6E44 00205E44 2D204000 */   daddu     $a0, $v0, $zero
    /* 6E48 00205E48 FBFF4010 */  beqz       $v0, .L00205E38
    /* 6E4C 00205E4C 1000BFDF */   ld        $ra, 0x10($sp)
  .L00205E50:
    /* 6E50 00205E50 0000B0DF */  ld         $s0, 0x0($sp)
    /* 6E54 00205E54 E6150808 */  j          func_00205798
    /* 6E58 00205E58 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00205DF8
