.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00206518, 0x60

glabel func_00206518
    /* 7518 00206518 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 751C 0020651C 2D108000 */  daddu      $v0, $a0, $zero
    /* 7520 00206520 0000B0FF */  sd         $s0, 0x0($sp)
    /* 7524 00206524 1000BFFF */  sd         $ra, 0x10($sp)
    /* 7528 00206528 AE1D080C */  jal        func_002076B8
    /* 752C 0020652C 2D804000 */   daddu     $s0, $v0, $zero
    /* 7530 00206530 06000010 */  b          .L0020654C
    /* 7534 00206534 00000492 */   lbu       $a0, 0x0($s0)
  .L00206538:
    /* 7538 00206538 2A16080C */  jal        func_002058A8
    /* 753C 0020653C 00000000 */   nop
    /* 7540 00206540 0A004004 */  bltz       $v0, .L0020656C
    /* 7544 00206544 1000BFDF */   ld        $ra, 0x10($sp)
    /* 7548 00206548 00000492 */  lbu        $a0, 0x0($s0)
  .L0020654C:
    /* 754C 0020654C FAFF8014 */  bnez       $a0, .L00206538
    /* 7550 00206550 01001026 */   addiu     $s0, $s0, 0x1
    /* 7554 00206554 2A16080C */  jal        func_002058A8
    /* 7558 00206558 3D000424 */   addiu     $a0, $zero, 0x3D
    /* 755C 0020655C FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 7560 00206560 2A186200 */  slt        $v1, $v1, $v0
    /* 7564 00206564 0B100300 */  movn       $v0, $zero, $v1
    /* 7568 00206568 1000BFDF */  ld         $ra, 0x10($sp)
  .L0020656C:
    /* 756C 0020656C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 7570 00206570 0800E003 */  jr         $ra
    /* 7574 00206574 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00206518
