.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching write_osd_config, 0x114

glabel write_osd_config
    /* 4AD8 00203AD8 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 4ADC 00203ADC 3700073C */  lui        $a3, %hi(D_00371808)
    /* 4AE0 00203AE0 1000B1FF */  sd         $s1, 0x10($sp)
    /* 4AE4 00203AE4 1F00063C */  lui        $a2, (0x1F1284 >> 16)
    /* 4AE8 00203AE8 0000B0FF */  sd         $s0, 0x0($sp)
    /* 4AEC 00203AEC 0818E824 */  addiu      $t0, $a3, %lo(D_00371808)
    /* 4AF0 00203AF0 2000BFFF */  sd         $ra, 0x20($sp)
    /* 4AF4 00203AF4 FF009030 */  andi       $s0, $a0, 0xFF
    /* 4AF8 00203AF8 2D280000 */  daddu      $a1, $zero, $zero
    /* 4AFC 00203AFC 3700113C */  lui        $s1, %hi(var_mechacon_config_param_1)
    /* 4B00 00203B00 8412C634 */  ori        $a2, $a2, (0x1F1284 & 0xFFFF)
    /* 4B04 00203B04 00000000 */  nop
  .L00203B08:
    /* 4B08 00203B08 2110A600 */  addu       $v0, $a1, $a2
    /* 4B0C 00203B0C 2120A800 */  addu       $a0, $a1, $t0
    /* 4B10 00203B10 00004390 */  lbu        $v1, 0x0($v0)
    /* 4B14 00203B14 0100A524 */  addiu      $a1, $a1, 0x1
    /* 4B18 00203B18 0F00A228 */  slti       $v0, $a1, 0xF
    /* 4B1C 00203B1C 000083A0 */  sb         $v1, 0x0($a0)
    /* 4B20 00203B20 F9FF4014 */  bnez       $v0, .L00203B08
    /* 4B24 00203B24 00000000 */   nop
    /* 4B28 00203B28 1F00023C */  lui        $v0, (0x1F1284 >> 16)
    /* 4B2C 00203B2C 84124290 */  lbu        $v0, (0x1F1284 & 0xFFFF)($v0)
    /* 4B30 00203B30 18182526 */  addiu      $a1, $s1, %lo(var_mechacon_config_param_1)
    /* 4B34 00203B34 2D300002 */  daddu      $a2, $s0, $zero
    /* 4B38 00203B38 0818E424 */  addiu      $a0, $a3, %lo(D_00371808)
    /* 4B3C 00203B3C 11004230 */  andi       $v0, $v0, 0x11
    /* 4B40 00203B40 F612080C */  jal        func_00204BD8
    /* 4B44 00203B44 0818E2A0 */   sb        $v0, %lo(D_00371808)($a3)
    /* 4B48 00203B48 9A32080C */  jal        set_osd_config_to_eekernel
    /* 4B4C 00203B4C 00000000 */   nop
    /* 4B50 00203B50 6446080C */  jal        func_00211990
    /* 4B54 00203B54 00000000 */   nop
    /* 4B58 00203B58 F211080C */  jal        flush_hdd_osd_config
    /* 4B5C 00203B5C 2D200002 */   daddu     $a0, $s0, $zero
    /* 4B60 00203B60 7646080C */  jal        func_002119D8
    /* 4B64 00203B64 00000000 */   nop
    /* 4B68 00203B68 3700033C */  lui        $v1, %hi(D_00371848)
    /* 4B6C 00203B6C 2000BFDF */  ld         $ra, 0x20($sp)
    /* 4B70 00203B70 18182726 */  addiu      $a3, $s1, %lo(var_mechacon_config_param_1)
    /* 4B74 00203B74 48186624 */  addiu      $a2, $v1, %lo(D_00371848)
    /* 4B78 00203B78 0700E468 */  ldl        $a0, 0x7($a3)
    /* 4B7C 00203B7C 0000E46C */  ldr        $a0, 0x0($a3)
    /* 4B80 00203B80 0F00E568 */  ldl        $a1, 0xF($a3)
    /* 4B84 00203B84 0800E56C */  ldr        $a1, 0x8($a3)
    /* 4B88 00203B88 0700C4B0 */  sdl        $a0, 0x7($a2)
    /* 4B8C 00203B8C 0000C4B4 */  sdr        $a0, 0x0($a2)
    /* 4B90 00203B90 0F00C5B0 */  sdl        $a1, 0xF($a2)
    /* 4B94 00203B94 0800C5B4 */  sdr        $a1, 0x8($a2)
    /* 4B98 00203B98 1700E468 */  ldl        $a0, 0x17($a3)
    /* 4B9C 00203B9C 1000E46C */  ldr        $a0, 0x10($a3)
    /* 4BA0 00203BA0 1F00E568 */  ldl        $a1, 0x1F($a3)
    /* 4BA4 00203BA4 1800E56C */  ldr        $a1, 0x18($a3)
    /* 4BA8 00203BA8 1700C4B0 */  sdl        $a0, 0x17($a2)
    /* 4BAC 00203BAC 1000C4B4 */  sdr        $a0, 0x10($a2)
    /* 4BB0 00203BB0 1F00C5B0 */  sdl        $a1, 0x1F($a2)
    /* 4BB4 00203BB4 1800C5B4 */  sdr        $a1, 0x18($a2)
    /* 4BB8 00203BB8 2700E468 */  ldl        $a0, 0x27($a3)
    /* 4BBC 00203BBC 2000E46C */  ldr        $a0, 0x20($a3)
    /* 4BC0 00203BC0 2F00E568 */  ldl        $a1, 0x2F($a3)
    /* 4BC4 00203BC4 2800E56C */  ldr        $a1, 0x28($a3)
    /* 4BC8 00203BC8 2700C4B0 */  sdl        $a0, 0x27($a2)
    /* 4BCC 00203BCC 2000C4B4 */  sdr        $a0, 0x20($a2)
    /* 4BD0 00203BD0 2F00C5B0 */  sdl        $a1, 0x2F($a2)
    /* 4BD4 00203BD4 2800C5B4 */  sdr        $a1, 0x28($a2)
    /* 4BD8 00203BD8 2D100000 */  daddu      $v0, $zero, $zero
    /* 4BDC 00203BDC 1000B1DF */  ld         $s1, 0x10($sp)
    /* 4BE0 00203BE0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 4BE4 00203BE4 0800E003 */  jr         $ra
    /* 4BE8 00203BE8 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel write_osd_config
