.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching Font_SetLocate, 0x24

glabel Font_SetLocate
    /* 13690 00212690 00008444 */  mtc1       $a0, $f0
    /* 13694 00212694 20008046 */  cvt.s.w    $f0, $f0
    /* 13698 00212698 3900023C */  lui        $v0, %hi(D_003969B0)
    /* 1369C 0021269C 00088544 */  mtc1       $a1, $f1
    /* 136A0 002126A0 60088046 */  cvt.s.w    $f1, $f1
    /* 136A4 002126A4 B0694224 */  addiu      $v0, $v0, %lo(D_003969B0)
    /* 136A8 002126A8 301040E4 */  swc1       $f0, 0x1030($v0)
    /* 136AC 002126AC 0800E003 */  jr         $ra
    /* 136B0 002126B0 341041E4 */   swc1      $f1, 0x1034($v0)
endlabel Font_SetLocate
