.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00213FC0, 0x38

glabel func_00213FC0
    /* 14FC0 00213FC0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 14FC4 00213FC4 2D108000 */  daddu      $v0, $a0, $zero
    /* 14FC8 00213FC8 0000B0FF */  sd         $s0, 0x0($sp)
    /* 14FCC 00213FCC 3900033C */  lui        $v1, %hi(D_003979C4)
    /* 14FD0 00213FD0 2D80A000 */  daddu      $s0, $a1, $zero
    /* 14FD4 00213FD4 C479648C */  lw         $a0, %lo(D_003979C4)($v1)
    /* 14FD8 00213FD8 1000BFFF */  sd         $ra, 0x10($sp)
    /* 14FDC 00213FDC A449080C */  jal        Font_SetLocate
    /* 14FE0 00213FE0 2D284000 */   daddu     $a1, $v0, $zero
    /* 14FE4 00213FE4 2D200002 */  daddu      $a0, $s0, $zero
    /* 14FE8 00213FE8 1000BFDF */  ld         $ra, 0x10($sp)
    /* 14FEC 00213FEC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 14FF0 00213FF0 924F0808 */  j          j_Font_PutsPackets_0
    /* 14FF4 00213FF4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00213FC0
