.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00212808, 0x10

glabel func_00212808
    /* 13808 00212808 3900033C */  lui        $v1, %hi(D_003979D0)
    /* 1380C 0021280C 01000224 */  addiu      $v0, $zero, 0x1
    /* 13810 00212810 0800E003 */  jr         $ra
    /* 13814 00212814 D07962AC */   sw        $v0, %lo(D_003979D0)($v1)
endlabel func_00212808
