.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0021D6C0, 0x184

glabel func_0021D6C0
    /* 1E6C0 0021D6C0 90FFBD27 */  addiu      $sp, $sp, -0x70
    /* 1E6C4 0021D6C4 3600023C */  lui        $v0, %hi(D_00365128)
    /* 1E6C8 0021D6C8 5000B0FF */  sd         $s0, 0x50($sp)
    /* 1E6CC 0021D6CC 3000A427 */  addiu      $a0, $sp, 0x30
    /* 1E6D0 0021D6D0 6000BFFF */  sd         $ra, 0x60($sp)
    /* 1E6D4 0021D6D4 2D280000 */  daddu      $a1, $zero, $zero
    /* 1E6D8 0021D6D8 28514924 */  addiu      $t1, $v0, %lo(D_00365128)
    /* 1E6DC 0021D6DC 07002369 */  ldl        $v1, 0x7($t1)
    /* 1E6E0 0021D6E0 0000236D */  ldr        $v1, 0x0($t1)
    /* 1E6E4 0021D6E4 0F002769 */  ldl        $a3, 0xF($t1)
    /* 1E6E8 0021D6E8 0800276D */  ldr        $a3, 0x8($t1)
    /* 1E6EC 0021D6EC 0700A3B3 */  sdl        $v1, 0x7($sp)
    /* 1E6F0 0021D6F0 0000A3B7 */  sdr        $v1, 0x0($sp)
    /* 1E6F4 0021D6F4 0F00A7B3 */  sdl        $a3, 0xF($sp)
    /* 1E6F8 0021D6F8 0800A7B7 */  sdr        $a3, 0x8($sp)
    /* 1E6FC 0021D6FC 5E710A0C */  jal        memset
    /* 1E700 0021D700 20000624 */   addiu     $a2, $zero, 0x20
    /* 1E704 0021D704 1F00063C */  lui        $a2, (0x1F0CA4 >> 16)
    /* 1E708 0021D708 C08681C7 */  lwc1       $f1, %gp_rel(D_00370030)($gp)
    /* 1E70C 0021D70C B40CC28C */  lw         $v0, (0x1F0CB4 & 0xFFFF)($a2)
    /* 1E710 0021D710 1000B027 */  addiu      $s0, $sp, 0x10
    /* 1E714 0021D714 8041013C */  lui        $at, (0x41800000 >> 16)
    /* 1E718 0021D718 00008144 */  mtc1       $at, $f0
    /* 1E71C 0021D71C 3800A2AF */  sw         $v0, 0x38($sp)
    /* 1E720 0021D720 42080046 */  mul.s      $f1, $f1, $f0
    /* 1E724 0021D724 1041013C */  lui        $at, (0x41100000 >> 16)
    /* 1E728 0021D728 00188144 */  mtc1       $at, $f3
    /* 1E72C 0021D72C B40CC28C */  lw         $v0, (0x1F0CB4 & 0xFFFF)($a2)
    /* 1E730 0021D730 C48682C7 */  lwc1       $f2, %gp_rel(D_00370034)($gp)
    /* 1E734 0021D734 4800A2AF */  sw         $v0, 0x48($sp)
    /* 1E738 0021D738 3700A26B */  ldl        $v0, 0x37($sp)
    /* 1E73C 0021D73C 3000A26F */  ldr        $v0, 0x30($sp)
    /* 1E740 0021D740 3F00A36B */  ldl        $v1, 0x3F($sp)
    /* 1E744 0021D744 3800A36F */  ldr        $v1, 0x38($sp)
    /* 1E748 0021D748 4700A56B */  ldl        $a1, 0x47($sp)
    /* 1E74C 0021D74C 4000A56F */  ldr        $a1, 0x40($sp)
    /* 1E750 0021D750 4F00A76B */  ldl        $a3, 0x4F($sp)
    /* 1E754 0021D754 4800A76F */  ldr        $a3, 0x48($sp)
    /* 1E758 0021D758 1700A2B3 */  sdl        $v0, 0x17($sp)
    /* 1E75C 0021D75C 1000A2B7 */  sdr        $v0, 0x10($sp)
    /* 1E760 0021D760 1F00A3B3 */  sdl        $v1, 0x1F($sp)
    /* 1E764 0021D764 1800A3B7 */  sdr        $v1, 0x18($sp)
    /* 1E768 0021D768 2700A5B3 */  sdl        $a1, 0x27($sp)
    /* 1E76C 0021D76C 2000A5B7 */  sdr        $a1, 0x20($sp)
    /* 1E770 0021D770 2F00A7B3 */  sdl        $a3, 0x2F($sp)
    /* 1E774 0021D774 2800A7B7 */  sdr        $a3, 0x28($sp)
    /* 1E778 0021D778 B40CC38C */  lw         $v1, (0x1F0CB4 & 0xFFFF)($a2)
    /* 1E77C 0021D77C B80CC28C */  lw         $v0, (0x1F0CB8 & 0xFFFF)($a2)
    /* 1E780 0021D780 00008344 */  mtc1       $v1, $f0
    /* 1E784 0021D784 20008046 */  cvt.s.w    $f0, $f0
    /* 1E788 0021D788 02000346 */  mul.s      $f0, $f0, $f3
    /* 1E78C 0021D78C 02000246 */  mul.s      $f0, $f0, $f2
    /* 1E790 0021D790 00000000 */  nop
    /* 1E794 0021D794 00000000 */  nop
    /* 1E798 0021D798 03000146 */  div.s      $f0, $f0, $f1
    /* 1E79C 0021D79C 64000046 */  .word      0x46000064                    # cvt.w.s    $f1, $f0 # 00000000 <InstrIdType: CPU_COP1_FPUS>
    /* 1E7A0 0021D7A0 00080544 */  mfc1       $a1, $f1
    /* 1E7A4 0021D7A4 23104500 */  subu       $v0, $v0, $a1
    /* 1E7A8 0021D7A8 01004224 */  addiu      $v0, $v0, 0x1
    /* 1E7AC 0021D7AC C21F0200 */  srl        $v1, $v0, 31
    /* 1E7B0 0021D7B0 21104300 */  addu       $v0, $v0, $v1
    /* 1E7B4 0021D7B4 43100200 */  sra        $v0, $v0, 1
    /* 1E7B8 0021D7B8 21284500 */  addu       $a1, $v0, $a1
    /* 1E7BC 0021D7BC 2C00A2AF */  sw         $v0, 0x2C($sp)
    /* 1E7C0 0021D7C0 2400A5AF */  sw         $a1, 0x24($sp)
    /* 1E7C4 0021D7C4 1C00A2AF */  sw         $v0, 0x1C($sp)
    /* 1E7C8 0021D7C8 A40CC58C */  lw         $a1, (0x1F0CA4 & 0xFFFF)($a2)
    /* 1E7CC 0021D7CC B673080C */  jal        vif1SetXYOffset
    /* 1E7D0 0021D7D0 01000424 */   addiu     $a0, $zero, 0x1
    /* 1E7D4 0021D7D4 7C73080C */  jal        vif1SetZTest
    /* 1E7D8 0021D7D8 2D200000 */   daddu     $a0, $zero, $zero
    /* 1E7DC 0021D7DC 8E73080C */  jal        vif1SetZWrite
    /* 1E7E0 0021D7E0 2D200000 */   daddu     $a0, $zero, $zero
    /* 1E7E4 0021D7E4 01000424 */  addiu      $a0, $zero, 0x1
    /* 1E7E8 0021D7E8 01000524 */  addiu      $a1, $zero, 0x1
    /* 1E7EC 0021D7EC F06E080C */  jal        vif1SetAlphaBlend
    /* 1E7F0 0021D7F0 80000624 */   addiu     $a2, $zero, 0x80
    /* 1E7F4 0021D7F4 FF00073C */  lui        $a3, (0xFFFFFF >> 16)
    /* 1E7F8 0021D7F8 2D200002 */  daddu      $a0, $s0, $zero
    /* 1E7FC 0021D7FC 2D28A003 */  daddu      $a1, $sp, $zero
    /* 1E800 0021D800 01000624 */  addiu      $a2, $zero, 0x1
    /* 1E804 0021D804 2C6F080C */  jal        vif1SetFlatRect
    /* 1E808 0021D808 FFFFE734 */   ori       $a3, $a3, (0xFFFFFF & 0xFFFF)
    /* 1E80C 0021D80C FF00073C */  lui        $a3, (0xFFFFFF >> 16)
    /* 1E810 0021D810 2000A427 */  addiu      $a0, $sp, 0x20
    /* 1E814 0021D814 2D28A003 */  daddu      $a1, $sp, $zero
    /* 1E818 0021D818 01000624 */  addiu      $a2, $zero, 0x1
    /* 1E81C 0021D81C 2C6F080C */  jal        vif1SetFlatRect
    /* 1E820 0021D820 FFFFE734 */   ori       $a3, $a3, (0xFFFFFF & 0xFFFF)
    /* 1E824 0021D824 8E73080C */  jal        vif1SetZWrite
    /* 1E828 0021D828 01000424 */   addiu     $a0, $zero, 0x1
    /* 1E82C 0021D82C 7C73080C */  jal        vif1SetZTest
    /* 1E830 0021D830 01000424 */   addiu     $a0, $zero, 0x1
    /* 1E834 0021D834 6000BFDF */  ld         $ra, 0x60($sp)
    /* 1E838 0021D838 5000B0DF */  ld         $s0, 0x50($sp)
    /* 1E83C 0021D83C 0800E003 */  jr         $ra
    /* 1E840 0021D840 7000BD27 */   addiu     $sp, $sp, 0x70
endlabel func_0021D6C0
