.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_00213FF8, 0x58

glabel func_00213FF8
    /* 14FF8 00213FF8 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 14FFC 00213FFC 1000B1FF */  sd         $s1, 0x10($sp)
    /* 15000 00214000 0000B0FF */  sd         $s0, 0x0($sp)
    /* 15004 00214004 2D88A000 */  daddu      $s1, $a1, $zero
    /* 15008 00214008 2D808000 */  daddu      $s0, $a0, $zero
    /* 1500C 0021400C 2000BFFF */  sd         $ra, 0x20($sp)
    /* 15010 00214010 BA4F080C */  jal        func_00213EE8
    /* 15014 00214014 2D202002 */   daddu     $a0, $s1, $zero
    /* 15018 00214018 3900033C */  lui        $v1, %hi(D_003969B0)
    /* 1501C 0021401C 2D280002 */  daddu      $a1, $s0, $zero
    /* 15020 00214020 B0696324 */  addiu      $v1, $v1, %lo(D_003969B0)
    /* 15024 00214024 1810668C */  lw         $a2, 0x1018($v1)
    /* 15028 00214028 1410648C */  lw         $a0, 0x1014($v1)
    /* 1502C 0021402C 21208600 */  addu       $a0, $a0, $a2
    /* 15030 00214030 A449080C */  jal        Font_SetLocate
    /* 15034 00214034 23208200 */   subu      $a0, $a0, $v0
    /* 15038 00214038 2D202002 */  daddu      $a0, $s1, $zero
    /* 1503C 0021403C 2000BFDF */  ld         $ra, 0x20($sp)
    /* 15040 00214040 1000B1DF */  ld         $s1, 0x10($sp)
    /* 15044 00214044 0000B0DF */  ld         $s0, 0x0($sp)
    /* 15048 00214048 904F0808 */  j          j_Font_PutsPackets
    /* 1504C 0021404C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00213FF8
