.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching func_0026A420, 0x44

glabel func_0026A420
    /* 6B420 0026A420 4F00033C */  lui        $v1, %hi(D_004E90C0)
    /* 6B424 0026A424 3100023C */  lui        $v0, %hi(D_00311288)
    /* 6B428 0026A428 C0906324 */  addiu      $v1, $v1, %lo(D_004E90C0)
    /* 6B42C 0026A42C 88124224 */  addiu      $v0, $v0, %lo(D_00311288)
    /* 6B430 0026A430 3100053C */  lui        $a1, %hi(D_003111F8)
    /* 6B434 0026A434 3100063C */  lui        $a2, %hi(D_00311318)
    /* 6B438 0026A438 09000424 */  addiu      $a0, $zero, 0x9
    /* 6B43C 0026A43C F811A524 */  addiu      $a1, $a1, %lo(D_003111F8)
    /* 6B440 0026A440 1813C624 */  addiu      $a2, $a2, %lo(D_00311318)
    /* 6B444 0026A444 482062AC */  sw         $v0, 0x2048($v1)
    /* 6B448 0026A448 382064AC */  sw         $a0, 0x2038($v1)
    /* 6B44C 0026A44C 2D100000 */  daddu      $v0, $zero, $zero
    /* 6B450 0026A450 3C2065AC */  sw         $a1, 0x203C($v1)
    /* 6B454 0026A454 442066AC */  sw         $a2, 0x2044($v1)
    /* 6B458 0026A458 302064AC */  sw         $a0, 0x2030($v1)
    /* 6B45C 0026A45C 0800E003 */  jr         $ra
    /* 6B460 0026A460 342064AC */   sw        $a0, 0x2034($v1)
endlabel func_0026A420
