.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching j_Font_PutsPackets, 0x8

glabel j_Font_PutsPackets
    /* 14E40 00213E40 EA4E0808 */  j          Font_PutsPackets
    /* 14E44 00213E44 00000000 */   nop
endlabel j_Font_PutsPackets
