.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching pktSetSCISSOR_1, 0x60

glabel pktSetSCISSOR_1
    /* 1C4C8 0021B4C8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 1C4CC 0021B4CC 2D40A000 */  daddu      $t0, $a1, $zero
    /* 1C4D0 0021B4D0 0000BFFF */  sd         $ra, 0x0($sp)
    /* 1C4D4 0021B4D4 40000524 */  addiu      $a1, $zero, 0x40
    /* 1C4D8 0021B4D8 0C00068D */  lw         $a2, 0xC($t0)
    /* 1C4DC 0021B4DC 0800098D */  lw         $t1, 0x8($t0)
    /* 1C4E0 0021B4E0 0400038D */  lw         $v1, 0x4($t0)
    /* 1C4E4 0021B4E4 0000028D */  lw         $v0, 0x0($t0)
    /* 1C4E8 0021B4E8 21186600 */  addu       $v1, $v1, $a2
    /* 1C4EC 0021B4EC 0400078D */  lw         $a3, 0x4($t0)
    /* 1C4F0 0021B4F0 21104900 */  addu       $v0, $v0, $t1
    /* 1C4F4 0021B4F4 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 1C4F8 0021B4F8 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 1C4FC 0021B4FC 0000068D */  lw         $a2, 0x0($t0)
    /* 1C500 0021B500 3C1C0300 */  dsll32     $v1, $v1, 16
    /* 1C504 0021B504 3C380700 */  dsll32     $a3, $a3, 0
    /* 1C508 0021B508 38140200 */  dsll       $v0, $v0, 16
    /* 1C50C 0021B50C 2530C300 */  or         $a2, $a2, $v1
    /* 1C510 0021B510 2538E200 */  or         $a3, $a3, $v0
    /* 1C514 0021B514 DA6D080C */  jal        pktSetAD
    /* 1C518 0021B518 2530C700 */   or        $a2, $a2, $a3
    /* 1C51C 0021B51C 0000BFDF */  ld         $ra, 0x0($sp)
    /* 1C520 0021B520 0800E003 */  jr         $ra
    /* 1C524 0021B524 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel pktSetSCISSOR_1
