.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching pktSetTEST_1, 0x58

glabel pktSetTEST_1
    /* 1C970 0021B970 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 1C974 0021B974 38430800 */  dsll       $t0, $t0, 12
    /* 1C978 0021B978 1000A2DF */  ld         $v0, 0x10($sp)
    /* 1C97C 0021B97C F8530A00 */  dsll       $t2, $t2, 15
    /* 1C980 0021B980 78300600 */  dsll       $a2, $a2, 1
    /* 1C984 0021B984 38390700 */  dsll       $a3, $a3, 4
    /* 1C988 0021B988 78140200 */  dsll       $v0, $v0, 17
    /* 1C98C 0021B98C B84B0900 */  dsll       $t1, $t1, 14
    /* 1C990 0021B990 385C0B00 */  dsll       $t3, $t3, 16
    /* 1C994 0021B994 2528A200 */  or         $a1, $a1, $v0
    /* 1C998 0021B998 25400A01 */  or         $t0, $t0, $t2
    /* 1C99C 0021B99C 2530C700 */  or         $a2, $a2, $a3
    /* 1C9A0 0021B9A0 25482B01 */  or         $t1, $t1, $t3
    /* 1C9A4 0021B9A4 2528A800 */  or         $a1, $a1, $t0
    /* 1C9A8 0021B9A8 2530C900 */  or         $a2, $a2, $t1
    /* 1C9AC 0021B9AC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 1C9B0 0021B9B0 2530A600 */  or         $a2, $a1, $a2
    /* 1C9B4 0021B9B4 DA6D080C */  jal        pktSetAD
    /* 1C9B8 0021B9B8 47000524 */   addiu     $a1, $zero, 0x47
    /* 1C9BC 0021B9BC 0000BFDF */  ld         $ra, 0x0($sp)
    /* 1C9C0 0021B9C0 0800E003 */  jr         $ra
    /* 1C9C4 0021B9C4 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel pktSetTEST_1
