.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sprAlloc, 0x84

glabel sprAlloc
    /* 1CE48 0021BE48 E086868F */  lw         $a2, %gp_rel(D_00370050)($gp)
    /* 1CE4C 0021BE4C 0070023C */  lui        $v0, (0x70004000 >> 16)
    /* 1CE50 0021BE50 00404234 */  ori        $v0, $v0, (0x70004000 & 0xFFFF)
    /* 1CE54 0021BE54 2B104600 */  sltu       $v0, $v0, $a2
    /* 1CE58 0021BE58 08004010 */  beqz       $v0, .L0021BE7C
    /* 1CE5C 0021BE5C E090858F */   lw        $a1, %gp_rel(D_00370A50)($gp)
  .L0021BE60:
    /* 1CE60 0021BE60 00000000 */  nop
    /* 1CE64 0021BE64 00000000 */  nop
    /* 1CE68 0021BE68 00000000 */  nop
    /* 1CE6C 0021BE6C 00000000 */  nop
    /* 1CE70 0021BE70 00000000 */  nop
    /* 1CE74 0021BE74 FAFF0010 */  b          .L0021BE60
    /* 1CE78 0021BE78 00000000 */   nop
  .L0021BE7C:
    /* 1CE7C 0021BE7C 2000A22C */  sltiu      $v0, $a1, 0x20
    /* 1CE80 0021BE80 08004014 */  bnez       $v0, .L0021BEA4
    /* 1CE84 0021BE84 3E00023C */   lui       $v0, %hi(D_003D8020)
  .L0021BE88:
    /* 1CE88 0021BE88 00000000 */  nop
    /* 1CE8C 0021BE8C 00000000 */  nop
    /* 1CE90 0021BE90 00000000 */  nop
    /* 1CE94 0021BE94 00000000 */  nop
    /* 1CE98 0021BE98 00000000 */  nop
    /* 1CE9C 0021BE9C FAFF0010 */  b          .L0021BE88
    /* 1CEA0 0021BEA0 00000000 */   nop
  .L0021BEA4:
    /* 1CEA4 0021BEA4 80180500 */  sll        $v1, $a1, 2
    /* 1CEA8 0021BEA8 20804224 */  addiu      $v0, $v0, %lo(D_003D8020)
    /* 1CEAC 0021BEAC 0100A524 */  addiu      $a1, $a1, 0x1
    /* 1CEB0 0021BEB0 21186200 */  addu       $v1, $v1, $v0
    /* 1CEB4 0021BEB4 2120C400 */  addu       $a0, $a2, $a0
    /* 1CEB8 0021BEB8 000066AC */  sw         $a2, 0x0($v1)
    /* 1CEBC 0021BEBC 2D10C000 */  daddu      $v0, $a2, $zero
    /* 1CEC0 0021BEC0 E09085AF */  sw         $a1, %gp_rel(D_00370A50)($gp)
    /* 1CEC4 0021BEC4 0800E003 */  jr         $ra
    /* 1CEC8 0021BEC8 E08684AF */   sw        $a0, %gp_rel(D_00370050)($gp)
endlabel sprAlloc
