.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching Tim2GetMipMapHeader, 0x38

glabel Tim2GetMipMapHeader
    /* 67A58 00266A58 11008290 */  lbu        $v0, 0x11($a0)
    /* 67A5C 00266A5C 30008324 */  addiu      $v1, $a0, 0x30
    /* 67A60 00266A60 2D300000 */  daddu      $a2, $zero, $zero
    /* 67A64 00266A64 0200422C */  sltiu      $v0, $v0, 0x2
    /* 67A68 00266A68 0700A010 */  beqz       $a1, .L00266A88
    /* 67A6C 00266A6C 0A306200 */   movz      $a2, $v1, $v0
    /* 67A70 00266A70 11008290 */  lbu        $v0, 0x11($a0)
    /* 67A74 00266A74 3600033C */  lui        $v1, %hi(D_00366C08)
    /* 67A78 00266A78 086C6324 */  addiu      $v1, $v1, %lo(D_00366C08)
    /* 67A7C 00266A7C 21104300 */  addu       $v0, $v0, $v1
    /* 67A80 00266A80 00004480 */  lb         $a0, 0x0($v0)
    /* 67A84 00266A84 0000A4AC */  sw         $a0, 0x0($a1)
  .L00266A88:
    /* 67A88 00266A88 0800E003 */  jr         $ra
    /* 67A8C 00266A8C 2D10C000 */   daddu     $v0, $a2, $zero
endlabel Tim2GetMipMapHeader
