.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching Tim2LoadPicture, 0x4C

glabel Tim2LoadPicture
    /* 68508 00267508 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 6850C 0026750C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 68510 00267510 2D808000 */  daddu      $s0, $a0, $zero
    /* 68514 00267514 2000B2FF */  sd         $s2, 0x20($sp)
    /* 68518 00267518 1000B1FF */  sd         $s1, 0x10($sp)
    /* 6851C 0026751C 3000BFFF */  sd         $ra, 0x30($sp)
    /* 68520 00267520 569D090C */  jal        Tim2LoadImage
    /* 68524 00267524 2D90C000 */   daddu     $s2, $a2, $zero
    /* 68528 00267528 2D884000 */  daddu      $s1, $v0, $zero
    /* 6852C 0026752C 2D200002 */  daddu      $a0, $s0, $zero
    /* 68530 00267530 289E090C */  jal        Tim2LoadClut
    /* 68534 00267534 2D284002 */   daddu     $a1, $s2, $zero
    /* 68538 00267538 2D102002 */  daddu      $v0, $s1, $zero
    /* 6853C 0026753C 3000BFDF */  ld         $ra, 0x30($sp)
    /* 68540 00267540 2000B2DF */  ld         $s2, 0x20($sp)
    /* 68544 00267544 1000B1DF */  ld         $s1, 0x10($sp)
    /* 68548 00267548 0000B0DF */  ld         $s0, 0x0($sp)
    /* 6854C 0026754C 0800E003 */  jr         $ra
    /* 68550 00267550 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel Tim2LoadPicture
