.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching vif1SetFramebuffer, 0x134

glabel vif1SetFramebuffer
    /* 1CD10 0021BD10 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 1CD14 0021BD14 0000B0FF */  sd         $s0, 0x0($sp)
    /* 1CD18 0021BD18 4000B4FF */  sd         $s4, 0x40($sp)
    /* 1CD1C 0021BD1C 00840500 */  sll        $s0, $a1, 16
    /* 1CD20 0021BD20 3000B3FF */  sd         $s3, 0x30($sp)
    /* 1CD24 0021BD24 2DA0E000 */  daddu      $s4, $a3, $zero
    /* 1CD28 0021BD28 2000B2FF */  sd         $s2, 0x20($sp)
    /* 1CD2C 0021BD2C 03841000 */  sra        $s0, $s0, 16
    /* 1CD30 0021BD30 1000B1FF */  sd         $s1, 0x10($sp)
    /* 1CD34 0021BD34 2D90C000 */  daddu      $s2, $a2, $zero
    /* 1CD38 0021BD38 2D888000 */  daddu      $s1, $a0, $zero
    /* 1CD3C 0021BD3C 5000BFFF */  sd         $ra, 0x50($sp)
    /* 1CD40 0021BD40 9E6D080C */  jal        vif1Begin
    /* 1CD44 0021BD44 2D980001 */   daddu     $s3, $t0, $zero
    /* 1CD48 0021BD48 82191200 */  srl        $v1, $s2, 6
    /* 1CD4C 0021BD4C 7A891100 */  dsrl       $s1, $s1, 5
    /* 1CD50 0021BD50 3F006330 */  andi       $v1, $v1, 0x3F
    /* 1CD54 0021BD54 0F001032 */  andi       $s0, $s0, 0xF
    /* 1CD58 0021BD58 381C0300 */  dsll       $v1, $v1, 16
    /* 1CD5C 0021BD5C 38861000 */  dsll       $s0, $s0, 24
    /* 1CD60 0021BD60 25882302 */  or         $s1, $s1, $v1
    /* 1CD64 0021BD64 2D204000 */  daddu      $a0, $v0, $zero
    /* 1CD68 0021BD68 25303002 */  or         $a2, $s1, $s0
    /* 1CD6C 0021BD6C DA6D080C */  jal        pktSetAD
    /* 1CD70 0021BD70 4C000524 */   addiu     $a1, $zero, 0x4C
    /* 1CD74 0021BD74 FFFF4626 */  addiu      $a2, $s2, -0x1
    /* 1CD78 0021BD78 FFFF8326 */  addiu      $v1, $s4, -0x1
    /* 1CD7C 0021BD7C 3C300600 */  dsll32     $a2, $a2, 0
    /* 1CD80 0021BD80 3C1C0300 */  dsll32     $v1, $v1, 16
    /* 1CD84 0021BD84 3A340600 */  dsrl       $a2, $a2, 16
    /* 1CD88 0021BD88 2D204000 */  daddu      $a0, $v0, $zero
    /* 1CD8C 0021BD8C 2530C300 */  or         $a2, $a2, $v1
    /* 1CD90 0021BD90 DA6D080C */  jal        pktSetAD
    /* 1CD94 0021BD94 40000524 */   addiu     $a1, $zero, 0x40
    /* 1CD98 0021BD98 22006012 */  beqz       $s3, .L0021BE24
    /* 1CD9C 0021BD9C 2D204000 */   daddu     $a0, $v0, $zero
    /* 1CDA0 0021BDA0 01000224 */  addiu      $v0, $zero, 0x1
    /* 1CDA4 0021BDA4 20006216 */  bne        $s3, $v0, .L0021BE28
    /* 1CDA8 0021BDA8 5000BFDF */   ld        $ra, 0x50($sp)
    /* 1CDAC 0021BDAC 47000524 */  addiu      $a1, $zero, 0x47
    /* 1CDB0 0021BDB0 DA6D080C */  jal        pktSetAD
    /* 1CDB4 0021BDB4 0300063C */   lui       $a2, (0x30000 >> 16)
    /* 1CDB8 0021BDB8 2D204000 */  daddu      $a0, $v0, $zero
    /* 1CDBC 0021BDBC 2D280000 */  daddu      $a1, $zero, $zero
    /* 1CDC0 0021BDC0 DA6D080C */  jal        pktSetAD
    /* 1CDC4 0021BDC4 06000624 */   addiu     $a2, $zero, 0x6
    /* 1CDC8 0021BDC8 2D204000 */  daddu      $a0, $v0, $zero
    /* 1CDCC 0021BDCC 00FE0634 */  ori        $a2, $zero, 0xFE00
    /* 1CDD0 0021BDD0 BC330600 */  dsll32     $a2, $a2, 14
    /* 1CDD4 0021BDD4 DA6D080C */  jal        pktSetAD
    /* 1CDD8 0021BDD8 01000524 */   addiu     $a1, $zero, 0x1
    /* 1CDDC 0021BDDC 2D204000 */  daddu      $a0, $v0, $zero
    /* 1CDE0 0021BDE0 04000524 */  addiu      $a1, $zero, 0x4
    /* 1CDE4 0021BDE4 DA6D080C */  jal        pktSetAD
    /* 1CDE8 0021BDE8 2D300000 */   daddu     $a2, $zero, $zero
    /* 1CDEC 0021BDEC 00191200 */  sll        $v1, $s2, 4
    /* 1CDF0 0021BDF0 00311400 */  sll        $a2, $s4, 4
    /* 1CDF4 0021BDF4 3C180300 */  dsll32     $v1, $v1, 0
    /* 1CDF8 0021BDF8 3C300600 */  dsll32     $a2, $a2, 0
    /* 1CDFC 0021BDFC 3E180300 */  dsrl32     $v1, $v1, 0
    /* 1CE00 0021BE00 3A340600 */  dsrl       $a2, $a2, 16
    /* 1CE04 0021BE04 25306600 */  or         $a2, $v1, $a2
    /* 1CE08 0021BE08 2D204000 */  daddu      $a0, $v0, $zero
    /* 1CE0C 0021BE0C DA6D080C */  jal        pktSetAD
    /* 1CE10 0021BE10 04000524 */   addiu     $a1, $zero, 0x4
    /* 1CE14 0021BE14 2D204000 */  daddu      $a0, $v0, $zero
    /* 1CE18 0021BE18 47000524 */  addiu      $a1, $zero, 0x47
    /* 1CE1C 0021BE1C DA6D080C */  jal        pktSetAD
    /* 1CE20 0021BE20 0500063C */   lui       $a2, (0x50000 >> 16)
  .L0021BE24:
    /* 1CE24 0021BE24 5000BFDF */  ld         $ra, 0x50($sp)
  .L0021BE28:
    /* 1CE28 0021BE28 4000B4DF */  ld         $s4, 0x40($sp)
    /* 1CE2C 0021BE2C 3000B3DF */  ld         $s3, 0x30($sp)
    /* 1CE30 0021BE30 2000B2DF */  ld         $s2, 0x20($sp)
    /* 1CE34 0021BE34 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1CE38 0021BE38 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1CE3C 0021BE3C BC6D0808 */  j          vif1End
    /* 1CE40 0021BE40 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel vif1SetFramebuffer
