.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching vif1SetTEST_1, 0xA0

glabel vif1SetTEST_1
    /* 1CB20 0021BB20 60FFBD27 */  addiu      $sp, $sp, -0xA0
    /* 1CB24 0021BB24 8000B7FF */  sd         $s7, 0x80($sp)
    /* 1CB28 0021BB28 7000B6FF */  sd         $s6, 0x70($sp)
    /* 1CB2C 0021BB2C 2DB86001 */  daddu      $s7, $t3, $zero
    /* 1CB30 0021BB30 6000B5FF */  sd         $s5, 0x60($sp)
    /* 1CB34 0021BB34 2DB04001 */  daddu      $s6, $t2, $zero
    /* 1CB38 0021BB38 5000B4FF */  sd         $s4, 0x50($sp)
    /* 1CB3C 0021BB3C 2DA82001 */  daddu      $s5, $t1, $zero
    /* 1CB40 0021BB40 4000B3FF */  sd         $s3, 0x40($sp)
    /* 1CB44 0021BB44 2DA00001 */  daddu      $s4, $t0, $zero
    /* 1CB48 0021BB48 3000B2FF */  sd         $s2, 0x30($sp)
    /* 1CB4C 0021BB4C 2D98E000 */  daddu      $s3, $a3, $zero
    /* 1CB50 0021BB50 2000B1FF */  sd         $s1, 0x20($sp)
    /* 1CB54 0021BB54 2D90C000 */  daddu      $s2, $a2, $zero
    /* 1CB58 0021BB58 1000B0FF */  sd         $s0, 0x10($sp)
    /* 1CB5C 0021BB5C 2D88A000 */  daddu      $s1, $a1, $zero
    /* 1CB60 0021BB60 9000BFFF */  sd         $ra, 0x90($sp)
    /* 1CB64 0021BB64 9E6D080C */  jal        vif1Begin
    /* 1CB68 0021BB68 2D808000 */   daddu     $s0, $a0, $zero
    /* 1CB6C 0021BB6C 2D280002 */  daddu      $a1, $s0, $zero
    /* 1CB70 0021BB70 2D302002 */  daddu      $a2, $s1, $zero
    /* 1CB74 0021BB74 2D384002 */  daddu      $a3, $s2, $zero
    /* 1CB78 0021BB78 2D406002 */  daddu      $t0, $s3, $zero
    /* 1CB7C 0021BB7C 2D488002 */  daddu      $t1, $s4, $zero
    /* 1CB80 0021BB80 2D50A002 */  daddu      $t2, $s5, $zero
    /* 1CB84 0021BB84 2D58C002 */  daddu      $t3, $s6, $zero
    /* 1CB88 0021BB88 0000B7FF */  sd         $s7, 0x0($sp)
    /* 1CB8C 0021BB8C 5C6E080C */  jal        pktSetTEST_1
    /* 1CB90 0021BB90 2D204000 */   daddu     $a0, $v0, $zero
    /* 1CB94 0021BB94 9000BFDF */  ld         $ra, 0x90($sp)
    /* 1CB98 0021BB98 8000B7DF */  ld         $s7, 0x80($sp)
    /* 1CB9C 0021BB9C 7000B6DF */  ld         $s6, 0x70($sp)
    /* 1CBA0 0021BBA0 6000B5DF */  ld         $s5, 0x60($sp)
    /* 1CBA4 0021BBA4 5000B4DF */  ld         $s4, 0x50($sp)
    /* 1CBA8 0021BBA8 4000B3DF */  ld         $s3, 0x40($sp)
    /* 1CBAC 0021BBAC 3000B2DF */  ld         $s2, 0x30($sp)
    /* 1CBB0 0021BBB0 2000B1DF */  ld         $s1, 0x20($sp)
    /* 1CBB4 0021BBB4 1000B0DF */  ld         $s0, 0x10($sp)
    /* 1CBB8 0021BBB8 BC6D0808 */  j          vif1End
    /* 1CBBC 0021BBBC A000BD27 */   addiu     $sp, $sp, 0xA0
endlabel vif1SetTEST_1
